src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Wales</fullName>
                </value>
                <value>
                    <fullName>Northern Ireland</fullName>
                </value>
                <value>
                    <fullName>Scotland</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Champion_exchange_access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has champion exchange access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ExchangeDataFactory_Test.cls
@isTest
public class ExchangeDataFactory_Test {
    
public static testMethod void TestDataCreation()
{  
Community_Settings__c cs = new Community_Settings__c(name='Exchange_Site', Value__c='Champions Exchange');
insert cs;

Community_Settings__c cs2 = new Community_Settings__c(name='Exchange_Domain', Value__c='exchange');
insert cs2;

Community_Settings__c cs6=new Community_Settings__c();
        cs6.name='Exchange_Domain';
        cs6.value__c='exchange';
        insert cs6;
        Community_Settings__c cs7=new Community_Settings__c();
        cs7.name='Exchange_Feed_Moderator_Perm';
        cs7.value__c='Exchange_Feed_Moderator';
        insert cs7;
        Community_Settings__c cs8=new Community_Settings__c();
        cs8.name='Exchange_Permission_Set';
        cs8.value__c='Exchange_User';
        insert cs8;
        Community_Settings__c cs9=new Community_Settings__c();
        cs9.name='Exchange_Site';
        cs9.value__c='Champions Exchange';
        insert cs9;
        Community_Settings__c cs10=new Community_Settings__c();
        cs10.name='Exchange_Stub_Url';
        cs10.value__c='https://uat-alzheimerscommunities.cs81.force.com/exchange/';
        insert cs10;

        Community_Settings__c cs11=new Community_Settings__c();
        cs11.name='Exchange_Public_Group';
        cs11.value__c='Group chat';
        insert cs11;

 Map<String,Id> roles = new Map<String,Id>();
        List<UserRole> rl = [select id, name from UserRole];
        for(UserRole r : rl){ roles.put(r.name, r.id); }
 Map<String, RecordType> mapRecordTypes = new Map<String, RecordType>();
        List<RecordType> recordTypes = [Select Id, DeveloperName, SObjectType From RecordType];
        for (RecordType rt : recordTypes) { mapRecordTypes.put(rt.DeveloperName + '$' + rt.SObjectType, rt); }


User sysAdminUser =  [select id from user where UserRoleId =:roles.get('CEO') and isActive=true limit 1];

Profile profileForUser = [SELECT Id FROM Profile WHERE Name='DF HVCP'];        


Account a = new Account(Name='Test Account Name');
        a.OwnerId = sysAdminUser.id;
insert a;

 Contact c = new Contact();
        c.firstname = 'Test';
        c.LastName = 'TestContact';
        c.AccountId = a.Id;
        c.Email = 'test.testcontact@myemail.com';
        c.title='Mr';

insert c;
         


 User user = new User(Alias = 'standt',
                              Email='test.testcontact@myemail.com',
                              EmailEncodingKey='UTF-8',
                              LastName='Testing', 
                              LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', 
                              ProfileId = profileForUser.Id, 
                              TimeZoneSidKey='Europe/London',
                              ContactId =c.id, 
                              UserName = 'test.testcontact@myemail.com'
                               );        
        try {
            insert user;
            system.debug('Test User Inserted: ' + user.id);
            system.debug('Test User ContactId: ' + user.ContactId);
        } catch (Exception x) {
            system.debug(x.getMessage());
        } 

 DF_Contact__c DFchamp = new DF_Contact__c();
        DFchamp.RecordTypeId = mapRecordTypes.get('Dementia_Friend_Champion$DF_Contact__c').Id;
        DFchamp.First_Name__c ='test2';
        DFchamp.Last_Name__c = 'test2';
        DFchamp.Title__c = 'Mr';
        DFchamp.Status__c ='Converted';
        DFchamp.Champion_exchange_access__c = true;
        DFchamp.Name='test'+' ' +'test';
        DFchamp.Contact_Number__c = '02085180934';
        DFchamp.Email__c = 'test.testcontact@myemail.com';
        DFchamp.Postcode__c = 'TS1 3TN';
        DFchamp.Street__c = 'test street';
        DFchamp.City__c = 'test';
        DFchamp.County__c = 'test county';
        DFchamp.Country__c = 'test country';
        DFchamp.Newsletters__c = true;
        DFchamp.Portal_Contact__c = c.Id;
        
 insert DFchamp;



 
}
    
}