src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Wales</fullName>
                </value>
                <value>
                    <fullName>Northern Ireland</fullName>
                </value>
                <value>
                    <fullName>Scotland</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_User_TriggerHandler_Test.cls
@isTest
public class DF_User_TriggerHandler_Test {

@testSetup
static void setupData() {  ExchangeDataFactory_Test.TestDataCreation(); }

private static Profile testProfile {

    get {

        if ( testProfile == null) {
             testProfile = [SELECT Id FROM Profile WHERE Name='DF HVCP'];
        }

        return testProfile;
    }

    set;
}


static testMethod void coverMethod() {
    Map<String,Id> roles = new Map<String,Id>();
    List<UserRole> rl = [select id, name from UserRole];
    for(UserRole r : rl){ roles.put(r.name, r.id); }

    User sysAdminUser =  [select id from user where UserRoleId =:roles.get('CEO') and isActive=true limit 1];
    Account a = new Account(Name='Test Account Name');
    a.OwnerId = sysAdminUser.id;
    insert a;

    Contact c = new Contact();
    c.firstname = 'Test';
    c.LastName = 'TestContact';
    c.AccountId = a.Id;
    c.Email = 'test.testcontact2@myemail.com';
    c.Salutation='Mr';
    insert c;

    Map<String, RecordType> mapRecordTypes = new Map<String, RecordType>();    
    List<RecordType> recordTypes = [Select Id, DeveloperName, SObjectType From RecordType];
    for (RecordType rt : recordTypes) { mapRecordTypes.put(rt.DeveloperName + '$' + rt.SObjectType, rt); }

    DF_Contact__c DFc = new DF_Contact__c();
    DFc.RecordTypeId = mapRecordTypes.get('Dementia_Friend$DF_Contact__c').Id;
    DFc.First_Name__c ='test';
    DFc.Last_Name__c = 'test';
    DFc.Title__c = 'Mr';
    DFc.Name='test'+' ' +'test';
    DFc.Contact_Number__c = '02085180934';
    DFc.Email__c = 'test.testcontact2@myemail.com';
    DFc.Postcode__c = 'TS1 3TN';
    DFc.Street__c = 'test street';
    DFc.City__c = 'test';
    DFc.County__c = 'test county';
    DFc.Country__c = 'test country';
    DFc.Newsletters__c = true;
    DFc.Portal_Contact__c = c.Id;
    insert dfc;

    User user = new User(Alias = 'standt',
                  Email='test.testcontact2@myemail.com',
                  EmailEncodingKey='UTF-8',
                  LastName='Testing', 
                  LanguageLocaleKey='en_US', 
                  LocaleSidKey='en_US', 
                  ProfileId = testProfile.Id, 
                  TimeZoneSidKey='Europe/London',
                  ContactId =c.id, 
                  UserName = 'test.testcontact2@myemail.com'
  
                   );  
    try {      
      insert user;
       
    } catch (Exception x) {
            system.debug(x.getMessage());
    }  
    

 }

static testMethod void coverMethod2() {
   User u = [SELECT Id FROM User WHERE Email = 'test.testcontact@myemail.com'];
   Set<Id> updatedUserIds = new Set<Id> ();
   updatedUserIds.add(u.Id);
   if(updatedUserIds.size()>0){
      Test.startTest();
      DF_User_TriggerHandler.disableChampionExchangeAccess(updatedUserIds);
      DF_User_TriggerHandler.enableExchangeModeratorAccess(updatedUserIds);
      DF_User_TriggerHandler.disableExchangeModeratorAccess(updatedUserIds);
      Test.stopTest();
    }

}

}