src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Carry out a personal action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Admin_block_from_requesting_info_session__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin block from requesting info session</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Block_champion_exchange_access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Block champion exchange access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Blocked_due_to_excessive_req_sessions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Automatic block set from having too many open information requests</description>
        <label>Autoblock due to excessive req sessions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Digital_Friend_Signup_Time__c</fullName>
        <description>The date the DF Contact became a Digital Friend. This is the date the contact watched the video to 
4 mins and 10 seconds.</description>
        <inlineHelpText>When did the DF Contact watch the Video</inlineHelpText>
        <label>Digital Friend Signup Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Champion__c</fullName>
        <label>Type of Champion</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Super Champion</fullName>
                </value>
                <value>
                    <fullName>Welsh Champion</fullName>
                </value>
                <value>
                    <fullName>Staff Champion</fullName>
                </value>
                <value>
                    <fullName>Scouts</fullName>
                </value>
                <value>
                    <fullName>Young Persons Champion</fullName>
                </value>
                <value>
                    <fullName>Digital Champion</fullName>
                </value>
                <value>
                    <fullName>PR Champion</fullName>
                </value>
                <value>
                    <fullName>Children’s Champion</fullName>
                </value>
                <value>
                    <fullName>Fast tracked</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Mentor Champion</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Type 3</fullName>
                </value>
                <value>
                    <fullName>Type 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact_Inbound_Change__c.object
<CustomObject>
    <description>Changes to DF contact records on progress</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Contact Inbound Changes</relationshipLabel>
        <relationshipName>DF_Contact_Inbound_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact Inbound Change</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>DF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF Contact Inbound Changes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <label>Event End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_Of_Attendee_Records__c</fullName>
        <label>Number Of Attendees Booked</label>
        <summaryFilterItems>
            <field>DF_EventAttendee__c.Event_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>DF_EventAttendee__c.DF_Event__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Friends Logged</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Total session audience capacity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Info_Session__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies Info Session records that were requested (as opposed to sessions offered up by a champion)</inlineHelpText>
        <label>Requested Info Session</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Information Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Contact__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dementia Friend Champion</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Champions Induction</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Push_Notifications__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Push Notifications</relationshipLabel>
        <relationshipName>Push_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Unread</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Push Notification</label>
    <nameField>
        <displayFormat>PN{000000}</displayFormat>
        <label>Push Notifications Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBChampion.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Page WEBChampion.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class that looks after the WEBChampion VF Page.
 *                  This class determins what to render for the Champion on the Champion Dashboard
 *                  based on different flags etc.
 *               
 *  Modification History
 *  Date            Who         Description 
 *  27/05/2014      CSL         New code to enable 'You have sessions to be reported on' prompt     
 *  03/11/2015      LV          hasWatchedVideo
*******************************************************************************************/
public without sharing class WEBChampion extends DF_WEBC_ControllerBase {
    
    public final String CHAMPION_CODE = 'Register Champions\' code';
    public final String CHAMPION_CODE_ENTERED = 'Registered Champions\' code';
    public final String INVALID_CHAMPION_CODE = 'The Champions\' code you entered was not recognised. Please try again.';
    public final String ALERT_ERROR_CLASS = 'alert-danger';
    public final String STATUS_CANCELLED = 'Cancelled';
    public final String ACTION = 'Tell us about your action';
    public final String ACTION_ENTERED = 'You\'ve created an action';
    public boolean hasActions {get;set;}
    public String actionText {get;set;}
    public List<Action__c> actions {get; set;}
    public String showActionText {get; set;}
    public boolean showAction {get; set;}
    public Action__c theAction {get; set;}
    public boolean message {get;set;}
    public boolean orgRegisterSuccess {get;set;}
    public static final String SESSION_RT = 'Dementia_Friend_Awareness_Session';
    public List<Push_Notifications__c> champMessages{get;set;}
    public String pushMId {get;set;}
    public List<DF_Event__c> upcomingEvents {
        get {
            if (upcomingEvents == null){
                upcomingEvents = new List<DF_Event__c>();
            }
            return upcomingEvents;
        }
        set;
    }
    
    public List<DF_Event__c> eventsRequiringFeedback {
        get {
            if (eventsRequiringFeedback == null){
                eventsRequiringFeedback = new List<DF_Event__c>();
            }
            return eventsRequiringFeedback;
        }
        set;
    }
    
    public List<DF_Contact_Inbound_Change__c> contactDetailsChanged {
        get {
            if (contactDetailsChanged == null){
                contactDetailsChanged = new List<DF_Contact_Inbound_Change__c>();
            }
            return contactDetailsChanged;
        }
        set;
    }

    public Boolean isChampion {get;set;}
    public Boolean isSuperChampion {get;set;}
    public Boolean isBlockedFromInfoSessions {get;set;}
    public Boolean isChampionConverted {get; set;}
    public Boolean isChampionRetired { get; set; }
    public Boolean isChampionProspective { get; set; }
    public Boolean isChampionDeclined { get; set; }
    public Boolean isChampionSuspended { get; set; }
    public Boolean isChampionHiatus { get; set; }
    public Boolean registeredAsChampion {get;set;}
    public Boolean newChampionRegistration {get; set;}
    public Boolean showReportingPrompt {get; set;}
    public Boolean showChangeDetailsPrompt {get; set;}
    public Boolean showActionShare {get; set;}
    public Boolean isChampionVerified{get; set;}
    public String championCode {get;set;}
    public String championCodeError {get;set;}
    public String championCodeText {get;set;}

    public String messageArea {get;set;}
    public String messageAreaClass {get;set;}

    public Integer sessionCount {get;set;}
    public Integer friendCount {get;set;}
    public Integer friendActionCount {get;set;}
    
    public boolean isTraining {get; set;}
    public boolean isSession {get; set;}
    
    public boolean showViewDetailsButton {get; set;}
    public boolean showSaveConfirmation {get; set;}
    
    public Map<Id, RecordType> rtMap {get; set;}
    public Map<String, RecordType> rtMapByName {get; set;}
    
    public List<DF_EventAttendee__c> myTraining {get; set;}
    public boolean isExchangeBlocked {get; set;}
    
    
    
   /* public PageReference registerCode() {
        
        messageArea = null;
        messageAreaClass = null;
        championCodeError = '';
        
        if (championCode.length() == 0) {
        
            messageArea = INVALID_CHAMPION_CODE;
            messageAreaClass = ALERT_ERROR_CLASS;
            return null;
        
        }
        
        system.debug('*** -- Registering code ' + championCode + ' -- ***');
            
        String sConvertMessage = dfcW.confirmChampion(championCode);

        if ( sConvertMessage == null) {

            registeredAsChampion = true;
            currentDfc = DF_Utils.getDFContactForUser(UserInfo.getUserId());            
            dfcW = new DF_Contact_Wrapper(currentDfc);
            isChampion = true;
            isChampionConverted = true;
            isChampionVerified = true;
            isChampionProspective = false;
            
        } else {
                messageArea = sConvertMessage;
                messageAreaClass = ALERT_ERROR_CLASS;
                return null;
        }
        
        return null;

    }*/

    public PageReference convertBackToFriend() {
        

        if ( dfcW.convertToFriend() ) {

            PageReference pr = Page.WEBFriend;
            pr.getParameters().put('convertBack', 'TRUE');
            return pr;

        }

        return null;

        /*
        system.debug('*** -- Into convertBackToFriend -- ***');
        Boolean isSuccess = WEBConversionClass.convertChampionToFriend(currentContact.Id, WEBGlobalSettings.friendConvertCode);
        system.debug('*** -- Conversion returned : ' + isSuccess + ' -- ***');

        if (isSuccess) {
            PageReference pr = Page.WEBFriend;
            pr.getParameters().put('convertBack', 'TRUE');
            return pr;
        }
        else
            return null;
        */

    
    }

    /* 03/11/2015 */
    public Boolean hasWatchedVideo {get;set;}
    public Boolean confirmWithdrawal {get;set;}
    public Boolean sessionDropped {get;set;}
    public Boolean fdBackSubmitted {get;set;}

    public WEBChampion() {
        
        system.debug('*** -- Into WEBChampion Constructor -- ***');
        
        sessionCount = 0;
        hasActions = FALSE;
        friendCount = 0;
        friendActionCount = 0;        
        registeredAsChampion = FALSE;
        newChampionRegistration = false;
        showAction = false;
        actionText = ACTION;
        isSession = false;
        isTraining = false; 
        orgRegisterSuccess = false ;    
        showReportingPrompt = false;
        showActionShare = false;
        if(currentDfc.Type_of_Champion__c != null) {
            isSuperChampion = (currentDfc.Type_of_Champion__c.contains('Super')) ? true : false;
        } else {
            isSuperChampion = false;
        }
        isBlockedFromInfoSessions = currentDfc.Blocked_due_to_excessive_req_sessions__c || currentDfc.Admin_block_from_requesting_info_session__c
            						|| currentDfc.Status__c == 'Prospective' 
                                    || currentDfc.Status__c == 'Suspended' || currentDfc.Status__c == 'Declined'
                                    || currentDfc.Status__c == 'Retired' || currentDfc.Status__c == 'On Hiatus/Resting';
        
        if (ApexPages.currentPage().getParameters().get('nr') != null){
            newChampionRegistration = true; 
        }
        
        if (ApexPages.currentPage().getParameters().get('rc') != null){
            registeredAsChampion = true;    
        }
        
        System.debug('?????: ' + ApexPages.currentPage().getParameters().get('confirmWithdrawal'));
        if (ApexPages.currentPage().getParameters().get('confirmWithdrawal') == 'true') {
            confirmWithdrawal = true;
        } else {
            confirmWithdrawal = false;
        }
        
        System.debug('?????: ' + ApexPages.currentPage().getParameters().get('sessionDropped'));
        if (ApexPages.currentPage().getParameters().get('sessionDropped') == 'true') {
            sessionDropped = true;
        } else {
            sessionDropped = false;
        }

       if (ApexPages.currentPage().getParameters().get('action_created') != null || ApexPages.currentPage().getParameters().get('action_updated')!=null){
        
            showActionShare = true;    
        
        }
        
        if (ApexPages.currentPage().getParameters().get('ds') != null){
            showSaveConfirmation = true;
        } else {
            showSaveConfirmation = false;
        }
        
        if (ApexPages.currentPage().getParameters().get('fdBackSubmitted') == 'true') {
            fdBackSubmitted = true;
        } else {
            fdBackSubmitted = false;
        }
        
        if (ApexPages.currentPage().getParameters().get('org-registered') != null){
        system.debug('URL Parameter'+ApexPages.currentPage().getParameters().get('org-registered'));
          if (!DFP_Utils.isExistingAdminbyOrgName(currentDfc.Email__c,ApexPages.currentPage().getParameters().get('org-registered'))){
            orgRegisterSuccess = true; 
          }
        }
        
        champMessages = new List<Push_Notifications__c>();
        
        for(Push_Notifications__c pn : [select Message__c,Id from Push_Notifications__c where DF_Contact__c=:currentdfc.Id and Status__c = 'Unread']){
            champMessages.add(pn);

        }
        

        if ( currentDfc == null ) { return; }

        isChampion = DF_Utils.isChampion(currentDfc);
        isChampionConverted = DF_Utils.isChampionConverted(currentDfc);
        isChampionRetired = DF_Utils.isChampionRetired(currentDfc);
        isChampionProspective = DF_Utils.isChampionProspective(currentDfc);
        isChampionDeclined = DF_Utils.isChampionDeclined(currentDfc);
        isChampionSuspended = DF_Utils.isChampionSuspended(currentDfc);
        isChampionHiatus = DF_Utils.isChampionHiatus(currentDfc);
        ischampionVerified = DF_Utils.isChampionVerified(currentDfc);
        friendCount = currentDfc.Total_No_of_Friends_Created__c.intValue(); // #ISS - 1482
        isExchangeBlocked = currentDfc.Block_champion_exchange_access__c;
        
        actions = DF_Utils.dfActions(currentdfc);
        if (!actions.isEmpty()) {
            hasActions = TRUE;
            actionText = ACTION_ENTERED;
            theAction = actions[0];
            showActionText = theAction.Action__c;
        }
        
        hasWatchedVideo = (currentDfc.Digital_Friend_Signup_Time__c != null );
        system.debug('champion watched video ' + hasWatchedVideo);
        /* Events organised by this DFC */
        String sdt = Datetime.now().format('yyyy-MM-dd HH:mm:ss', 'Europe/London');
        Datetime dt = Datetime.valueOf(sdt);

        upcomingEvents = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c, Number_of_Attendee_Records__c, Requested_Info_Session__c 
                          FROM DF_Event__c 
                          WHERE Session_Organiser__c = :currentDfc.Id 
                          AND Event_End_Date_Time__c >=: dt 
                          AND Requested_Info_Session__c = false
                          AND Event_Status__c != :STATUS_CANCELLED 
                          AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT)  
                          LIMIT 20];
        
        eventsRequiringFeedback = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c, Requested_Info_Session__c 
                                   FROM DF_Event__c 
                                   WHERE Session_Organiser__c = :currentDfc.Id 
                                   AND Event_End_Date_Time__c <: dt AND (Number_of_Attendees__c = null 
                                                                         OR Number_of_Attendees__c = 0) 
                                   AND Event_Status__c != :STATUS_CANCELLED 
                                   AND  RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT)  LIMIT 10];
        contactDetailsChanged = [SELECT id 
                                 FROM DF_Contact_Inbound_Change__c 
                                 WHERE Related_DF_Contact__c=:currentdfc.id];
        
        if (eventsRequiringFeedback.size() > 0 && isChampionConverted ) {
            showReportingPrompt = true;
        }
        if(contactDetailsChanged.size()>0 ){
            
            showChangeDetailsPrompt = true;
        }

        List<DF_Event__c> events = [SELECT Id 
                                    FROM DF_Event__c 
                                    WHERE Session_Organiser__c = :currentDfc.id 
                                    AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                                    AND Event_Status__c ='Completed' 
                                    LIMIT 1000];

        if (events != null && !events.isEmpty()) {
            sessionCount = events.size();
        }
        
        system.debug('WEBChampion isChampion = ' + isChampion);
        system.debug('WEBChampion isChampionConverted = ' + isChampionConverted);

        myTraining = new List<DF_EventAttendee__c>();
        
        String championCourseRT = DF_Utils.getDfEventRecordTypeId(DF_Utils.RT_CHAMPION_COURSE);
                //championCodeText = CHAMPION_CODE;
        
                myTraining = [SELECT Id, DF_Event__r.Event_Date_Time__c, DF_Event__r.City__c, DF_Event__r.Postcode__c, DF_Event__r.Number_of_Attendees__c, DF_Event__r.RecordTypeId 
                            FROM DF_EventAttendee__C WHERE DF_Contact__c = :currentDfc.Id
                            and DF_Event__r.RecordTypeId = :championCourseRT LIMIT 1];
        
                if (!myTraining.isEmpty()){
            
                    isTraining = true;
                    isSession = false;
                    showViewDetailsButton = true;
            
                }
        
        

        system.debug('WEBChampion Champion Code Text ' + championCodeText);

        List<DF_EventAttendee__c> myEventContacts = [SELECT DF_Contact__r.Id FROM DF_EventAttendee__c WHERE DF_Event__c = :events LIMIT 1000];

        List<Id> myEventContactsId = new List<Id>();
        
        if (myEventContacts != null && !myEventContacts.isEmpty()) {
        
            for (DF_EventAttendee__c att : myEventContacts) {
                myEventContactsId.add(att.DF_Contact__r.Id);
            }

            List<Action__c> myEventContactsActions = [SELECT Id FROM Action__c WHERE DF_Contact__r.Id = :myEventContactsId LIMIT 1000];
    
            if (myEventContactsActions != null && !myEventContactsActions.isEmpty())
                friendActionCount = myEventContactsActions.size();
        }
    }

    
   


}