src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Carry out a personal action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Homepage__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Allow pledge (action) to be shown on the homepage.</inlineHelpText>
        <label>Homepage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>Partner Actions</relationshipLabel>
        <relationshipName>DF_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Leave this box ticked if you are happy for your pledge to be displayed on our website.</inlineHelpText>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Actions__c</fullName>
        <label>Actions</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Get in touch with someone with dementia</fullName>
                </value>
                <value>
                    <fullName>Volunteer for an org that helps PWD</fullName>
                </value>
                <value>
                    <fullName>Campaign for change</fullName>
                </value>
                <value>
                    <fullName>Wear my badge and tell five friends</fullName>
                </value>
                <value>
                    <fullName>Carry out own action</fullName>
                </value>
                <value>
                    <fullName>Sign up to a Local Dementia Action Alliance</fullName>
                </value>
                <value>
                    <fullName>Explore in depth dementia training for staff</fullName>
                </value>
                <value>
                    <fullName>Send the Dementia Friendly Employers Guide to my HR team</fullName>
                </value>
                <value>
                    <fullName>Fundraise for Alzheimer’s Society</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_ActionTriggerHandler.cls
public class DF_ActionTriggerHandler{


  private boolean m_isExecuting = false;
  private integer BatchSize = 0;    
 
  public DF_ActionTriggerHandler(boolean isExecuting, integer size){

     m_isExecuting = isExecuting;
     BatchSize = size;

  }


  public void OnBeforeInsert(List<Action__c> newActions, Map<ID, Action__c> actionOldMap){

     limitNoOfActions(newActions,null);
  }
  
  public void OnBeforeUpdate(List<Action__c> updatedActions, Map<ID, Action__c> actionOldMap){
     
        
  }


  public void limitNoOfActions( List<Action__c> updatedActions, Map<ID, Action__c> actionOldMap){
   
   List<Action__c> listoinsert = new List<Action__c> ();
   string pValue5 =  'Carry out own action';
   
   set<Id> contactIds = new set<Id>();
   set<Id> partnerIds = new set<Id>();
   Map<String,Action__c> contactAcMap= new Map<String,Action__c>();
    
   for ( Action__c a : updatedActions){    
     
     contactIds.add(a.df_contact__c);     
     partnerIds.add(a.partner_organisation__c);
   }
   
   List< Action__c> lisactions = [select partner_organisation__c,df_contact__c,standard_actions__c,action__c,public__c,homepage__c from action__c 
   where df_contact__c in:contactids and partner_organisation__c in:partnerIds ];
   
   for(action__c ac :lisactions){
   String key;
   if( ac.DF_Contact__c !=null){
    key= ac.DF_Contact__c +'~'+ ac.Standard_Actions__c;
    }
    
    if(ac.partner_organisation__c != null){
    key= ac.partner_organisation__c +'~'+ ac.Standard_Actions__c;
    }
    contactAcMap.put(key,ac);
    
    
    system.debug('ACTION MAP'+contactAcMap);
   
   }
   
   for ( Action__c a : updatedActions){
    
    if(actionOldMap==null){ 

        if(contactAcMap.get(a.DF_Contact__c +'~'+ a.Standard_Actions__c )!=null || contactAcMap.get(a.partner_organisation__c +'~'+ a.Standard_Actions__c )!=null ){
         system.debug('action  already exist'+contactAcMap.get(a.DF_Contact__c +'~'+ a.Standard_Actions__c));
         a.addError('The standard action you have selected already exists for the contact');
        }
         
    
     }
   
 
   }
  
  }



}