src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Carry out a personal action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Actions__c</fullName>
        <label>Actions</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Get in touch with someone with dementia</fullName>
                </value>
                <value>
                    <fullName>Volunteer for an org that helps PWD</fullName>
                </value>
                <value>
                    <fullName>Campaign for change</fullName>
                </value>
                <value>
                    <fullName>Wear my badge and tell five friends</fullName>
                </value>
                <value>
                    <fullName>Carry out own action</fullName>
                </value>
                <value>
                    <fullName>Sign up to a Local Dementia Action Alliance</fullName>
                </value>
                <value>
                    <fullName>Explore in depth dementia training for staff</fullName>
                </value>
                <value>
                    <fullName>Send the Dementia Friendly Employers Guide to my HR team</fullName>
                </value>
                <value>
                    <fullName>Fundraise for Alzheimer’s Society</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_ActionTriggerHandler_Test.cls
@isTest
private class DF_ActionTriggerHandler_Test
{


  @isTest
  static void coverMethod()
  {
    Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
    Action__c action  = (Action__c)mapTestData.get('Action');
    DF_Contact__c Dfc  = (DF_Contact__c)mapTestData.get('DFc');
    test.starttest();  
    
     update action;
    Action__c act = new Action__c();
    act.DF_Contact__c = Dfc.id;
    act.Standard_Actions__c='Campaign for change';
    insert act;

    
    }

 
}