src/objects/CKE_Pack_Request__c.object
<CustomObject>
    <description>A pack request from the Cupcakes site</description>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address Line1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Don&apos;t make this an email field, because the form does interim saves, where the email address may not be valid. Only &apos;Completed&apos; status forms have a valid email address.</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progress_Form_Id__c</fullName>
        <label>Progress Form Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proximity_to_Dementia__c</fullName>
        <description>This field will need to map to longer string values on the display page (see the wireframes for the site design).</description>
        <label>Proximity to Dementia</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Person with Dementia</fullName>
                </value>
                <value>
                    <fullName>Current Family or Friend</fullName>
                </value>
                <value>
                    <fullName>Past Family or Friend</fullName>
                </value>
                <value>
                    <fullName>Carer</fullName>
                </value>
                <value>
                    <fullName>Past Carer</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Interested Party</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CKE Pack Request</label>
    <nameField>
        <displayFormat>CKE-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKE Pack Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CKE_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address_Line1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift_Aid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gift Aid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progress_Form_Id__c</fullName>
        <label>Progress Form ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proximity_to_Dementia__c</fullName>
        <label>Proximity to Dementia</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Checkout1</fullName>
                </value>
                <value>
                    <fullName>Checkout2</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pay-in</fullName>
                </value>
                <value>
                    <fullName>Donation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CKE Payment</label>
    <nameField>
        <displayFormat>PMT-{0000000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKE Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/classes/CkePackRequestLinkBatcher_Test.cls
@isTest
private class CkePackRequestLinkBatcher_Test
{

 	@testSetup
   	static void testSetup(){

   		Community_Settings__c setting = new Community_Settings__c();
		setting.Name = 'CKE_Pack_Progress_Id';
		setting.Value__c = 'xxx';
		insert setting;

		setting = new Community_Settings__c();
		setting.Name = 'CKE_Payment_Progress_Id';
		setting.Value__c = 'xxxp';
		insert setting;

		setting = new Community_Settings__c();
		setting.Name = 'CKE_Donate_Progress_Id';
		setting.Value__c = 'xxxd';
		insert setting;
   		 

		CKE_Pack_Request__c pr = new CKE_Pack_Request__c();
		pr.Title__c = 'Mr';
		pr.First_Name__c = 'Test';
		pr.Last_Name__c = 'Test';
		pr.Email__c = 'Test@test.com';

		pr.City__c = 'test';
		pr.County__c = 'test';
		pr.Address_Line1__c = 'test';
		pr.Postcode__c = 'SW3 1PE';		
		pr.Status__c= 'Completed';
		pr.Progress_Form_Id__c = 'xxx';
		insert pr;


		pr = new CKE_Pack_Request__c();
		pr.Title__c = 'Mr';
		pr.First_Name__c = 'Test';
		pr.Last_Name__c = 'Test';
		pr.Email__c = 'Test@test.com';

		pr.City__c = 'test';
		pr.County__c = 'test';
		pr.Address_Line1__c = 'test';
		pr.Postcode__c = 'SW3 1PE';		
		pr.Status__c= 'Completed';
		pr.Progress_Form_Id__c = 'xxx';
		insert pr;

		CKE_Payment__c payment = new CKE_Payment__c();
		payment.Title__c = 'Mr';
		payment.First_Name__c = 'Test';
		payment.Last_Name__c = 'Test';
		payment.Email__c = 'Test@test.com';

		payment.City__c = 'test';
		payment.County__c = 'test';
		payment.Address_Line1__c = 'test';
		payment.Postcode__c = 'SW3 1PE';
		payment.Proximity_to_Dementia__c = 'xxx';
		payment.Gift_Aid__c = false;
		payment.Progress_Form_Id__c = 'xxxp';
		payment.Status__c = 'Completed';

		payment.Amount__c = 100;

		payment.Type__c = CkePaymentController.TYPE_PAYIN;

		insert payment;

		payment = new CKE_Payment__c();
		payment.Title__c = 'Mr';
		payment.First_Name__c = 'Test';
		payment.Last_Name__c = 'Test';
		payment.Email__c = 'Test@test.com';

		payment.City__c = 'test';
		payment.County__c = 'test';
		payment.Address_Line1__c = 'test';
		payment.Postcode__c = 'SW3 1PE';
		payment.Proximity_to_Dementia__c = 'xxx';
		payment.Gift_Aid__c = false;
		payment.Progress_Form_Id__c = 'xxxp';
		payment.Status__c = 'Completed';

		payment.Amount__c = 100;

		payment.Type__c = CkePaymentController.TYPE_DONATION;

		insert payment;


   	}


	@isTest
	static void itShould()
	{




		Test.startTest();

		CkeLinkBatchScheduler scheduler = new CkeLinkBatchScheduler();
		String timeString = '0 0 23 * * ?'; 
		system.schedule('Link Batch Scheduler', timeString, scheduler); 

		Test.stopTest();

	}

	@isTest
	static void itShould2() {


		CkePackRequestLinkBatcher batcher = new CkePackRequestLinkBatcher('xxx', 'xxxp','xxxd');
		Database.executeBatch(batcher);


	}

}