src/objects/CKE_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Id__c</fullName>
        <label>Transaction Reference</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pay-in</fullName>
                </value>
                <value>
                    <fullName>Donation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CKE Payment</label>
    <nameField>
        <displayFormat>PMT-{0000000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKE Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CkeMailClient_Test.cls
@isTest
public class CkeMailClient_Test {

 @isTest    
 public static void itShould() {

    Cke_Payment__c p = new Cke_Payment__c();
    p.First_Name__c = 'xxx';
    p.Type__c = 'Pay-in';
    p.Amount__c = 10;
    p.Transaction_Id__c = 'xxx';     

    Test.startTest();

    Test.setMock(HttpCalloutMock.class, new CkeMailClientMockHttp_Test());
    CkeMailClient client = new CkeMailClient();
    client.sendTestMail('xxx@xxx.com', 'xxx', 10);
    client.sendPackConfirmationMail('xxx@xxx.com', 'xxx', 10);
    client.sendPayinConfirmationMail('xxx@xxx.com', 'xxx', 10, 'xxx');
    client.sendDonationConfirmationMail('xxx@xxx.com', 'xxx', 10, 'xxx');
    client.sendRegisterInterestConfirmationMail('xxx@xxx.com', 'xxx');

    client.sendPaymentConfirmationMail(p);
    
    p.Type__c = CkePaymentController.TYPE_DONATION;
    client.sendPaymentConfirmationMail(p);    

    p.Type__c = null;
    client.sendPaymentConfirmationMail(p);    

 }

}