src/objects/CKE_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paypal_Token__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Paypal Token</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Checkout1</fullName>
                </value>
                <value>
                    <fullName>Checkout2</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CKE Payment</label>
    <nameField>
        <displayFormat>PMT-{0000000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKE Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/objects/PayPal_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Gateway_Data_1__c</fullName>
        <label>Gateway Data 1</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway_Data_2__c</fullName>
        <label>Gateway Data 2</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway_Data_3__c</fullName>
        <label>Gateway Data 3</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway_Data_4__c</fullName>
        <label>Gateway Data 4</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gateway_Data_5__c</fullName>
        <label>Gateway Data 5</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Payments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live Payments</label>
        <type>Checkbox</type>
    </fields>
    <label>PayPal Settings</label>
</CustomObject>

src/classes/TestDataFactory_CC.cls
/*
    Class used to create test data for unit tests
*/
public class TestDataFactory_CC {

    public static void createAllCustomSettings() {
    
        createCkeRecordSettings();
        createPaypalSettings();
        
    }
    
    private static void createCkeRecordSettings() {
        
        List<Community_Settings__c> cupcakeCustomSettings = new List<Community_Settings__c>{ new Community_Settings__c(Name = 'CKE_Donate_Progress_Id', Value__c = 'EVCD17_DON'),
                                                                                             new Community_Settings__c(Name = 'CKE_Pack_Progress_Id', Value__c = 'EVCD17_KIT'),
                                                                                             new Community_Settings__c(Name = 'CKE_Payment_Progress_Id', Value__c = 'EVCD17_PAY')};
        insert cupcakeCustomSettings;
        
    }
    
    private static void createPaypalSettings() {
        
        PayPal_Settings__c settings = new PayPal_Settings__c();
        settings.Gateway_Data_1__c= 'xxx';
        settings.Gateway_Data_2__c = 'xxx';
        settings.Gateway_Data_3__c = 'xxx';
        settings.Gateway_Data_4__c = 'xxx';
        settings.Gateway_Data_5__c = 'xxx.xxx.xxx.com';
        settings.Live_Payments__c = false;
        insert settings;

        Cke_Payment__c payment = new Cke_Payment__c();
        payment.Status__c = 'Checkout1';
        payment.Amount__c = 100;
        payment.Paypal_Token__c = 'xxxx';
        payment.First_Name__c = 'Test';
        payment.Last_Name__c = 'Test';
        payment.Email__c = 'Test@test.com';
        insert payment;

        Cke_Payment__c payment2 = new Cke_Payment__c();
        payment2.Status__c = 'Checkout99';
        payment2.Amount__c = 100;
        payment2.Paypal_Token__c = 'bad';
        payment2.First_Name__c = 'Test';
        payment2.Last_Name__c = 'Test';
        payment2.Email__c = 'Test@test.com';
        insert payment2;

        Cke_Payment__c payment3 = new Cke_Payment__c();
        payment3.Status__c = 'Checkout2';
        payment3.Amount__c = 100;
        payment3.Paypal_Token__c = 'EC-4HD21310W5753063G';
        payment3.First_Name__c = 'Test';
        payment3.Last_Name__c = 'Test';
        payment3.Email__c = 'Test@test.com'; 
        insert payment3;
        
    }

}