src/objects/CKE_Pack_Request__c.object
<CustomObject>
    <description>A pack request from the Cupcakes site</description>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address Line1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line2__c</fullName>
        <label>Address Line2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line3__c</fullName>
        <label>Address Line3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BirthDate__c</fullName>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Name of the company for when Cupcake Day is being hosted at work</description>
        <inlineHelpText>Name of the company for when Cupcake Day is being hosted at work</inlineHelpText>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Don&apos;t make this an email field, because the form does interim saves, where the email address may not be valid. Only &apos;Completed&apos; status forms have a valid email address.</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Work</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optin_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Optin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optin_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Phone Optin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optin_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Optin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optin_Social_Media__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Social Media Optin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optin_TermsConditions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TC Optin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optout_Post__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Post Optout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progress_Form_Id__c</fullName>
        <label>Progress Form Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proximity_to_Dementia__c</fullName>
        <description>This field will need to map to longer string values on the display page (see the wireframes for the site design).</description>
        <label>Proximity to Dementia</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Person with Dementia</fullName>
                </value>
                <value>
                    <fullName>Current Family or Friend</fullName>
                </value>
                <value>
                    <fullName>Past Family or Friend</fullName>
                </value>
                <value>
                    <fullName>Carer</fullName>
                </value>
                <value>
                    <fullName>Past Carer</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Interested Party</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referer_Header__c</fullName>
        <inlineHelpText>Give the webpage information from the webpage a user was on before arriving at the packrequest form</inlineHelpText>
        <label>Referer Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Submitted__c</fullName>
        <label>Time Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CKE Pack Request</label>
    <nameField>
        <displayFormat>CKE-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKE Pack Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/classes/CkePackRequestController.cls
global without sharing class CkePackRequestController extends EdtPageController {
   
   private static final String PACK_FORM_ID = Community_Settings__c.getInstance('CKE_Pack_Progress_Id').Value__c;
   public class RequestException extends Exception{}

   public static String captchaSite{

    get {

        String s = '6Lc8lxkTAAAAABWgV2BcYEDEsy6Ff9IU8iEAxpyO';
        try { 
                String sCap = (String)Community_Settings__c.getInstance('Cke_Captcha_Site').value__c;
                if ( sCap != null && sCap.length() > 0) { s = sCap; }
                } catch (Exception x) { }

        return s;        

    }

    set;}

   public static String captchaSecret {

    get {

        String s = '6Lc8lxkTAAAAAKhi7vXZgBKHxZ96hkXRuMr2kJzD';
        try { 
                String sCap = (String)Community_Settings__c.getInstance('Cke_Captcha_Secret').value__c;
                if ( sCap != null && sCap.length() > 0) { s = sCap; }
                } catch (Exception x) {}

        return s;        

    }

    set;}


   @RemoteAction        
   global static Object processSubmit(Command cmd)
   {
       Boolean isPartialSubmission = false;
       try {
       
           
            
            /*// Removed Captcha for 2017
            if ( cmd.submitted == true ) {
                          
                         WEBC_Recaptcha2Handler cpt = new WEBC_Recaptcha2Handler(captchaSecret, cmd.captchaResponse );
              
                if ( !cpt.verify() ) {
                        return new CkeException('Google Captcha Failed');
                     }
             }*/
                
            Cke_Pack_Request__c item = buildRecord(cmd, isPartialSubmission);
            if ( item.Email__c != '' && item.Email__c != null && item.Email__c != 'undefined' 
              && item.First_Name__c != '' && item.First_Name__c != null && item.First_Name__c != 'undefined') {       
            Database.UpsertResult dur = Database.upsert(item, true);
            
            if(!dur.isSuccess()) {
            
                List<Database.Error> errors = dur.getErrors();
                String combinedErrorMsgs = '';
                for(Database.Error err : errors) {
                    combinedErrorMsgs+=err.getMessage();
                    CustomUtils.saveWebError('Cupcake Day Pack Request', combinedErrorMsgs);
                }
                return new RequestException(); 
                            
            } else {
                          
                //if ( cmd.submitted == true ) {
                
                      sendEmailConfirmation(item.Email__c, item.First_Name__c, 3);
                //}
    
                System.debug('Item Id : ' + item.id);
                cmd.id = item.id;
                return cmd;
            }
            } else {
             String errMsg = 'Issues with email (' + item.Email__c + ') and/or firstname (' + item.First_Name__c + ')';
             CustomUtils.saveWebError('Cupcake Day', errMsg);
            return new RequestException(); 
            }
       }

       catch (Exception e) {
          return new SysRestError(e, 550); 
       }
    }

    @RemoteAction        
   global static Object processPartialSubmit(Command cmd)
   {        
       Boolean isPartialSubmission = true;
       try {
                
             Cke_Pack_Request__c item = buildRecord(cmd, isPartialSubmission);       
             System.debug('item is: ' + item );

           // June 2018 - GG - THIS IF STATEMENT NOT YET DEPLOYED as of June 2018
           if ( item.Status__c == null || item.Status__c != 'Completed') {

               // Prevent recording personal identifiable data before a full page submit
               if (item.Email__c != null) {
                   item.Email__c = 'partialsubmission@mailinator.com';
               }
               if (item.First_Name__c != null) {
                   item.First_Name__c = 'Anon';
               }
               if (item.Last_Name__c != null) {
                   item.Last_Name__c = 'Anon';
               }
               if (item.Phone__c != null) {
                   item.Phone__c = '077777777777';
               }
               if (item.Address_Line1__c != null) {
                   item.Address_Line1__c = 'Anon';
               }

           }

            Database.UpsertResult dsr = Database.upsert(item, false);
           
           if(!dsr.isSuccess()) {
               String allErrs = '';
               for(Database.Error err : dsr.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    allErrs += err.getStatusCode() + ': ' + err.getMessage() + ' | ';
                }
               CustomUtils.saveWebError('Cupcake Day Payment', 'All errors recorded as: ' + allErrs);
           }
                          
            if ( cmd.submitted == true ) {
                sendEmailConfirmation(item.Email__c, item.First_Name__c, 3);
            }

            System.debug('Item Id : ' + item.id);
            cmd.id = item.id;
            return cmd;

       }

       catch (Exception e) {
          CustomUtils.saveWebError('Cupcake Day Payment', e.getMessage()); 
          return new SysRestError(e, 550); 
       }
    }
    
    @Future(callout=true)
    public static void sendEmailConfirmation(String email, String name, Integer d) {
    
        CkeMailClient client = new CkeMailClient();
        client.sendPackConfirmationMail(email, name, d);
    
    }

    public static Cke_Pack_Request__c buildRecord(Command cmd, Boolean isPartialSubmission)
    {

        System.debug('Submitted cmd:' + cmd);

        Cke_Pack_Request__c item;
        if ( cmd.id != null && cmd.id != '' ) {

            item = (Cke_Pack_Request__c)CustomUtils.ObjectWithAllFields('id', cmd.id, Schema.sObjectType.CKE_Pack_Request__c);

        } else { 

            item = new Cke_Pack_Request__c();

        }
        
        // If the item is already completed don't do any updates
        if ( item.Status__c == 'Completed') { return item; }

        item.Email__c = cmd.email;
        item.Title__c = cmd.title;
        item.First_Name__c = cmd.firstName;
        item.Last_Name__c = cmd.lastName;
        item.Address_Line1__c = cmd.addressLine1;
        item.Address_Line2__c = cmd.addressLine2;
        item.Address_Line3__c = cmd.addressLine3;
        item.City__c = cmd.city;
        item.County__c = cmd.county;
        item.Postcode__c = cmd.postcode;
        item.Country__c = cmd.country;
        item.Phone__c = cmd.phone;
        item.Optin_Email__c = cmd.optinEmail == true;
        item.Optin_Phone__c = cmd.optinPhone == true;
        item.Optin_Sms__c = cmd.optinSms == true;
        //item.Optin_TermsConditions__c = cmd.optinTc == true;
        item.Optin_TermsConditions__c = true;  // implied by requesting the pack
        item.Optout_Post__c = cmd.optoutPost == true;
        item.Optin_Social_Media__c = cmd.optinSocial == true;
        item.Event_Location__c = cmd.location;
        item.Proximity_to_Dementia__c = cmd.proximity;  
        item.Referer_Header__c = cmd.refererHeader;
        item.Progress_Form_Id__c = PACK_FORM_ID;
        item.Company_Name__c = cmd.companyName;
        
        if(cmd.dob != '') {

            Datetime dobDt = Datetime.newInstance(Long.valueOf(cmd.dob));
            item.BirthDate__c = dobDt.date();
        }

        item.Time_Submitted__c = DateTime.now();         
        //if ( cmd.submitted == true ) { item.Status__c = 'Completed'; }
        if (!isPartialSubmission) { 
          item.Status__c = 'Completed';
          item.Optin_TermsConditions__c = true;  // implied by requesting the pack 
        }

        return item;
    
    }

    /*
    private static Date getDate(String sDate) {

        try { 

            String[] partsMajor = sDate.split('T');                
            String[] parts = partsMajor[0].split('-');
            System.debug(parts);
            
            Date dt = null;
            dt = Date.newInstance(Integer.valueOf(parts[0]),Integer.valueOf(parts[1]),Integer.valueOf(parts[2]));       
            return dt;
            
        } catch (Exception x) { 
          System.Debug('Date Error : ' + x.getCause() + ' ' + x.getMessage());
          return null; 

        }

    }
    */

    
    global class Command 
    {

        public String dob { get;set; }
        public String captchaResponse { get;set; }      
      
        public String id { get;set; }
        public Boolean submitted { get; set;}  
        public String email { get; set; }
        public String title { get; set; }
        public String firstName { get; set; }
        public String lastName { get; set; }
        public String phone { get; set; }

        public Boolean optinEmail { get; set;}  
        public Boolean optinPhone { get; set;}          
        public Boolean optinSms { get; set;} 
        public Boolean optoutPost { get; set;} 
        public Boolean optinSocial { get; set;}         
        public Boolean optinTc{ get; set;}  

        public String postcode { get; set; }
        public String county { get; set; }
        public String city { get; set; }
        public String addressLine1 { get; set; }
        public String addressLine2 { get; set; }
        public String addressLine3 { get; set; }
        public String country { get; set; }
        
        public String location { get; set; }
        public String proximity { get; set; }
        public String refererHeader { get; set; }
        
        public String companyName {get;set;}
        
        public String requestCode { get; set; }

    }    


}