src/objects/CKE_Pack_Request__c.object
<CustomObject>
    <description>A pack request from the Cupcakes site</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Don&apos;t make this an email field, because the form does interim saves, where the email address may not be valid. Only &apos;Completed&apos; status forms have a valid email address.</description>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optin_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Optin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optin_TermsConditions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TC Optin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Progress_Form_Id__c</fullName>
        <label>Progress Form Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Submitted__c</fullName>
        <label>Time Submitted</label>
        <type>DateTime</type>
    </fields>
    <label>CKE Pack Request</label>
    <nameField>
        <displayFormat>CKE-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKE Pack Requests</pluralLabel>
    <recordTypes>
        <fullName>Register_Interest</fullName>
        <active>true</active>
        <label>Register Interest</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/classes/CkeHomeHoldingController.cls
global without sharing class CkeHomeHoldingController extends EdtPageController {

	public final Static String PROGRESS_CODE = 'EVCD17_ENQ';

	public CkeHomeHoldingController() {
		
	}

    public static String captchaSite{

    get {

        String s = '6Lc8lxkTAAAAABWgV2BcYEDEsy6Ff9IU8iEAxpyO';
        try { 
                String sCap = (String)Community_Settings__c.getInstance('Cke_Captcha_Site').value__c;
                if ( sCap != null && sCap.length() > 0) { s = sCap; }
                } catch (Exception x) { }

        return s;        

    }

    set;}

   public static String captchaSecret {

    get {

        String s = '6Lc8lxkTAAAAAKhi7vXZgBKHxZ96hkXRuMr2kJzD';
        try { 
                String sCap = (String)Community_Settings__c.getInstance('Cke_Captcha_Secret').value__c;
                if ( sCap != null && sCap.length() > 0) { s = sCap; }
                } catch (Exception x) {}

        return s;        

    }

    set;}


   @RemoteAction	
   global static Object processSubmit(Command cmd)
   {
       try {
            
             WEBC_Recaptcha2Handler cpt = new WEBC_Recaptcha2Handler(captchaSecret, cmd.captchaResponse );
              
             if ( !cpt.verify() ) {
                   return new CkeException('Google Captcha Failed');
             }

             List<CKE_Pack_Request__c> lisPr = [select id, Last_Name__c, First_Name__c, Email__c from Cke_Pack_Request__c where 
             									Email__c =: cmd.Email.toLowerCase() 
             									and Progress_Form_Id__c =: PROGRESS_CODE 	
             									];
			 Cke_Pack_Request__c item;       

             if ( !lisPr.isEmpty() ) {


             		for ( Cke_Pack_Request__c pr : lisPr ) {

             			if ( pr.Last_Name__c.equalsIgnoreCase(cmd.lastName) && 
 							 pr.First_Name__c.equalsIgnoreCase(cmd.firstName) )

             			item = pr;
             			break;

             		}
             
             }

             if ( item == null ) { 
    
             	item = buildRecord(cmd);
	            upsert item;		    

	         }      

             sendEmailConfirmation(item.Email__c, item.First_Name__c, 3);

		     System.debug('Item Id : ' + item.id);
		     cmd.id = item.id;
		     return cmd;

       }

       catch (Exception e) {
          return new SysRestError(e, 550); 
       }
    }
    
    @Future(callout=true)
    public static void sendEmailConfirmation(String email, String name, Integer d) {
    
        CkeMailClient client = new CkeMailClient();
        //client.sendPackConfirmationMail(email, name, d);
        client.sendRegisterInterestConfirmationMail(email, name);
    
    }
    public static Cke_Pack_Request__c buildRecord(Command cmd)
    {

        Cke_Pack_Request__c item;
        item = new Cke_Pack_Request__c();
        item.Email__c = cmd.email.toLowerCase();
        item.First_Name__c = cmd.firstName;
        item.Last_Name__c = cmd.lastName;
        //item.Optin_TermsConditions__c = true; 
        //item.Optin_Email__c = true;
        item.Progress_Form_Id__c = PROGRESS_CODE;
        item.Status__c = 'Completed';

        List<RecordType> lisRt= [select id from RecordType where DeveloperName = 'Register_Interest' and sObjectType = 'Cke_Pack_Request__c'];
        RecordType rt = lisRt[0];
        item.RecordTypeId = rt.id;

        item.Time_Submitted__c = DateTime.now();         
        if ( cmd.submitted == true ) { item.Status__c = 'Completed'; }

        return item;
    
    }
 
    global class Command 
    {
     
      	public String id { get;set; }
      	public Boolean submitted { get; set;}  
        public String email { get; set; }
        public String firstName { get; set; }
        public String lastName { get; set; }
        public String captchaResponse { get;set; }  

    }    


}