src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/objects/DCE_OrgAmend__c.object
<CustomObject>
    <description>This custom object is used to track changes that a Dementia Connect external partner would like to make to their Org details on the Dementia Connect website. We keep these changes on a separate object as it allows an approval process to be put in place and for locks, etc, to be implemented</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DCE_Amendment_Statuses</valueSetName>
        </valueSet>
    </fields>
    <label>DCE Partner Amendment</label>
    <nameField>
        <displayFormat>DCEP{0}</displayFormat>
        <label>DCE Partner Change or Amendment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCE Partner Amendments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DCE_RecordUpdateIssue__c.object
<CustomObject>
    <description>This object is used to hold the details of any issues that arise from an attempted update into the Dementia Connect database.</description>
    <fields>
        <fullName>DCEService__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>DCE Service Creation or Amendment</label>
        <referenceTo>DCE_ServiceAmend__c</referenceTo>
        <relationshipLabel>Record Amend Issues</relationshipLabel>
        <relationshipName>DCEAmendmentIssues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DCE_Partner_Amendment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Which is the Organisation amendment which has had the issue?</description>
        <label>DCE Partner Amendment</label>
        <referenceTo>DCE_OrgAmend__c</referenceTo>
        <relationshipLabel>DCE Record Amend Issues</relationshipLabel>
        <relationshipName>DCEAmendmentIssues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <description>Contains the details of any errors that may need resolving</description>
        <label>Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DCE Record Amend Issue</label>
    <nameField>
        <displayFormat>DCEIss{0}</displayFormat>
        <label>DCE Record Amend Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCE Record Amend Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DCE_ServiceAmend__c.object
<CustomObject>
    <description>Used within the Dementia Connect Extranet community to represent a new service (to be created within the Dementia Connect Database) or the amendment to an existing Service (to be updated within the Dementia Connect Database</description>
    <fields>
        <fullName>ServiceId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Stores the value of the Service ID in the production system.</description>
        <externalId>true</externalId>
        <label>Dementia Connect - Service Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Amendment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DCE_Amendment_Statuses</valueSetName>
        </valueSet>
    </fields>
    <label>DCE Service Creation or Amendment</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DCE Service Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DCE_RestCallout_Handler.cls
/*
*	Name		DCE_RestCallout_Handler
*	Author		Andy Rouse
*	Created		2016-02
*
*
*	Purpose		This class is called by other classes within the Dementia Connect Portal application when they need to send information to update Dementia Connect Live
*				
*
*
*/
public with sharing class DCE_RestCallout_Handler implements Queueable, Database.allowsCallouts{
    
    string postEndPointStem = Community_Settings__c.getInstance('DCE_RestEndpoint').value__c+'/services/apexrest/DCERecordAmend/';
    list<SObject> amends;
    map<string, string> fieldMappings;
    boolean updateStatus;
    
	/*Used to update a record in Dementia Connect Live from a source record in the portal*/
	public DCE_RestCallout_Handler(list<SObject> amends, map<string, string> fieldMappings){
    	
    	this.amends = amends;
    	this.fieldMappings = fieldMappings;
    	this.updateStatus = true;
	}
	
	/*Used to update a record - Does not update the source portal record status afterwards if given "False".*/
	public DCE_RestCallout_Handler(list<SObject> amends, map<string, string> fieldMappings, boolean updateStatus){
    	
    	this.amends = amends;
    	this.fieldMappings = fieldMappings;
    	this.updateStatus = updateStatus;
	}
    
	public void execute(QueueableContext context) {
    	
    	list<DCE_RecordUpdateIssue__c> issues = new list<DCE_RecordUpdateIssue__c>();
    	list<SObject> recordsToUpdate = new list<SObject>();
    	
    	for(SObject amend : amends){
    		
    		DCE_RestConnector callout;
    		
    		ID amendId = amend.id;
    		Schema.SObjectType amendType = amendId.getSObjectType();
    		
    		try{
    			callout = new DCE_RestConnector(postEndPointStem, 'POST', amend, fieldMappings);
    		} catch (exception e) {
				
				DCE_RecordUpdateIssue__c newIssue = new DCE_RecordUpdateIssue__c(Details__c=e.getTypeName()+' - '+e.getMessage()+'\r\r'+e.getStackTraceString());
				newIssue.put(lookupFieldPopulator.get(amendType), amend.id);
				
				issues.add(newIssue);
    		}
    		
    		if(callout == null){ continue; }
    		
    		if(callout.restError){
    			
				DCE_RecordUpdateIssue__c newIssue = new DCE_RecordUpdateIssue__c(Details__c=callout.res.getBody(), StatusCode__c=callout.res.getStatusCode());
				newIssue.put(lookupFieldPopulator.get(amendType), amend.id);
				
				issues.add(newIssue);
			} else {
				
				SObject castRecord = amendType.newSObject(amendId);
				
				if(updateStatus){
					castRecord.put('status__c','Accepted - Transfer Complete');
				}
				
				// This code links updates the "ServiceId__c" field on the record in the portal with the live id from Dementia Connect, to "sew" the two records together
				if(amendType == Schema.DCE_ServiceAmend__c.SObjectType){
					
					system.debug('Here is the body to be put into ServiceId__c - '+callout.res.getBody());
					map<string, Object> deserializeMap = (map<string, Object>)Json.deserializeUntyped(callout.res.getBody());
					
					string recordId = (string)deserializeMap.get('RecordId');
					
					castRecord.put(DCE_ServiceAmend__c.ServiceId__c,recordId);
				}
				
				recordsToUpdate.add(castRecord);
			}
		}
    	
    	if(recordsToUpdate.size() > 0){
    		
    		list<Database.SaveResult> srList = Database.Update(recordsToUpdate, false);
    		
    		for(integer i = 0 ; i < srList.size() ; i++){
    			
    			Database.SaveResult sr = srList[i];
    			
    			if(sr.isSuccess()){ continue; }
    			
    			SObject amend = recordsToUpdate[i];
    			Schema.SObjectType amendType = amend.getSObjectType();
    			
    			
    			for(Database.Error err : sr.getErrors()){
    				
    				string fieldsAffected = '';
    				
    				for(string s : err.getFields()){
    					fieldsAffected += s+'; ';
    				}
    				
    				DCE_RecordUpdateIssue__c newIssue = new DCE_RecordUpdateIssue__c(Details__c=err.getStatusCode()+' - '+err.getMessage()+'\r\rFields Affected: '+fieldsAffected);
					newIssue.put(lookupFieldPopulator.get(amendType), amend.id);
					
					issues.add(newIssue);
    			}
    		}
    	}
    	
    	if(issues.size() > 0){
    		try{
				insert issues;
			} catch (exception e){
				system.debug('Well......Damn. My exception handling failed.');
			}
    	}
    }
    
    
    //The "DCE Record Amend Issue" SObject has 2 lookups on it. One to Service Amendments and one to Partner Org amendments. This mapping tells the code at run-time which
    //one of those 2 fields to populate, based upon the record being amended
    private map<Schema.SObjectType, Schema.SObjectField> lookupFieldPopulator{
    	get{
    		if(lookupFieldPopulator != null){ return lookupFieldPopulator; }
    		
    		lookupFieldPopulator = new map<Schema.SObjectType, Schema.SObjectField>();
    		
    		lookupFieldPopulator.put(Schema.DCE_ServiceAmend__c.SObjectType, DCE_RecordUpdateIssue__c.DCEService__c);
    		lookupFieldPopulator.put(Schema.DCE_OrgAmend__c.SObjectType, DCE_RecordUpdateIssue__c.DCE_Partner_Amendment__c);
    		
    		return lookupFieldPopulator;
    	}
    	
    	private set;
    }
    
}