src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/objects/DCE_ServiceAmend__c.object
<CustomObject>
    <description>Used within the Dementia Connect Extranet community to represent a new service (to be created within the Dementia Connect Database) or the amendment to an existing Service (to be updated within the Dementia Connect Database</description>
    <fields>
        <fullName>DCEPartner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dementia Connect External Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ServiceChanges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastReviewed__c</fullName>
        <description>This field contains the date of last reviewed</description>
        <label>Last Reviewed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PortalServiceNumber__c</fullName>
        <displayFormat>{00000}</displayFormat>
        <label>Portal Service Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ServiceId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Stores the value of the Service ID in the production system.</description>
        <externalId>true</externalId>
        <label>Dementia Connect - Service Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ServiceOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Holds the Service Owner - We do not use the actual owner field as that can only be updated by the actual owner or an admin, etc.</description>
        <inlineHelpText>We will contact you to request an update to the information you have submitted and to send you updates about the service from time to time.</inlineHelpText>
        <label>Service Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>service_status__c</fullName>
        <description>Defines the status of the service in Dementia Connect</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DCE Service Creation or Amendment</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DCE Service Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DCE_EmailServiceDigest_Controller.cls
/******************************************************************************************
 *  Alzheimers
 *  
 *  Purpose : This class is used on a Visualforce email template which gets sent to DCE Users. It returns a table of services which need reviewing. The services are grouped by month of last reviewed date (hence the "amendMap")
 *            
 *  Author  : Andy Rouse
 *  Date    : 02-2016
 *  Version : 1.0
 *
 *  Description:
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
public with sharing class DCE_EmailServiceDigest_Controller {
    public id recipientId{get; set;}
    
    private User u{
        get{
            if(u != null){ return u;}
            
            if(recipientId == null){return new User();}
            
            u = [select id, firstName, LastName, AccountId, ContactId, Contact.AccountId, Contact.Account.Name //Account.Name, 
                    from User
                    where id = :recipientId];
            
            return u;
        }
        set;
    }
    
    private list<DCE_ServiceAmend__c> allAmends{
        private get{
            if(allAmends != null){ return allAmends;}
            
            if(recipientId == null){return new list<DCE_ServiceAmend__c>();}
            
            allAmends = [select id, Name, ServiceOwner__c, DCEPartner__c, ServiceOwner__r.Name, LastReviewed__c, ServiceId__c,PortalServiceNumber__c 
                            from DCE_ServiceAmend__c 
                            where DCEPartner__c = :u.Contact.AccountId and service_status__c = 'Open' and (LastReviewed__c = null or (LastReviewed__c < LAST_N_MONTHS:9 and LastReviewed__c >= LAST_N_MONTHS:15))
                            order by LastReviewed__c asc nulls first];
            
            if(allAmends.size() == 0 ){allAmends = new list<DCE_ServiceAmend__c>();}
            
            return allAmends;
        } 
        
        private set;
        
    }
    
    /*Returns a map of services due review, keyed by the last reviewed month.*/
    public map<Date, list<amendWrapper>> amendMap{
        public get{
            if(amendMap != null){ return amendMap;}
            
            amendMap = new map<Date, list<amendWrapper>>();
            
            for(DCE_ServiceAmend__c amend : allAmends){
                
                date lastReviewed = date.newInstance(1900,1,1);
                
                if(amend.lastReviewed__c != null){
                    /*
                    DateTime lastReviewdt = datetime.newInstance(amend.lastReviewed__c.year(), amend.lastReviewed__c.month(),amend.lastReviewed__c.day());
                    lastReviewed = lastReviewdt.format('MMMMM yyyy');*/
                    lastReviewed = amend.lastReviewed__c.toStartOfMonth();
                }
                
                list<amendWrapper> monthAmends = new list<amendWrapper>();
                
                if(amendMap.containsKey(lastReviewed)){monthAmends = amendMap.get(lastReviewed);}
                
                monthAmends.add(new amendWrapper(amend));
                amendMap.put(lastReviewed, monthAmends);
                
            }
            
            return amendMap;
        }
        
        private set;
    }
    
    public list<Date> orderedDates{
        
        public get{
            if(orderedDates != null){ return orderedDates;}
            
            orderedDates = new list<Date>(amendMap.keySet());
            
            orderedDates.sort();
            
            return orderedDates;
        }
        
        private set;
    }
    
    public boolean getShowTable(){
        boolean showTable = false;
        
        if(amendMap.size() > 0){
            showTable = true;
        }
        
        return showTable;
    }
    
    public class amendWrapper{
        public DCE_ServiceAmend__c amend {get; set;}
        public string link {get; set;}
        
        public amendWrapper(DCE_ServiceAmend__c amend){
            this.amend = amend;
            
            this.link = Community_Settings__c.getInstance('DCE_Stub_Url').value__c+'ServiceView/'+amend.PortalServiceNumber__c;
        }
    }
}