src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Push_Notifications__c.object
<CustomObject>
    <fields>
        <fullName>Button_link__c</fullName>
        <label>Button link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Button_title__c</fullName>
        <label>Button title</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Push Notifications</relationshipLabel>
        <relationshipName>Push_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Unread</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Push Notification</label>
    <nameField>
        <displayFormat>PN{000000}</displayFormat>
        <label>Push Notifications Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunityUtils.cls
/*
* Class with certain utility methods for Salesforce communities
*/
public class CommunityUtils {
    
    public class CommunityUtilsException extends Exception {}
    
    public static Map<String,String> getEnvironmentDomains() {
        
        Map<String, String> domainMap = new Map<string, String>();
        // Get the Dementia Friends communtiy base URL
        Network[] network = [SELECT Id, Name, UrlPathPrefix 
                             FROM Network 
                             WHERE Name ='Dementia Friends'];
        System.debug(network);
        
        Domain[] domains = [SELECT Domain, DomainType FROM Domain];
        System.debug(domains);
        
        for(Domain d : domains) {
            if(d.Id == network[0].Id) {
                System.debug('Selecting Community URL as: ' + d.Domain);
                domainMap.put('communityDomain', d.Domain);
            }
        }
        
        // Get the internal domain
        String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        domainMap.put('internalDomain', baseUrl);
        System.debug('baseUrl =' + baseUrl);
        
        System.debug('Returning map: ' + domainMap);
        
        return domainMap;
        
    }
    
    /*
     * Info sessions must have hte session organiser field populated.
     * This is set to a placeholder contact until a champion signs up to the session
    */
    public static Id getDfCommunityPlaceholderContactId() {
        
        Id dfContactId = null;
        Community_Settings__c[] setting = [SELECT Value__c 
                                           FROM Community_Settings__c 
                                           WHERE Name = 'DF_Placeholder_InfoSessionOrganiser'];
        
        if(setting.size() != 1) {
            throw new CommunityUtilsException('Please set the DF_Placeholder_InfoSessionOrganiser ' + 
                                              'setting to the Community Settings custom setting');
        } else {
            dfContactId = setting[0].Value__c;
        }
        
        return dfContactId;
        
    }
    
    public static Boolean createCommunityUserAndSendWelcomeEmail(Id dfContactId, String password) {
        
        try {
            string var = '?cp=true';
            string startUrl='/change-password'+var;
            string templateName ='Custom_Verification_Request';
            WEBC_CommunityWrapper community = new WEBC_CommunityWrapper('DF');                 
            Contact contact=  DF_Utils.getContactRecordForDfcId(dfContactId);  
            community.sendVerificationRequest(contact, password, startUrl, templateName);
            
            return true;
        } catch(Exception e) {
            
            return false;
        }
        
    } 
	
    public static String getInternalSalesforceUrl() {
        
        String instanceInternalUrl = null;
        Organization orgDetails = [SELECT Name, InstanceName, NamespacePrefix, IsSandbox FROM Organization];
    
        if(orgDetails.IsSandbox) {
            
            System.debug('Determinging Sandbox name: ' + URL.getSalesforceBaseUrl().getHost());
            String sandboxName = URL.getSalesforceBaseUrl().getHost().substringBetween('--','.');
            
            if(sandboxName == null) {
                sandboxName = URL.getSalesforceBaseUrl().getHost().substringBefore('-');
            }
            
            if(sandboxName == null) {
                throw new CommunityUtilsException('Could not determine the internal URL from the CommunityUtils class method');
            }
            instanceInternalUrl = 'alzheimerscommunities--' + sandboxName + '.' + orgDetails.InstanceName + '.my.salesforce.com';
        
        } else {
            instanceInternalUrl = 'alzheimerscommunities.' + orgDetails.InstanceName + '.my.salesforce.com';
        }
    
        return instanceInternalUrl;    
    }
    
    /*public static void setPageLoadModalNotification(Id champDfContactId, Integer noEventsInChampRadius) {
        
        String TITLE = 'There are info sessions in your area';
        String MESSAGE = 'There are info sessions without an assigned champion within your search radius';
        
        Push_Notifications__c[] existingInfoSessionModal = [SELECT Id 
                                                            FROM Push_Notifications__c
                                                            WHERE Title__c = :TITLE];
        
        / Create the push notification to be presented to the user on next page load in
        if(noEventsInChampRadius > 0) {
        pn= new Push_Notifications__c();
        
        pn.Message__c = MESSAGE;
        pn.DF_Contact__c=champDfContactId;
        pn.Status__c = 'Unread'; // Should pop up every time
        pn.Title__c = TITLE;
        pn.Button_title__c = BTN_TITEL;
        pn.Button_link__c = btnLink;
    }*/
}