src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CommunityUtils_Test.cls
@isTest
private class CommunityUtils_Test {
      
    static testMethod void getEnvironmentDomains_positive() {
        
        CommunityUtils.getEnvironmentDomains();
        
    }
    
    static testmethod void getDfCommunityPlaceholderContactId_positive() {
        
        Id rtId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Dementia_Friend_Champion' AND SObjectType = 'DF_Contact__c'].Id;
        
        DF_Contact__c defaultOrganiser = new DF_Contact__c();
        defaultOrganiser.RecordTypeId = rtId;
        defaultOrganiser.First_Name__c ='test3';
        defaultOrganiser.Last_Name__c = 'test3';
        defaultOrganiser.Title__c = 'Mr';
        defaultOrganiser.Name='test'+' ' +'test';
        defaultOrganiser.Contact_Number__c = '02011180935';
        defaultOrganiser.Email__c = 'tobeconfirmed@mailinator.com';
        defaultOrganiser.Postcode__c = 'TS1 3TN';
        defaultOrganiser.Street__c = 'test street';
        defaultOrganiser.City__c = 'test';
        defaultOrganiser.County__c = 'test county';
        defaultOrganiser.Country__c = 'test country';
        insert defaultOrganiser;
        
        Community_Settings__c cs=new Community_Settings__c();
        cs.name='DF_Placeholder_InfoSessionOrganiser';
        cs.value__c= [SELECT Id FROM DF_Contact__c WHERE Email__c = 'tobeconfirmed@mailinator.com'].Id;
        insert cs;
        
        CommunityUtils.getDfCommunityPlaceholderContactId();
        
    }
    
    static testmethod void getInternalSalesforceUrl_positive() {
        CommunityUtils.getInternalSalesforceUrl();
    }

}