src/objects/Community_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Values for the Communities</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>A generic string value</description>
        <label>Value</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

src/objects/Edt_Item__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text1__c</fullName>
        <inlineHelpText>Enter the text that you want to appear on the page in this field</inlineHelpText>
        <label>Text1</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Editable Item</label>
    <nameField>
        <displayFormat>EDT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Editable Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CkePackRequestController_Test.cls
@isTest
public class CkePackRequestController_Test {

    Public static CkePackRequestController.Command getData() {
        
        Community_Settings__c progressIdSetting = new Community_Settings__c(Name = 'CKE_Pack_Progress_Id', Value__c = 'testProgressId');
        insert progressIdSetting;

        CkePackRequestController.Command cmd = new CkePackRequestController.Command();
        cmd.title = 'Mr';
        cmd.firstName = 'Test';
        cmd.lastName = 'Test';
        cmd.email = 'Test@test.com';

        cmd.city = 'test';
        cmd.county = 'test';
        cmd.addressLine1 = 'test';
        cmd.postcode = 'SW3 1PE';
        cmd.optinEmail = true;
        cmd.optinPhone = true;
        cmd.optinSMS = true;
        cmd.optinTC = true;
        cmd.optoutPost = true;
        cmd.optinSocial = true;
        cmd.phone = '07777777777';
        cmd.dob = '2000-04-23T18:25:43.511Z';
        cmd.captchaResponse = 'xxxx';
        cmd.submitted = true;

        return cmd;

    }

    // Successful save and Submit
    @isTest
    static void itShould()
    {        
        Edt_Item__c ei1 = new Edt_Item__c(Group__c='gdpr', Key__c='contact-preferences',Text1__c='test');
        insert ei1;
        Edt_Item__c ei2 = new Edt_Item__c(Group__c='gdpr', Key__c='connection-to-dementia',Text1__c='test');
        insert ei2;
        Edt_Item__c ei3 = new Edt_Item__c(Group__c='gdpr', Key__c='company',Text1__c='test');
        insert ei3;
        
        Community_Settings__c cs1 = new Community_Settings__c(Name='CKE_Pack_Progress_Id', Value__c='asdfasdf');
        insert cs1;
        Community_Settings__c cs2 = new Community_Settings__c(Name='Cke_Captcha_Site', Value__c='asdfasdf');
        insert cs2;
        Community_Settings__c cs3 = new Community_Settings__c(Name='Cke_Captcha_Secret', Value__c='asdfasdf');
        insert cs3;
        CkePackRequestController prc = new CkePackRequestController();
        
        /*CkePackRequestController prc = new CkePackRequestController();
        prc.companyTooltip = '1';
        prc.proximityTooltip = '1';
        prc.preferencesTooltip = '1';*/

        Test.setMock(HttpCalloutMock.class, new CkeMailClientMockHttp_Test());
        CkePackRequestController.Command cmd = getData();
        CkePackRequestController.processSubmit(cmd);

    }

}