src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Employees__c</fullName>
        <label>Number of Employees</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-250</fullName>
                </value>
                <value>
                    <fullName>251-1000</fullName>
                </value>
                <value>
                    <fullName>1001-5000</fullName>
                </value>
                <value>
                    <fullName>5001-20000</fullName>
                </value>
                <value>
                    <fullName>20001+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector_other__c</fullName>
        <label>Sector - other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friends_Website</fullName>
        <active>true</active>
        <businessProcess>Dementia Friends Lead Process</businessProcess>
        <label>Dementia Friends Website</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Employees__c</fullName>
        <label>Number of Employees</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-250</fullName>
                </value>
                <value>
                    <fullName>251-1000</fullName>
                </value>
                <value>
                    <fullName>1001-5000</fullName>
                </value>
                <value>
                    <fullName>5001-20000</fullName>
                </value>
                <value>
                    <fullName>20001+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>update to picklist values must update DF_WEBC_RegisterOrg component selectlist values and partner resources-category field</description>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector_other__c</fullName>
        <label>Sector - other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_RegisterPartner_Controller.cls
/******************************************************************************************
 *  Alzheimers
 *  
 *  Purpose : APEX controller class for VF Page DF_WEBC_RegisterPartner
 *  Author  : Lakshmi Vasudevan
 *  Date    : 26/04/2016
 *  Version : 1.0
 *
 *  Description:    Apex Class controller for the DF_WEBC_RegisterPartner_Controller class.
 *                  Provides functionality for users to register a DF Organisation

                    There is no submit on this action. The submit is handled by 
                    js methods in the page to various services
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
global without sharing class DF_WEBC_RegisterPartner_Controller extends DF_WEBC_ControllerBase {
    
    public Boolean isChampion {get;set;}
    public Boolean isChampionConverted {get;set;}
    public String orgName{get;set;}   
    public String sector{get;set;}
    public String sectorOther{get;set;}
    public String employees {get;set;}
    
    public String orgPostCode {get;set;}
    public String orgStreet {get;set;}
    public String orgcity {get;set;}
    public String orgCounty {get;set;}
    public String orgCountry {get;set;}
    public String orgTelephone {get;set;}
    public string orgNameError {get;set;}
    public string employeesError {get;set;}
    public string orgCountryError {get;set;}
    public string orgPostCodeError {get;set;}
    public string orgStreetError {get;set;}
    public string orgCityError {get;set;}
    public string orgCountyError {get;set;}
    public string orgTelephoneError {get;set;}
    public Boolean isError = FALSE;
    public string friendoptionsselect {get;set;}
    public string LEAD_RT = 'Dementia_Friends_Website';
    
    public User thisUser {
        get {
            return WEBController.thisUser;
        }
        set;
    }
    
    //Constructor
    public DF_WEBC_RegisterPartner_Controller() {
    	currentDfc = DF_Utils.getDFContactForUser(UserInfo.getUserId());            
        dfcW = new DF_Contact_Wrapper(currentDfc);
        orgNameError ='';
		employeesError='';
		orgCountryError='';
		orgPostCodeError='';
		orgStreetError='';
		orgCityError='';
		orgCountyError='';
		orgTelephoneError='';
           
        isChampion = WEBConversionClass.isChampion(thisUser.ContactId);
        isChampionConverted = DF_Utils.isChampionConverted(currentDfc);    
    
    }

    @RemoteAction
    global static boolean isExistingOrg(String orgName) {

        List<Partner_Organisation__c> lisOrg = [select id from Partner_Organisation__c where name = :orgName];
        return (!lisOrg.isEmpty());

    }
    
    public PageReference register() {
    	
   
     Contact contact = DF_Utils.getContactRecordForDfcId(currentDfc.Id); 
     list<Group> DFQueue = [select id, Name from Group where DeveloperName = 'DF_Website_Admins' and Type = 'Queue'];
     if (contact==null) { return null;}
     system.debug( 'ORGANISATION NAME '+orgName + employees);
     if ( currentDfc== null ){return null;}
     
      // only one lead record can linked with dfcontact 
      Lead ld = new Lead();
     /* List<Lead > lis = [select contact__c,Email, df_contact__c,Phone,RecordTypeId,LeadSource,Number_of_employees__c,Sector__c,Sector_other__c,lastname,Company ,Street,State,City,
                          Country ,PostalCode  from Lead 
                                                where   Contact__c =: contact.id                                               
                                                and df_contact__c =: currentDfc.id
                                                and IsConverted = false
                                                limit 1 ];
      
      if ( !lis.isEmpty() ) { ld =lis[0];}*/
      
            if(DFQueue.size() > 0){ 
    
    		ld.ownerId = DFQueue[0].id; 
    
    		} else {
    
   			 ld.ownerId = [select id from User where isActive = true and Profile.Name = 'System Administrator' limit 1].id;
    		}
            ld.contact__c = contact.id;
            ld.df_contact__c = currentDfc.id; 
            ld.Company = orgName; 
            ld.LastName = contact.LastName;  
            ld.FirstName= contact.FirstName;     
            ld.Email = contact.Email;      
            ld.Street = orgStreet;
            ld.Phone = orgTelephone;
            ld.State = orgCounty;
            ld.City = orgCity;
            ld.Country = orgCountry;
            ld.PostalCode = orgPostCode;
            ld.Number_of_employees__c = employees;
            ld.Sector__c = sector;
            ld.Sector_other__c = sectorOther;
            ld.RecordTypeId = DF_Utils.getsObjectRecordTypeId('Lead',LEAD_RT);
            ld.LeadSource='Web';
            
          insert ld;
        
       return new PageReference('/user-home?org-registered=true');
     
    } 
    
    public pageReference cancel(){
    	
    return new PageReference('/user-home');
    }

}