src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_SandboxEmailDisable_Batcher.cls
global class DF_SandboxEmailDisable_Batcher implements Database.Batchable<sObject> {
    
    String query;
    Integer i;
    
    global DF_SandboxEmailDisable_Batcher() {
    
        query = 'select id, email__c from DF_Contact__c where not Email__c like \'%.uat\'';
        i = 0;

    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
    

        List<DF_Contact__c> lis = new List<DF_Contact__c>();

        for (Object o : scope) {

            DF_Contact__c dfc = (DF_Contact__c)o;

            if ( dfc.Email__c.length() < 76 ) {

	            if (!dfc.Email__c.endsWith('.uat')) {

	                dfc.Email__c = dfc.Email__c + '.uat';
	                lis.add(dfc);
	                i++;
	            }

        	}

        }

        update lis;

    }
    
    global void finish(Database.BatchableContext BC) {

        system.debug('DF Contact Email Disabler updated : ' + i);
        
    }
    
}