src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <label>Event End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Friends Logged</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Total session audience capacity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Contact__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dementia Friend Champion</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Champions Induction</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WEBChampionContactDetailsClass.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Component WEBChampionContactDetails.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class controller for the VF Component WEBChampionDetails
 *               
 *  Modification History
 *  Date            Who         Description 
                   
*******************************************************************************************/
public without sharing class WEBChampionContactDetailsClass extends DF_WEBC_ControllerBase{

    public final String EMPTY_FIELD_VALUE_MSG = 'Value is required and can\'t be empty';
    public static final String REQUIRED_FIELD_MSG_END = ' is required';

    public Datetime courseDate{get;set;}
    public Datetime courseEndDate{get;set;}
    public String courseDetails{get;set;}
    public String courseStreet{get;set;}
    public String courseCity{get;set;}
    public String courseCounty{get;set;}
    public String courseCountry{get;set;}
    public String coursePostcode{get;set;}
    public String firstName{get;set;}
    public String lastName{get;set;}
    public String address1{get;set;}
    public String address2{get;set;}
    public String town_City{get;set;}
    public String county{get;set;}
    public String postCode{get;set;}
    public String EventId{get;set;}

    public List<DF_Contact__c> contacts {get;set;}
    public List<DF_Event__c> events {get;set;}
    public DF_Event__c courseObj {get;set;}
    
    public Boolean displayThankyoupage{get;set;}
    public Boolean displayFormPage{get;set;}

    public Boolean isError {get; set;}
    public String firstNameError {get; set;}
    public String lastNameError {get; set;}
    public String address1Error {get; set;}
    public String townCityError {get; set;}
    public String countyError {get; set;}
    public String postCodeError {get; set;}
    
    public User thisUser {
        get {
            return WEBController.thisUser;
        }
        set;
    }

    //Constructor
    public WEBChampionContactDetailsClass(){
        EventId = ApexPages.currentPage().getParameters().get('event');
        displayThankyoupage = false;
        displayFormPage = true;
        if (EventId != null){
            getEventInformation();
        }
        getContactInformation();

        isError = false;
        firstNameError = null;
        lastNameError = null;
        address1Error = null;
        townCityError = null;
        countyError = null;
        postCodeError = null;
        
    }
    
    private String buildErrorMsgTxt(String field) {
        return field + REQUIRED_FIELD_MSG_END;
    }
    
    
    //Returns the event information for the selected event
    public void getEventInformation(){
        events = new List<DF_Event__c>();
        events = [SELECT Id, Event_Date_Time__c, Event_End_Date_Time__c, Street__c, Postcode__c, City__c, Country__c, County__c, Location__c, Number_of_Attendees__c, Number_of_Places__c 
                  FROM DF_Event__c 
                  WHERE Id=:EventId LIMIT 1];
        
        if (events.size() > 0){
            for (DF_Event__c dfevents:events){
                courseDetails = dfevents.Location__c;
                courseDate = dfevents.Event_Date_Time__c;
                courseEndDate = dfevents.Event_End_Date_Time__c;
                courseStreet = dfevents.Street__c;
                courseCity = dfevents.City__c;
                courseCounty = dfevents.County__c;
                courseCountry = dfevents.Country__c;
                coursePostcode = dfevents.Postcode__c;
                // Save the object for field output on VF component
                courseObj = dfevents;
            }
        }
    }
    
    //Returns contact information for the logged in contact
    public void getContactInformation() {
        contacts = new List<DF_Contact__c>();
        contacts = [SELECT Id, First_Name__c,Last_Name__c,Street__c,City__c,Country__c,County__c,Postcode__c,Portal_Contact__r.Id FROM DF_Contact__c WHERE Portal_Contact__r.Id = :WEBController.thisUser.ContactId LIMIT 1];
        
        if (contacts.size() > 0){
            for (DF_Contact__c dfcontact:contacts){
                firstName = dfcontact.First_Name__c;
                lastName = dfcontact.Last_Name__c;
                address1 = dfcontact.Street__c;
                //address2 = dfcontact.Street__c;
                town_City = dfcontact.City__c;
                county = dfcontact.County__c;
                postCode = dfcontact.Postcode__c;
            }
        }
    }

    //Submits the event booking form
    public PageReference submitForm() {
        isError = false;
        firstNameError = null;
        lastNameError = null;
        address1Error = null;
        townCityError = null;
        countyError = null;
        postCodeError = null;

        DF_Event__c selectedEvent = events[0];
        if (contacts.size() > 0) {
            for (DF_Contact__c dfcontact : contacts){

                if (String.isBlank(firstName)) {
                    isError = true;
                    firstNameError = buildErrorMsgTxt('First Name');
                }

                if (String.isBlank(lastName)) {
                    isError = true;
                    lastNameError = buildErrorMsgTxt('Last Name');
                }

                if (String.isBlank(address1)) {
                    isError = true;
                    address1Error = buildErrorMsgTxt('Address');
                }

                if (String.isBlank(town_City)) {
                    isError = true;
                    townCityError = buildErrorMsgTxt('Town or City');
                }

                if (String.isBlank(county) && String.isBlank(town_City)) {
                    isError = true;
                    countyError = buildErrorMsgTxt('County');
                }

                if (String.isBlank(postCode)) {
                    isError = true;
                    postCodeError = buildErrorMsgTxt('Postcode');
                }

                if (isError) {
                    return null;
                }

                 dfcontact.First_Name__c = firstName;
                 dfcontact.Last_Name__c = lastName;
                 dfcontact.Street__c = address1;
                 //dfcontact.Street__c = address2;
                 dfcontact.City__c = town_City;
                 dfcontact.County__c = county;
                 dfcontact.Postcode__c = postCode;
            }   
            try {
                update contacts;
            }   
            catch(System.DmlException e) {
                system.debug('We have found an DML Exception please check the following error : '+e);
            }
            
            //Now we need to create the Event Attendee record
             DF_EventAttendee__c attendanceRecord = new DF_EventAttendee__c();
            attendanceRecord.DF_Contact__c = contacts[0].Id;
            attendanceRecord.DF_Event__c = events[0].Id;
            
            system.debug('*** -- Insert record -- ***');
            
            insert attendanceRecord;
            
            /* Alz - 27/01/2015 This code is not required. Numbers are tracked with Roll up Summary fields 
            
            if (selectedEvent.Number_of_Attendees__c == null){
                selectedEvent.Number_of_Attendees__c = 0;
            }
            
            if (selectedEvent.Number_of_Attendees__c == selectedEvent.Number_of_Places__c){
                //Do we want to save this record?
                
            }else if (selectedEvent.Number_of_Attendees__c < selectedEvent.Number_of_Places__c){
                selectedEvent.Number_of_Attendees__c = selectedEvent.Number_of_Attendees__c + 1;    
            }
                       
            
            update selectedEvent;
            */
            
        }
        displayThankyoupage = true;
        displayFormPage = false;
        //google tracking QP-7
        return new PageReference('/user-home?champion_induction_session_booked=true');
    }

}