src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Code_Verefied__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Champion Code has been entered</description>
        <label>Champion Code Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Employees__c</fullName>
        <label>Number of Employees</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-250</fullName>
                </value>
                <value>
                    <fullName>251-1000</fullName>
                </value>
                <value>
                    <fullName>1001-5000</fullName>
                </value>
                <value>
                    <fullName>5001-20000</fullName>
                </value>
                <value>
                    <fullName>20001+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_code__c</fullName>
        <label>Partner code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector_other__c</fullName>
        <label>Sector - other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friends_Website</fullName>
        <active>true</active>
        <businessProcess>Dementia Friends Lead Process</businessProcess>
        <label>Dementia Friends Website</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Employees__c</fullName>
        <label>Number of Employees</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-250</fullName>
                </value>
                <value>
                    <fullName>251-1000</fullName>
                </value>
                <value>
                    <fullName>1001-5000</fullName>
                </value>
                <value>
                    <fullName>5001-20000</fullName>
                </value>
                <value>
                    <fullName>20001+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>update to picklist values must update DF_WEBC_RegisterOrg component selectlist values and partner resources-category field</description>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector_other__c</fullName>
        <label>Sector - other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_ContactWrapper_Test.cls
@isTest
private class DF_ContactWrapper_Test
{

  
    @isTest
    static void doTest1()
    {
        
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();     
        DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');  
                
        Test.startTest();
        DF_Contact_Wrapper dfcW = new DF_Contact_Wrapper(dfc);
        
        boolean b = dfcW.isSubscriber;
        b = dfcW.isChampion;
        b = dfcW.isChampionConverted;
        
        b = dfcW.isFriend;
        b = dfcW.isFriendConverted;

    }


    /* Confirm Friend */
    @isTest
    static void doTest2()
    {
        
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();     
        DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');  
        test.starttest();
        DF_Contact_Wrapper dfcW = new DF_Contact_Wrapper(dfc);

        String s = dfcW.confirmFriend('DEMENTIAFRIEND123'); 
        system.assertEquals(true, dfcW.isFriendConverted);

    }

    /* Confirm Friend Bad Code */
    @isTest
    static void doTest3()
    {
        
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();     
        DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');  

        test.starttest();
        DF_Contact_Wrapper dfcW = new DF_Contact_Wrapper(dfc);
              
        String s = dfcW.confirmFriend('XXX');   
        system.assertEquals(false, dfcW.isFriendConverted);

        s = dfcW.confirmFriend('');             
        system.assertEquals(false, dfcW.isFriendConverted);

    }

    /* Convert to Champion */
    @isTest
    static void doTest4()
    {
        
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();     
        DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');  

        DF_Contact_Wrapper dfcW = new DF_Contact_Wrapper(dfc);
        test.starttest();
        Boolean b = dfcW.convertToChampion();               
        system.assertEquals(true, dfcW.isChampion);

        b = dfcW.convertToFriend();
        system.assertEquals(true, dfcW.isFriend);       

    }


    /* Convert to Champion and Convert */
    @isTest
    static void doTest5()
    {
        
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();     
        DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');  
        Partner_Organisation__c part = (Partner_Organisation__c)mapTestData.get('partnerOrg');
                
        Test.startTest();
        DF_Contact_Wrapper dfcW = new DF_Contact_Wrapper(dfc);
        
        Boolean b = dfcW.convertToChampion();               
       // String s = dfcW.confirmChampion(part.DFC_Code__c);
        
        Boolean d = dfcw.isFriendProspective;
        dfc.Status__c =  DF_Utils.STATUS_CONVERTED ;
        Contact df=dfcw.Contact;
        User u = dfcw.User;
        boolean c = dfcw.isChampionActive;
        String e = dfcw.ChampionStatus;
        dfc.Code_verefied__c = true;
        update dfc;
        
       // system.assertEquals(true, dfcW.isChampionActive);

        dfcW.convertToFriend();
       // system.assertEquals(true, dfcW.isFriendConverted);

    }


    /* Convert to Champion and Convert bad code*/
    @isTest
    static void doTest6()
    {
        
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();     
        DF_Contact__c dfc2 = (DF_Contact__c)mapTestData.get('DFc2');  
        Lead lead=new Lead(
                      Company='Test',
                      df_contact__c = DFc2.id,  
                      LastName = 'test',  
                      FirstName= 'test',                              
                      Number_of_employees__c = '8',
                      Sector__c = 'Other',
                      Sector_other__c = 'Test',
                      RecordTypeId = DF_Utils.getsObjectRecordTypeId('Lead','Dementia_Friends_Website'),
                      LeadSource='Web',
                      status='Open' ,
                      partner_code__c = 'test55'
                      );
                      insert lead;
        
        Partner_Organisation__c part = (Partner_Organisation__c)mapTestData.get('partnerOrg');
        DF_Contact_Wrapper dfcW = new DF_Contact_Wrapper(dfc2);
        system.assertNotEquals(null,dfcw.orgLeads);
        test.starttest();
        Boolean b = dfcW.convertToChampion();
        
      
                
        //String s = dfcW.confirmChampion('dfc123');
        system.assertEquals(false, dfcW.isChampionConverted);

       // s = dfcW.confirmChampion('');
        system.assertEquals(false, dfcW.isChampionConverted);


    }
    
    

}