src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contacted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contacted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c &amp; &quot;,  &quot; &amp; First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Description__c</fullName>
        <label>Event Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <label>Event End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Total session audience capacity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Information Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/WEBChampionCreateEditSession_Test.cls
@isTest
 public class WEBChampionCreateEditSession_Test{

 static testmethod  void tesWEBChampionCreate() 
   {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        Profile p1 = [SELECT Id FROM profile WHERE name='DF HVCP'];
        
        Page_Snippet__c  pagesnipp=new Page_Snippet__c(name__c='sample',Body_Text__c='SampleText',Unique_Name__c='DementiaFriendsTotalSnippet');
        Insert  pagesnipp;
        Page_Snippet__c  pagesnipp1=new Page_Snippet__c(name__c='sample',Body_Text__c='SampleText2',Unique_Name__c='CreateSessionNameHelp');
        Insert  pagesnipp1;
        Page_Snippet__c  pagesnipp2=new Page_Snippet__c(name__c='sample',Body_Text__c='SampleText3',Unique_Name__c='CreateSessionDateHelp');
        Insert  pagesnipp2;
        Page_Snippet__c  pagesnipp3=new Page_Snippet__c(name__c='sample',Body_Text__c='SampleText4',Unique_Name__c='CreateSessionVisibleHelp');
        Insert  pagesnipp3;
        Page_Snippet__c  pagesnipp4=new Page_Snippet__c(name__c='sample',Body_Text__c='SampleText5',Unique_Name__c='CreateSessionStatusHelp');
        Insert  pagesnipp4;
        Page_Snippet__c  pagesnipp5=new Page_Snippet__c(name__c='sample',Body_Text__c='SampleText6',Unique_Name__c='CreateSessionPlacesHelp');
        Insert  pagesnipp5;
        Page_Snippet__c  pagesnipp6=new Page_Snippet__c(name__c='sample',Body_Text__c='SampleText7',Unique_Name__c='CreateSessionDescriptionHelp');
        Insert  pagesnipp6;
        
        Page_Snippet__c  pagesnipp7=new Page_Snippet__c(name__c='sample',Body_Text__c='SampleText8',Unique_Name__c='CreateSessionWheelchairHelp');
        Insert  pagesnipp7;
        
        
        
         Account acc=new  Account(Name='Acme');
        Insert acc;
        
        Contact c1 = new Contact(LastName='SampleContact');
        c1.accountId = acc.Id;
        c1.email = 'test12@gmail.com';
        c1.firstName = 'firstName';
        c1.lastName = 'lastName';
        insert(c1);
        
        
        RecordType rt = [select r.Id, r.DeveloperName from RecordType r where r.IsActive = true and r.SobjectType = 'DF_Event__c' and r.DeveloperName='Dementia_Friend_Awareness_Session'];
        
        
        RecordType rt12 = [select r.Id, r.DeveloperName from RecordType r where r.IsActive = true and r.SobjectType = 'DF_Contact__c' and Name='Dementia Friend'] ;
        
        RecordType rt13 = [select r.Id, r.DeveloperName from RecordType r where r.IsActive = true and r.SobjectType = 'DF_Contact__c' and Name='Dementia Friend Champion'] ;

        DF_Contact__c dfcon = new DF_Contact__c(Name='testname',First_Name__c='testfirsname',Last_Name__c='testlastname',Portal_Contact__c=c1.id,Recordtypeid=rt13.id, Email__c = 'test.testcontact@myemail.com');
        insert dfcon;
    
        DF_Event__c evnt = new DF_Event__c(Name='test12',Event_Description__c='test Description',Event_Status__c='Available',Event_Date_Time__c=system.now(),Event_End_Date_Time__c=system.now().addHours(2),Street__c='teststreet',City__c='testcity',County__c='uk',Postcode__c='12345678912',Number_of_Places__c=1234,Session_Organiser__c=dfcon.id); 
       
        insert evnt;
       
       /******************** Creating user for Webcontroller******************/
        User u1 = new User();
         u1.username =  'Advavabd@acmecorp.com';
         u1.email = 'Sampleemail@gmail.com';
         u1.lastName = 'lastName';
         u1.firstName = 'FirstName';
         String alias = 'advanchgi';
         //Alias must be 8 characters or less
         if(alias.length() > 8) {
            alias = alias.substring(0, 8);
         }
         u1.alias = alias;
         u1.languagelocalekey = 'en_US';
         u1.localesidkey = 'en_US';
         u1.emailEncodingKey = 'UTF-8';
         u1.timeZoneSidKey = 'America/Los_Angeles';
         u1.profileId = p1.Id;
         u1.contactId = c1.Id;
         insert u1;  
       
       /*******************************************************/
  
    
    
     
     DF_Contact__c dfcnt = new DF_Contact__c(Name='Testdfcontact12',First_Name__c='Test12',Last_Name__c='dfcontact12',Status__c='Prospective',Email__c='test12@dfcon.com',
     RecordTypeId=[Select Id from RecordType where SObjectType='DF_Contact__c' and Name Like 'Dementia Friend Champion'].Id,
                                            Contact_Number__c='12385678',Eligible__c=FALSE,Contacted__c=FALSE,
                                            Attended__c=FALSE,Note__c='Test Notes2'); 
     insert dfcnt;
      ApexPages.currentPage().getParameters().put('eventId', evnt.id);
     System.runAs(u1)
    {    
    
    Pagereference pr = page.WEBChampionCreateEditSession;
    WEBChampionCreateEditSession webch = new WEBChampionCreateEditSession();
    
     webch.totalFriendsSnippet=null;
     Page_Snippet__c pp=webch.totalFriendsSnippet;
     webch.createSessionNameHelp=null;
     Page_Snippet__c pp1=webch.createSessionNameHelp;
     webch.CreateSessionDateHelp=null;
     Page_Snippet__c pp2=webch.CreateSessionDateHelp;
     webch.CreateSessionVisibleHelp=null;
     Page_Snippet__c pp3=webch.CreateSessionVisibleHelp;
     webch.CreateSessionStatusHelp=null;
     Page_Snippet__c pp4=webch.CreateSessionStatusHelp;
     webch.CreateSessionPlacesHelp=null;
     Page_Snippet__c pp5=webch.CreateSessionPlacesHelp;
     webch.CreateSessionDescriptionHelp=null;
     Page_Snippet__c pp6=webch.CreateSessionDescriptionHelp;
     webch.CreateSessionWheelchairHelp=null;
     Page_Snippet__c pp7=webch.CreateSessionWheelchairHelp;
  
     
   //  webch.isSuccess = TRUE;
     webch.getEventStatusOptions();
     List<SelectOption> lis = webch.visibleOptions;
     lis = webch.getSessionTypeOptions();
     lis = webch.getFootballTeamOptions();
     lis = webch.getTimeHour();
     lis = webch.getTimeMinute();
     webch.saveSession();
    
     /*******/
     
     // evnt.Session_Organiser__c = dfcnt.id;
    //  update evnt;                                      
     
     PageReference pageRef = Page.WEBChampion;
      Test.setCurrentPage(pageref);
   }   
}
}