src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <recordTypes>
        <fullName>Registration</fullName>
        <active>true</active>
        <label>Registration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Created_As_Type__c</fullName>
        <description>What type of Friend was this contact originally created as</description>
        <label>Created As Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>Subscriber</fullName>
                </value>
                <value>
                    <fullName>Digital Friend</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Champion</fullName>
                </value>
                <value>
                    <fullName>Community Representative</fullName>
                </value>
                <value>
                    <fullName>Registration</fullName>
                </value>
                <value>
                    <fullName>DF Mailer</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Partner Organisation Admin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Digital_Friend_Signup_Time__c</fullName>
        <description>The date the DF Contact became a Digital Friend. This is the date the contact watched the video to 
4 mins and 10 seconds.</description>
        <inlineHelpText>When did the DF Contact watch the Video</inlineHelpText>
        <label>Digital Friend Signup Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <recordTypes>
        <fullName>Registration</fullName>
        <active>true</active>
        <label>Registration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WEBController.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : Main APEX class for all WEB* classes
 *            
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    THIS CLASS TO BE REMOVED WHEN ALL DEPENDENT CLASSES ARE UPDATED
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
    Superceded DF_WEBC_ControllerBase
    To be deleted when all dependenent classes have been updated. 

*******************************************************************************************/
global abstract class WEBController {
    
    public static final String pageId_PARAM = 'pageId';
    public static final String USER_TYPE_CHAMPION = 'Champion';
    public static final String USER_TYPE_FRIEND = 'Friend';
    public static final String RT_DFCONTACT_CHAMPION = 'Dementia_Friend_Champion';
    public static final String RT_DFCONTACT_FRIEND = 'Dementia_Friend';
    
    public static String pageId {
        get {
            return ApexPages.currentPage().getParameters().get(pageId_PARAM);
        }
    }

    public static final String showPreview_PARAM = 'preview';
    public static Boolean showPreview {
        get {
            Boolean showPreview = false;

            if (ApexPages.currentPage().getParameters().get(showPreview_PARAM) != null
                && ApexPages.currentPage().getParameters().get(showPreview_PARAM).equalsIgnoreCase('true')) {

                showPreview = true;
            }

            return showPreview;
        }
    }

    public Boolean showCookiePolicy {
        get {
            if (showCookiePolicy == null) {
                showCookiePolicy = true;
            }

            return showCookiePolicy;
        }
        private set;
    }

    public static Boolean isLoggedIn {
        get {
            system.debug('Controller Base: User Type' + UserInfo.getUserType());
            return (UserInfo.getUserType() == 'Guest' ? false : true);
        }
    }

    public static Boolean isChampion {
        get { 

            if (thisUser != null && thisUser.contactId != null)
                return WEBConversionClass.isChampion(thisUser.contactId);

            return FALSE;
        }
    }
    
    public static Boolean isChampionConverted {
        get {
            if (thisUser != null && thisUser.contactId != null)
                return WEBConversionClass.isChampionConverted(thisUser.contactId);
            
            return false;
        }
    }

    public static Boolean userAlreadyExists {
        get {
            if (userAlreadyExists == null){
                userAlreadyExists = false;
            }
            return userAlreadyExists;
        }
        set;
    }

    public static User thisUser {
        get {
            if (thisUser == null
                    && isLoggedIn) {

                thisUser = [SELECT Id, Email, Username, AccountId, ContactId, firstName, lastName, title, CommunityNickname
                                FROM User
                                WHERE Id = :UserInfo.getUserId()];

            }

            return thisUser;
        }
        private set;
    }

    public static Id userAccountId {
        get {
            return (thisUser == null ? null : thisUser.AccountId);
        }
    }

    public DF_Contact__c dfContact {get; set;}

    private static final String XUACompatible_PARAM = 'X-UA-Compatible';
    private static final String XUACompatible_VALUE = 'IE=edge';
   
    //Constructor
    public WEBController() {
  
        isChampion = false;
        system.debug('*** -- Into WEBController constructor -- ***');
  
        ApexPages.currentPage().getHeaders().put(XUACompatible_PARAM, XUACompatible_VALUE);

        Cookie cookiePolicyAcceptance = ApexPages.currentPage().getCookies().get('cookiePolicyAcceptance');

        if (cookiePolicyAcceptance == null) {

            showCookiePolicy = true;

            List<Cookie> cookies = new List<Cookie>();
            cookies.add(new Cookie('cookiePolicyAcceptance', 'true', null, 15552000, false));

            ApexPages.currentPage().setCookies(cookies);
     
        } else {
     
            showCookiePolicy = false;
     
        }

        system.debug('Web Controller Constructor - cookie done');
        
        //2014-04-03 : SM : We also need to return the DF_Contact__c record
        if (test.isRunningTest()){

            DF_Contact__c dfContactRecord = new DF_Contact__c();
            dfContactRecord.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :RT_DFCONTACT_CHAMPION and r.SObjectType = 'DF_Contact__c' LIMIT 1].Id;
            dfContactRecord.First_Name__c = 'Test';
            dfContactRecord.Last_Name__c = 'Contact';
            dfContactRecord.Email__c = 'test.contact@myemail.com';
            
            isChampion = true;
            
            dfContact = dfContactRecord;
    
        } else {
    
            if (thisUser != null){
    
                system.debug('Web Controller Constructor - User is not Null');

    
                List<DF_Contact__c> dfContactList = [select d.Postcode__c, d.Contact_Number__c, d.Digital_Friend_Signup_Time__c, d.Created_As_Type__c from DF_Contact__c d where d.Portal_Contact__c = :thisUser.ContactId LIMIT 1];                    

                if ( !dfContactList.isEmpty() ){
    
                    dfContact = dfContactList[0];
    
                }
    
            }   
        }

        system.debug('Webcontroller Constructor - Complete');

        
    }
    
    public String baseSiteSecureURL {
        get {            
             return '';   
        }
        private set;
    }

    public PageReference loginRedirect() {
        PageReference returnReference;

        if (isLoggedIn == false) {
            returnReference = loginReference;
        }

        return returnReference;
    }

    public PageReference loginReference {
        get {
            PageReference loginReference = Page.WEBLogin;
            loginReference.setRedirect(true);

            return loginReference;
        }
    }

    public String loginUrl {
        get {
            return loginReference.getUrl();
        }
    }

    public String homepageUrl {
        get {
            return Page.WEBHome.getUrl();
        }
    }

    public static Boolean checkUserExists(String emailAddress) {
        List<User> users = [SELECT UserType
                                FROM User
                                WHERE Email = :emailAddress
                                        AND IsActive = true];

        return (users.size() > 0);
    }

    //Registration method
    public static PageReference registerUser(String title, String firstName, String lastName, String telephone, String emailAddress, String postCode, String password, String password2, String userType, boolean newsletters) {
        return null;
    }

}