src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Registration</fullName>
        <active>true</active>
        <label>Registration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Created_As_Type__c</fullName>
        <description>What type of Friend was this contact originally created as</description>
        <label>Created As Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>Subscriber</fullName>
                </value>
                <value>
                    <fullName>Digital Friend</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Champion</fullName>
                </value>
                <value>
                    <fullName>Community Representative</fullName>
                </value>
                <value>
                    <fullName>Registration</fullName>
                </value>
                <value>
                    <fullName>DF Mailer</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Partner Organisation Admin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Registration</fullName>
        <active>true</active>
        <label>Registration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_RegisterSubscriber_Handler.cls
/******************************************************************************************
 *  Alzheimers
 *  
 *  Purpose : APEX Handler for JSON data Subscriber Registration
 *  Author  : Gary Grant
 *  Date    : 17/11/2015
 *  Version : 1.0
 *
 *  Description:    Handler for DF Subscriber Registration.
                    registration process
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
global without sharing class DF_WEBC_RegisterSubscriber_Handler extends DF_WEBC_RegisterBase_Handler {


  public DF_WEBC_RegisterSubscriber_Handler(String sJson) {
        
        init(sJson);

  }

  protected override Boolean handleExistingUser() {
      
        return true;

  }

  protected override void doHandleForm()
    {
            
        if ( !validate() ) { return; }        
  
        doRegistration();
          
        system.debug('RegisterBase_Remote_Log : returning PR');
        responseHolder = new ResponseHolder(dfc);
        return;

  }

  protected override boolean doRegistration() {

        dfc = DF_Utils.getDFContactForEmail(data.emailAddress);

        if ( dfc!= null ) {

            dfc.NewsLetters__c = true;
            update dfc;
            return true;

        }

        if ( dfc == null ) { 
    
            dfc = new DF_Contact__c();                          

            /* Only update the email address if this is a new Record */ 
            dfc.Email__c = data.emailAddress.toLowerCase();
            dfc.Created_As_Type__c = getCreatedAsValue();

        }

        dfc.RecordTypeId = DF_Utils.getDfcRecordTypeId(getRecordTypeName());
        dfc.Status__c = DF_Utils.STATUS_PROSPECTIVE;

        populateData();
        return true;


  }

    protected override void populateData() {
        
        dfc.Last_Name__c = data.lastName;
        dfc.First_Name__c = data.firstName;
        dfc.NewsLetters__c = true;
        dfc.RecordTypeId = DF_Utils.getDfcRecordTypeId(getRecordTypeName());
        Database.UpsertResult dsr = Database.upsert(dfc, true);
        if(dsr.isSuccess()) {
            populateIndvData();
        } else {
            throw new RegisterBaseException('Contact could not be created correctly');
        } 
        
    }


  protected override boolean isRegistrationDataOK() {
    
    boolean b = true;    

    if ( data.firstName == null || data.firstName.length() == 0 ) {
        responseHolder.firstNameError = DF_Utils.EMPTY_FIELD_VALUE_MSG;
        b=false;
    }        
    
    if ( data.lastName == null || data.lastName.length() == 0 ) {
        responseHolder.lastNameError = DF_Utils.EMPTY_FIELD_VALUE_MSG;
        b=false;
    }

    if ( data.emailAddress == null || data.emailAddress.trim().length() == 0 ){

        responseHolder.emailAddressError = DF_Utils.EMPTY_FIELD_VALUE_MSG;
        b=false;

    }
    
    if ( data.emailAddress != data.emailAddress2 ){

        responseHolder.emailAddressError = DF_Utils.EMAILS_DO_NOT_MATCH_MSG;
        b=false;

    }

    if ( data.emailAddress != null && data.emailAddress.trim().length() > 0 ) {
        
        if ( !WEBC_CommunityWrapper.isEmailAddressOK(data.emailAddress) ) {
            responseHolder.emailAddressError = DF_Utils.INVALID_EMAIL_ADDRESS;
            b=false;
        }
        
    }

    return b;

   }


  protected override  String getRecordTypeName() { 

    return DF_Utils.RT_NEWSLETTER_CONTACT;

  }

  protected override String getCreatedAsValue() {

    return 'Subscriber';

  }
  
  protected override void populateDgData() {
    
    return;	
    	
    }

}