src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_CtrlBase_Test.cls
@isTest
private class DF_WEBC_CtrlBase_Test
{
        
    
    @isTest
    static void doTest()
    {
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();     
        User u = (User)mapTestData.get('User');
        Partner_Organisation__c partner = ( Partner_Organisation__c)mapTestData.get('partnerOrg');
        
        System.runAs(u) {
        test.starttest();
        DF_WEBC_HomePage ctl = new DF_WEBC_HomePage();
        User u2 = ctl.currentUser;
        boolean b = ctl.isLoggedIn;
        b = ctl.isOrgAdmin;
        double offset = ctl.currentUserOffset;
        Contact c = ctl.currentContact;
        String partnerid= ctl.partnerId;

        DF_Contact__c dfc = ctl.currentDfc;
        DF_Contact_Wrapper dfcW = ctl.dfcW;
        String s = ctl.totalFriendCount;
        List<String> lis = ctl.totalFriendCountList;

       }

    }

    @isTest
    static void doTest2() {

        DF_WEBC_HomePage ctl = new DF_WEBC_HomePage();
        PageReference pr = ctl.loginRedirect();
    }
    
  


}