src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Demographic_information__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Demographic information</relationshipLabel>
        <relationshipName>Demographic_information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ethnic_Group_Other__c</fullName>
        <label>Ethnic Group - Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ethnic_Group__c</fullName>
        <label>Ethnic Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>White - English / Welsh / Scottish / Northern Irish / British</fullName>
                </value>
                <value>
                    <fullName>White - Irish</fullName>
                </value>
                <value>
                    <fullName>White - Gypsy or Irish Traveller</fullName>
                </value>
                <value>
                    <fullName>White - Any other White background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British – Indian</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Pakistani</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Bangladeshi</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Chinese</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Any other Asian background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Black/African/Caribbean/Black British – Caribbean</fullName>
                </value>
                <value>
                    <fullName>Black/African/Caribbean/Black British – African</fullName>
                </value>
                <value>
                    <fullName>Black/African/Caribbean/Black British – Any other Black background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – White &amp; Black Caribbean</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – White and Black African</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – White and Asian</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – Any other mixed background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Other Ethnic Group – Arab</fullName>
                </value>
                <value>
                    <fullName>Other Ethnic Group – Any other Ethnic Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proximity_to_dementia__c</fullName>
        <label>Proximity to dementia</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Person with dementia</fullName>
                </value>
                <value>
                    <fullName>Family or Friend</fullName>
                </value>
                <value>
                    <fullName>Past Family or Friend</fullName>
                </value>
                <value>
                    <fullName>Carer</fullName>
                </value>
                <value>
                    <fullName>Past Carer</fullName>
                </value>
                <value>
                    <fullName>Dementia Professional</fullName>
                </value>
                <value>
                    <fullName>Interested In Dementia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Demographic information</label>
    <nameField>
        <displayFormat>DG{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demographic information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>BirthDate__c</fullName>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ethnic_Group__c</fullName>
        <label>Ethnic Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arab</fullName>
                </value>
                <value>
                    <fullName>Asian – Any other background</fullName>
                </value>
                <value>
                    <fullName>Asian – Bangladeshi</fullName>
                </value>
                <value>
                    <fullName>Asian – Chinese</fullName>
                </value>
                <value>
                    <fullName>Asian – Indian</fullName>
                </value>
                <value>
                    <fullName>Asian – Pakistani</fullName>
                </value>
                <value>
                    <fullName>Black – African</fullName>
                </value>
                <value>
                    <fullName>Black – Any other background</fullName>
                </value>
                <value>
                    <fullName>Black – Caribbean</fullName>
                </value>
                <value>
                    <fullName>Mixed – Any other background</fullName>
                </value>
                <value>
                    <fullName>Mixed - White and Asian</fullName>
                </value>
                <value>
                    <fullName>Mixed – White and Black African</fullName>
                </value>
                <value>
                    <fullName>Mixed – White and Black Caribbean</fullName>
                </value>
                <value>
                    <fullName>Not disclosed</fullName>
                </value>
                <value>
                    <fullName>Other – Any other ethnic group</fullName>
                </value>
                <value>
                    <fullName>White – Any other background</fullName>
                </value>
                <value>
                    <fullName>White – British (English/Welsh/Scottish/Northern Irish)</fullName>
                </value>
                <value>
                    <fullName>White – Gypsy or Irish Traveller</fullName>
                </value>
                <value>
                    <fullName>White - Irish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact_Inbound_Change__c.object
<CustomObject>
    <description>Changes to DF contact records on progress</description>
    <fields>
        <fullName>BirthDate__c</fullName>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Contact Inbound Changes</relationshipLabel>
        <relationshipName>DF_Contact_Inbound_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact Inbound Change</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>DF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF Contact Inbound Changes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Individual.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This one-to-one link on the DF Contact is required to minimise the changes required to existing integration queries. This was considered the solution that required minimal developer effort and most likely to be achievable within the tight timeframe.</description>
        <inlineHelpText>This one-to-one link on the DF Contact is required to minimise the changes required to existing integration queries. This was considered the solution that required minimal developer effort and most likely to be achievable within the tight timeframe.</inlineHelpText>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Individuals</relationshipLabel>
        <relationshipName>Individuals_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WEBFriendEditMyDetails.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Page WEBFriendEditMyDetails.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class controller for the WEBFriendEditMyDetails page.
 *                  This controller will look after editing and viewing profile information 
 *                  from the DF_Contact__c record
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
public without sharing class WEBFriendEditMyDetails extends DF_WEBC_ControllerBase {
    public final String EMPTY_FIELD_VALUE_MSG = 'Value is required and can\'t be empty';
    public final String EMAIL_FOUND_MSG = 'The email address you have entered already exists. If you own this email address please contact the Dementia Friends team on 0207 264 2662.';
    public static final String RT_CONTACT_CHAMPION = 'Dementia_Friend_Champion';
    public static final String RT_DFCONTACT_FRIEND = 'Dementia_Friend';
        
    public Boolean emailOptIn{get;set;}
    public Boolean telephoneOptIn{get;set;}
    public Boolean textMessageOptIn{get;set;}
    public Boolean socialMediaOptIn{get;set;}
    public Boolean postOptOut{get;set;}
    
    public String standardErrorMsg {get;set;}
    public String emailError {get; set;}
    public String firstNameError {get; set;}
    public String lastNameError {get; set;}
    public String phoneError {get; set;}
    public String title{get;set;}
    public String titleOther{get;set;}
    
    public String birthDateError {get; set;}
    public String birthDateString {get;set;}
    public String pOption1 =  'Family or Friend';
    public String pOption2 =  'Past Family or Friend';
    public String pOption3 =  'Past Carer';
    public String pOption4 =  'Person with dementia';
    public String pOption5 =  'Interested In Dementia';
    public String pOption6 =  'Carer';
    public String pOption7 =  'Dementia Professional';
    public String pValue1 =  'I am a family member or friend of someone with dementia';
    public String pValue2 =  'I was a family member or friend of someone who had dementia';
    public String pValue3 =  'I used to be a carer of someone with dementia';
    public String pValue4 =  'I have dementia';
    public String pValue5 =  'I am generally interested in dementia';
    public String pValue6 =  'I am a carer of someone with dementia';
    public String pValue7 =  'I am a dementia professional';
    public Map<String,String> opValueMap = new Map<String,String> 
    {pOption1 => pValue1, pOption2 => pValue2,pOption3 => pValue3,pOption4 => pValue4,pOption5 => pValue5,pOption6 => pValue6,pOption7 => pValue7};
    
    public list<string> proximity  {get;set;}
    public List<string> proximityOptions = new List<string>{pOption1,pOption2,pOption3,pOption4,pOption5,pOption6,pOption7};
    public String proximityString='' ;
    public Boolean isError = FALSE;
    public Boolean showChangeDetailsPrompt {get; set;}
    
    public List<SelectOption> titleList {
        get {
            if (titleList == null){
                titleList = new List<SelectOption>();
                titleList.add(new SelectOption('-None-','-None-'));
                titleList.add(new SelectOption('Mr.','Mr.'));
                titleList.add(new SelectOption('Mrs.','Mrs.'));
                titleList.add(new SelectOption('Miss.','Miss.'));
                titleList.add(new SelectOption('Ms.','Ms.'));
                titleList.add(new SelectOption('Other','Other'));           
            }
            return titleList;
        }
        set;
    }
    
    
    
    public List<SelectOption> genderOptionList {
        
        get { return DF_Utils.genderOptions; }
        set;        
    }


  public List<SelectOption> getProxmityOptions() {

      List<SelectOption> options = new List<SelectOption>();
          
      Schema.DescribeFieldResult fieldResult = Demographic_Information__c.Proximity_to_dementia__c.getDescribe();

      list<schema.picklistentry> values = fieldResult.getPickListValues();               
        
      for (Schema.PicklistEntry a : values) {     
        for(string s :opValueMap.keyset()){
       if(a.getValue() == s){             
        options.add(new SelectOption(a.getlabel(),opValueMap.get(s)));
        }
       
      }
    }
       
     return options;
       
    }
        

    

    public Page_Snippet__c totalFriendsSnippet {
        get {
            if (totalFriendsSnippet == null){
                totalFriendsSnippet = [select p.Body_Text__c, p.Unique_Name__c from Page_Snippet__c p where p.Unique_Name__c = 'DementiaFriendsTotalSnippet' LIMIT 1];
            }
            return totalFriendsSnippet;
        }
        set ;
    }
    
    public List<DF_Contact_Inbound_Change__c> contactDetailsChanged {
        get {
            if (contactDetailsChanged == null){
                contactDetailsChanged = new List<DF_Contact_Inbound_Change__c>();
            }
            return contactDetailsChanged;
        }
        set;
    }

    public DF_Contact__c dfContactRecord {get; set;}

    public User thisUser {
        get {
            //if (thisUser == null)
            //  thisUser = WEBController.thisUser;
            //return thisUser;
            return WEBController.thisUser;
        }
        set;
    }

    public WEBFriendEditMyDetails() {
        if (test.isRunningTest()){
        
            Contact c = new Contact();
            c.firstname = 'Test';
            c.LastName = 'TestContact';
            c.Email = 'test.testcontact@myemail.com';
            c.Salutation='Mr';
            insert c;
            dfContactRecord = new DF_Contact__c();
            dfContactRecord.RecordTypeId = [select r.Id from RecordType r where r.DeveloperName = :RT_DFCONTACT_FRIEND and r.SObjectType = 'DF_Contact__c' LIMIT 1].Id;
            dfContactRecord.First_Name__c = 'Test';
            dfContactRecord.Last_Name__c = 'Contact';
            dfContactRecord.portal_contact__c=c.id;
            dfContactRecord.BirthDate__c = Date.valueOf('2013-05-05');
            dfContactRecord.Email__c = 'test.contact@myemail.com';
            dfContactRecord.Last_Name__c = 'Contact';
            dfContactRecord.Street__c = '4 SWtuart';
            dfContactRecord.City__c = 'London';
            dfContactRecord.County__c = 'London';
            dfContactRecord.Postcode__c = 'EC3 2AW';
            GDPR gdprSettings = new GDPR(false,false,false,false,false);
            GDPR.createDefaultIndivRecord(new List<Contact>{c});
            
        }else {
            dfContactRecord =  [Select d.Email__c, d.Title__c,d.BirthDate__c ,d.Newsletters__c, d.Street__c, d.Portal_Contact__c, d.Last_Name__c, d.First_Name__c, d.County__c, d.City__c, d.Postcode__c, d.Contact_Number__c, d.Country__c, d.Gender__c, d.Ethnic_Group__c  From DF_Contact__c d where d.Portal_Contact__c = :thisUser.ContactId LIMIT 1];
       		
            GDPR gdprSettings = GDPR.getExistingDfContactPrefs(currentDfc.Id);
            emailOptIn = gdprSettings.EmailOptIn;
            telephoneOptIn = gdprSettings.PhoneOptIn;
            textMessageOptIn = gdprSettings.SmsOptIn;
            socialMediaOptIn = gdprSettings.SocialOptIn;
            postOptOut = gdprSettings.PostOptOut;
        }
        
        standardErrorMsg = '';
        emailError = '';
        firstNameError = '';
        lastNameError = '';
        phoneError = '';
        birthDateError = '';
        
        contactDetailsChanged = [select id from DF_Contact_Inbound_Change__c where Related_DF_Contact__c=:currentdfc.id];
         if(contactDetailsChanged.size()>0 ){
            
            showChangeDetailsPrompt = true;
        }
        boolean bIsOtherTitleVaue = true;
        
         if ( dfContactRecord.BirthDate__c != null ) {
            DateTime dt = dfContactRecord.birthDate__c;
            birthDateString = dt.format('dd/MM/yyyy');
        }
    
        for ( SelectOption option : titleList ) {
            if ( dfContactRecord.Title__c == option.getValue()) {
                bIsOtherTitleVaue = false;
            }           
        }
        title = ( bIsOtherTitleVaue ? 'Other' : dfContactRecord.Title__c);
        titleOther = ( bIsOtherTitleVaue ? dfContactRecord.Title__c : '');
        proximity = new List<string>();
        
        for (string s :proximityOptions){
         
         if(clientDgData==null){return;}
          
         if( clientDgData.proximity_to_dementia__c!=null && clientDgData.proximity_to_dementia__c.contains(s)){
          proximity.add(s);
          }
        }
    }
    
    @Future
    //This needs to be a future call as you can't mix DML statements on setup objects & non setup objects
    public static void updateUserRecord(String userId, String emailAddress, String firstName, String lastName){
        try {
            User u = [select u.Email, u.UserName, u.CommunityNickname, u.Firstname, u.Lastname from User u where u.Id = :userId LIMIT 1];
            u.Firstname = firstName;
            u.Lastname = lastName;
            u.Email = emailAddress;
            u.CommunityNickname = emailAddress;
            u.UserName = emailAddress;
            
            update u;
        }catch (DMLException dmlEx){
            system.debug('*** -- Error saving user : ' + dmlEx + ' -- ***');
        }
    }
    
    public PageReference saveUserDetails(){
        standardErrorMsg = '';
        emailError = '';
        firstNameError = '';
        lastNameError = '';
        phoneError = '';
        birthDateError = '';
        isError = false;
        
        
        
        //if (this.dfContactRecord.Email__c.length() == 0){
        //  emailError = EMPTY_FIELD_VALUE_MSG;
        //  isError = TRUE;
        //}

        if (this.dfContactRecord.First_Name__c.length() == 0) {
            firstNameError = EMPTY_FIELD_VALUE_MSG;
            isError = TRUE;
        }

        if (this.dfContactRecord.Last_Name__c.length() == 0) {
            lastNameError = EMPTY_FIELD_VALUE_MSG;
            isError = TRUE;
        }
         if (this.dfContactRecord.Contact_Number__c == null || this.dfContactRecord.Contact_Number__c.length() == 0){
            phoneError = EMPTY_FIELD_VALUE_MSG;
            isError = TRUE;
        } else {
        
        
         if(!WEBC_CommunityWrapper.isPhoneOK(this.dfContactRecord.Contact_Number__c)){
         
            phoneError = 'Please enter telephone number in correct format';
            isError = TRUE;
         }
        
        }
        
        if ( birthDateString == null || birthDateString.length() == 0 ) {
        
         //  birthDateError = EMPTY_FIELD_VALUE_MSG;
          // isError=False;
        
        } else {
         // if ( birthDateString != null || birthDateString.length() > 0 ) {
        

            Date dt = date.parse(birthDateString);
            system.debug('Edit Friend Details : bdy ' + birthDateString);
            system.debug('Edit Friend Details : bdy ' + dt.format());

            if ( dt == null ) {
                
                birthDateError = 'Birth Date is invalid format (DD/MM/YYY)';
                isError = TRUE;
            
            }
            if ( dt > date.today() ) {
                
                birthDateError = 'Birth Date cannot be in the future';
                isError = TRUE;
            
            }
            
            } 
        
        List<DF_Contact__c> dfContactCheckList = new List<DF_Contact__c>();
        dfContactCheckList = [select d.Id, d.Email__c from DF_Contact__c d where d.Email__c = :this.DFContactRecord.Email__c];
        
        for (DF_Contact__c dfc : dfContactCheckList){
            if (dfc.Id != this.dfContactRecord.Id){
                isError = TRUE;
                emailError = EMAIL_FOUND_MSG;
            }
        }
        
        if (isError){
            return null;
        }
        
          //**************DG data upsert************************//
         Demographic_Information__c dg = clientDgData;
         
         
        
         for(string s:proximity ){
             if(s != null){   
                 proximityString = proximityString +';'+ s;
             }
         }
        
         if(dg!=null ){ 
         
                     
           if(proximityString != null || proximityString != ''){
             
              dg.Proximity_to_dementia__c = proximityString;
                
           }
          upsert dg; 
         }
         
         
         
         system.debug('upsert dg  '+dg);
         
         //**************DG data upsert end************************//

         //**************Individual update start************************//
        
        GDPR gdprInst = new GDPR(emailOptIn, telephoneOptIn, textMessageOptIn, socialMediaOptIn, postOptOut);
        gdprInst.populateIndvData(dfContactRecord);
         //**************Individual update end************************//
        
         try {
            if (dfContactRecord != null) {
        
                dfContactRecord.Title__c = (title=='Other' ? titleOther : title);
                
               
                if ( birthDateString == null || birthDateString.length() == 0 ) {
                dfContactRecord.BirthDate__c = null;
               
                } else{
                
                Date dt1 = date.parse(birthDateString);
                dfContactRecord.BirthDate__c = date.parse(birthDateString);
                dfContactRecord.BirthDate__c = dt1;
                }
                
                if (test.isRunningTest()){
                    insert dfContactRecord;
                }else {
                    update dfContactRecord;
                }
                
                //Check to see if core data has been changed and if so, update the user record
                if (thisUser.Email != dfContactRecord.Email__c ||
                    thisUser.Firstname != dfContactRecord.First_Name__c ||
                    thisUser.Lastname != dfContactRecord.Last_Name__c){
                        system.debug('*** -- About to call the user save future method -- ***');
                        updateUserRecord(thisUser.Id, dfContactRecord.Email__c, dfContactRecord.First_Name__c, dfContactRecord.Last_Name__c);                       
                    }
                }
                
                
               

        } catch (Exception e) {
            standardErrorMsg = e.getMessage();
        }
        
        PageReference pageRef = Page.WEBFriend;
        pageRef.getParameters().put('ds','true');
        //return Page.WEBChampion;
        return pageRef;
    }
    
    /*March 2016*/
    
    
    
    public Demographic_Information__c clientDgData {

      get { return dgDataMap.get(dfContactRecord.portal_contact__c); }

      set;
    }
    
     public Map<String, Demographic_Information__c> dgDataMap {

    get{

      if (dgDataMap != null) { return dgDataMap; }

      
      initDgDataMap();      
      return dgDataMap;

    } 
    
    set;

  }

  private void initDgDataMap() {

      Map<String, Demographic_Information__c> dgMap = new Map<String, Demographic_Information__c>();
      List<Demographic_Information__c> lis = [  select id, Ethnic_Group__c,Ethnic_Group_Other__c,Contact__c,Proximity_to_dementia__c
                                                from Demographic_Information__c 
                                                where   Contact__c =: dfContactRecord.portal_contact__c                                               
                                                limit 1 ];
     
      System.debug(' Controller DGData SOQL: ' + lis);                                         

      for ( Demographic_Information__c dgData : lis ) {

       

        if ( dfContactRecord.portal_contact__c !=null && dfContactRecord.portal_contact__c == dgData.Contact__c ) {
             System.debug('getting Client dgData');                                                  
             dgMap.put(dfContactRecord.portal_contact__c, dgData);
        }

       

      }                                          
       if ( dgMap.get(dfContactRecord.portal_contact__c) == null ) {
           dgMap.put(dfContactRecord.portal_contact__c, getNewDgData(dfContactRecord.portal_contact__c));
      }
      
      this.dgDataMap = dgMap;

  }

  private Demographic_Information__c getNewDgData (id contact) {
  
    List <contact> c = [select ownerid from contact where id =:contact limit 1];
    if(contact == null) { return null; }
  
    System.debug(' Creating New DG Data');

    Demographic_Information__c dgData = new Demographic_Information__c();
    dgData.Contact__c = contact;
    dgData.OwnerId = c[0].ownerid;
             
   
    // Don't insert here. A subsequent update will fail. 
    return dgData;

  }
    
    
    
    
    
    
    
   /* //////////////////////////////////////*/
    
    /*
    public PageReference saveUserDetails () {
        standardErrorMsg = '';
        firstNameError = '';
        lastNameError = '';

        if (this.thisUser.firstName.length() == 0) {
            firstNameError = EMPTY_FIELD_VALUE_MSG;
            isError = TRUE;
        }

        if (this.thisUser.lastName.length() == 0) {
            lastNameError = EMPTY_FIELD_VALUE_MSG;
            isError = TRUE;
        }

        if (isError)
            return null;
        
        // Update the Contact Record
        List<Contact> contacts = [SELECT Id, firstName, lastName, Newsletters__c FROM Contact WHERE Id = :thisUser.ContactId LIMIT 1];

        Contact c = null;

        if (contacts.size() > 0)
            c = contacts[0];

        try {
            if (c!=null) {
                
                c.firstName=this.thisUser.firstName;
                c.lastName=this.thisUser.lastName;

                update c;
            }

            update thisUser;

        } catch (Exception e) {
            standardErrorMsg = e.getMessage();
        }
        
        return Page.WEBFriend;
    }
*/
    
}