src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Description__c</fullName>
        <label>Event Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Champion_Training_Course</fullName>
        <active>true</active>
        <description>Events organised by Alzheimers Society/Trusted Partners</description>
        <label>Champions Induction</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Information Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Contact__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dementia Friend Champion</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Champions Induction</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

src/objects/Saved_Search__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Range__c</fullName>
        <label>Range</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sent_Mail__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether the mail is sent or not to the user</inlineHelpText>
        <label>Sent Mail</label>
        <type>Checkbox</type>
    </fields>
    <label>Saved Search</label>
    <nameField>
        <displayFormat>Search-{0000}</displayFormat>
        <label>Saved Searches Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Searches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_DFEventTriggerMethods.cls
@isTest
private class Test_DFEventTriggerMethods{
    
   

     
     static testMethod void testDFEventTriggerMethods() {
        try{
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseDFeventGenerator());        
           test.starttest();
            Saved_Search__c ssavedsearch= new Saved_Search__c();
            ssavedsearch.Post_Code__c = '560033';
            ssavedsearch.Email__c = 'test@gmail.com';
            ssavedsearch.Sent_Mail__c= false;
            ssavedsearch.Range__c = 5;
            ssavedsearch.Geolocation__Latitude__s = 30;
            ssavedsearch.Geolocation__Longitude__s = 30;
            insert ssavedsearch;
            
            DF_Contact__c contact = new DF_Contact__c();
            contact.First_Name__c = 'simon';
            contact.Last_Name__c= 'molloy';
            contact.Name = 'simonm';
            insert contact;
            
            DF_Event__c dfevent= new DF_Event__c();
            dfevent.Postcode__c = '560033';
            dfevent.Location_Geographic_Details__Latitude__s = 30;
            dfevent.Location_Geographic_Details__Longitude__s = 30;
            dfevent.Session_Organiser__c = contact.id;
            insert dfevent;
            
            DF_Event__c dfevent1 = new DF_Event__c();
            dfevent1.Postcode__c = '516001';
            dfevent1.Session_Organiser__c = contact.id;
            insert dfevent1;
            
            
            Set<Id> dfeventIds = new Set<Id>();
            dfeventIds.add(dfevent.Id);            
            dfeventIds.add(dfevent1.Id); 
           
            DFEventTriggerMethods.sendEmailToMembers(dfeventIds); 
           
            Double d1 = 90.0;
            Double d2 = 60.0;
            Double d3 = 70.0;
            Double d4 = 50.0;
            
            DFEventTriggerMethods.calculateDistance(d1,d2,d3,d4);
            test.stoptest();
        }
        catch(Exception e){}     
      
    } 
    
    static testMethod void testDFEventTriggerMethods2() {
        try{
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseDFeventGenerator());        
           test.starttest();
            Saved_Search__c ssavedsearch= new Saved_Search__c();
            ssavedsearch.Post_Code__c = '560033';
            ssavedsearch.Email__c = 'test@gmail.com';
            ssavedsearch.Sent_Mail__c= false;
            ssavedsearch.Geolocation__Latitude__s = 30;
            ssavedsearch.Geolocation__Longitude__s = 30;
            insert ssavedsearch;
            
            Map<String,Id> roles = new Map<String,Id>();
            List<UserRole> rl = [select id, name from UserRole];
        for(UserRole r : rl){ roles.put(r.name, r.id); }
            
             User sysAdminUser =  [select id from user where UserRoleId =:roles.get('CEO') and isActive=true limit 1];
            Account a = new Account(Name='Test Account Name');
            a.OwnerId = sysAdminUser.id;
            insert a;
            
            Contact c = new Contact();
            c.firstname = 'Test';
            c.LastName = 'TestContact';
            c.AccountId = a.Id;
            c.Email = 'test.testcontact@myemail.com';
            c.Salutation='Mr';
            insert c;
            
            DF_Contact__c contact = new DF_Contact__c();
            contact.First_Name__c = 'simon';
            contact.Last_Name__c= 'molloy';
            contact.Name = 'simonm';
            contact.Email__c = 'simonm@test.com';
            contact.Portal_Contact__c=c.Id;
            insert contact;
            
            
            DF_Event__c dfevent= new DF_Event__c();
            dfevent.Postcode__c = '560033';
            dfevent.Location_Geographic_Details__Latitude__s = 30;
            dfevent.Location_Geographic_Details__Longitude__s = 50;
            dfevent.Session_Organiser__c = contact.id;
            insert dfevent;
            
            DF_Event__c dfevent1 = new DF_Event__c();
            dfevent1.Postcode__c = '516001';
            dfevent1.Session_Organiser__c = contact.id;
            dfevent1.RecordTypeId = DF_Utils.getsObjectRecordTypeId('DF_Event__c','Dementia_Friend_Awareness_Session');
            dfevent1.Event_Date_Time__c = system.now()+5 ;
            insert dfevent1;
            
             
            DF_EventAttendee__c eAt2 = new DF_EventAttendee__c ();
            eAt2.DF_Contact__c = contact.id;
            eAt2.DF_Event__c = dfevent1.id;
        
            insert eAt2 ;
            
            Map<Id, DF_Event__c>  mapevents = new  Map<Id, DF_Event__c> ();
            mapevents.put(dfevent1.Id,dfevent1);
            List<DF_Event__c> lisdfevent = [select Postcode__c from DF_Event__c where Postcode__c='516001'];
            lisdfevent[0].Postcode__c='TE12 2RE';
            update lisdfevent[0];
                        
            Set<Id> dfeventIds = new Set<Id>();
            dfeventIds.add(dfevent.Id);            
            dfeventIds.add(dfevent1.Id); 
          
           
            DFEventTriggerMethods.sendEmailToMembers(dfeventIds); 
             DFEventTriggerMethods.sendEmailNotifications(lisdfevent, mapevents);
             List<DF_Event__c> lisdfeventcancel = [select Postcode__c from DF_Event__c where Postcode__c='TE12 2RE'];
            lisdfeventcancel[0].Event_Status__c = 'Cancelled';
            
            update lisdfeventcancel[0];
             DFEventTriggerMethods.sendEmailNotifications(lisdfeventcancel, mapevents);
            Double d1 = 90.0;
            Double d2 = 60.0;
            Double d3 = 70.0;
            Double d4 = 50.0;
            
            DFEventTriggerMethods.calculateDistance(d1,d2,d3,d4);
            test.stoptest();
        }
        catch(Exception e){}     
      
    } 
    
 static testMethod void setUpSystemData(){
 /*   String FRIEND_RT_NAME = 'Dementia_Friend';
    String CHAMPION_RT_NAME = 'Dementia_Friend_Champion';
    String SESSION_RT_NAME = 'Dementia_Friend_Awareness_Session';
    String TRAINING_RT_NAME = 'Champion_Training_Course';
    String STATUS_CANCELLED = 'Cancelled';*/
    
   // User adminUser;
   // User guestUser;
    User portalUser;
    Contact contactRecord;
    Contact soContactRecord;
    DF_Contact__c sessionOrganiser;
    DF_Contact__c dfContactRecord;
    DF_Event__c testSession;
    DF_Event__c testTraining;
    DF_EventAttendee__c dfe1;
    DF_EventAttendee__c dfe2;
    /*
        RecordType dfcFriend = [select r.Id from RecordType r where r.DeveloperName = :FRIEND_RT_NAME and r.SobjectType = 'DF_Contact__c' and IsActive = true LIMIT 1];
        RecordType cFriend = [select r.Id from RecordType r where r.DeveloperName = :FRIEND_RT_NAME and r.SobjectType = 'Contact' and IsActive = true LIMIT 1];
        RecordType dfcChampion = [select r.Id from RecordType r where r.DeveloperName = :CHAMPION_RT_NAME and r.SobjectType = 'DF_Contact__c' and IsActive = true LIMIT 1];
        RecordType cChampion = [select r.Id from RecordType r where r.DeveloperName = :CHAMPION_RT_NAME and r.SobjectType = 'Contact' and IsActive = true LIMIT 1];
       */ 
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();
        portalUser= (User)mapTestData.get('adminUser');
        test.starttest();
       // adminUser = [Select Id From User Where Profile.Name='System Administrator' And IsActive=true limit 1];
        //guestUser = [Select Id From User Where UserType='Guest' limit 1];
        //portalUser = [Select Id, ContactId from User where Profile.Name='DF HVCP' and IsActive = true LIMIT 1];
        contactRecord = (contact)mapTestData.get('contact');
        //soContactRecord = [Select FirstName, LastName, Email from Contact where RecordTypeId = :cChampion.Id LIMIT 1];
        
    /*    Global_Setting__c setting = Global_Setting__c.mapTestData('webAccountOwnerId');
        if (setting == null){
            setting = new Global_Setting__c(Name='webAccountOwnerId',Value__c=adminUser.Id);
            insert setting;
        }*/
        List<DF_Contact__c> dfConList = new List<DF_Contact__c>();
        dfConList = [select d.First_Name__c, d.Last_Name__c, d.Email__c, d.RecordTypeId, d.Portal_Contact__c from DF_Contact__c d where d.Portal_Contact__c = :contactRecord.Id LIMIT 1];
        if (dfConList.size() == 0){
            dfContactRecord =(DF_Contact__c)mapTestData.get('DFc2');
        }else {
            dfContactRecord = dfConList[0];
        }
        
        
        
        testSession = (DF_Event__c)mapTestData.get('FriendSession');
        
        testTraining = (DF_Event__c)mapTestData.get('ChampCourse');
        
        dfe1 = (DF_EventAttendee__c)mapTestData.get('ChampAtten');
        dfe2 = (DF_EventAttendee__c)mapTestData.get('FriendAtten');
    }
  
   
    static void testSessionTrigger() {
       // setupSystemData();
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();
        DF_Event__c fevent= (DF_Event__c)mapTestData.get('FriendSession');
    
        //Update the session and save it - this should fire the 'update' email 
        test.starttest();
        fevent.Event_Description__c = 'This is an update';
        update fevent;
        
        //Now we cancel the session, and this should fire the 'cancellation' email
        fevent.Event_Status__c = 'Cancelled';
        update fevent;  

             
    }
    
   
    
}