src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation ID</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Admin</fullName>
        <active>true</active>
        <label>Admin</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Description__c</fullName>
        <label>Event Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <label>Event End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Friends Logged</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Total session audience capacity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>DF Events</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Information Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Internal_purpose__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal purpose only</label>
        <type>Checkbox</type>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PO_Administrator__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>PO Administrators</relationshipLabel>
        <relationshipName>PO_Administrators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>PO Administrators</relationshipLabel>
        <relationshipName>PO_Administrators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PO Administrator</label>
    <nameField>
        <displayFormat>POA{000000}</displayFormat>
        <label>POA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Administrators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEBChampionSessionFeedback.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Page WEBChampionSessionFeedback.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class controller for the WEBChampionSessionFeedback class.
 *                  This is used to create Session Feedback records for DF Events
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
public without sharing class WEBChampionSessionFeedback extends DF_WEBC_ControllerBase {
    
    public final String STATUS_CANCELLED = 'Cancelled';  
    public final String STATUS_COMPLETED = 'Completed';      
    public static final String SESSION_RT = 'Dementia_Friend_Awareness_Session';
    public String messageArea {get;set;}
    public String messageAreaClass {get;set;}
    public Boolean ispartnerSession {get;set;}
    public DF_Contact__c dfc {get;set;}
    public String partnerError {get;set;}
    public Boolean isOrgChampion {get;set;}
    public Boolean isOrgAdmin {get;set;}
    public List<SelectOption> partnerList {
        get {

            if (partnerList == null)
                partnerList = new List<SelectOption>();
                
            return partnerList;

        }

        set;

    }
    
    public Integer partnerListSize {

        get {

            return partnerList.size();

        }

        set;

    }

    public DF_Event__c event {

        get {
            if (event == null)
                event = new DF_Event__c();
            return event;
        }
        set;

    }

    public List<SelectOption> sessionList {

        get {

            if (sessionList == null)
                sessionList = new List<SelectOption>();
            return sessionList;

        }

        set;

    }

    public Integer sessionListSize {

        get {

            return sessionList.size();

        }

        set;

    }

    public Boolean thereAreNoSessions {get;set;}
    public String selectedSession {get;set;}
    public string selectedPartner {get;set;}
    public Integer noOfAttendees {get;set;}
    public String sessionComments {get;set;}

    public List<DF_Event__c> eventsRequiringFeedback {

        get {
            if (eventsRequiringFeedback == null)
                eventsRequiringFeedback = new List<DF_EVENT__c>();
            
            return eventsRequiringFeedback;
        }
        set;

    }

    //Save method
    public PageReference save() {
        partnerError='';
        
        
        if(ispartnerSession && selectedPartner == 'none' ){
            
            partnerError='Please select partner organisation';
            return null;
        }

        if (event.Id == null && selectedSession != null) {
            event = [SELECT Id, Name, Event_Description__c, Partner_Organisation__c,Comments__c, Number_of_Attendees__c, Event_Status__c
                        FROM DF_Event__c
                        WHERE Id = :selectedSession ];
        }

        if (event.Id == null && selectedSession != null && selectedPartner != null) {
            event = [SELECT Id, Name,Partner_Organisation__c, Event_Description__c, Comments__c, Number_of_Attendees__c, Event_Status__c
                        FROM DF_Event__c
                        WHERE Id = :selectedSession  and Partner_Organisation__r.name =: selectedPartner ];
         
         }

        if (event != null ) {
           if(isPartnerSession==False) {
           	event.Partner_Organisation__c = null;
           	selectedPartner = null;
           }
           else{
           	event.Partner_Organisation__c = selectedPartner;
           }
            event.Number_of_Attendees__c = noOfAttendees;
            event.Comments__c = sessionComments;
            event.Event_Status__c = STATUS_COMPLETED;
                     
            upsert event;

        }
        
            PageReference pr = Page.WEBChampionManageMySessions;
            //google tracking QP-9
            pr.getParameters().put('info_session_reported','true');
            pr.getParameters().put('eventshare',noOfAttendees.format());
            return pr;
       

    }
    
    public PageReference cancelSession() {

        if (event.Id == null && selectedSession != null) {
            event = [SELECT Id, Name, Event_Description__c, Comments__c, Number_of_Attendees__c, Event_Status__c
                        FROM DF_Event__c
                        WHERE Id = :selectedSession];
        }

        if (event != null) {
            event.Event_Status__c = STATUS_CANCELLED;
            event.Comments__c = sessionComments;
            event.Number_of_Attendees__c=0;
            
            upsert event;
        }
        
        return Page.WEBChampionManageMySessions;

    }

    //Constructor
    public WEBChampionSessionFeedback() {
    	//list with duplicate partner name
    	List<SelectOption> partnerOrgList = new List<SelectOption> (); 
    	//create a unique partner list to select
    	Set<SelectOption> partnerSet =new Set <SelectOption> ();
        dfc = (currentdfc!=null? currentdfc:new DF_Contact__c());
        noOfAttendees = 0;
        sessionComments = '';
        thereAreNoSessions = FALSE;
        partnerError='';
        isPartnerSession=False;
        selectedPartner = 'none';
        String currentSession = ApexPages.currentPage().getParameters().get('eventId');
        isOrgChampion = (dfc.Partner_Organisation_Id__c != null && !dfc.Partner_Organisation_Id__r.Internal_purpose__c ? true: false);
        List<po_administrator__c> poadminlis = new List<po_administrator__c> ();
        poadminlis =[select name,Partner_Organisation__c,Partner_Organisation__r.Name from po_administrator__c where df_contact__c =:dfc.id and Status__c = 'Registered'];
        
        if(poadminlis.size()>0) { isOrgAdmin = true ;}
         for(po_administrator__c po : poadminlis){
            
                system.debug('partner admin'+po);
                if(po!=null && po.Partner_Organisation__c !=null ){
                
                partnerOrgList.add(new SelectOption(po.Partner_Organisation__c,po.Partner_Organisation__r.Name));
               
                }
            }
      
         	
         if(isOrgChampion){         	
              
               partnerOrgList.add(new SelectOption(dfc.Partner_Organisation_Id__c,dfc.Partner_Organisation_Id__r.Name));
          }
   
   //adding to a set make a unique list
    if(partnerOrgList.size()>0){
    	
        partnerSet.addAll(partnerOrgList);         
      }
   //unique partner list
       partnerList.addAll(partnerSet);
      
            
        if (currentSession != null) {
            
            
                
            event = [SELECT Id, Name, Event_Description__c, Partner_Organisation__c ,Partner_Organisation__r.name,Comments__c, Number_of_Attendees__c, Event_Status__c
                        FROM DF_Event__c
                        WHERE Id = :currentSession];

            if (event != null) {

                if (event.Number_of_Attendees__c != null)
                    noOfAttendees = event.Number_of_Attendees__c.intValue();

                if (event.Comments__c != null)
                    sessionComments = event.Comments__c;
               
                if (event.Partner_Organisation__c != null  )
                    selectedPartner = event.Partner_Organisation__c;
                    
                   
                isPartnerSession=(selectedPartner != 'none' && selectedPartner != null)?true:false;
                  
                
                
            } else {

                thereAreNoSessions = TRUE;

            }
        
        } else {

            // Choosing multiple sessions           
            String sdt = Datetime.now().format('yyyy-MM-dd HH:mm:ss', 'Europe/London');
            Datetime dt = Datetime.valueOf(sdt);

            eventsRequiringFeedback = [SELECT Id, Name, Event_Date_Time__c,Partner_Organisation__c, Event_End_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c 
                                        FROM DF_Event__c 
                                        WHERE Session_Organiser__c = :dfc.id
                                        AND Event_End_Date_Time__c <: datetime.now()
                                        AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) 
                                        And RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT)
                                        and Event_Status__c != :STATUS_CANCELLED LIMIT 10];
            system.debug('dfc.id '+ dfc.id+'datetime.now()');
            //TEST CODE
            //eventsRequiringFeedback = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Places__c FROM DF_Event__c WHERE Session_Organiser__r.Portal_Contact__r.Id = :WEBController.thisUser.ContactId AND Event_Date_Time__c <= TODAY LIMIT 10];

            if (eventsRequiringFeedback == null || eventsRequiringFeedback.size() == 0) {
                thereAreNoSessions = TRUE;

                return;

            }

            for (DF_Event__c sess : eventsRequiringFeedback) {
                SelectOption s = new SelectOption(sess.Id, sess.Name + ' ' + sess.Event_Date_Time__c.format('dd/MM/yyyy'));
                sessionList.add(s);

            }
            
           

        }
        

    }
   
     
}