src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Registration</fullName>
        <active>true</active>
        <label>Registration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>BirthDate__c</fullName>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Admin</fullName>
        <active>true</active>
        <label>Admin</label>
    </recordTypes>
    <recordTypes>
        <fullName>Registration</fullName>
        <active>true</active>
        <label>Registration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Pack_Request__c.object
<CustomObject>
    <description>A request for the Little Book OF Friendship</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Pack Requests</relationshipLabel>
        <relationshipName>DF_Pack_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Pack Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Pack Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF_Pack Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Employees__c</fullName>
        <label>Number of Employees</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-250</fullName>
                </value>
                <value>
                    <fullName>251-1000</fullName>
                </value>
                <value>
                    <fullName>1001-5000</fullName>
                </value>
                <value>
                    <fullName>5001-20000</fullName>
                </value>
                <value>
                    <fullName>20001+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector_other__c</fullName>
        <label>Sector - other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dementia_Friends_Website</fullName>
        <active>true</active>
        <businessProcess>Dementia Friends Lead Process</businessProcess>
        <label>Dementia Friends Website</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PO_Administrator__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>PO Administrators</relationshipLabel>
        <relationshipName>PO_Administrators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>DF_Contact__r.Email__c</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invited_Email__c</fullName>
        <label>Invited Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PO Administrator</label>
    <nameField>
        <displayFormat>POA{000000}</displayFormat>
        <label>POA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Administrators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_WEBC_RegisterOrgAdmin_Handler.cls
/******************************************************************************************
 *  Alzheimers
 *  
 *  Purpose : APEX Handler for JSON data Org Registration
 *  Author  : Lakshmi Vasudevan
 *  Date    : 25/04/2016
 *  Version : 1.0
 *
 *  Description:    Handler for DF Org Registration. 
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
global without sharing class DF_WEBC_RegisterOrgAdmin_Handler extends DF_WEBC_RegisterBase_Handler {

  public DF_WEBC_RegisterOrgAdmin_Handler(String sJson) {
    
    init(sJson);

  }
  
  protected override boolean isExtendedRegistrationDataOK() {

    return true;

  }
  
   protected override void sendVerificationRequest() {

        if ( !isRequestVerification() ) { return; }

        WEBC_CommunityWrapper community = new WEBC_CommunityWrapper('DF');                 
        //Contact contact = DF_Utils.getContactRecord(dfc); 
        Contact contact=  DF_Utils.getContactRecordForDfcId(dfc.id); 
        if ( handleInvite(contact, community) ) { return; } 
        community.sendAdminVerificationRequest(contact,data.orgName, data.password, getStartUrl(), getEmailTemplateName());
        system.debug('DF_WEBC_RegisterBase_Handler : user registered');

    }
    
    
    private Boolean handleInvite(Contact contact, WEBC_CommunityWrapper community) {

        if ( data.inviteId == null ) { 

          System.debug('Invite Handling : No Invite');          
          return false; 

        }

        List<Po_Administrator__c> lisInvites = 
        [SELECT Id, Status__c, Invited_Email__c, DF_Contact__r.Email__c
         FROM Po_Administrator__c WHERE Id =: data.inviteId];        

        if ( lisInvites.size() == 0 ) { 

          System.debug('Invite Handling : no invites');          
          return false;  
        }

        Po_Administrator__c invite = lisInvites[0];

        // The invite is set to registered when the DFC record is created
        //if ( invite.Role__c != 'Invited' || invite.Invited_Email__c != dfc.Email__c ) {  return false; }
        if ( WEBC_CommunityWrapper.hasUserRecord(contact) ) { 

          System.debug('Invite Handling : has user record');          
          return false; 
        }        

        if ( invite.DF_Contact__r.Email__c != data.emailAddress ) { 

            system.debug('Email Address does not match');          
            return false; 
        }  

        string startUrl= '/user-home';
        responseHolder.redirectUrl = community.getVerifyUrl(contact, data.password, startUrl);
        system.debug('Invite Handling redirect Url: ' + responseHolder.redirectUrl);
        
        responseHolder.returnCode = 3;

        return true;

  }
  

  /* Extend these Methods for different classes of Friend */


  // Don't include the Community Prefix in the name  
  protected override String getEmailTemplateName() {

    return 'Partner_Admin_Verification_Request';

  }


  protected override  String getRecordTypeName() { 

    return DF_Utils.RT_FRIEND;

  }

  protected override String getCreatedAsValue() {

    return 'Partner Organisation Admin';

  }

  protected override String getStartUrl() {
    //display messsage on user dashboard
    string var ='?org-registered='+ EncodingUtil.urlEncode(data.orgName,'UTF-8')+'&'+'df_organisation_verified=true';
    return '/user-home'+ var ;

  }


  protected override void populateExtendedData() {

     dfc.BirthDate__c = getDate(data.birthDate); 

  }

  protected override void doPostRegistration() {

        system.debug('WEBC_RegisterFriend_Loggin : Handle Pack Request ' + data.packRequest);

        if ( data.packRequest!=null && data.packRequest) {
             String packStatus = handlePackRequest(dfc);
        }
       
        createOrgLead();

   }

   /* Create a new pack request if one does not already exist */
   private static String handlePackRequest(DF_Contact__c dfc) {
        
      /* TODO !!! Only two packs can be sent to each address - need some firm rules for that */
      
      system.debug('WEBC_RegisterFriend_Loggin : Handle Pack Request');
      DF_Pack_Request__c dfpr = null;
              
      List<DF_Pack_Request__c> lis = [select id, DF_Contact__c, Status__c,City__c,Street__c,PostCode__c,County__c,Country__c from DF_Pack_Request__c where DF_Contact__c = :dfc.id LIMIT 1];
      
      if ( lis.isEmpty() ) {
        
          system.debug('WEBC_RegisterFriend_Loggin : creating pack request');

          dfpr = new DF_Pack_Request__c();
          dfpr.Status__c= 'New';
          dfpr.DF_Contact__c = dfc.id;
          dfpr.City__c = dfc.City__c;
          dfpr.Street__c = dfc.Street__c;
          dfpr.PostCode__c = dfc.PostCode__c;
          dfpr.County__c = dfc.County__c;
          dfpr.Country__c = dfc.Country__c;
          
          insert dfpr;        
      
      }  else {        
      
          dfpr = lis[0]; 

      }          

      return dfpr.Status__c;
        
    }
    

  @TestVisible
   // create  partner organisation leads
  public void createOrgLead() {

    if ( dfc== null ){return;}
    // Contact contact = DF_Utils.getContactRecord(dfc); 
    Contact contact = DF_Utils.getContactRecordForDfcId(dfc.id); 
    if (contact==null) { return;}
     
    if(data.orgName==null || data.orgName.length()<=0){return;}
      
    // only one lead record can linked with dfcontact 
    Lead ld = new Lead();
    string LEAD_RT = 'Dementia_Friends_Website'; 
    list<Group> DFQueue = [select id, Name from Group where DeveloperName = 'DF_Website_Admins' and Type = 'Queue'];
            
    List<Lead > lis = [select Contact__c,Email,Number_of_Employees__c,Phone,RecordTypeId,LeadSource,Sector__c,Sector_other__c,Df_contact__c,Lastname,Company ,Street,State,City,
                          Country ,PostalCode  from Lead 
                                                where   Contact__c =: contact.Id                                               
                                                and df_contact__c =: dfc.Id
                                                limit 1 ];
      
    if ( !lis.isEmpty() ) { ld =lis[0];}
    
    
    if(DFQueue.size() > 0){ 
    
    ld.ownerId = DFQueue[0].id; 
    
    } else {
    
    ld.ownerId = [select id from User where isActive = true and Profile.Name = 'System Administrator' limit 1].id;
    }
    ld.LeadSource='Web';
    ld.Contact__c = contact.id;
    ld.Df_contact__c = dfc.id; 
    ld.Company = data.orgName;
    ld.Sector__c = data.sector;
    ld.Sector_other__c = data.sectorOther;
    ld.Number_of_Employees__c = data.employees; 
    ld.LastName = contact.LastName;  
    ld.FirstName= contact.FirstName; 
    ld.Email = data.emailAddress;       
    ld.Street = data.orgStreet;
    ld.State = data.orgCounty;
    ld.Phone=data.orgTelephone;
    ld.City = data.orgCity;
    ld.Country = data.orgCountry;
    ld.PostalCode = data.orgPostCode;
    ld.RecordTypeId = DF_Utils.getsObjectRecordTypeId('Lead',LEAD_RT);
 
    upsert ld;
        
      
     
  }
    
    


}