src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Demographic_information__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Ethnic_Group_Other__c</fullName>
        <label>Ethnic Group - Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ethnic_Group__c</fullName>
        <label>Ethnic Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>White - English / Welsh / Scottish / Northern Irish / British</fullName>
                </value>
                <value>
                    <fullName>White - Irish</fullName>
                </value>
                <value>
                    <fullName>White - Gypsy or Irish Traveller</fullName>
                </value>
                <value>
                    <fullName>White - Any other White background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British – Indian</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Pakistani</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Bangladeshi</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Chinese</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Any other Asian background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Black/African/Caribbean/Black British – Caribbean</fullName>
                </value>
                <value>
                    <fullName>Black/African/Caribbean/Black British – African</fullName>
                </value>
                <value>
                    <fullName>Black/African/Caribbean/Black British – Any other Black background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – White &amp; Black Caribbean</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – White and Black African</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – White and Asian</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – Any other mixed background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Other Ethnic Group – Arab</fullName>
                </value>
                <value>
                    <fullName>Other Ethnic Group – Any other Ethnic Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Demographic information</label>
    <nameField>
        <displayFormat>DG{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demographic information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/WEBFriendEditMyDetailsTest.cls
@IsTest 

public without sharing class WEBFriendEditMyDetailsTest {
   
      @IsTest
     public static void covermethodTest() {
     
    
      
         Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();   
         User u = (User)mapTestData.get('User');
        //Contact c = (Contact)mapTestData.get('Contact');
        //Demographic_Information__c dg =( Demographic_Information__c)mapTestData.get('Demographic');
        
        test.starttest();
        System.runAs(u) {
         PageReference pageRef = Page.WEBFriendEditMyDetails;        
         WEBFriendEditMyDetails controller = new WEBFriendEditMyDetails();
                   
         controller.clientdgdata.ethnic_group__c='please specify';
         controller.clientdgdata.ethnic_group_other__c='test';
            controller.emailOptIn = false;
             controller.telephoneOptIn = false;
             controller.textMessageOptIn = false;
             controller.socialMediaOptIn = false;
             controller.postOptOut = false;
         List<SelectOption> titleList = controller.titleList;
         Page_Snippet__c pn= new Page_Snippet__c (
         Body_Text__c='test',
         Unique_Name__c='DementiaFriendsTotalSnippet',
         Name__c='test'
        );
         
         insert pn;
         
         pn= controller.totalFriendsSnippet;
         list<string> proximitylis = new list<string>(); 
         proximitylis .add('Carer');
        System.assertEquals(null,controller.saveUserDetails());

        controller.thisUser.firstName = '';
        controller.thisUser.lastName = '';
        
         
        controller.dfContactRecord.First_Name__c = '';
        controller.dfContactRecord.Last_Name__c = '';
        controller.dfContactRecord.Postcode__c = '';
        controller.dfContactRecord.Title__c ='Other';
        controller.dfContactRecord.Birthdate__c =date.today().addyears(-19);
        controller.proximitystring='carer;professional';
        controller.proximity = proximitylis;
        System.assertEquals(null,controller.saveUserDetails());
        WEBFriendEditMyDetails.updateUserRecord(u.Id, u.Email, u.FirstName, u.LastName);
        controller.getProxmityOptions();
        controller.saveUserDetails();
        
        
        }
        
    }
}