src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Individual.object
<CustomObject>
    <fields>
        <fullName>DF_ContactExternalId__c</fullName>
        <externalId>true</externalId>
        <label>DF_ContactExternalId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This one-to-one link on the DF Contact is required to minimise the changes required to existing integration queries. This was considered the solution that required minimal developer effort and most likely to be achievable within the tight timeframe.</description>
        <inlineHelpText>This one-to-one link on the DF Contact is required to minimise the changes required to existing integration queries. This was considered the solution that required minimal developer effort and most likely to be achievable within the tight timeframe.</inlineHelpText>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Individuals</relationshipLabel>
        <relationshipName>Individuals_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GdrpInitialSyncBatch.cls
global class GdrpInitialSyncBatch implements Database.Batchable<sObject> {
    
    global Database.Querylocator start(Database.BatchableContext BC) {
       //Query to fetch contacts that don't have Individual created. You may modify the query to add custom fields  
       //Please add  "IsPersonAccount = false" condition to below query to exclude person accounts
       return Database.getQueryLocator('Select FirstName, LastName, Salutation, DF_Contact__c from Contact where IndividualId = NULL');
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> contactList) { 
        Map<Id, Individual> individualRecordsToCreate = new Map<Id, Individual>();
        for(Contact con : contactList) {
            individualRecordsToCreate.put(con.Id, new Individual(FirstName = con.FirstName, 
                                                                 LastName = con.LastName, 
                                                                 Salutation=con.Salutation,
                                                                 DF_Contact__c = con.DF_Contact__c,
                                                                 DF_ContactExternalId__c = con.DF_Contact__c)
                                         );
        }
        Database.insert(individualRecordsToCreate.values(), true);
        for(Contact con : contactList) {
            con.IndividualId = individualRecordsToCreate.get(con.Id).Id;
        }
        update contactList;
    }
    
    global void finish(Database.BatchableContext BC) {}
   
}