src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_Lead_TriggerHandler_Test.cls
/************************************************************************************************
*Alzheimer's Society

     * @author          Lakshmi Vasudevan 
     * @date            24-05-2016
     * @description     Test class for DF_Lead_TriggerHandler
***********************************************************************************************/
@isTest
private class DF_Lead_TriggerHandler_Test {

   @testsetup  static void mytestdata(){
   
   DFP_DataFactory_Test.TestDataCreation();
   
   }

    static testMethod void myUnitTest() {
 
    List<Contact> c  = [select id,FirstName,LastName from Contact where email='test.testcontact@myemail.com' limit 1]; 
    List<DF_Contact__c> DFc  = [select id from DF_Contact__c where email__c='test.testcontact@myemail.com' limit 1] ;
    List<Lead> lead = [select id from lead limit 1];
        // create a Lead
    test.starttest();
                 
   
   Database.LeadConvert lc = new database.LeadConvert();
   lc.setLeadId(lead[0].id);
   lc.setDoNotCreateOpportunity(true);
   LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
   lc.setConvertedStatus(convertStatus.MasterLabel);
   
   Database.LeadConvertResult lcr = Database.convertLead(lc);
   System.assert(lcr.isSuccess());
        
    }
}