src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isVerifyEmailNotSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>created to indicate people who hasn&apos;t received verify email on 21/07/2016</description>
        <label>isVerifyEmailNotSent</label>
        <type>Checkbox</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchSendVerificationEmail.cls
global class BatchSendVerificationEmail implements Database.Batchable<SObject>, Database.Stateful, Schedulable

 // Batch class to update df contacts with portal user
    {
    public String query;
 
        global void execute( SchedulableContext SC )
        {
          // batch run 
          BatchSendVerificationEmail batch = new BatchSendVerificationEmail();
          Database.executeBatch( batch, 4 );
        }

        global Database.QueryLocator start(Database.BatchableContext BC)
        {
      
           
          query = 
                'Select Id, ' +
                'Last_Name__c, '+
                'First_name__c, '+
                'Email__c '+
                ' From ' +
                'DF_Contact__c ' +
                ' Where ' +
                'isVerifyEmailNotSent__c = true';
                
    
            system.debug('+++Query+++'+ query);
            if(Test.isRunningTest())
                {
                    query += ' Limit 1';
                }

            return Database.getQueryLocator(query);
        }

        global void execute(Database.BatchableContext BC, List<SObject> scope)
        {
        
         List<DF_Contact__c> lisdfc = new List<DF_Contact__c> ();
         string var = '?cp=true';
         string password = 'dfReg1234';
         string startUrl='/change-password'+var;
         string templateName ='Custom_Verification_Request';
         WEBC_CommunityWrapper community = new WEBC_CommunityWrapper('DF');
        for ( sObject s : scope ) {
              
              DF_Contact__c  dfc = (DF_Contact__c)s;
             
              lisdfc.add(dfc);
            }
            
         for(DF_Contact__c dfc : lisdfc){
       
         Contact contact=  DF_Utils.getContactRecordForDfcId(dfc.id);  
         community.sendVerificationRequest(contact, password, startUrl, templateName);
         system.debug('BatchSendVerificationEmail: send verification request');

            
          
          }

         
         
        }
        
        global void finish(Database.BatchableContext BC)
        {
          // do something interesting
        }


}