src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Demographic_information__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Ethnic_Group_Other__c</fullName>
        <label>Ethnic Group - Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ethnic_Group__c</fullName>
        <label>Ethnic Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>White - English / Welsh / Scottish / Northern Irish / British</fullName>
                </value>
                <value>
                    <fullName>White - Irish</fullName>
                </value>
                <value>
                    <fullName>White - Gypsy or Irish Traveller</fullName>
                </value>
                <value>
                    <fullName>White - Any other White background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British – Indian</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Pakistani</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Bangladeshi</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Chinese</fullName>
                </value>
                <value>
                    <fullName>Asian/Asian British - Any other Asian background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Black/African/Caribbean/Black British – Caribbean</fullName>
                </value>
                <value>
                    <fullName>Black/African/Caribbean/Black British – African</fullName>
                </value>
                <value>
                    <fullName>Black/African/Caribbean/Black British – Any other Black background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – White &amp; Black Caribbean</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – White and Black African</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – White and Asian</fullName>
                </value>
                <value>
                    <fullName>Mixed/Multiple Ethnic Groups – Any other mixed background (please specify)</fullName>
                </value>
                <value>
                    <fullName>Other Ethnic Group – Arab</fullName>
                </value>
                <value>
                    <fullName>Other Ethnic Group – Any other Ethnic Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Demographic information</label>
    <nameField>
        <displayFormat>DG{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demographic information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>BirthDate__c</fullName>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Champion_exchange_access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has champion exchange access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ethnic_Group__c</fullName>
        <label>Ethnic Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arab</fullName>
                </value>
                <value>
                    <fullName>Asian – Any other background</fullName>
                </value>
                <value>
                    <fullName>Asian – Bangladeshi</fullName>
                </value>
                <value>
                    <fullName>Asian – Chinese</fullName>
                </value>
                <value>
                    <fullName>Asian – Indian</fullName>
                </value>
                <value>
                    <fullName>Asian – Pakistani</fullName>
                </value>
                <value>
                    <fullName>Black – African</fullName>
                </value>
                <value>
                    <fullName>Black – Any other background</fullName>
                </value>
                <value>
                    <fullName>Black – Caribbean</fullName>
                </value>
                <value>
                    <fullName>Mixed – Any other background</fullName>
                </value>
                <value>
                    <fullName>Mixed - White and Asian</fullName>
                </value>
                <value>
                    <fullName>Mixed – White and Black African</fullName>
                </value>
                <value>
                    <fullName>Mixed – White and Black Caribbean</fullName>
                </value>
                <value>
                    <fullName>Not disclosed</fullName>
                </value>
                <value>
                    <fullName>Other – Any other ethnic group</fullName>
                </value>
                <value>
                    <fullName>White – Any other background</fullName>
                </value>
                <value>
                    <fullName>White – British (English/Welsh/Scottish/Northern Irish)</fullName>
                </value>
                <value>
                    <fullName>White – Gypsy or Irish Traveller</fullName>
                </value>
                <value>
                    <fullName>White - Irish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c &amp; &quot;,  &quot; &amp; First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_opted_out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User opted out</label>
        <type>Checkbox</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact_Inbound_Change__c.object
<CustomObject>
    <description>Changes to DF contact records on progress</description>
    <fields>
        <fullName>BirthDate__c</fullName>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact Inbound Change</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>DF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF Contact Inbound Changes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WEBChampionEditMyDetailsTest.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX test class for WEBChampionEditMyDetails.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex test class.
 *               
 *  Modification History
 *  Date            Who         Description 
 *                    
*******************************************************************************************/
@IsTest public without sharing class WEBChampionEditMyDetailsTest {
    
    @IsTest
    public static void championEditMyDetailsTest() {

        Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();   
        User u = (User)mapTestData.get('User');
		
        System.debug('???: ' + u.Contact.DF_Contact__c);
        
         test.starttest();
         System.runAs(u) {
         PageReference pageRef = Page.WEBChampionEditMyDetails;        
         WEBChampionEditMyDetails controller = new WEBChampionEditMyDetails();
         List<SelectOption> ProxmityOptions = controller.getProxmityOptions();
         controller.getDate('2012-01-12');
             controller.emailOptIn = false;
             controller.telephoneOptIn = false;
             controller.textMessageOptIn = false;
             controller.socialMediaOptIn = false;
             controller.postOptOut = false;
             controller.infoSessionRadius = 25;
          Demographic_Information__c dg = controller.clientdgdata;
         controller.clientdgdata.ethnic_group__c='please specify';
         controller.clientdgdata.ethnic_group_other__c='test';
         List<SelectOption> titleList = controller.titleList;
         Page_Snippet__c pn= new Page_Snippet__c (
         Body_Text__c='test',
         Unique_Name__c='DementiaFriendsTotalSnippet',
         Name__c='test'
        );
         
         insert pn;
         
         pn= controller.totalFriendsSnippet;
         list<string> proximitylis = new list<string>(); 
         proximitylis .add('Carer');
         //System.assertEquals(null,controller.saveUserDetails());

        controller.thisUser.firstName = '';
        controller.thisUser.lastName = '';
        
         
        controller.dfContactRecord.First_Name__c = '';
        controller.dfContactRecord.Last_Name__c = '';
        controller.dfContactRecord.Postcode__c = '';
        controller.dfContactRecord.Title__c ='';
        controller.dfContactRecord.Contact_Number__c ='012345';
        controller.dfContactRecord.Champion_exchange_access__c=true;
        controller.dfContactRecord.Newsletters__c=true;
        controller.dfContactRecord.Street__c=''; 
        controller.dfContactRecord.County__c='';
        controller.dfContactRecord.City__c='';
        controller.dfContactRecord.User_opted_out__c =false;
        controller.dfContactRecord.Birthdate__c =date.today().addyears(-15).adddays(-10);
        controller.isChampion = true;
        controller.isChampionConverted = true;
        controller.proximity = proximitylis;

        List<SelectOption> genderOptionList = controller.genderOptionList;
        List<DF_Contact_Inbound_Change__c> contactDetailsChanged = controller.contactDetailsChanged;
        
        /*System.assertEquals(null,controller.saveUserDetails());
        System.assertNotEquals(null,controller.birthDateError);
        System.assertNotEquals(null,controller.phoneError);
         System.assertEquals(null,controller.convertToChampion());
        //System.assertEquals(null,controller.saveBirthdate());
         //System.assertEquals(true,controller.isError);
        //System.assertNotEquals(null,controller.clientDgData);*/
   
        WEBChampionEditMyDetails.updateUserRecord(u.Id, u.Email, u.FirstName, u.LastName);
        test.stopTest();
        controller.saveBirthdate();
        controller.convertToChampion();
        controller.saveUserDetails();
                     
         }
        
        
    }
   
    
    
}