src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Individual.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This one-to-one link on the DF Contact is required to minimise the changes required to existing integration queries. This was considered the solution that required minimal developer effort and most likely to be achievable within the tight timeframe.</description>
        <inlineHelpText>This one-to-one link on the DF Contact is required to minimise the changes required to existing integration queries. This was considered the solution that required minimal developer effort and most likely to be achievable within the tight timeframe.</inlineHelpText>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Individuals</relationshipLabel>
        <relationshipName>Individuals_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GDPR_Test.cls
@isTest
public class GDPR_Test {
    
    private static testmethod void coverageOnly() {
        
        DF_DataFactory_Test.getTestData();  
        Id rtId = [SELECT Id FROM RecordType WHERE Name='Dementia Friend' AND SobjectType='Contact'].Id;
        Id orgId = [SELECT Id FROM Account LIMIT 1].Id;
        
        Contact c = new Contact(Firstname='Test',Lastname='Test',RecordTypeId=rtId, AccountId = orgId);
        Database.SaveResult dsr = Database.insert(c, true);

        GDPR inst = new GDPR(false, false, false, false, false);
        inst.populateIndvData(c);

        Contact c2 = [select id, DF_Contact__c, IndividualId from Contact where id =:c.id];
        inst = new GDPR(true, true, false, false, false);
        inst.populateIndvData(c2);

        Id indvId = [SELECT Id FROM Individual LIMIT 1].Id;
        DF_Contact__c dfContact = [SELECT Id, First_Name__c, Last_Name__c, Portal_Contact__c FROM DF_Contact__c LIMIT 1];
        inst.populateIndvData(dfContact);

        GDPR.createDefaultIndivRecord(new List<Contact>{c});
        
        Individual indv = new Individual(Firstname=dfContact.First_Name__c, Lastname=dfContact.Last_Name__c);
        insert indv;
        
        Contact cIndv = [SELECT IndividualId FROM Contact WHERE DF_Contact__c = :dfContact.Id];
        cIndv.IndividualId = indv.Id;
        update cIndv;
        
        GDPR.getExistingDfContactPrefs(dfContact.Id);
        
    }
}