src/objects/DCE_ServiceAmend__c.object
<CustomObject>
    <description>Used within the Dementia Connect Extranet community to represent a new service (to be created within the Dementia Connect Database) or the amendment to an existing Service (to be updated within the Dementia Connect Database</description>
    <fields>
        <fullName>Accessibility__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the ‘Additional Information’ field below.</inlineHelpText>
        <label>Venue Accessibility</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastReviewed__c</fullName>
        <description>This field contains the date of last reviewed</description>
        <label>Last Reviewed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opening_times_Other__c</fullName>
        <inlineHelpText>If you cannot fit your service&apos;s opening times into the standard format, please write a description here.</inlineHelpText>
        <label>Opening times - Other</label>
        <length>230</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parking__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the ‘Additional Information’ field below.</inlineHelpText>
        <label>Parking</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes-on site</fullName>
                </value>
                <value>
                    <fullName>Yes-off site</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_only__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick this box if the service can only be accessed via a referral from health and social care professionals. Do not tick it if self-referrals are accepted.</inlineHelpText>
        <label>Referral  only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ServiceId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Stores the value of the Service ID in the production system.</description>
        <externalId>true</externalId>
        <label>Dementia Connect - Service Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Criteria__c</fullName>
        <inlineHelpText>e.g. People with dementia only, carers or anyone.</inlineHelpText>
        <label>Who can use this service?</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Amendment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DCE_Amendment_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Toilet_Facilities__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the ‘Additional Information’ field below.</inlineHelpText>
        <label>Toilet Facilities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>service_city__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_county__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_description__c</fullName>
        <inlineHelpText>Our Dementia Connect team may contact you with guidance if the service description requires more detail (max. 100 words)</inlineHelpText>
        <label>Service Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>service_postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>service_telephone__c</fullName>
        <inlineHelpText>This should be the telephone number that service users can use to contact you about the service.</inlineHelpText>
        <label>Telephone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Please select one option, most appropriate to the service.</inlineHelpText>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>Carer Support &amp; Groups</fullName>
                </value>
                <value>
                    <fullName>Carer Training</fullName>
                </value>
                <value>
                    <fullName>Counselling</fullName>
                </value>
                <value>
                    <fullName>Day care and support (establishment based)</fullName>
                </value>
                <value>
                    <fullName>Dementia cafe</fullName>
                </value>
                <value>
                    <fullName>Dementia Support &amp; Groups</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Home facilities &amp; services</fullName>
                </value>
                <value>
                    <fullName>Information and Advice (Dementia)</fullName>
                </value>
                <value>
                    <fullName>Information and Advice (Financial &amp; Legal)</fullName>
                </value>
                <value>
                    <fullName>Information programme</fullName>
                </value>
                <value>
                    <fullName>Lifestyle &amp; Wellbeing</fullName>
                </value>
                <value>
                    <fullName>Memory Assessment</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Online forum</fullName>
                </value>
                <value>
                    <fullName>Registered home care and support</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Residential/nursing home care</fullName>
                </value>
                <value>
                    <fullName>Respite</fullName>
                </value>
                <value>
                    <fullName>Social Services</fullName>
                </value>
                <value>
                    <fullName>Telephone helpline</fullName>
                </value>
                <value>
                    <fullName>Transport, Driving &amp; Mobility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DCE Service Creation or Amendment</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DCE Service Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DCE_ServiceEditController_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class DCE_ServiceEditController_Test {

	private static DCE_SingleRequestMock responseCorrectRecord = new DCE_SingleRequestMock(200, 'Complete', '{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Services__c","url":"/services/data/v35.0/sobjects/Services__c/a0z1234567890ABCDE"},"Id":"a0z1234567890ABCDE","Name":"Example Service Name From Dementia Connect"}]}', null);
    private static DCE_SingleRequestMock responseNoRecords = new DCE_SingleRequestMock(200, 'Complete', '{"totalSize":0,"done":true,"records":[]}', null);
    private static DCE_SingleRequestMock responseRestError = new DCE_SingleRequestMock(404, 'Error', 'There was a random problem', null);
    
    @testSetup private static void setupData(){
    	DCE_TestDataFactory.setUpDataWithAmends();
    }
    
    static testMethod void testEditModeWithoutURLParams() {
        
		Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			list<selectOption> recOpps = cont.recurrenceOptions;
			list<selectOption> recDays = cont.recurrenceDays;
			
			DCE_ServiceAmend__c amend = cont.service;
			
			system.assertEquals('Draft', amend.status__c);
			system.assertEquals(false, cont.doneCallout);
			system.assertEquals(false, cont.isLockedForApproval);
			system.assertEquals('edit', cont.mode);
			
			amend.Name = 'New Service Name';
			
			cont.save();
			
			cont.discardDraft();
			
			test.stopTest();
		}
	}
	
	static testMethod void testEditModeWithoutURLParamsSendApproval() {
        
		Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			DCE_ServiceAmend__c amend = cont.service;
			
			system.assertEquals('Draft', amend.status__c);
			system.assertEquals(false, cont.doneCallout);
			system.assertEquals(false, cont.isLockedForApproval);
			system.assertEquals('edit', cont.mode);
			
			amend.Name = null;
			
			cont.commitApproval();
			
			system.assert(cont.pageMessage.startsWith('Before submission for Approval, the following fields still require completion:'));
			system.assertEquals(false, cont.isLockedForApproval);
			
			amend.Name = 'Exciting New Name';
			amend.Service_Type__c = 'Example Type';
			amend.Service_DEscription__c = 'Example Description';
			amend.Opening_Times_Other__c = 'Example open times';
			amend.service_telephone__c = '0123456789';
			amend.service_street__c = 'Example Street 1';
			amend.service_city__c = 'City';
			amend.service_county__c = 'County';
			amend.service_country__c = 'City';
			amend.service_postcode__c = 'RH8 0LY';
			amend.National_Service__c = false;
			amend.Parking__c = 'Some';
			amend.Referral_only__c = false;
			amend.Toilet_Facilities__c = 'Some';
			amend.Accessibility__c = 'Some';
			amend.Service_Criteria__c = 'Some';			
			
			cont.commitApproval();
			
			system.assertEquals('Record Locked and sent for approval',cont.pageMessage);
			system.assertEquals(true, cont.isLockedForApproval);
			
			cont.recallApproval();
			
			system.assertEquals(false, cont.isLockedForApproval);
			
			test.stopTest();
		}
	}
	
	static testMethod void testViewModeWithoutURLParams() {
        
		Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceView);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			system.assertEquals('view', cont.mode);
			
			DCE_ServiceAmend__c amend = cont.service;
			
			system.assertEquals(null, amend);
			system.assertEquals('Could not find the service you are looking for. Please check your URL. [DCE108]', cont.pageMessage);
			
			test.stopTest();
		}
	}
    
    static testMethod void testEditModeWithOnlyIncorrectAmendParam() {
    	Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			ApexPages.currentPage().getParameters().put('aid','a0s1234567890ABCDE');
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			DCE_ServiceAmend__c amend = cont.service;
			
			test.stopTest();
			
			system.assertEquals(null, amend);
			system.assertEquals('Could not find the service you are looking for. Please check your URL. [DCE101]', cont.pageMessage);
		}
    }
    
    static testMethod void testEditModeWithOnlyCorrectAmendParamDraftService() {
    	Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			DCE_ServiceAmend__c draftAmend = [select id, Name from DCE_ServiceAmend__c where Status__c = 'Draft' limit 1];
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			ApexPages.currentPage().getParameters().put('aid',draftAmend.id);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			DCE_ServiceAmend__c amend = cont.service;
			
			test.stopTest();
			
			system.assertNotEquals(null, amend);
			system.assertNotEquals(null, amend.id);
			system.assertEquals('Draft', amend.status__c);
			system.assertEquals(draftAmend.Name, amend.Name);
			system.assertEquals(null, cont.pageMessage);
			system.assertEquals(false, cont.isLockedForApproval);
		}
    }
    
    static testMethod void testRestErrorResponse() {
		Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			DCE_ServiceAmend__c nonDraftAmend = [select id, Name from DCE_ServiceAmend__c where Status__c != 'Draft' limit 1];
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			ApexPages.currentPage().getParameters().put('aid',nonDraftAmend.id);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			test.SetMock(HttpCalloutMock.class, responseRestError);
			
			DCE_ServiceAmend__c amend = cont.service;
			
			test.stopTest();
			
			system.assertEquals(null, amend);
			system.assertEquals('Could not find the service you are looking for. Please check your URL. [DCE103]', cont.pageMessage);
		}
	}
    
    
    static testMethod void testEditModeWithOnlyCorrectAmendParamNonDraftServiceBadCalloutResponse() {
    	Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			DCE_ServiceAmend__c nonDraftAmend = [select id, Name from DCE_ServiceAmend__c where Status__c != 'Draft' limit 1];
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			ApexPages.currentPage().getParameters().put('aid',nonDraftAmend.id);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			test.SetMock(HttpCalloutMock.class, responseNoRecords);
			
			DCE_ServiceAmend__c amend = cont.service;
			
			test.stopTest();
			
			system.assertEquals(null, amend);
			system.assertEquals('Could not find the service you are looking for. Please check your URL. [DCE106]', cont.pageMessage);
		}
    }
    
    static testMethod void testEditModeWithOnlyCorrectAmendParamNonDraftServiceGoodCalloutResponse() {
    	Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			DCE_ServiceAmend__c nonDraftAmend = [select id, Name from DCE_ServiceAmend__c where Status__c != 'Draft' limit 1];
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			ApexPages.currentPage().getParameters().put('aid',nonDraftAmend.id);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			test.SetMock(HttpCalloutMock.class, responseCorrectRecord);
			
			DCE_ServiceAmend__c amend = cont.service;
			
			test.stopTest();
			
			//Check that the amend is real AND has been overwritted from Dementia Connect
			system.assertNotEquals(null, amend);
			system.assertNotEquals(null, amend.id);
			system.assertEquals(nonDraftAmend.id, amend.id);
			system.assertEquals('Draft', amend.status__c);
			system.assertEquals('Example Service Name From Dementia Connect', amend.Name);
			system.assertEquals(null, cont.pageMessage);
			system.assertEquals(false, cont.isLockedForApproval);
		}
    }
    
	static testMethod void testEditModeWithInCorrectAmendAndServiceParam() {
    	Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			ApexPages.currentPage().getParameters().put('aid','a0s1234567890ABCDE');
			ApexPages.currentPage().getParameters().put('sid','a0z9994567890ABCDE');
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			DCE_ServiceAmend__c amend = cont.service;
			
			test.stopTest();
			
			system.assertEquals(null, amend);
			system.assertEquals('Could not find the service you are looking for. Please check your URL. [DCE101]', cont.pageMessage);
		}
    }
    
	/* No longer required - The controller no longer accepts aid and sid. Just aid.
	static testMethod void testEditModeWithCorrectAmendAndIncorrectServiceParam() {
    	Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			ApexPages.currentPage().getParameters().put('aid',Amends[0].id);
			ApexPages.currentPage().getParameters().put('sid','a0z1234567890ABCDE');
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			DCE_ServiceAmend__c amend = cont.service;
			
			test.stopTest();
			
			system.assertEquals(null, amend);
			system.assertEquals('Could not find the service you are looking for. Please check your URL. [DCE102]', cont.pageMessage);
		}
    }*/
    
    static testMethod void testEditModeWithIncorrectAmendAndCorrectServiceParam() {
    	Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name, ServiceId__c from DCE_ServiceAmend__c];
			system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceEdit);
			ApexPages.currentPage().getParameters().put('aid','a0s1234567890ABCDE');
			ApexPages.currentPage().getParameters().put('sid',Amends[0].Serviceid__c);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			
			DCE_ServiceAmend__c amend = cont.service;
			
			test.stopTest();
			
			system.assertEquals(null, amend);
			system.assertEquals('Could not find the service you are looking for. Please check your URL. [DCE101]', cont.pageMessage);
		}
    }
    
    static testMethod void testViewModeWithURLParamsGoodResponse() {
        
		Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name, ServiceId__c from DCE_ServiceAmend__c where Status__c != 'Draft' and ServiceId__c != null limit 1];
			//system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceView);
			//ApexPages.currentPage().getParameters().put('sid',Amends[0].Serviceid__c);
			ApexPages.currentPage().getParameters().put('aid',Amends[0].Id);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			system.assertEquals('view', cont.mode);
			
			test.SetMock(HttpCalloutMock.class, responseCorrectRecord);
			
			DCE_ServiceAmend__c amend = cont.service;
			
			system.assertNotEquals(null, amend);
			system.assertEquals(null, cont.pageMessage);
			system.assertEquals('Example Service Name From Dementia Connect', amend.Name);
			
			/*
			cont.reviewed();
			
			amend = [select id, lastReviewed__c from DCE_ServiceAmend__c where Serviceid__c = :Amends[0].Serviceid__c];
			
			system.assertEquals(system.today(), amend.lastReviewed__c);*/
			
			test.stopTest();
		}
	}
	
	static testMethod void testViewModeWithURLParamsBadResponse() {
        
		Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name, ServiceId__c from DCE_ServiceAmend__c where Status__c != 'Draft' and ServiceId__c != null limit 1];
			//system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceView);
			ApexPages.currentPage().getParameters().put('aid',Amends[0].Id);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			system.assertEquals('view', cont.mode);
			
			test.SetMock(HttpCalloutMock.class, responseNoRecords);
			
			DCE_ServiceAmend__c amend = cont.service;
			
			system.assertEquals(null, amend);
			system.assertEquals('Could not find the service you are looking for. Please check your URL. [DCE106]', cont.pageMessage);
			
			
			test.stopTest();
		}
	}
	
	static testMethod void testReviewedFunctionality() {
        
		Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name, ServiceId__c, lastReviewed__c from DCE_ServiceAmend__c where Status__c != 'Draft' and ServiceId__c != null limit 1];
			//system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceView);
			//ApexPages.currentPage().getParameters().put('sid',Amends[0].Serviceid__c);
			ApexPages.currentPage().getParameters().put('aid',Amends[0].Id);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			system.assertEquals('view', cont.mode);
			
			//directly set the amendment for test purposes, this isn't how it would be done in a non-test scenario
			cont.service = Amends[0];
			
			system.assertNotEquals(system.today(), cont.service.lastReviewed__c);
			
			cont.reviewed();
			
			DCE_ServiceAmend__c amend = [select id, lastReviewed__c from DCE_ServiceAmend__c where Serviceid__c = :Amends[0].Serviceid__c];
			
			system.assertEquals(system.today(), amend.lastReviewed__c);
			
			test.stopTest();
		}
	}
	
	static testMethod void testCloningFunctionality() {
        
		Account partnerAccount = [select id from Account where Name = 'PartnerAccount1'];
		
		User u = [select id, AccountId from User where AccountId = :partnerAccount.id and isActive = true and Id IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :DCE_ControllerUtils.DCE_PERMISSION_SET_NAME) limit 1];
		
		list<DCE_ServiceAmend__c> Amends = [select id, Name from DCE_ServiceAmend__c];
		system.assertEquals(125, Amends.size());
		
		system.runAs(u){
			
			Amends = [select id, Name, ServiceId__c, lastReviewed__c from DCE_ServiceAmend__c where Status__c != 'Draft' and ServiceId__c != null limit 1];
			//system.assertEquals(25, Amends.size());
			
			test.startTest();
			
			test.setCurrentPage(page.DCE_ServiceView);
			//ApexPages.currentPage().getParameters().put('sid',Amends[0].Serviceid__c);
			ApexPages.currentPage().getParameters().put('aid',Amends[0].Id);
			
			DCE_ServiceEditController cont = new DCE_ServiceEditController();
			system.assertEquals('view', cont.mode);
			
			//directly set the amendment for test purposes, this isn't how it would be done in a non-test scenario
			cont.service = Amends[0];
			
			cont.cloneRecord();
			
			test.stopTest();
		}
	}
	
	static testMethod void randomTestControllerUtils(){
		
		Account acc = new Account(Name = null);
		
		DCE_ServiceEditController contr = new DCE_ServiceEditController();
		
		try{
			insert acc;
			system.assert(false);
		} catch (dmlException e){
			contr.errorMessage(e);
		}
		
		
		list<selectOption> accountUserSelectList = contr.accountUserSelectList;
	}
}