src/objects/DCE_ServiceAmend__c.object
<CustomObject>
    <description>Used within the Dementia Connect Extranet community to represent a new service (to be created within the Dementia Connect Database) or the amendment to an existing Service (to be updated within the Dementia Connect Database</description>
    <fields>
        <fullName>DCEPartner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dementia Connect External Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ServiceChanges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastReviewed__c</fullName>
        <description>This field contains the date of last reviewed</description>
        <label>Last Reviewed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>service_status__c</fullName>
        <description>Defines the status of the service in Dementia Connect</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DCE Service Creation or Amendment</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DCE Service Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DCE_EmailServiceDigest_Batcher.cls
/******************************************************************************************
 *  Alzheimers
 *  
 *  Purpose : This class sends emails to DCE users where their org has services due a review. It's batchable, because we're assuming that the portal will be a BIG DEAL one day.
 *            
 *  Author  : Andy Rouse
 *  Date    : 02-2016
 *  Version : 1.0
 *
 *  Description:
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/

public with sharing class DCE_EmailServiceDigest_Batcher implements Database.Batchable<SObject>{
    
    private string query;
    
    public static integer EMAIL_BATCH_SIZE = 60;
    
    private string PSName = DCE_ControllerUtils.DCE_PERMISSION_SET_NAME; //Need to bring this variable into the class, so it is visible to the dynamic SOQL below.
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
    	
    	string query = 'Select id, FirstName, LastName from User where isActive = true and ID IN (select AssigneeId from PermissionSetAssignment where PermissionSet.Name = :PSName) and AccountId IN (Select DCEPartner__c from DCE_ServiceAmend__c where service_status__c = \'Open\' and (LastReviewed__c = null or (LastReviewed__c < LAST_N_MONTHS:9 and LastReviewed__c >= LAST_N_MONTHS:15 ) ) )';
    	
    	if(test.isRunningTest()){
    		query += ' LIMIT '+EMAIL_BATCH_SIZE;
    	}
    	
    	return Database.getQueryLocator(query);
    }
    
    public void execute (Database.BatchableContext BC, List<SObject> scope) {
    	DCE_MailUtils.monthlyMailDigest(scope);
    }
    
    public void finish(Database.BatchableContext bc){
    	
    }
    
}