src/objects/DCE_ServiceAmend__c.object
<CustomObject>
    <description>Used within the Dementia Connect Extranet community to represent a new service (to be created within the Dementia Connect Database) or the amendment to an existing Service (to be updated within the Dementia Connect Database</description>
    <fields>
        <fullName>Accessibility__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the ‘Additional Information’ field below.</inlineHelpText>
        <label>Venue Accessibility</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <inlineHelpText>Add any other specific information on toilets/parking/refreshments/venue accessibility if required.</inlineHelpText>
        <label>Additional Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Advertising_Start_Date__c</fullName>
        <inlineHelpText>Enter date to promote your service on Dementia Connect before the service starts.</inlineHelpText>
        <label>Advertising Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Advertising_end_date__c</fullName>
        <inlineHelpText>Enter date to remove your service from Dementia Connect online directory. The service will remain open in the Portal.</inlineHelpText>
        <label>Advertising End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days__c</fullName>
        <inlineHelpText>Which days does your Service open?</inlineHelpText>
        <label>Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funder_restriction__c</fullName>
        <inlineHelpText>Enter if the service is restricted to a specific group based on location e.g. Residents of London Borough of Wandsworth only.</inlineHelpText>
        <label>Funder restriction</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Getting_There__c</fullName>
        <inlineHelpText>Record any additional information regarding public transport/directions by car or on foot.</inlineHelpText>
        <label>Getting There</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LastReviewed__c</fullName>
        <description>This field contains the date of last reviewed</description>
        <label>Last Reviewed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>National_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Service?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opening_Times_Guidebook__c</fullName>
        <inlineHelpText>Record the days and times the service is available in the following format: Monday and Thursday, 2pm -5pm</inlineHelpText>
        <label>Service Opening times</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operated_By__c</fullName>
        <description>Contains the Id of the organisation in Dementia Connect that this record will link to.</description>
        <label>Operated By</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parking__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the ‘Additional Information’ field below.</inlineHelpText>
        <label>Parking</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes-on site</fullName>
                </value>
                <value>
                    <fullName>Yes-off site</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_External__c</fullName>
        <inlineHelpText>This should be the name of the person who the public should contact about the service. This information will be kept for internal use only e.g. for signposting purposes.</inlineHelpText>
        <label>Public contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referral_only__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick this box if the service can only be accessed via a referral from health and social care professionals. Do not tick it if self-referrals are accepted.</inlineHelpText>
        <label>Referral  only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Refreshments__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the ‘Additional Information’ field below.</inlineHelpText>
        <label>Refreshments</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_telephone_number__c</fullName>
        <inlineHelpText>Additional telephone number for the service</inlineHelpText>
        <label>Secondary telephone number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ServiceId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Stores the value of the Service ID in the production system.</description>
        <externalId>true</externalId>
        <label>Dementia Connect - Service Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Criteria__c</fullName>
        <inlineHelpText>e.g. People with dementia only, carers or anyone.</inlineHelpText>
        <label>Who can use this service?</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Reference__c</fullName>
        <label>Service Reference</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Amendment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DCE_Amendment_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Line_1__c</fullName>
        <label>Street Line 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Line_2__c</fullName>
        <label>Street Line 2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Line_3__c</fullName>
        <label>Street Line 3</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Line_4__c</fullName>
        <label>Street Line 4</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Toilet_Facilities__c</fullName>
        <inlineHelpText>Select from the drop down list and record additional information in the ‘Additional Information’ field below.</inlineHelpText>
        <label>Toilet Facilities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>service_city__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_closedate__c</fullName>
        <inlineHelpText>Add a close date to mark this service as closed</inlineHelpText>
        <label>Close date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>service_country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_county__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_description__c</fullName>
        <inlineHelpText>Our Dementia Connect team may contact you with guidance if the service description requires more detail (max. 100 words)</inlineHelpText>
        <label>Service Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>service_email__c</fullName>
        <inlineHelpText>This should be the email address that service users can use to contact you about the service.</inlineHelpText>
        <label>Email address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>service_postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>service_status__c</fullName>
        <description>Defines the status of the service in Dementia Connect</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>service_street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>service_telephone__c</fullName>
        <inlineHelpText>This should be the telephone number that service users can use to contact you about the service.</inlineHelpText>
        <label>Telephone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Please select one option, most appropriate to the service.</inlineHelpText>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>Carer Support &amp; Groups</fullName>
                </value>
                <value>
                    <fullName>Carer Training</fullName>
                </value>
                <value>
                    <fullName>Counselling</fullName>
                </value>
                <value>
                    <fullName>Day care and support (establishment based)</fullName>
                </value>
                <value>
                    <fullName>Dementia cafe</fullName>
                </value>
                <value>
                    <fullName>Dementia Support &amp; Groups</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Home facilities &amp; services</fullName>
                </value>
                <value>
                    <fullName>Information and Advice (Dementia)</fullName>
                </value>
                <value>
                    <fullName>Information and Advice (Financial &amp; Legal)</fullName>
                </value>
                <value>
                    <fullName>Information programme</fullName>
                </value>
                <value>
                    <fullName>Lifestyle &amp; Wellbeing</fullName>
                </value>
                <value>
                    <fullName>Memory Assessment</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Online forum</fullName>
                </value>
                <value>
                    <fullName>Registered home care and support</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Residential/nursing home care</fullName>
                </value>
                <value>
                    <fullName>Respite</fullName>
                </value>
                <value>
                    <fullName>Social Services</fullName>
                </value>
                <value>
                    <fullName>Telephone helpline</fullName>
                </value>
                <value>
                    <fullName>Transport, Driving &amp; Mobility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>service_website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>DCE Service Creation or Amendment</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DCE Service Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DCE_ServiceAmendWrapper.cls
public without sharing class DCE_ServiceAmendWrapper extends DCE_ControllerUtils{
    
	private static map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
    private static map<String, Schema.SObjectField> ServiceAmendmentFieldMap = globalDescribe.get('dce_serviceamend__c').getDescribe().Fields.getMap();
    
    public static set<string> editingStatuses = new set<string>{'Draft', 'In Approval', 'Accepted - Pending Transfer'};
    
    @testVisible private static map<string, string> productionToPortalFieldMap{
    	get{
    		if(productionToPortalFieldMap != null){ return productionToPortalFieldMap; }
    		
    		productionToPortalFieldMap = new map<string, string>();
    		
    		productionToPortalFieldMap.put('Id', 'serviceid__c');
    		productionToPortalFieldMap.put('Portal_ID__c', 'Id');
    		productionToPortalFieldMap.put('Name', 'Name');
    		productionToPortalFieldMap.put('service_type__c', 'service_type__c');
    		productionToPortalFieldMap.put('service_description__c', 'service_description__c');
    		productionToPortalFieldMap.put('Opening_Times_Guidebook__c', 'Opening_Times_Guidebook__c');
    		productionToPortalFieldMap.put('service_email__c', 'service_email__c');
    		productionToPortalFieldMap.put('service_telephone__c', 'service_telephone__c');
    		productionToPortalFieldMap.put('Secondary_telephone_number__c', 'Secondary_telephone_number__c');
    		productionToPortalFieldMap.put('Street_Line_1__c', 'Street_Line_1__c');
    		productionToPortalFieldMap.put('Street_Line_2__c', 'Street_Line_2__c');
    		productionToPortalFieldMap.put('Street_Line_3__c', 'Street_Line_3__c');
    		productionToPortalFieldMap.put('Street_Line_4__c', 'Street_Line_4__c');
    		productionToPortalFieldMap.put('service_street__c', 'service_street__c');
    		productionToPortalFieldMap.put('service_street__c', 'service_street__c');
    		productionToPortalFieldMap.put('service_city__c', 'service_city__c');
    		productionToPortalFieldMap.put('service_county__c', 'service_county__c');
    		productionToPortalFieldMap.put('service_postcode__c', 'service_postcode__c');
    		productionToPortalFieldMap.put('service_country__c', 'service_country__c');
    		productionToPortalFieldMap.put('Additional_Information__c', 'Additional_Information__c');
    		productionToPortalFieldMap.put('Funder_restriction__c', 'Funder_restriction__c');
    		productionToPortalFieldMap.put('Getting_There__c', 'Getting_There__c');
    		productionToPortalFieldMap.put('National_Service__c', 'National_Service__c');
    		productionToPortalFieldMap.put('Operated_By__c', 'Operated_By__c');
    		productionToPortalFieldMap.put('Parking__c', 'Parking__c');
    		productionToPortalFieldMap.put('Price__c', 'Price__c');
    		productionToPortalFieldMap.put('Primary_Contact_External__c', 'Primary_Contact_External__c');
    		productionToPortalFieldMap.put('Referral_only__c', 'Referral_only__c');
    		productionToPortalFieldMap.put('Refreshments__c', 'Refreshments__c');
    		productionToPortalFieldMap.put('Last_Reviewed__c', 'LastReviewed__c');
    		productionToPortalFieldMap.put('Toilet_Facilities__c', 'Toilet_Facilities__c');
    		productionToPortalFieldMap.put('Accessibility__c', 'Accessibility__c');
    		productionToPortalFieldMap.put('service_website__c', 'service_website__c');
    		productionToPortalFieldMap.put('Advertising_Start_Date__c', 'Advertising_Start_Date__c');
    		productionToPortalFieldMap.put('Advertising_end_date__c', 'Advertising_end_date__c');
    		productionToPortalFieldMap.put('service_closedate__c', 'service_closedate__c');
    		productionToPortalFieldMap.put('Service_Criteria__c', 'Service_Criteria__c');
    		productionToPortalFieldMap.put('service_status__c', 'service_status__c');
    		productionToPortalFieldMap.put('Service_Reference__c', 'Service_Reference__c');
    		productionToPortalFieldMap.put('Days__c', 'Days__c');
    		productionToPortalFieldMap.put('Recurrence__c', 'Recurrence__c');
    		productionToPortalFieldMap.put('Start_time_Hours__c', 'Start_time_Hours__c');
    		productionToPortalFieldMap.put('Start_time_Minutes__c', 'Start_time_Minutes__c');
    		productionToPortalFieldMap.put('End_time_Hours__c', 'End_time_Hours__c');
    		productionToPortalFieldMap.put('End_time_Minutes__c', 'End_time_Minutes__c');
    		productionToPortalFieldMap.put('Opening_times_Other__c', 'Opening_times_Other__c');
    		productionToPortalFieldMap.put('Further_contact_requirements__c', 'Further_contact_requirements__c');
    		productionToPortalFieldMap.put('Reach__c', 'Reach__c');
    		productionToPortalFieldMap.put('Where_does_this_service_operate__c', 'Where_does_this_service_operate__c');
    		
    		return productionToPortalFieldMap;
    	}
    	
    	set;
    }
    
    public static string fieldsOfInterest{
    	get{
    		if(fieldsOfInterest != null){ return fieldsOfInterest; }
    		
    		fieldsOfInterest = '';
    		
    		for(string s : productionToPortalFieldMap.keySet()){
    			fieldsOfInterest += s+', ';
    		}
    		
    		fieldsOfInterest = fieldsOfInterest.substring(0, fieldsOfInterest.length()-2);
    		
    		return fieldsOfInterest;
    	}
    	
    	private set;
    }
    
    public static map<string, string> portalToProductionFieldMap{
    	public get{
    		if(portalToProductionFieldMap != null){ return portalToProductionFieldMap;}
    		
    		portalToProductionFieldMap = new map<string, string>();
    		
    		for(string s : productionToPortalFieldMap.keySet()){
    			string value = productionToPortalFieldMap.get(s);
    			
    			portalToProductionFieldMap.put(value, s);
    		}
    		
    		return portalToProductionFieldMap;
    	}
    	
    	private set;
    }
    
    public static string fieldsOfInterestPortal{
    	get{
    		if(fieldsOfInterestPortal != null){ return fieldsOfInterestPortal; }
    		
    		fieldsOfInterestPortal = '';
    		
    		for(string s : portalToProductionFieldMap.keySet()){
    			fieldsOfInterestPortal += s+', ';
    		}
    		
    		fieldsOfInterestPortal = fieldsOfInterestPortal.substring(0, fieldsOfInterestPortal.length()-2);
    		
    		return fieldsOfInterestPortal;
    	}
    	
    	private set;
    }
    
    public DCE_ServiceAmend__c amend{get; set;}
    
    /*This constructor will create a service Amendment record from a JSON string*/
    public DCE_ServiceAmendWrapper(string JSONString){
    	
    	amend = (DCE_ServiceAmend__c)DCE_JSONResponseConverter.DCE_JSONResponseConvertSingleRecord('dce_serviceamend__c', productionToPortalFieldMap, JSONString);
    	
    	system.debug('Here is the amendment with details - '+amend);
    	
    	if(amend==null){
    		system.debug('Error');
    		//displayPageError('No record can be found. Please check your URL and try again.');
    	} else {
	    	amend.DCEPartner__c = currentUser.AccountId;
	    	amend.ServiceOwner__c = currentUser.id;
	    	amend.Status__c = 'Draft';
    	}
    }
    
    public DCE_ServiceAmendWrapper(string JSONString, SObject existingRecord, string mode){
    	
    	amend = (DCE_ServiceAmend__c)DCE_JSONResponseConverter.DCE_JSONResponseConvertSingleRecord(existingRecord, productionToPortalFieldMap, JSONString);
    	
    	system.debug('Here is the amendment with details - '+amend);
    	
    	if(amend==null){
    		system.debug('Error');
    		//displayPageError('No record can be found. Please check your URL and try again.');
    	} else {
	    	if(mode=='edit'){
	    		amend.ServiceOwner__c = currentUser.id;
	    		amend.Status__c = 'Draft';
	    	}
    	}
    }
    
    //private static map<String, Schema.SObjectField> externalServiceFieldMap = globalDescribe.get('services_c__x').getDescribe().Fields.getMap();
    /*This constructor will create a service Amendment record from a provided Service from Dementia Connect
    public DCE_ServiceAmendWrapper(Services_c__x externalService){
    	
    	amend = new DCE_ServiceAmend__c();
    	
    	system.debug('externalServiceFieldMap - '+externalServiceFieldMap);
        system.debug('ServiceAmendmentFieldMap - '+ServiceAmendmentFieldMap);
        
        if (externalServiceFieldMap != null &&  ServiceAmendmentFieldMap != null){
        	
        	for (Schema.SObjectField ft : externalServiceFieldMap.values()){
        		
        		system.debug('ft - '+ft);
        		
        		Schema.DescribeFieldResult fd = ft.getDescribe();
        		
        		string externalName = fd.getName();
        		
        		system.debug('externalName - '+externalName);
        		
        		// Some fields we don't want to copy to the amendment
        		if(fieldsNotToCopy.contains(externalName)){ continue; }
        		
        		string amendName;
        		
        		if(externalName.contains('_c__c')){
        			amendName = externalName.replace('_c__c','__c');
        		} else if(externalName.contains('__c')) {
        			amendName = externalName.replace('__c','');
        		}
        		
        		system.debug('Amend Name - '+amendName);
        		
        		system.debug('ServiceAmendmentFieldMap.containsKey(amendName) - '+ServiceAmendmentFieldMap.containsKey(amendName));
        		
        		if(!ServiceAmendmentFieldMap.containsKey(amendName)){ continue; }
        		
        		Schema.DescribeFieldResult fdAmend = ServiceAmendmentFieldMap.get(amendName).getDescribe();
        		
        		system.debug('ServiceAmendmentFieldMap.get(amendName).getDescribe() - '+ServiceAmendmentFieldMap.get(amendName).getDescribe());
        		
        		system.debug('fd.getType() - '+fd.getType());
        		system.debug('fdAmend.getType() - '+fdAmend.getType());
        		
        		if(fd.getType() == fdAmend.getType() || (fieldTypeMappings.get(fdAmend.getType().name()) != null && fieldTypeMappings.get(fdAmend.getType().name()).contains(fd.getType().name()))){ 
        		
	        		system.debug('fdAmend.isUpdateable() - '+fdAmend.isUpdateable());
	        		
	        		if(!fdAmend.isUpdateable()){ continue; }
	        		
	        		system.debug('Putting in this value - '+externalService.get(fd.getName()));
	        		
	        		amend.put(amendName, externalService.get(fd.getName()));
        		}
        	}
        }
    }*/  
    
    //private static set<string> fieldsNotToCopy = new set<string>{'id','createdbbByid','createddate','lastmodifiedbyid','lastmodifieddate','systemmodstamp','service_reference__c', 'recordtypeId'};
    
	/*This map allows certain field types in External Objects to be moved into the objects in this one
    private static map<string, set<string>> fieldTypeMappings{
    	
    	private get{
    		if(fieldTypeMappings != null){ return fieldTypeMappings;}
    		
    		fieldTypeMappings = new map<string, set<string>>();
    		
    		fieldTypeMappings.put('PICKLIST', new set<string>{'STRING'});
    		
    		return fieldTypeMappings;
    	}
    	
    	private set;
    
    }*/
}