src/objects/DCE_ServiceAmend__c.object
<CustomObject>
    <description>Used within the Dementia Connect Extranet community to represent a new service (to be created within the Dementia Connect Database) or the amendment to an existing Service (to be updated within the Dementia Connect Database</description>
    <fields>
        <fullName>DCEPartner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dementia Connect External Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ServiceChanges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastReviewed__c</fullName>
        <description>This field contains the date of last reviewed</description>
        <label>Last Reviewed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Operated_By__c</fullName>
        <description>Contains the Id of the organisation in Dementia Connect that this record will link to.</description>
        <label>Operated By</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Stores the value of the Service ID in the production system.</description>
        <externalId>true</externalId>
        <label>Dementia Connect - Service Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ServiceOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Holds the Service Owner - We do not use the actual owner field as that can only be updated by the actual owner or an admin, etc.</description>
        <inlineHelpText>We will contact you to request an update to the information you have submitted and to send you updates about the service from time to time.</inlineHelpText>
        <label>Service Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Reference__c</fullName>
        <label>Service Reference</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Amendment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DCE_Amendment_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>service_status__c</fullName>
        <description>Defines the status of the service in Dementia Connect</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <inlineHelpText>Please select one option, most appropriate to the service.</inlineHelpText>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>Carer Support &amp; Groups</fullName>
                </value>
                <value>
                    <fullName>Carer Training</fullName>
                </value>
                <value>
                    <fullName>Counselling</fullName>
                </value>
                <value>
                    <fullName>Day care and support (establishment based)</fullName>
                </value>
                <value>
                    <fullName>Dementia cafe</fullName>
                </value>
                <value>
                    <fullName>Dementia Support &amp; Groups</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Home facilities &amp; services</fullName>
                </value>
                <value>
                    <fullName>Information and Advice (Dementia)</fullName>
                </value>
                <value>
                    <fullName>Information and Advice (Financial &amp; Legal)</fullName>
                </value>
                <value>
                    <fullName>Information programme</fullName>
                </value>
                <value>
                    <fullName>Lifestyle &amp; Wellbeing</fullName>
                </value>
                <value>
                    <fullName>Memory Assessment</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Online forum</fullName>
                </value>
                <value>
                    <fullName>Registered home care and support</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Residential/nursing home care</fullName>
                </value>
                <value>
                    <fullName>Respite</fullName>
                </value>
                <value>
                    <fullName>Social Services</fullName>
                </value>
                <value>
                    <fullName>Telephone helpline</fullName>
                </value>
                <value>
                    <fullName>Transport, Driving &amp; Mobility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DCE Service Creation or Amendment</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DCE Service Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DCE_Dashboard_Controller.cls
public with sharing class DCE_Dashboard_Controller extends DCE_ControllerUtils{
    
    public void initiation(){
    	loginRedirect();
    	services = services;
    	//initiateServices();
    	
    	/*
    	if(pageMessage != null){
    		displayPageMessage = true;
    		
    	}*/
    }
	
	public list<serviceHolder> services {
    	public get{
    		if(services != null){ return services; }
    		
    		//First query live Salesforce for the latest versions of all this partner's services
    		string queryEndPoint = WEBC_CommunityWrapper.getCustomSetting('RestEndpoint','DCE')+'/services/data/v35.0/query';
			queryEndPoint += '?q='+EncodingUtil.urlEncode('select id, Name, Service_Type__c, last_reviewed__c, Service_Reference__c, service_status__c from Services__c where Operated_By__c = \''+CRSAccountId+'\'', 'UTF-8'); //where Operated_By__c = \'0013E000001QUSy\'
			
			DCE_RestConnector restConnection = new DCE_RestConnector(queryEndPoint, 'GET');
			
			if(restConnection != null && restConnection.res != null){ system.debug('Here is the response body - '+restConnection.res.getbody()); }
			
			if(restConnection.restError){
				
				displayPageError(restConnection.restErrorMessage);
				return null;
			} else {
				
				map<string, Object> m = (map<string, Object>)JSON.deserializeUntyped(restConnection.res.getbody());
	    		
	    		system.debug('Here is the map - '+m);
	    		
	    		//Here are the returned records from live
	    		list<Object> returnedRecords = (list<Object>)m.get('records');
	    		
	    		services = new list<serviceHolder>();
	    		
	    		list<DCE_ServiceAmend__c> notYetInPortal = new list<DCE_ServiceAmend__c>();
	    		
	    		for(Object o : returnedRecords){
	    			map<string, Object> rMap = (map<string, Object>)o;
	    			
	    			system.debug('rMap.get(Id) - '+rMap.get('Id'));
	    			system.debug('rMap for this record - '+rMap);
	    			system.debug('Existing Amendment - '+amendmentMap.get((string)rMap.get('Id')));
	    			
	    			//Get the version of the amend that is in the portal
	    			DCE_ServiceAmend__c amend = amendmentMap.get((string)rMap.get('Id'));
	    			
	    			//If there isn't a version in the portal, create a basic version of it now
	    			if(amend == null){
	    				
	    				system.debug('No existing amendment in the portal');
	    				
	    				amend = new DCE_ServiceAmend__c(Name = (string)rMap.get('Name'), ServiceId__c = (string)rMap.get('Id'), Status__c='Accepted - Transfer Complete', DCEPartner__c=userWithDCEDetails.AccountId, ServiceOwner__c=userWithDCEDetails.id, Operated_By__c = CRSAccountId);
	    					
	    				amend.service_type__c = rMap.get('service_type__c') == null ? null : (string)rMap.get('service_type__c'); 
	    				amend.lastReviewed__c = rMap.get('Last_Reviewed__c') == null ? null : Date.valueOf((string)rMap.get('Last_Reviewed__c'));
	    				amend.service_status__c = rMap.get('service_status__c') == null ? null : (string)rMap.get('service_status__c');
	    				amend.service_reference__c = rMap.get('Service_Reference__c') == null ? null : (string)rMap.get('Service_Reference__c');
	    					
	    				notYetInPortal.add(amend);
	    				continue;
	    			}
	    			
	    			services.add(new serviceHolder((string)rMap.get('Name'), (string)rMap.get('Id'), (string)rMap.get('service_type__c'), (string)rMap.get('service_status__c'), amend));//, amendmentMap.containsKey((string)rMap.get('Id'))
	    		}
	    		
	    		if(notYetInPortal.size() > 0){
    				
    				system.debug('WE NEED TO ADD - '+notYetInPortal);
    				
    				list<Database.SaveResult> results = database.insert(notYetInPortal, false);
    				system.debug('Save result size - '+results);
    				
    				for(integer i = 0 ; i <results.size() ; i++){
    					
    					system.debug('Here is the save result - '+results[i]);
    					
    					Database.SaveResult result = results[i];
    					
    					if(result.isSuccess()){
    						
    						system.debug('Success');
    							
    						DCE_ServiceAmend__c amend = notYetInPortal[i];
    						
    						services.add(new serviceHolder(amend.Name, amend.ServiceId__c, amend.service_type__c, amend.service_status__c, amend));
    						
    						system.debug('services after adding new - '+services);
    					}
    					
    				}
    			}
			}
		
			//Pick up the amendments in the system that aren't yet in Dementia Connect
			for(DCE_ServiceAmend__c amend : Amendments){
				
				system.debug('Cycling through existing - '+amend);
				
				if(amend.ServiceId__c == null){
					
					system.debug('Not yet in the portal');
					
					services.add(new serviceHolder(amend.Name, null, amend.service_type__c, '', amend));
				}
			}
    		
    		if((services == null || services.size() == 0)){
    			displayPageSuccess('Your organisation does not currently have any services listed. If you would like to create one, start by clicking the "New service" button.');
    		}
    		
    		system.debug('services - '+services);
    		return services;
    	}
    	
    	private set;
	}
    
    /*A map of the services in the portal, keyed by their LIVE Id*/
    public map<string, DCE_ServiceAmend__c> amendmentMap{
    	public get{
    		if(amendmentMap != null){ return amendmentMap; }
    		
    		amendmentMap = new map<string, DCE_ServiceAmend__c>();
    		
    		for(DCE_ServiceAmend__c sa : Amendments){
    			if(sa.ServiceId__c != null){ amendmentMap.put(sa.ServiceId__c, sa); }
    		}
    		
    		return amendmentMap;
    	}
    	
    	private set;
    }
    
    /*The record for the partner account in the portal*/
    public Account partnerAccount{
    	public get{
    		if(partnerAccount != null){ return partnerAccount;}
    		
    		partnerAccount = [select id, Name,billingstreet, billingcity,billingstate,billingcountry,billingPostalCode,Phone
    							from Account
    							where id = :userWithDCEDetails.accountId];
    		
    		
    		system.debug('Here is the partner account - '+partnerAccount);
    		
    		return partnerAccount;
    	}
    	
    	private set;
    }
    
    public DCE_Dashboard_Controller(){
    	//services = services;
    }
    
    /*Wrapper class to display the Services on the page*/
    public class serviceHolder{
    	
		public string Name{get;set;}
		public string Id{get;set;}
		public string serviceType{get; set;}
		public DCE_ServiceAmend__c amend{get; set;}
        public string liveServiceStatus{get; set;}
        
        /*public boolean hasDraft{get; set;}
        public string status{get; set;}*/
    	
    	public serviceHolder(string Name, string Id, string ServiceType, string liveServiceStatus, DCE_ServiceAmend__c amend){
    		this.Name = Name;
    		this.Id = Id;
    		this.serviceType = serviceType;
    		this.liveServiceStatus = liveServiceStatus;
            
            this.amend = (amend != null) ? amend : new DCE_ServiceAmend__c(status__c ='Live');
    	}
    	
    }
    
    /*public string getBaseUrl(){
    	return system.URL.getSalesforceBaseUrl().ToExternalForm();
    }
    
    public string getBaseUrlHost(){
    	return system.URL.getSalesforceBaseUrl().getHost();
    }*/
    
    
}