src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>About_me__c</fullName>
        <label>About me</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Champion_Training__c</fullName>
        <label>Date of Champion Training</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interests__c</fullName>
        <label>Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Audience: Children</fullName>
                </value>
                <value>
                    <fullName>Audience: Young adults</fullName>
                </value>
                <value>
                    <fullName>Audience: Large groups</fullName>
                </value>
                <value>
                    <fullName>Audience: Black, Asian and minority ethnic communities</fullName>
                </value>
                <value>
                    <fullName>Audience: Adults with a learning disability</fullName>
                </value>
                <value>
                    <fullName>Audience: D/deaf</fullName>
                </value>
                <value>
                    <fullName>Audience: Adults with a visual impairment</fullName>
                </value>
                <value>
                    <fullName>Languages: BSL</fullName>
                </value>
                <value>
                    <fullName>Languages: Other</fullName>
                </value>
                <value>
                    <fullName>Languages: Welsh</fullName>
                </value>
                <value>
                    <fullName>Sector: Health &amp; social care</fullName>
                </value>
                <value>
                    <fullName>Sector: Retail</fullName>
                </value>
                <value>
                    <fullName>Sector: Finance</fullName>
                </value>
                <value>
                    <fullName>Sector: Leisure &amp; tourism</fullName>
                </value>
                <value>
                    <fullName>Sector: Housing</fullName>
                </value>
                <value>
                    <fullName>Sector: Utilities</fullName>
                </value>
                <value>
                    <fullName>Sector: Transport</fullName>
                </value>
                <value>
                    <fullName>Sector: Faith groups</fullName>
                </value>
                <value>
                    <fullName>Skills: Promotion</fullName>
                </value>
                <value>
                    <fullName>Skills: Working with the press</fullName>
                </value>
                <value>
                    <fullName>Skills: IT</fullName>
                </value>
                <value>
                    <fullName>Skills: Social media</fullName>
                </value>
                <value>
                    <fullName>Other: Local Dementia Friendly Community</fullName>
                </value>
                <value>
                    <fullName>Other: Rural communities</fullName>
                </value>
                <value>
                    <fullName>Other: Events</fullName>
                </value>
                <value>
                    <fullName>Other: Campaining</fullName>
                </value>
                <value>
                    <fullName>Other: Volunteering</fullName>
                </value>
                <value>
                    <fullName>Other: Fundraising</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c &amp; &quot;,  &quot; &amp; First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Interests__c</fullName>
        <label>Other Interests</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordType Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Completed_Info_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total No of Completed Info Sessions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Why_do_you_want_to_become_a_Champion__c</fullName>
        <label>Why do you want to become a Champion?</label>
        <type>TextArea</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ExchangeDFCDetailController_Test.cls
@isTest
public without sharing class ExchangeDFCDetailController_Test {
	

	@testSetup
    static void setupData() {  ExchangeDataFactory_Test.TestDataCreation(); }

	
	@isTest static void test_method_one() {

	   User u = [SELECT Id FROM User WHERE Email = 'test.testcontact@myemail.com'];
	   DF_Contact__c dfc = [SELECT About_me__c,Date_of_Champion_Training__c,Title__c,city__c,Why_do_you_want_to_become_a_Champion__c,First_Name__c,name__c,name,recordtype_name__c,County__c,Total_No_of_Friends_Created__c,Total_No_of_Completed_Info_Sessions__c,interests__c,Other_interests__c FROM DF_Contact__c WHERE Email__c = 'test.testcontact@myemail.com'];          
      system.runAs(u){
       Test.startTest();
      //  system.assertEquals(null,ExchangeDFCDetailController.getDFCDetails(u.Id));
       system.assertNotEquals(null,ExchangeDFCDetailController.getpickval());
       system.assertEquals(u.id,ExchangeDFCDetailController.getCurrentUser());
       ExchangeDFCDetailController.getCurrentUserName();
        system.assertNotEquals(null,ExchangeDFCDetailController.getUserProfile(u.id));
        ExchangeDFCDetailController.saveDFC(dfc);
        ExchangeDFCDetailController.cancelSave(dfc);
        Test.stopTest();
      }
	}

	
	
}