src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>BirthDate__c</fullName>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact_Inbound_Change__c.object
<CustomObject>
    <description>Changes to DF contact records on progress</description>
    <fields>
        <fullName>BirthDate__c</fullName>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Contact Inbound Changes</relationshipLabel>
        <relationshipName>DF_Contact_Inbound_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact Inbound Change</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>DF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF Contact Inbound Changes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DF_WEBC_InboundChangesToDFCController.cls
public without sharing class DF_WEBC_InboundChangesToDFCController extends DF_WEBC_ControllerBase {
   
    public Boolean isChampion {get;set;}
    public DF_Contact__c master{get;set;}
    public DF_Contact_Inbound_Change__c child{
     get{
        if( child==null)
        child = new DF_Contact_Inbound_Change__c();      
        return child;
    
        }  
     set;
    }
   
    
    public DF_WEBC_InboundChangesToDFCController(){
        master =  new DF_Contact__c();
        currentDfc = DF_Utils.getDFContactForUser(UserInfo.getUserId());            
        dfcW = new DF_Contact_Wrapper(currentDfc);
        isChampion = DF_Utils.isChampion(currentDfc);  
            
        
        child = [Select Name,First_Name__c,Last_Name__c ,Postcode__c,City__c ,Street__c,
               County__c,Birthdate__c,Title__c,Contact_Number__c 
               from DF_Contact_Inbound_Change__c
               where Related_DF_Contact__c =:currentdfc.id limit 1];
               system.debug('child record'+child);
        master = [Select Name,First_Name__c,Last_Name__c ,Postcode__c,City__c ,Street__c,
               County__c,Birthdate__c,Title__c,Contact_Number__c 
               from DF_Contact__c
               where id =:currentdfc.id limit 1];
               
       
    }
    
    
    
    
    public pageReference autoRunCopyChanges(){
        
    pageReference pr;
    Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
     Map<String, Schema.SObjectField> tFields = schemaMap.get('DF_Contact__c').getDescribe().fields.getMap();
     Map<String, Schema.SObjectField> sFields = schemaMap.get('DF_Contact_Inbound_Change__c').getDescribe().fields.getMap();
     DF_Contact__c obTarget = master;     

    DF_Contact_Inbound_Change__c obSource = ( DF_Contact_Inbound_Change__c )DF_Utils.objectWithAllFields('id',child.id, Schema.sObjectType.DF_Contact_Inbound_Change__c );
  // for (String fieldName: cFields.keySet()) {
    for (Schema.SObjectField f : tFields.values()) {

        Schema.DescribeFieldResult fd = f.getDescribe(); 
         if ( !fd.isUpdateable() ) continue;
        if ( sFields.get(fd.getName())==null ) continue;
        if ( fd.getName()== 'ownerid' ) continue;
        if ( fd.getName()=='RecordTypeId' ) continue;
        if ( fd.getName()=='Name' ) continue;
        if (obSource.get(fd.getName())==null) continue;
        obTarget.put(f,obSource.get(fd.getName()));
   
      }
      update obTarget;
   
        delete child;
        pr = page.DF_WEBC_ViewMyDetails;
        return pr;
    }
    
    public DF_Contact__c getDFContactDetails(String Id){
        return [Select Name,First_Name__c,Last_Name__c ,Postcode__c,City__c ,Street__c,
               County__c,Birthdate__c,Title__c,Contact_Number__c from DF_Contact__c
               where Id =:Id];
        
    }
    
    public pagereference reject(){
        try{
        delete child;
        }catch (Exception e){}
        
        return new PageReference('/user-home');
        
    }
    
    
    
}