src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portal_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchUpdateUserIdOnDFContacts_Test.cls
@isTest
public class BatchUpdateUserIdOnDFContacts_Test {
/*  
***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            10-08-2015
     * @description     Test class for BatchUpdateUserIdOnDFContacts
***********************************************************************************************/

static testMethod void CoverMethod () {

   
   Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();   
   DF_Contact__c Dc = (DF_Contact__c )mapTestData.get('DFc');
   BatchUpdateUserIdOnDFContacts batch = new BatchUpdateUserIdOnDFContacts();
  // batch.query =  'Select ID, Portal_Contact__c ,Portal_User__c from DF_Contact__c  where  id=DFc.id';
   test.starttest();
   Database.executeBatch( batch,4);
   

}
}