src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c &amp; &quot;,  &quot; &amp; First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Admin</fullName>
        <active>true</active>
        <label>Admin</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PO_Administrator__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>PO Administrators</relationshipLabel>
        <relationshipName>PO_Administrators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>DF_Contact__r.Email__c</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invited_Email__c</fullName>
        <label>Invited Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invited_Name__c</fullName>
        <label>Invited Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>PO Administrators</relationshipLabel>
        <relationshipName>PO_Administrators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PO Administrator</label>
    <nameField>
        <displayFormat>POA{000000}</displayFormat>
        <label>POA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Administrators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_WEBC_ManagePartnerAdmins_Ctr.cls
global without sharing class DF_WEBC_ManagePartnerAdmins_Ctr extends DF_WEBC_ControllerBase {
  
  public final String ID_PARAM = 'Id';
  public boolean hasActions {get; set;} 
  public static Id partnerId{get; set;} 
  public List<AdminWrapper> AdminsWrappersList {get;set;} 
  public string email { get;set;}
  public string name { get;set;} 
  public string nameError { get;set;}  
  
     
  @RemoteAction
  global static Holder handleinvites(String email,string orgId) {
  
  	boolean isError;
    Holder holder = new Holder();
    holder.isInvite = false; 
    holder.isUser = false; 
    holder.emailError='' ;
   //validate email address     
    if(email==null || email.length() <=0){ 
    
    holder.emailError = 'Please enter email.';
    isError =true;
    }
            
    if( email.length()>0 && !DFP_Utils.validEmail(email)){
    
    holder.emailError = 'Enter valid email.';
    isError =true;
    }        
    
    if( email.length()>0 && DFP_Utils.isExistingAdmin(email,orgId)){ 
    holder.emailError = 'Existing admin.';
    isError =true;
   }
   if(email.length()>0 && DFP_Utils.validEmail(email) &&! DFP_Utils.isExistingAdmin(email,orgId)){
   	holder.emailError='';
  List<User> lisUser = [select id from User where UserName = :email];
      
   if(lisUser.isEmpty()){
   	
   	 holder.isInvite = true;  
   }else {
   	
   	 holder.isUser = true;   
   
   }
   }
   return holder;

  } 
  
  global class Holder  
  {    
  //data holder for remote action	   
       public String emailError = '';
       public Boolean isInvite ;
       public Boolean isUser ;
  }
  
 

 public List<AdminWrapper> getAdminList() {
 //wrapper list to display existing admins on org 
  if (AdminsWrappersList == null){
       AdminsWrappersList  = new List<AdminWrapper>();

  for (PO_Administrator__c admin : [select Status__c,Invited_Email__c, Invited_Name__c,DF_Contact__r.Name__c,DF_Contact__r.First_Name__c,DF_Contact__r.Last_Name__c,DF_Contact__r.Email__c,Partner_Organisation__c from PO_Administrator__c
      
      where Partner_Organisation__c=:ApexPages.currentPage().getParameters().get(ID_PARAM) and Status__c in('Registered','Invited') order by createddate desc]){

            AdminsWrappersList.add(new AdminWrapper(admin));
       }
   } 
   return  AdminsWrappersList ;
}


    
public Pagereference SaveAdmin() {
//remove admins
  List<PO_Administrator__c> adminsSelected = new List<PO_Administrator__c>();
  List<PO_Administrator__c> adminsToUpdate = new List<PO_Administrator__c>();        
  List<PO_Administrator__c> adminsToInsert = new List<PO_Administrator__c>(); 
        
  for (AdminWrapper a: getAdminList() )  {

          if (a.updatedAdmin == True){

              if (a.admin.id != null){
              adminsSelected.add(a.admin);}
             }
      }
                
    for(PO_Administrator__c ad : adminsSelected){
              ad.Status__c = 'Inactive';
              adminsToUpdate.add(ad);
     }
        system.debug ('adminsSelected.size()@@@ '+ adminsSelected.size());
      // disable removing all admins linked with the org  
      if((getAdminList().size()-adminsSelected.size())<1){  
      
       ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Cannot remove all administrators.');
       ApexPages.addMessage(myMsg );return null;
      }
      else{
       update adminsToUpdate;
       AdminsWrappersList=null; 
      }
       

       
       
       return null;
   }


  public DF_WEBC_ManagePartnerAdmins_Ctr(){
  //constructor
   partnerId = ApexPages.currentPage().getParameters().get(ID_PARAM);
   hasActions = DFP_Utils.hasActions(partnerId);
 
  }
  
 
 
 
 public pageReference  addAdmin(){
 //get the user that the email address linked with   
 List<User> lisUsers =[select id from User where UserName = :email]; 
    
 if(lisUsers.size()>0 && email.length()>0 )   {
     system.debug('lisUser@@@@@@@@@@ ' + lisUsers);
    //add admin to wrapper list
     AdminsWrappersList.add(new AdminWrapper(DFP_Utils.addAdministrator(partnerid,df_utils.getDFContactForUser(lisUsers[0].Id).Id)));
 }
     //refresh wrapperlist/existing admins list 
     getAdminList();
     return new PageReference('/manage-partner-admins?Id='+partnerId);
     
 }
 
 public pageReference invite(){
 
   if(name.length()>0 && email.length()>0){ 
   	 //add invite to wrapper list
 	AdminsWrappersList.add(new AdminWrapper(DFP_Utils.inviteAdministrator(partnerid,email,name)));
   }
   //refresh wrapperlist/existing admins list
   getAdminList();
   
   return new PageReference('/manage-partner-admins?Id='+partnerId);
 }
 
 public pageReference cancel(){
    
    return new PageReference('/manage-partner-admins?Id='+partnerId);
 }
 
 
 public class AdminWrapper

  {
     public PO_Administrator__c admin {get; private set;}
     public Boolean UpdatedAdmin {get; set;}
    
     public AdminWrapper(PO_Administrator__c a){
     UpdatedAdmin = false;
     admin = a;
     }

  }
  
}