src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DF_WEBC_ForgotPassword_Controller_Test.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Test Class for DF_WEBC_ForgotPassword_Controller
 *  Author  : Lakshmi Rajendram
 *  Date    : 12-03-2015
 *  Version : 0.1 Unit Test
 *
 *               
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ????                           
*******************************************************************************************/
@isTest
public with sharing class DF_WEBC_ForgotPassword_Controller_Test {
    
    
    static testMethod void doTest() {
      
       DF_WEBC_ForgotPassword_Controller ctl = new DF_WEBC_ForgotPassword_Controller();
       Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();  
       DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');
       test.starttest();
       ctl.emailAddress = dfc.Email__c;

       ctl.forgotPassword();

       Page_Snippet__c snip = ctl.forgotPasswordSnippet;

     }

    /* Test a bad email address */
    static testMethod void doTest2() {
      
       DF_WEBC_ForgotPassword_Controller ctl = new DF_WEBC_ForgotPassword_Controller();
       ctl.emailAddress = 'Somewhere@test.com';
       ctl.forgotPassword();

     }

    /* Test support methods */
    static testMethod void doTest3() {
      
       DF_WEBC_ForgotPassword_Controller ctl = new DF_WEBC_ForgotPassword_Controller();
       ctl.getLisForOrgAdmin('someone@test.com');

       Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData(); 
       DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');
       test.starttest();
       List<User> lis = new List<User>();
       lis.add((User)mapTestData.get('User'));
       ctl.handleLis(lis);
        test.stoptest();

     }     


}