src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Champion_Feedback_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This boolean shows or hides the &quot;Tell us how your session went&quot; button for requested info sessions</description>
        <label>Champion Feedback Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <label>Event End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Host_Feedback_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This boolean shows or hides the &quot;Tell us how your session went&quot; button for requested info sessions</description>
        <label>Host Feedback Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Of_Attendee_Records__c</fullName>
        <label>Number Of Attendees Booked</label>
        <summaryFilterItems>
            <field>DF_EventAttendee__c.Event_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>DF_EventAttendee__c.DF_Event__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Friends Logged</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Total session audience capacity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preference_1_Date__c</fullName>
        <label>Preference 1: Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preference_1_Period__c</fullName>
        <label>Preference 1: Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Morning (7am-12pm)</fullName>
                </value>
                <value>
                    <fullName>Afternoon (12pm-5pm)</fullName>
                </value>
                <value>
                    <fullName>Evening (5pm-10pm)</fullName>
                </value>
                <value>
                    <fullName>Any time</fullName>
                </value>
                <value>
                    <fullName>Specific time (hh:mm)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preference_2_Date__c</fullName>
        <label>Preference 2: Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preference_2_Period__c</fullName>
        <label>Preference 2: Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Morning (7am-12pm)</fullName>
                </value>
                <value>
                    <fullName>Afternoon (12pm-5pm)</fullName>
                </value>
                <value>
                    <fullName>Evening (5pm-10pm)</fullName>
                </value>
                <value>
                    <fullName>Any time</fullName>
                </value>
                <value>
                    <fullName>Specific time (hh:mm)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preference_3_Date__c</fullName>
        <label>Preference 3: Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preference_3_Period__c</fullName>
        <label>Preference 3: Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Morning (7am-12pm)</fullName>
                </value>
                <value>
                    <fullName>Afternoon (12pm-5pm)</fullName>
                </value>
                <value>
                    <fullName>Evening (5pm-10pm)</fullName>
                </value>
                <value>
                    <fullName>Any time</fullName>
                </value>
                <value>
                    <fullName>Specific time (hh:mm)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting for approval</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open - waiting for champion</fullName>
                </value>
                <value>
                    <fullName>Matched with champion</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Info_Session__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies Info Session records that were requested (as opposed to sessions offered up by a champion)</inlineHelpText>
        <label>Requested Info Session</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Session_Organiser_Firstname__c</fullName>
        <formula>Session_Organiser__r.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Session Organiser Firstname</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser_Lastname__c</fullName>
        <formula>Session_Organiser__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Session Organiser Lastname</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session Requester</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Events (Session Requester)</relationshipLabel>
        <relationshipName>Session_Requester</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Information Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DF_EventListingHelper.cls
/*
* Class to assist with the DF Community pages
* where the information sessions are shown for
* Dem Friends and Dem Champions
*/
public class DF_EventListingHelper {
    
    private static final String SESSION_RT = 'Dementia_Friend_Awareness_Session';
    private static final String STATUS_AVAILABLE = 'Available';
    private static final List<String> VALID_UPCOMING_STATUS_REQ_SESSION = new List<String>{'Waiting for approval', 'Open - waiting for champion','Matched with champion'};
    private static final String EVENT_STATUS_UNSUCCESSFUL = 'Cancelled';
    private static final List<String> REQUEST_STATUS_UNSUCCESSFUL = new List<String>{'Withdrawn','Unsuccessful'};
    private static final String STATUS_COMPLETED = 'Completed';
    private static final String STATUS_FULL = 'Full';
    private static String sdt = Datetime.now().format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().getDisplayName());
    private static Datetime dt = Datetime.valueOf(sdt);
    

    public static Map<String, List<DF_Event__c>> getDeliveredSessions(Id dfcId) {
    	// Delivered sessions are a combination of created sessions and champ-hosted requested sessions
    	Map<String, List<DF_Event__c>> deliveredSessionMap = new Map<String, List<DF_Event__c>>();
        Map<String, List<DF_Event__c>> createdSessionsMap = getCreatedSessions(dfcId);
        Map<String, List<DF_Event__c>> requestedSessionsMap = getRequestedSessions(true, false, dfcId);
        
        List<DF_Event__c> combinedListFeedback = new List<DF_Event__c>();
        combinedListFeedback.addAll(createdSessionsMap.get('eventsAwaitingFeedback'));
        System.debug('combinedList: ' + combinedListFeedback);
        combinedListFeedback.addAll(requestedSessionsMap.get('eventsAwaitingFeedback'));
        System.debug('combinedList: ' + combinedListFeedback);
        deliveredSessionMap.put('eventsAwaitingFeedback', combinedListFeedback);
        
        List<DF_Event__c> combinedListUpcoming = new List<DF_Event__c>();
        combinedListUpcoming.addAll(createdSessionsMap.get('upcomingEvents'));
        combinedListUpcoming.addAll(requestedSessionsMap.get('upcomingEvents'));
        deliveredSessionMap.put('upcomingEvents', combinedListUpcoming);
                   
        List<DF_Event__c> combinedListPast = new List<DF_Event__c>();
        combinedListPast.addAll(createdSessionsMap.get('pastEvents'));
        combinedListPast.addAll(requestedSessionsMap.get('pastEvents'));
        deliveredSessionMap.put('pastEvents', combinedListPast);
        
        return deliveredSessionMap;
    }
    
        public static Map<String, List<DF_Event__c>> getRequestedSessions(Boolean isChamp, Boolean isChampAndRequester, Id dfcId) {
        
        // Initialize the event lists
        Map<String,List<DF_Event__c>> sessionsMap = new Map<String, List<DF_Event__c>>();
        sessionsMap.put('eventsAwaitingFeedback', new List<DF_Event__c>());
        sessionsMap.put('upcomingEvents', new List<DF_Event__c>());
        sessionsMap.put('pastEvents', new List<DF_Event__c>());
        List<DF_Event__c> sessionsList = new List<DF_Event__c>();
        
        if(isChamp && isChampAndRequester) {
            
            sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                            Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                            Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                            Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                            FROM DF_Event__c 
                            WHERE Event_Status__c != :EVENT_STATUS_UNSUCCESSFUL 
                            AND Request_Status__c NOT IN :REQUEST_STATUS_UNSUCCESSFUL 
                            AND Session_Requester__c = :dfcId
                            AND Host_Feedback_Submitted__c = false
                            AND Event_End_Date_Time__c <= :dt 
                            AND RecordTypeId = :DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                            AND Requested_Info_Session__c = true
                            ORDER BY Event_Date_Time__c DESC];
            sessionsMap.put('eventsAwaitingFeedback', sessionsList);
            
            sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                            Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                            Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                            Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                            FROM DF_Event__c 
                            WHERE Session_Requester__c = :dfcId
                            AND Requested_Info_Session__c = true
                            AND Request_Status__c IN :VALID_UPCOMING_STATUS_REQ_SESSION 
                            AND Event_End_Date_Time__c >: dt 
                            AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                            ORDER BY Event_Date_Time__c DESC];
            sessionsMap.put('upcomingEvents', sessionsList);
            
            sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                            Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                            Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                            Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                            FROM DF_Event__c 
                            WHERE Session_Requester__c = :dfcId 
                            AND Host_Feedback_Submitted__c = true
                            AND Event_End_Date_Time__c <:dt 
                            AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                            AND Requested_Info_Session__c = true
                            ORDER BY Event_Date_Time__c DESC];
            sessionsMap.put('pastEvents', sessionsList);
            
        } else if(isChamp && !isChampAndRequester) {
            
            sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                            Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                            Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                            Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                            FROM DF_Event__c 
                            WHERE Event_Status__c != :EVENT_STATUS_UNSUCCESSFUL 
                            AND Request_Status__c NOT IN :REQUEST_STATUS_UNSUCCESSFUL 
                            AND Session_Organiser__c = :dfcId
                            AND Champion_Feedback_Submitted__c = false
                            AND Event_End_Date_Time__c <= :dt 
                            AND RecordTypeId = :DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                            AND Requested_Info_Session__c = true
                            ORDER BY Event_Date_Time__c DESC];
            sessionsMap.put('eventsAwaitingFeedback', sessionsList);
            
            sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                            Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                            Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                            Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                            FROM DF_Event__c 
                            WHERE Session_Organiser__c = :dfcId 
                            AND Request_Status__c = 'Matched with champion'
                            AND Event_End_Date_Time__c >: dt 
                            AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                            AND Requested_Info_Session__c = true
                            ORDER BY Event_Date_Time__c DESC];
            sessionsMap.put('upcomingEvents', sessionsList);
            
            sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                            Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                            Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                            Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                            FROM DF_Event__c 
                            WHERE Session_Organiser__c = :dfcId 
                            AND Champion_Feedback_Submitted__c = true
                            AND Event_Status__c = :STATUS_COMPLETED
                            AND Event_End_Date_Time__c <:dt 
                            AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                            AND Requested_Info_Session__c = true
                            ORDER BY Event_Date_Time__c DESC];
            sessionsMap.put('pastEvents', sessionsList);
        } else {
            
            sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c,
                            Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                            Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                            Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                            FROM DF_Event__c 
                            WHERE Event_Status__c != :EVENT_STATUS_UNSUCCESSFUL
                            AND Host_Feedback_Submitted__c = false
                            AND Session_Requester__c = :dfcId
                            AND Event_End_Date_Time__c <: dt 
                            AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) 
                            And RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                            ORDER BY Event_Date_Time__c DESC];
            sessionsMap.put('eventsAwaitingFeedback', sessionsList);
            
            sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                            Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                            Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                            Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                            FROM DF_Event__c 
                            WHERE Session_Requester__c = :dfcId
                            AND Request_Status__c IN :VALID_UPCOMING_STATUS_REQ_SESSION 
                            AND Event_End_Date_Time__c >: dt 
                            AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                            ORDER BY Event_Date_Time__c DESC];
            sessionsMap.put('upcomingEvents', sessionsList);
            
            sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                            Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                            Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                            Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                            FROM DF_Event__c 
                            WHERE Session_Requester__c = :dfcId
                            AND Host_Feedback_Submitted__c = true
                            AND Event_End_Date_Time__c <:dt 
                            AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                            ORDER BY Event_Date_Time__c DESC];
            sessionsMap.put('pastEvents', sessionsList);
            
        }
        
        System.debug('sessionsMap: ' + sessionsMap);
        return sessionsMap;
    }
    
    
    
    public static Map<String, List<DF_Event__c>> getCreatedSessions(Id dfcId) {
        
        // Initialize the event lists
        Map<String,List<DF_Event__c>> sessionsMap = new Map<String, List<DF_Event__c>>();
        sessionsMap.put('eventsAwaitingFeedback', new List<DF_Event__c>());
        sessionsMap.put('upcomingEvents', new List<DF_Event__c>());
        sessionsMap.put('pastEvents', new List<DF_Event__c>());
        List<DF_Event__c> sessionsList = new List<DF_Event__c>();
        
        sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                        Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                        Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                        Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                        FROM DF_Event__c 
                        WHERE Event_Status__c != :EVENT_STATUS_UNSUCCESSFUL
                        AND (Number_of_Attendees__c = 0 OR Number_of_Attendees__c = null) 
                        AND Requested_Info_Session__c = false
                        AND Session_Organiser__c = :dfcId
                        AND Event_End_Date_Time__c <=: dt 
                        AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                        ORDER BY Event_Date_Time__c DESC];
        sessionsMap.put('eventsAwaitingFeedback', sessionsList);
        
        sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                        Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                        Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                        Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                        FROM DF_Event__c 
                        WHERE Session_Organiser__c = :dfcId 
                        AND Requested_Info_Session__c = false
                        AND Event_End_Date_Time__c >: dt 
                        AND Event_Status__c = :STATUS_AVAILABLE 
                        AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                        ORDER BY Event_Date_Time__c DESC];
        sessionsMap.put('upcomingEvents', sessionsList);
        
        sessionsList = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, 
                        Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c, Session_Requester__c,
                        Requested_Info_Session__c, Preference_1_Date__c, Preference_1_Period__c, Preference_2_Date__c, Preference_2_Period__c, Preference_3_Date__c, Preference_3_Period__c,
                        Champion_Feedback_Submitted__c, Host_Feedback_Submitted__c
                        FROM DF_Event__c 
                        WHERE Session_Organiser__c = :dfcId
                        AND Requested_Info_Session__c = false
                        AND Event_Status__c = :STATUS_COMPLETED
                        AND Number_of_Attendees__c != 0 
                        AND Number_of_Attendees__c != null
                        AND Event_End_Date_Time__c <:dt 
                        AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                        ORDER BY Event_Date_Time__c DESC];
        sessionsMap.put('pastEvents', sessionsList);
        
        System.debug('sessionsMap: ' + sessionsMap);
        return sessionsMap;
    }
    
}