src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Created_As_Type__c</fullName>
        <description>What type of Friend was this contact originally created as</description>
        <label>Created As Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>Subscriber</fullName>
                </value>
                <value>
                    <fullName>Digital Friend</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Champion</fullName>
                </value>
                <value>
                    <fullName>Community Representative</fullName>
                </value>
                <value>
                    <fullName>Registration</fullName>
                </value>
                <value>
                    <fullName>DF Mailer</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Partner Organisation Admin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Digital_Friend_Signup_Time__c</fullName>
        <description>The date the DF Contact became a Digital Friend. This is the date the contact watched the video to 
4 mins and 10 seconds.</description>
        <inlineHelpText>When did the DF Contact watch the Video</inlineHelpText>
        <label>Digital Friend Signup Time</label>
        <type>DateTime</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Edt_Item__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text1__c</fullName>
        <inlineHelpText>Enter the text that you want to appear on the page in this field</inlineHelpText>
        <label>Text1</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text2__c</fullName>
        <label>Text2</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Editable Item</label>
    <nameField>
        <displayFormat>EDT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Editable Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ExchangeHeaderCmpController.cls
public without sharing class ExchangeHeaderCmpController{
   
    @AuraEnabled
    public static String Stub_Url(){
        
        return WEBC_CommunityWrapper.getCustomSetting('Stub_Url', 'DF');
       
    }
    
    
    @AuraEnabled
     public static String totalFriendCount() {
                


            /* June 2016. Change from Custom Setting to Editable Item */

            String sDate = '2015-4-18 00:00:00';
            String sBaseLine = '1000000';
            
            List<Edt_Item__c> items = [select Id, Text1__c, Text2__c from Edt_Item__c where Group__c = 'df-generic' and Key__c = 'total-friend-count' limit 1];
            if ( items.size() > 0 ) {
                 sBaseLine = items[0].Text1__c;
                 sDate = items[0].Text2__c;
            }

             Date dt = Date.valueOf(sDate);
             AggregateResult[] res = [select count(id) dc from DF_Contact__c 
                        where Digital_Friend_Signup_Time__c !=null AND Digital_Friend_Signup_Time__c>:dt
                        AND Created_As_Type__c ='Digital Friend'];
             
             Integer iDDF = (Integer)res[0].get('dc');

       

             Integer iBaseline = Integer.valueOf(sBaseLine);
         system.debug('count'+(iBaseline + iDDF).format());
             return (iBaseline + iDDF).format();

    }
    @AuraEnabled
    public static String getCurrentUser() {
      string toReturn;  
        if(UserInfo.getUserType()!='Guest'){
      toReturn =UserInfo.getUserId();
        system.debug('returned user'+toReturn);
        }
      return toReturn.substring(0, 15);
   }
  
}