src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pure360_Event_Report__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Pure360 Event Report</relationshipLabel>
        <relationshipName>Pure360_Event_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Pure360 Event Report</label>
    <nameField>
        <displayFormat>PE{00000}</displayFormat>
        <label>Pure360 Event Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pure360 Event Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_Pure360EventReportTriggerHander.cls
public class DF_Pure360EventReportTriggerHander{
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Handler Class contains the execution logic of the DF_Pure360EventReportTrigger .
 *  Author  : Lakshmi Vasudevan
 *  Date    : 27-10-2016
 *  Version : 0.1 Unit Test
 *               
 *  Modification History
 *  Date            Who         Description 
 *                           
*******************************************************************************************/

private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    
    public DF_Pure360EventReportTriggerHander(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
  
  
  
  public void OnBeforeInsert(Pure360_Event_Report__c[] eventReportLis, Map<ID, Pure360_Event_Report__c> eventReportMap){
    
    Set<String> emailSet = new Set<String>();
    Set<Id> dfcIds= new Set<Id>();
    Map<String,String> dfcEmailMap = new Map<String,String>();
    List<Pure360_Event_Report__c> eventReportsToUpdate = new List<Pure360_Event_Report__c>();
    List<DF_Contact__c> dfcToUpdate = new List<DF_Contact__c>();
    
    for(Pure360_Event_Report__c event :eventReportLis)
    {
      if(event.email__c !=null){
         
         emailSet.add(event.email__c);
       }
     
    }
    
    for(DF_contact__c dfc: [select Id,email__c from DF_Contact__c where email__c in : emailSet])
    {
    
       dfcEmailMap.put(dfc.email__c,dfc.Id);
    
    }
    
    for(Pure360_Event_Report__c ev :eventReportLis)
    {
      if(dfcEmailMap.get(ev.email__c)!=null){
      ev.DF_Contact__c = dfcEmailMap.get(ev.email__c);
      eventReportsToUpdate.add(ev);
      
       if(ev.Type__c =='OPTOUT'){
        dfcIds.add(dfcEmailMap.get(ev.email__c));
       }
      }
         
    }
    
    if(dfcIds.size()>0){
     for(DF_Contact__c dfc :[select Newsletters__c from DF_Contact__c where id in:dfcIds])
     {
     
       dfc.Newsletters__c = False;
       dfcToUpdate.add(dfc);
     }
     
    }
    
    update dfcToUpdate;
   // update eventReportsToUpdate;
  }
 

}