src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c &amp; &quot;,  &quot; &amp; First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DFC_Activity__c.object
<CustomObject>
    <description>Community Activities linked to a specific Focus Area</description>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Activity Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DFC Activity</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Alliance__c.object
<CustomObject>
    <description>Dementia Action Alliance</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>DFC Alliance</label>
    <nameField>
        <label>Alliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC Alliances</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DFC_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <description>The date the Annual Assessment was submitted</description>
        <inlineHelpText>The date the Annual Assessment was submitted</inlineHelpText>
        <label>Date Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_Number__c</fullName>
        <label>Year Number</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DFC Assessment</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>DFC Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Assessment_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Assessment</label>
        <referenceTo>DFC_Assessment__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>DFC Assessment Answer</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>DFC Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Assessment Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <fields>
        <fullName>Date_Approved__c</fullName>
        <description>The date the Community was approved</description>
        <label>Date Approved</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <description>The date the community was submitted for approval</description>
        <label>Date Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The Community Location</description>
        <inlineHelpText>You can give the name of the village / town / city, region and county for example.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Community Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DFC_Community_Action_Area__c.object
<CustomObject>
    <description>Links action areas to a community</description>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipLabel>DFC Community Action Area</relationshipLabel>
        <relationshipName>Action_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A brief description of how you plan to work towards to make your community dementia-friendly</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>DFC Community Action Area</label>
    <nameField>
        <displayFormat>DFCMA - {000000}</displayFormat>
        <label>Action Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Community Action Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Community_Representative__c.object
<CustomObject>
    <description>A person taking responsibility for meeting the requirements of the recognition process</description>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipName>Representatives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipName>DFC_Community_Representatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DFC Representative</label>
    <nameField>
        <displayFormat>DFCR - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Resource__c.object
<CustomObject>
    <description>Resources for Dementia Friendly Communities</description>
    <fields>
        <fullName>Applies_To_Status__c</fullName>
        <label>Applies To Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Resource Description</description>
        <inlineHelpText>Resource Description</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>Resource Title</inlineHelpText>
        <label>Title</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>DFC Resource</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>DFC Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Dfc_Util_Test.cls
@isTest
private class Dfc_Util_Test
{

    @testSetup
    public static void setupData() {

        Dfc_DataFactory_Test.TestDataCreation(); 

        // Set some of the focus areas to be selected
        List<DFC_Community_Action_Area__c> actions = [select id, Community__c, Selected__c from DFC_Community_Action_Area__c order by Community__c];
        String id = actions[0].Community__c;
        Integer i = 0;
        for ( DFC_Community_Action_Area__c action : actions ) { 

            String cid = action.Community__c;
            if ( cid != id ) { i = 0; }

            if ( i< 4 ) { action.Selected__c= true;}

        }

        update actions;

    }

    // test get communities, related activities and get invites
    // and a new unregistered representative
    @isTest
    static void itShould()
    {

        // Get the user linked to the Active Community with Assessment
        User u = [select Id from User where Email = 'test2.testcontact@myemail.com'];    
        DFC_Community__c comm = [select Id from DFC_Community__c limit 1];
        comm.Status__c = 'Active';
        update comm;

        test.startTest();

        // Run as a specific user
        System.runAs(u) {

         // Get the current Communities   
         List<DFC_Community__c> communities = Dfc_Util.getCommunitiesForCurrentUser();
         DFC_Community__c community = communities[0];
         System.assertEquals('Here Somewhere', community.Location__c);

         // Get an assessment
         DFC_Assessment__c assessment = Dfc_Util.getAssessmentForCommunityAndYear(community.Id, 1);
         System.assertEquals(1, assessment.Year_Number__c);
         
         DFC_Assessment__c assess = Dfc_Util.readAssessment(assessment.Id);
         DFC_Activity__c[] activities = Dfc_Util.readCommunityActivities(community.Id);

         // Get the community activities
         Object o = Dfc_Util.readCommunityActivitiesWithSigning(community.Id);

         o = Dfc_Util.getDraftContext(community);

         String contactId = Dfc_Util.getDfContactIdForCurrentUser();       
         DFC_Community_Representative__c invited = Dfc_Util.inviteRepresentative(community.Id, 'someonelese@myemail.com', 'Test Another');


       }


        test.stopTest();
    }

     // test create assessment
    @isTest
    static void itShould2()
    {

        // Get the user linked to the Active Community with Assessment
        User u = [select Id from User where Email = 'test1.testcontact@myemail.com'];    
        DFC_Community__c comm = [select Id, Name__c, Status__c from DFC_Community__c where Status__c = 'Draft'];
        comm.Status__c = 'Active';
        comm.Date_Submitted__c = system.today().addYears(-1).adddays(-1);
        comm.Date_Approved__c  = system.today().addYears(-1).adddays(-1);

        update comm;

        test.startTest();

        // Run as a specific user
        System.runAs(u) {

         DFC_Assessment__c assessment = Dfc_Util.getAssessmentForCommunityAndYear(comm.Id, 1);
         System.assertEquals(1, assessment.Year_Number__c);         

       }


        test.stopTest();
    }


    // test getting communities for DAA
    @isTest
    static void itShould3()
    {

        DFC_Alliance__c alliance = [select Id from DFC_Alliance__c where Name= 'DFC Test Alliance' limit 1];
        // In the Test Scenario, there are two communities linked to this Alliance
        List<DFC_Community__c> lis = Dfc_Util.getCommunitiesForDaa(alliance.Id);
        System.assertEquals(2, lis.size());

    }


    // Test getting find id for email
    @isTest
    static void itShould4()
    {

        List<DF_Contact__c> lis = [select Email__c from DF_Contact__c where Email__c = 'test1.testcontact@myemail.com'];
        String s = Dfc_Util.findIdForEmail('test1.testcontact@myemail.com', lis);

        System.assertEquals(lis[0].id, s);

    }

    // Update assessment
    @isTest
    static void itShould5()
    { 


        // Get the user linked to the Active Community with Assessment
        User u = [select Id from User where Email = 'test2.testcontact@myemail.com'];    

        test.startTest();

        // Run as a specific user
        System.runAs(u) {

         // Get the current Communities   
         List<DFC_Community__c> communities = Dfc_Util.getCommunitiesForCurrentUser();
         DFC_Community__c comm = communities[0];
         
         // Get an assessment
         DFC_Assessment__c assessment = Dfc_Util.getAssessmentForCommunityAndYear(comm.Id, 1);

         List<DFC_Assessment_Answer__c> answers = [select id from DFC_Assessment_Answer__c where Assessment__c =: assessment.id];
         Dfc_Util.updateAssessment(assessment.id, 'Submitted', answers);         
         
        }


    }

    // Activity and update Community methods
    @isTest
    static void itShould6()
    { 
          
          User u = [select Id from User where Email = 'test2.testcontact@myemail.com'];    

          test.startTest();

          DFC_Activity__c activity = [select id from DFC_Activity__c limit 1];
          DFC_Activity__c activity1 = Dfc_Util.readActivity(activity.id);

        // Run as a specific user
        System.runAs(u) {

          DFC_Community__c comm = Dfc_Util.getCommunitiesForCurrentUser()[0];
          List<DFC_Community_Action_Area__c> areas = [select id from DFC_Community_Action_Area__c where Community__c =: comm.id];
          String[] ids = new String[]{};
          for ( DFC_Community_Action_Area__c area : areas ) { ids.add(area.id); }

          activity = new DFC_Activity__c(
                Title__c = 'Activity 1',
                Description__c = 'Activity Description',
                Community__c = comm.Id,
                Start__c =  system.today() + 90);
    
           Map<String, Object> result = Dfc_Util.addActivity(comm.id, activity, ids);
            
           activity.Title__c = 'Updated'; 
           result = Dfc_Util.updateActivity(activity, ids);

           // Update the Community
           comm.Name__c = 'Updated';
           DFC_Community__c comm2 = Dfc_Util.updateCommunity(comm, areas);

           // Update the action areas
           List<DFC_Community_Action_Area__c> areas2 = Dfc_Util.updateActionAreas(comm.id, areas);

           //Validate the Community
           Dfc_Util.validateCommunity(comm);

        }

        // Add an attachment 
        Attachment attach=new Attachment();

        attach.Name='Unit Test Attachment ';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.Body=bodyBlob;
        attach.ParentId=activity.id;
        attach.ContentType = 'application/msword';
        attach.IsPrivate = false;
        attach.Description = 'Test';

        insert attach;

        System.runAs(u) {

          Object o = Dfc_Util.removeActivityAttachment(activity.id, attach.id);
          List<DFC_Community_Action_Area__c> actions = Dfc_Util.removeActivity(activity.Id);


        }


  }


    // Create Community
    @isTest
    static void itShould7()
    { 

        // Get the user linked to the Active Community with Assessment
        User u = [select Id from User where Email = 'test2.testcontact@myemail.com'];    

        test.startTest();

        // Run as a specific user
        System.runAs(u) {

            DFC_Community__c comm = Dfc_Util.createNewCommunity();
         
        }


    }

    // Active Context
    @isTest
    static void itShould8()
    { 

        // Get the user linked to the Active Community with Assessment
        User u = [select Id from User where Email = 'test2.testcontact@myemail.com'];    

        test.startTest();

        // Run as a specific user
        System.runAs(u) {

         // Get the current Communities   
         List<DFC_Community__c> communities = Dfc_Util.getCommunitiesForCurrentUser();
         DFC_Community__c comm = communities[0];

         Dfc_CommunityContext context = Dfc_Util.getActiveContext(comm);        
         
        }


    }

   // Activity Methods
    @isTest
    static void itShould9()
    { 

        // Get the user linked to the Active Community with Assessment
        User u = [select Id from User where Email = 'test2.testcontact@myemail.com'];    

        test.startTest();

        // Run as a specific user
        System.runAs(u) {

         // Get the current Communities   
         List<DFC_Community__c> communities = Dfc_Util.getCommunitiesForCurrentUser();
         DFC_Community__c comm = communities[0];

         Dfc_CommunityContext context = Dfc_Util.getActiveContext(comm);        
         
        }


    }


    // Add a new representative methods
    @isTest
    static void itShould10()
    { 

        // Get the user linked to the Active Community with Assessment
        User u = [select Id from User where Email = 'test2.testcontact@myemail.com'];    

        test.startTest();

        // Run as a specific user
        System.runAs(u) {

         // Get the current Communities   
         List<DFC_Community__c> communities = Dfc_Util.getCommunitiesForCurrentUser();
         DFC_Community__c comm = communities[0];

         DFC_Community_Representative__c  rep = Dfc_Util.addRepresentative(comm.Id, 'someonenew@myemail.com');

         rep = Dfc_Util.addRepresentative(comm.id, 'test4.testcontact@myemail.com');         

         Dfc_Util.deleteRepresentative(comm.id, rep.id);

        }


    }

    // Signed payload
    @isTest
    static void itShould11()
    { 

        String s = 'payload';
        String payload = Dfc_Util.createSignedPayload(s);
        String result = Dfc_Util.extractSignedPayload(payload);

    }
    
  

    // Snippetts
    @isTest
    static void itShould12()
    { 


        Page_Snippet__c snip = new Page_Snippet__c();
        snip.Name__c = 'x';
        snip.Unique_Name__c = 'x';
        snip.Body_Text__c = 'x';
        insert snip;

        String s = Dfc_Util.readSnippet('x');
        snip.Body_Text__c = 'y';

        Dfc_Util.updateSnippet(snip);



    }

    // Resources
    @isTest
    static void itShould13()
    { 


        DFC_Resource__c res = new DFC_Resource__c();
        res.Title__c = 'x';
        res.Description__c = 'x';
        res.Applies_To_Status__c = 'Draft';
        insert res;

        Map<String, Object> result = Dfc_Util.getResourcesForState('Draft');

    }



}