src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Code_Verefied__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Champion Code has been entered</description>
        <label>Champion Code Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DF_Mail_ChampNoSessions_Bch_Test.cls
@isTest
public class DF_Mail_ChampNoSessions_Bch_Test {
/*  
***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            10-08-2015
     * @description     Test class for DF_Mail_ChampNoSessions_Batcher
***********************************************************************************************/

static testMethod void CoverMethod () {

    Id OW = Mail_Utils.getOrgWideEmail() ; 
    Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
   
    Date d = System.today().addDays(-60 );
      
    DF_Event__c De = (DF_Event__c )mapTestData.get('FriendSession');
    DF_Contact__c Dc = (DF_Contact__c )mapTestData.get('Champion'); 
     
     
    dc.Code_Verefied__c = True;
    dc.Status__c = DF_Utils.STATUS_CONVERTED;
    de.Event_Date_Time__c = d;   
   
  
    test.starttest();
    update de;
    update dc;
    
    DF_Mail_ChampNoSessions_Batcher batch = new DF_Mail_ChampNoSessions_Batcher();
    batch.templateName = DF_Mail_Utils.VF_CHAMPS_NO_SESSIONS_IN_2_MONTHS;
    batch.days = -60;
    Database.executeBatch( batch, 1 );
  }
  
  static testMethod void CoverMethod2 () {
  
   Date d = System.today().addDays(-120 );
   Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
   DF_Event__c De = (DF_Event__c )mapTestData.get('FriendSession');
   DF_Contact__c Dc = (DF_Contact__c )mapTestData.get('Champion');
   
   
   dc.Code_Verefied__c = True;
   dc.Status__c = DF_Utils.STATUS_CONVERTED;
   de.Event_Date_Time__c = d;
 

  test.starttest();
  update de;
  update dc ;
  DF_Mail_ChampNoSessions_Batcher batch = new DF_Mail_ChampNoSessions_Batcher();
  batch.templateName = DF_Mail_Utils.VF_CHAMPS_NO_SESSIONS_IN_4_MONTHS;
  batch.days = -120;
  Database.executeBatch( batch, 1 );
 
 }

  static testMethod void CoverMethod3 () {
  
   Date d = System.today().addDays(-180 );
   Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
   DF_Event__c De = (DF_Event__c )mapTestData.get('FriendSession');
   DF_Contact__c Dc = (DF_Contact__c )mapTestData.get('Champion');
   
   
   dc.Code_Verefied__c = True;
   dc.Status__c = DF_Utils.STATUS_CONVERTED;
   de.Event_Date_Time__c=d;

  
  test.starttest();
  update de;
  update dc ;
  DF_Mail_ChampNoSessions_Batcher batch = new DF_Mail_ChampNoSessions_Batcher();
  batch.templateName = DF_Mail_Utils.VF_CHAMPS_NO_SESSIONS_IN_6_MONTHS;
  batch.days = -180;
  Database.executeBatch( batch, 1 );
 
 }
 
   static testMethod void CoverMethod4 () {
  
   Date d = System.today().addDays(-240 );
   Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();    
   DF_Event__c De = (DF_Event__c )mapTestData.get('FriendSession');
   DF_Contact__c Dc = (DF_Contact__c )mapTestData.get('Champion');
   
   
  dc.Code_Verefied__c = True;
  dc.Status__c = DF_Utils.STATUS_CONVERTED;
  de.Event_Date_Time__c=d;

 
  test.starttest();
  update de;
  update dc ;
  DF_Mail_ChampNoSessions_Batcher batch = new DF_Mail_ChampNoSessions_Batcher();
  batch.templateName = DF_Mail_Utils.VF_CHAMPS_NO_SESSIONS_IN_8_MONTHS;
  batch.days = -240;
  Database.executeBatch( batch, 1 );
 
 }

   static testMethod void CoverMethod5 () {
  
   /*Date d = System.today().addDays(-300);
   Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();    
   DF_Event__c De = (DF_Event__c )mapTestData.get('FriendSession');
   DF_Contact__c Dc = (DF_Contact__c )mapTestData.get('Champion');
   
   
   dc.Code_Verefied__c = True;
   dc.Status__c = DF_Utils.STATUS_CONVERTED;
   de.Event_Date_Time__c=d;
  
     
  test.starttest();
  update de;
  update dc ;   
  DF_Mail_ChampNoSessions_Batcher batch = new DF_Mail_ChampNoSessions_Batcher();
  batch.templateName = DF_Mail_Utils.VF_CHAMPS_NO_SESSIONS_IN_10_MONTHS;
  batch.days = -300;
  batch.newStatus = DF_Utils.STATUS_RETIRED;
  Database.executeBatch( batch, 1 );*/
 
 }
}