src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Code_Verefied__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Champion Code has been entered</description>
        <label>Champion Code Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Champion__c</fullName>
        <label>Type of Champion</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Super Champion</fullName>
                </value>
                <value>
                    <fullName>Welsh Champion</fullName>
                </value>
                <value>
                    <fullName>Staff Champion</fullName>
                </value>
                <value>
                    <fullName>Scouts</fullName>
                </value>
                <value>
                    <fullName>Young Persons Champion</fullName>
                </value>
                <value>
                    <fullName>Digital Champion</fullName>
                </value>
                <value>
                    <fullName>PR Champion</fullName>
                </value>
                <value>
                    <fullName>Children’s Champion</fullName>
                </value>
                <value>
                    <fullName>Fast tracked</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Mentor Champion</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Type 3</fullName>
                </value>
                <value>
                    <fullName>Type 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>RSO</fullName>
        <active>true</active>
        <description>Regional Support Officer</description>
        <label>RSO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <formula>datevalue(Event_Date_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Contact__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dementia Friend Champion</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Champions Induction</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EventAttendeeStatus__c</fullName>
        <label>Event Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DF_Mail_ActivateChamp_Batcher.cls
global class DF_Mail_ActivateChamp_Batcher implements Database.Batchable<SObject>, Database.Stateful, Schedulable

 // Email to converted Champions who have not entered their code yet, sent by RSO, trigger is 2 weeks after training.

    {
   public string query;
  // public static final String VF_CHAMPCODENOTENTERED = 'TEREF04activatechampacc';
   public Id OW = Mail_Utils.getOrgWideEmail();
   public string templateName;
   public integer days;
   
        global void execute( SchedulableContext SC )
        {
          // batch run 
         DF_Mail_ActivateChamp_Batcher batch = new DF_Mail_ActivateChamp_Batcher();
          Database.executeBatch( batch, 1 );
        }

        global Database.QueryLocator start(Database.BatchableContext BC)
        {
            Date dt = System.today().addDays( days );
            Date d =date.newinstance(dT.year(), dT.month(), dT.day());
           system.debug('+++Date+++'+ d);
           
            String query = 
                'Select Id, ' +
                'DF_Event__r.name ,' +
                'DF_Contact__c'+
                ' From ' +
                'DF_Eventattendee__c ' +
                ' Where ' +
                'EventAttendeeStatus__c = \'' + DF_Utils.ATTENDEE_STATUS_ATTENDED+'\''   +
                ' and DF_Contact__c in '+
                '( select id from DF_Contact__c '+
                ' Where '+
                ' Code_Verefied__c = False '+
                'and Status__c = \'' + DF_Utils.STATUS_CONVERTED +'\'' +
                ' and Type_of_Champion__c excludes (\'VIP\')' +
                ')' +
                'and DF_Event__c  in'+
                ' ( select id from DF_Event__c'+
                ' Where '+                
                ' RecordType.DeveloperName =  \'' + DF_Utils.RT_CHAMPION_COURSE+'\'' +
                ' and Event_Date__c =:d )' ;
    
            system.debug('+++Query+++'+ query);

            return Database.getQueryLocator(query);
        }

        global void execute(Database.BatchableContext BC, List<SObject> scope) {
        
            Set<Id> ContactIdSet = new Set<Id>();  
            for ( sObject s : scope ) {                
              DF_Eventattendee__c  att = (DF_Eventattendee__c)s;
              ContactIdSet.add(att .DF_Contact__c);          
            }
          
            List<Messaging.SingleEmailMessage> lisEmails = new List<Messaging.SingleEmailMessage>();

            List <DF_Contact__c> liscon = [select id,Portal_Contact__c from DF_Contact__c where id in:ContactIdSet];
            for (DF_Contact__c con :liscon){
                     
              Map<String, EmailTemplate> mapTemp= Mail_Utils.getemailTemplateMap();
              templateName= (mapTemp.get(DF_Mail_Utils.VF_ACTIVATE_CHAMP).DeveloperName);
              lisEmails.add(Mail_Utils.getTemplatedEmail(templateName, con.Portal_Contact__c, con.id, OW, true, null));
           
             }
           
             if ( lisEmails.size() > 0 ) { Messaging.sendEmail(lisEmails); }


        }
        

        global void finish(Database.BatchableContext BC)
        {
          // do something interesting
        }
    }