src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>DF_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Region</label>
        <referenceTo>DF_Region__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Champions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode_Sector__c</fullName>
        <formula>TRIM(LEFT(Postcode__c,FIND(&quot; &quot;, Postcode__c)-1))</formula>
        <label>Postcode Sector</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_No_of_Completed_Info_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total No of Completed Info Sessions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Region__c.object
<CustomObject>
    <description>Dementia Friends Region</description>
    <label>DF Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DF_Region_Assignment_Batcher.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Batch Class to update region postcodes
 *  Author  : Gary Grant
 *  Date    : June 2015
 *  Version : 0.1 Unit Test
 *
 *  Description:    Batch update for linking DFCs to Regions
 *               
 *  Modification History
 *  Date            Who       Description 
 *  
*******************************************************************************************/

global class DF_Region_Assignment_Batcher implements Database.Batchable<sObject> {
    
    global String query;
    global Map<String, String> mapPostCodes;
    global Integer i;
    
    global DF_Region_Assignment_Batcher(Map<String, String> mapPostCodes) {

        this.mapPostCodes = mapPostCodes;
        i = 0;

        Integer c = 1;
        String RT_CHAMPION = DF_Utils.getDfcRecordTypeId(DF_UTILS.RT_CHAMPION);
        
        query = 'SELECT id, Postcode_Sector__c, DF_Region__c from DF_Contact__c where ' +
                ' ( ' + 
                ' ( RecordTypeId =\'' +  RT_CHAMPION + '\' and Status__c != \'' +  DF_Utils.STATUS_PROSPECTIVE + '\' )' +  
                ' OR ' +
                ' ( RecordTypeId !=\'' +  RT_CHAMPION + '\' and Total_No_of_Completed_Info_Sessions__c > 0 )' +  
                ' ) ' +
                ' and Postcode_Sector__c in (' ;
        
                for (String sPostCode : mapPostCodes.keySet()) { 

                    query = query + '\'' + sPostCode + '\'';
                    if (c < mapPostCodes.keySet().size()) { 
                        query = query + ',';
                    }            
        
                    c++;
                }
        
        query = query + ')';
        system.debug('Query = ' + query);
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
    
        List<DF_Contact__c> lis = new List<DF_Contact__c>();

        for (sObject o : scope) {

            DF_Contact__c dfc = (DF_Contact__c)o;
            system.debug('Batch Executing :' + dfc.id);

            String sRegionId = mapPostCodes.get(dfc.Postcode_Sector__c);

            if (dfc.DF_Region__c != sRegionId) {

                dfc.DF_Region__c = sRegionId;
                lis.add(dfc);
                i++;

            }

        }

        update lis;

    }


    
    global void finish(Database.BatchableContext BC) {

        system.debug('DF_Region_Assignment_Batcher records updated :' + i );
        
    }


    
}