src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pure360_Event_Report__c.object
<CustomObject>
    <fields>
        <fullName>Click_Date__c</fullName>
        <label>Click Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Pure360 Event Report</relationshipLabel>
        <relationshipName>Pure360_Event_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MessageName__c</fullName>
        <label>MessageName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>firstName__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lastName__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Pure360 Event Report</label>
    <nameField>
        <displayFormat>PE{00000}</displayFormat>
        <label>Pure360 Event Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pure360 Event Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_Pure360EventReportTriggerHander_Test.cls
@isTest
private class DF_Pure360EventReportTriggerHander_Test{

  static testMethod void myUnitTest() {
  Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();     
  DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc'); 
  
  List<Pure360_Event_Report__c> events = new List<Pure360_Event_Report__c>();
  Pure360_Event_Report__c report = new Pure360_Event_Report__c();
  report.type__c = 'Click';
  report.MessageName__c = 'messageName';
  report.lastName__c = 'test';
  report.firstName__c = 'test';
  report.Event_Date__c = DF_Utils.getDatetimeforUnixTimeStamp('1477562400');
  report.email__c = 'test.testcontact@myemail.com';
  report.Click_Date__c = system.now();

  events.add(report );
  insert events;
  test.starttest();
  DF_Pure360EventReportTriggerHander handler = new DF_Pure360EventReportTriggerHander(false, 1);
  handler.onBeforeInsert(events,null);
  system.assertNotEquals(null,report.DF_Contact__c);
  system.assertNotEquals(null,report.Click_Date__c);
  
  }


}