src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Champion__c</fullName>
        <label>Type of Champion</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Super Champion</fullName>
                </value>
                <value>
                    <fullName>Welsh Champion</fullName>
                </value>
                <value>
                    <fullName>Staff Champion</fullName>
                </value>
                <value>
                    <fullName>Scouts</fullName>
                </value>
                <value>
                    <fullName>Young Persons Champion</fullName>
                </value>
                <value>
                    <fullName>Digital Champion</fullName>
                </value>
                <value>
                    <fullName>PR Champion</fullName>
                </value>
                <value>
                    <fullName>Children’s Champion</fullName>
                </value>
                <value>
                    <fullName>Fast tracked</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Mentor Champion</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Type 3</fullName>
                </value>
                <value>
                    <fullName>Type 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Contact__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dementia Friend Champion</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EventAttendeeStatus__c</fullName>
        <label>Event Attendee Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DF_Mail_Utils_Test.cls
@isTest
public class DF_Mail_Utils_Test {
/*  
***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            10-08-2015
     * @description     Test class for DF_Mail_Utils
***********************************************************************************************/

    static testMethod void testSearchTaskHistory() {

    Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
    DF_Contact__c DFchamp = (DF_Contact__c )mapTestData.get('Champion'); 

    Task task = new Task();     
    task.whatId = DFChamp.id; 
    task.subject = 'xxx';
    task.Description ='xxx';   

    insert task;

    Map<String, task> mapTasks = new Map<String, task>();
    mapTasks.put(DFChamp.id + '~' + DF_Mail_Utils.DF_WELCOME_EMAIL, task);
    mapTasks.put(DFChamp.id + '~' + DF_Mail_Utils.DF_SUPERCHAMP_EMAIL, task);
    mapTasks.put(DFChamp.id + '~' + DF_Mail_Utils.DF_PROSNOTATTENDED_EMAIL, task);
    mapTasks.put(DFChamp.id + '~' + DF_Mail_Utils.DFC_ACTIVATE_CHAMP_ACCOUNT, task);
    mapTasks.put(DFChamp.id + '~' + DF_Mail_Utils.DFC_ENTERED_CODE_NO_SESSION, task);

    DF_Mail_Utils.searchTaskHistory(mapTasks, DFChamp.id, DF_Mail_Utils.DF_WELCOME_EMAIL);
    DF_Mail_Utils.searchTaskHistory(mapTasks, DFChamp.id, DF_Mail_Utils.DF_SUPERCHAMP_EMAIL);
    DF_Mail_Utils.searchTaskHistory(mapTasks, DFChamp.id, DF_Mail_Utils.DF_PROSNOTATTENDED_EMAIL);
    DF_Mail_Utils.searchTaskHistory(mapTasks, DFChamp.id, DF_Mail_Utils.DFC_ACTIVATE_CHAMP_ACCOUNT);
    DF_Mail_Utils.searchTaskHistory(mapTasks, DFChamp.id, DF_Mail_Utils.DFC_ENTERED_CODE_NO_SESSION);

    }

    static testMethod void coverMethod () {

    Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
    DF_Contact__c DFchamp = (DF_Contact__c )mapTestData.get('Champion'); 
    DF_Eventattendee__c DFeatt = (DF_Eventattendee__c )mapTestData.get('ChampAtten');
    
    DFchamp.Status__c = 'Converted';
    DFeatt.EventAttendeeStatus__c = 'Attended';
    
    test.starttest();
    update DFchamp;
    update DFeatt;
    List<Task> lisTask =[select whatid,id,DFC_email_tracker__c from Task where DFC_email_tracker__c !=null and whatid =:DFchamp.Id];
    DF_Mail_Utils.isDuplicateEmail(DFchamp, 'TEREF01',lisTask );
       
    DF_Mail_Utils.isDuplicateEmail(DFchamp,'TEREF04',lisTask );
        
    
     
    }
    
    static testMethod void coverMethod1 () {

    Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
    DF_Contact__c DFchamp = (DF_Contact__c )mapTestData.get('Champion'); 
    DF_Eventattendee__c DFeatt = (DF_Eventattendee__c )mapTestData.get('ChampAtten');
    
    
    DFchamp.Status__c = 'Prospective';
    DFeatt.EventAttendeeStatus__c = 'No show';
    
    
    test.starttest();
    update DFchamp;
    update DFeatt;
    List<Task> lisTask2 =[select whatid,id,DFC_email_tracker__c from Task where DFC_email_tracker__c !=null and whatid =:DFchamp.Id];
    DF_Mail_Utils.isDuplicateEmail(DFchamp, 'TEREF03',listask2 );
    
    }
    
    static testMethod void coverMethod2 () {

    Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
    DF_Contact__c DFchamp = (DF_Contact__c )mapTestData.get('Champion'); 
    DF_Eventattendee__c DFeatt = (DF_Eventattendee__c )mapTestData.get('ChampAtten');
    
    DFchamp.Status__c = 'Converted';
    DFchamp.Type_of_Champion__c = 'Super Champion';
    
    
    test.starttest();
    update DFchamp;
    List<Task> lisTask =[select whatid,id,DFC_email_tracker__c from Task where DFC_email_tracker__c !=null and whatid =:DFchamp.Id];
    List<DF_Contact__c> conlis = [select id from DF_Contact__c where id =:DFchamp.id];
    Map<String,Task> sMap= DF_Mail_Utils.getNextEmailCounterRequired(conlis, Df_Mail_Utils.DFC_CONGRATS_REACHING_X_DF);
    
    }
    
    
}