src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Champion_Training_Course</fullName>
        <active>true</active>
        <description>Events organised by Alzheimers Society/Trusted Partners</description>
        <label>Champions Induction</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Information Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Contact__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dementia Friend Champion</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Champions Induction</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDF_EventAttendeeTriggerMethods.cls
/*
* 2014-03-25 : SM : Test methods for the DF_EventAttendeeTriggerMethods class
*/
@IsTest 
private class TestDF_EventAttendeeTriggerMethods {

  
    private static String FRIEND_RT_NAME = 'Dementia_Friend';
    private static String CHAMPION_RT_NAME = 'Dementia_Friend_Champion';
    private static String SESSION_RT_NAME = 'Dementia_Friend_Awareness_Session';
    private static String TRAINING_RT_NAME = 'Champion_Training_Course';
   

    
    
    
    
    static testmethod void testSessionTrigger() {
       Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();       
       DF_Event__c  testSession = (DF_Event__c)mapTestData.get('FriendSession');
       DF_Contact__c dfContactRecord = (DF_Contact__c)mapTestData.get('DFc');
        test.startTest();
      
        DF_EventAttendee__c dfe1 = new DF_EventAttendee__c();
        dfe1.DF_Contact__c = dfContactRecord.Id;
        dfe1.DF_Event__c = testSession.Id;
    
   
        
        
        insert dfe1;
        
        delete dfe1;
                
    }
    
    
    static testmethod void testTrainingTrigger() {        
        
       Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();   
       
       DF_Event__c  testTraining = (DF_Event__c)mapTestData.get('ChampCourse'); 
       DF_Contact__c dfContactRecord = (DF_Contact__c)mapTestData.get('DFc');
         
       test.startTest();
       
       DF_EventAttendee__c dfe1 = new DF_EventAttendee__c();
       dfe1.DF_Contact__c = dfContactRecord.Id;
       dfe1.DF_Event__c = testTraining.Id;
       system.debug('*** -- Test Code Debug 2 - ' + dfe1.DF_Contact__r.Portal_Contact__c + ' -- ***');
        //This should fire the first trigger
        
        
        insert dfe1;
        
        delete dfe1;
        
                
    }
}