src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordType Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <formula>datevalue(Event_Date_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Last_Event__c</fullName>
        <formula>Event_Date_Time__c =  Session_Organiser__r.Latest_Friends_Session_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Last Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Friends Logged</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordType Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DF_Mail_NoOfFriends_bch_Test.cls
@isTest
public class DF_Mail_NoOfFriends_bch_Test {
/*  
***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            10-08-2015
     * @description     Test class for DF_Mail_NoOfFriends_batcher
***********************************************************************************************/
@testSetup
  public static void testData() {

  Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
   
  DF_Contact__c Dc = (DF_Contact__c )mapTestData.get('Champion2');
   
  DF_Event__c DFe = (DF_Event__c )mapTestData.get('FriendSession2');
  
  DF_Contact__c Dc2 = (DF_Contact__c )mapTestData.get('Champion');
   
  DF_Event__c DFe2 = (DF_Event__c )mapTestData.get('FriendSession');

  }
static testMethod void CoverMethod25Friends () {
 Id OW = Mail_Utils.getOrgWideEmail() ;
 
  DF_Contact__c  DFc= [select id,Status__c,recordtype_name__c,Total_No_of_Friends_Created__c from DF_Contact__c where email__c ='test.testcontact3@myemail.com'];
  DF_Event__c DFe =[select Id,Event_Date__c,Number_of_Attendees__c,Session_Organiser__r.name,Event_Status__c,name from DF_Event__c where name='Test Friends Session 2' limit 1];
  DFe.Number_of_Attendees__c=26;
  DFe.Event_Status__c = DF_Utils.EVENT_STATUS_COMPLETED;
  DFc.Total_No_of_Friends_Created__c = 26;
  DFc.Status__c =  DF_Utils.STATUS_CONVERTED ;

 
 
 
  test.starttest();
  
  update DFc ;
  update DFe ; 
     

  DF_Mail_NoOfFriends_batcher batch = new DF_Mail_NoOfFriends_batcher();
  system.debug('MY Query'+batch.query );
  batch.templatename1 = DF_Mail_Utils.VF_NO_OF_FRIENDS;
  batch.templatename2 = DF_Mail_Utils.VF_NO_OF_FRIENDS_AND_CERT ;

  Database.executeBatch( batch, 1 );
  
   }
   
 static testMethod void CoverMethod50Friends () {
  
  DF_Contact__c  DFc= [select id,Status__c,Total_No_of_Friends_Created__c from DF_Contact__c where email__c ='test.testcontact3@myemail.com'];
  DF_Event__c DFe =[select Id,Number_of_Attendees__c,Event_Status__c,name from DF_Event__c where name='Test Friends Session 2' limit 1];
  
  DFe.Event_Status__c = DF_Utils.EVENT_STATUS_COMPLETED;
  DFe.Number_of_Attendees__c=51;
  DFc.Status__c =  DF_Utils.STATUS_CONVERTED ;
  
  test.starttest();
  update DFc ;
  update DFe ;  
  DF_Mail_NoOfFriends_batcher batch = new DF_Mail_NoOfFriends_batcher();
  batch.templatename1 = DF_Mail_Utils.VF_NO_OF_FRIENDS;
  batch.templatename2 = DF_Mail_Utils.VF_NO_OF_FRIENDS_AND_CERT ;

  Database.executeBatch( batch, 1 );
  
   }
   
   static testMethod void CoverMethod75Friends () {
 
 DF_Contact__c  DFc= [select id,recordtype_name__c,Status__c,Total_No_of_Friends_Created__c from DF_Contact__c where email__c ='test.testcontact3@myemail.com'];
 DF_Event__c DFe =[select Id,Number_of_Attendees__c,Event_Date__c,Is_Last_Event__c ,Event_Status__c,name from DF_Event__c where name='Test Friends Session 2' limit 1];
  
  DFe.Event_Status__c = DF_Utils.EVENT_STATUS_COMPLETED;
  DFe.Number_of_Attendees__c = 75;
  DFc.Status__c =  DF_Utils.STATUS_CONVERTED ;
  
  test.starttest();
  
  
  update DFc ;
  update DFe ;
  
  DF_Mail_NoOfFriends_batcher batch = new DF_Mail_NoOfFriends_batcher();
  batch.templatename1 = DF_Mail_Utils.VF_NO_OF_FRIENDS;
  batch.templatename2 = DF_Mail_Utils.VF_NO_OF_FRIENDS_AND_CERT ;

  Database.executeBatch( batch, 1 );
  
   }
   
 
   
 static testMethod void CoverMethod100Friends () {
  DF_Contact__c  DFc= [select id,Status__c,recordtype_name__c,Total_No_of_Friends_Created__c from DF_Contact__c where email__c ='test.testcontact3@myemail.com'];
  DF_Event__c DFe =[select Id,Event_Date__c,Number_of_Attendees__c,Session_Organiser__r.name,Event_Status__c,name from DF_Event__c where name='Test Friends Session 2' limit 1];
  
  DFe.Event_Status__c = DF_Utils.EVENT_STATUS_COMPLETED;
  DFe.Number_of_Attendees__c=101;
  DFc.Status__c =  DF_Utils.STATUS_CONVERTED ;
  
  test.starttest();
  update DFc ;
  update DFe ;  
  DF_Mail_NoOfFriends_batcher batch = new DF_Mail_NoOfFriends_batcher();
  batch.templatename1 = DF_Mail_Utils.VF_NO_OF_FRIENDS;
  batch.templatename2 = DF_Mail_Utils.VF_NO_OF_FRIENDS_AND_CERT ;

  Database.executeBatch( batch, 1 );
  
   }
  static testMethod void CoverMethod151Friends () {
   DF_Contact__c  DFc= [select id,Status__c,Total_No_of_Friends_Created__c from DF_Contact__c where email__c ='test.testcontact3@myemail.com'];
  DF_Event__c DFe =[select Id,Event_Status__c,Number_of_Attendees__c,name from DF_Event__c where name='Test Friends Session 2' limit 1];
  
  DFe.Event_Status__c = DF_Utils.EVENT_STATUS_COMPLETED;
  DFe.Number_of_Attendees__c = 151;
  DFc.Status__c =  DF_Utils.STATUS_CONVERTED ;
  
  test.starttest();
  update DFc ;
  update DFe ;  
  DF_Mail_NoOfFriends_batcher batch = new DF_Mail_NoOfFriends_batcher();
  batch.templatename1 = DF_Mail_Utils.VF_NO_OF_FRIENDS;
  batch.templatename2 = DF_Mail_Utils.VF_NO_OF_FRIENDS_AND_CERT ;

  Database.executeBatch( batch, 1 );
  
   }
   
    static testMethod void CoverMethod251Friends () {
   DF_Contact__c  DFc= [select id,Status__c,Total_No_of_Friends_Created__c from DF_Contact__c where email__c ='test.testcontact3@myemail.com'];
  DF_Event__c DFe =[select Id,Event_Status__c,Number_of_Attendees__c,name from DF_Event__c where name='Test Friends Session 2' limit 1];
  
  DFe.Event_Status__c = DF_Utils.EVENT_STATUS_COMPLETED;
  DFe.Number_of_Attendees__c = 251;
  DFc.Status__c =  DF_Utils.STATUS_CONVERTED ;
  
  test.starttest();
  update DFc ;
  update DFe ;  
  DF_Mail_NoOfFriends_batcher batch = new DF_Mail_NoOfFriends_batcher();
  batch.templatename1 = DF_Mail_Utils.VF_NO_OF_FRIENDS;
  batch.templatename2 = DF_Mail_Utils.VF_NO_OF_FRIENDS_AND_CERT ;

  Database.executeBatch( batch, 1 );
  
   }
   
    static testMethod void CoverMethod300Friends () {
   DF_Contact__c  DFc= [select id,Status__c,Total_No_of_Friends_Created__c from DF_Contact__c where email__c ='test.testcontact3@myemail.com'];
  DF_Event__c DFe =[select Id,Event_Status__c,Number_of_Attendees__c,name from DF_Event__c where name='Test Friends Session 2' limit 1];
  
  DFe.Event_Status__c = DF_Utils.EVENT_STATUS_COMPLETED;
  DFe.Number_of_Attendees__c = 300;
  DFc.Status__c =  DF_Utils.STATUS_CONVERTED ;
  
  test.starttest();
  update DFc ;
  update DFe ;  
  DF_Mail_NoOfFriends_batcher batch = new DF_Mail_NoOfFriends_batcher();
  batch.templatename1 = DF_Mail_Utils.VF_NO_OF_FRIENDS;
  batch.templatename2 = DF_Mail_Utils.VF_NO_OF_FRIENDS_AND_CERT ;

  Database.executeBatch( batch, 1 );
  
   }
    
}