src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_UserHomeRedir_Controller_Test.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Test Class for DF_WEBC_User_Home_Redirect_Controller
 *  Author  : Lakshmi Rajendram
 *  Date    : 12-03-2015
 *  Version : 0.1 Unit Test
 *
 *               
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ????                           
*******************************************************************************************/
@isTest
public with sharing class DF_WEBC_UserHomeRedir_Controller_Test {
    
    
    static testMethod void testdoAction() {
  
  	   Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
       DF_Contact__c DFc = (DF_Contact__c)mapTestData.get('DFc');
  	   PageReference testPage = Page.DF_WEBC_UserHome;
       testPage.getParameters().put('oid', '12345');
        
       Test.setCurrentPage(testPage);
       
       Test.StartTest();
        
	    DF_WEBC_User_Home_Redirect_Controller dhr=new DF_WEBC_User_Home_Redirect_Controller();
	    WEBC_Login controller = new WEBC_Login ();

        controller.emailAddress = DFc.email__c;
        controller.password = '123456'; 
        dhr.doAction();

    }
}