src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DF_EventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Contact__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dementia Friend Champion</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF EventAttendance</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Event__c</fullName>
        <label>DF Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DF_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Champions Induction</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>DF_Event__c</referenceTo>
        <relationshipLabel>DF EventAttendees</relationshipLabel>
        <relationshipName>DF_EventAttendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DF EventAttendee</label>
    <nameField>
        <displayFormat>DFE-{0000000}</displayFormat>
        <label>DF EventAttendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF EventAttendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Saved_Search__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Range__c</fullName>
        <label>Range</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Session</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Saved Search</label>
    <nameField>
        <displayFormat>Search-{0000}</displayFormat>
        <label>Saved Searches Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Searches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WEBSession_Test.cls
@isTest
 public class WEBSession_Test{
 static testmethod  void TestWEBSession()
    {
      Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
        User u  = (User)mapTestData.get('User');
        DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');
        DF_Event__c devent = (DF_Event__c)mapTestData.get('FriendSession');
        DF_EventAttendee__c  DevAtten = (DF_EventAttendee__c)mapTestData.get('FriendAtten');
       
       test.starttest();
      
        PageReference pageRef = Page.WEBSessionDetails;
        pageRef.getParameters().put('Id',devent.id);
        test.setCurrentPage(pageRef);
        //ApexPages.currentPage().getParameters().put('Id',devent.id);  

           
       // insert ss;
       
 
    } 
    
     static testmethod  void TestWEBSession2()
    {
      Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
        User u  = (User)mapTestData.get('User');
        DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');
        DF_Event__c devent = (DF_Event__c)mapTestData.get('FriendSession');
        DF_EventAttendee__c  DevAtten = (DF_EventAttendee__c)mapTestData.get('FriendAtten');
          
       Saved_Search__c ss=new Saved_Search__c(Type__c='Session',Email__c='sampleemail@gmail.com',Post_Code__c='3434',Range__c=564);
       System.runAs(u)
       {
         pagereference pr = page.WEBSession;
         
          test.setCurrentPage(pr);
          test.starttest();
        
            WEBSession  websee=new WEBSession();
            websee.searchRange = string.valueof(ss.Range__c);
            
            
            websee.selectedEvent = new WEBSession.EventWrapper(devent);
                   
           websee.bookOnSession();
           // DevAtten.DF_Event__c = devent1.id;
           // update DevAtten ;
           // websee.removeFromSession();
           websee.showUnavailable = false;
           
            websee.applyFilter();
            websee.attendanceRecord = DevAtten;
            //websee.removeFromSession();

          //  websee.attendanceRecord();
           // websee.EventWrapper webeven = new websee.EventWrapper();
            websee.saveSearch();
           Map<String, String> stringMap =websee.getLatLong('IG1 3HY');
           websee.nextPage();
           websee.previousPage();
           websee.changeRecordsPerPage();
           Boolean success =websee.showSuccess;
          Map<String, String> locationmap =websee.getLatLong('Ig1 3lq');
          system.assertNotEquals(null,websee.removeFromSession());
        }  
        
       
    }  
    
  }