src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c &amp; &quot;,  &quot; &amp; First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <fields>
        <fullName>Central_Location__c</fullName>
        <description>Does this Dementia Friendly Community have a central location ? Yes or No</description>
        <label>Central Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The Country where the community is located. This will determine the approval process</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Wales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>DFC_County__c</referenceTo>
        <relationshipLabel>DFC Communities</relationshipLabel>
        <relationshipName>DFC_Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DA_Alliance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Dementia Action Alliance that thae Dementia Friendly Community is associated with</description>
        <label>DA Alliance</label>
        <referenceTo>DFC_Alliance__c</referenceTo>
        <relationshipLabel>DA_Alliance</relationshipLabel>
        <relationshipName>Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <description>The date the community was submitted for approval</description>
        <label>Date Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duplicate_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Duplicate Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rural</fullName>
                </value>
                <value>
                    <fullName>Village</fullName>
                </value>
                <value>
                    <fullName>Town</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The Community Location</description>
        <inlineHelpText>You can give the name of the village / town / city, region and county for example.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Community Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Population__c</fullName>
        <inlineHelpText>Please give the approximate size of the population for the community becoming dementia friendly</inlineHelpText>
        <label>Population Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Region of England or Wales that the Community is in. This determines the Regional Lead which is the first approver</description>
        <label>Region</label>
        <referenceTo>DFC_DAA_Region__c</referenceTo>
        <relationshipLabel>DFC Communities</relationshipLabel>
        <relationshipName>DFC_Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Why_No_Central_Location__c</fullName>
        <description>Explanation field for when there is No Central Location - e.g. Online Community</description>
        <label>Why No Central Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DFC_Community_Action_Area__c.object
<CustomObject>
    <description>Links action areas to a community</description>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipLabel>DFC Community Action Area</relationshipLabel>
        <relationshipName>Action_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A brief description of how you plan to work towards to make your community dementia-friendly</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>DFC Community Action Area</label>
    <nameField>
        <displayFormat>DFCMA - {000000}</displayFormat>
        <label>Action Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Community Action Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Community_Representative__c.object
<CustomObject>
    <description>A person taking responsibility for meeting the requirements of the recognition process</description>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipName>Representatives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipName>DFC_Community_Representatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invited_Email__c</fullName>
        <label>Invited Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invited_Name__c</fullName>
        <label>Invited Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_User__c</fullName>
        <formula>DF_Contact__r.Portal_User__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portal User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DFC Representative</label>
    <nameField>
        <displayFormat>DFCR - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DFC_RegisterCommunityController.cls
public without sharing class DFC_RegisterCommunityController{

public static Dfc_CommunityContext context {get;set;}

public string ID_Param {get;set;}
public static string communitystatus {get;set;}


  public DFC_RegisterCommunityController(){
   ID_Param= ApexPages.currentPage().getParameters().get('dfcid');

 }

public  Object getdata() {

       if(communitystatus==null){return null;}
           
          return Dfc_Util.getResourcesForState(communitystatus);
       
 }

@RemoteAction
  public static Dfc_CommunityContext dfcDraftContext( string communityId){
   
   return Dfc_Util.getDraftContext(readCommunity(communityId));
  }

  public static DFC_Community__c readCommunity(string communityId){
    return Dfc_Util.readCommunity(communityId);
  }

  @RemoteAction
  public static DFC_Community__c[] getCommunitiesForDaa (String daaId){
    return Dfc_Util.getCommunitiesForDaa (daaId);
  }

   @RemoteAction
  public static object saveCommunity (Community comm,string communityId){
        return updateCommunity(comm,communityId);
  }
  @RemoteAction
  public static void validateCommunity (string communityId){
   Dfc_Util.validateCommunity(readCommunity(communityId));
  
  }
  private static object updateCommunity (Community comm,string communityId){
    DFC_Community__c com = readCommunity(communityId);
     
     system.debug('remote object@'+comm);
     com.country__c = comm.country;
     com.Central_Location__c=comm.centralLocation;
     com.Why_No_Central_Location__c=comm.noLocation;
     com.Region__c = comm.region ;
     com.DA_Alliance__c= comm.Daa;
     com.Duplicate_Confirmation__c= (comm.Daa==null?false:comm.Duplicate) ;
     com.Name__c = comm.name;
     com.County__c =comm.county;
     com.Location__c = comm.location;
     com.Population__c = comm.population;
     com.Location_Type__c = comm.ltype;
     com.Status__c = comm.status;
     //DateTime dt = DateTime.parse(comm.datesubmitted);
     com.Date_Submitted__c = comm.datesubmitted;
     if(comm.actionAreas!=null){
      updateActionAreas(comm.actionAreas);
     }
     update com;
     return new Community();

  }
  private static void updateActionAreas(List<DFC_Community_Action_Area__c> actionAreas){
    for(DFC_Community_Action_Area__c action:actionAreas){
      if(action.Selected__c == false && action.Description__c!=null){
        action.Description__c='';
        update actionAreas;
      }
     update actionAreas;
      }
    
  }
  
  public class Community{

   public string country {get;set;}
   public string centralLocation {get;set;}
   public string noLocation {get;set;}
   public string region {get;set;}
   public string Daa {get;set;}
   public Boolean Duplicate {get;set;}
   public string name {get;set;}
   public string county {get;set;}
   public string location{get;set;}
   public decimal population{get;set;}
   public string ltype {get;set;}
   public List<DFC_Community_Action_Area__c> actionAreas {get;set;}
   public DateTime datesubmitted {get;set;}
   public string status {get;set;}

  }
  //rep
  @RemoteAction
 public static List<Reps> existingReps(string communityId) {
 List<Reps> lisreps = new List<Reps>();

  for( DFC_Community_Representative__c  rp :[ SELECT Id,Invited_Name__c,Invited_Email__c,Role__c,DF_Contact__r.Id,DF_Contact__r.Portal_User__c,DF_Contact__r.Name,DF_Contact__r.Email__c FROM DFC_Community_Representative__c 
            
            WHERE  
            Community__r.Id = :communityId
            
            And
            (
            Role__c = 'Registered' OR Role__c = 'Invited'
            ) 
           ])  {
          Reps r = new Reps();
          r.Name = (rp.DF_Contact__r.Name!=null ?rp.DF_Contact__r.Name:rp.Invited_Name__c);
          r.Email = (rp.DF_Contact__r.Email__c!=null ?rp.DF_Contact__r.Email__c:rp.Invited_Email__c);
          r.Role =rp.Role__c;
          r.Id = rp.Id;
          r.Dfc =(rp.DF_Contact__r!=null? rp.DF_Contact__r.Id:null);
          lisreps.add(r);
      }
     return lisreps;
   }

public class Reps{
 public string Name;
 public string Email;
 public string Role;
 public string Id;
 public string Dfc;
}
@RemoteAction
  public static Holder handleinvites(String email,string communityId) {
  
    boolean isError;
    Holder holder = new Holder();
    holder.isInvite = false; 
    holder.emailError='' ;
    holder.existingRep =false;
   //validate email address     
    if(email==null || email.length() <=0){ 
    
    holder.emailError = 'Please enter email.';
    isError =true;
    }
            
    if( email.length()>0 && !validEmail(email)){
    
    holder.emailError = 'Enter valid email.';
    isError =true;
    }        
    
    if( email.length()>0 && Dfc_Util.existingRepresentative(communityId,email)){ 
    holder.existingRep =true;
    holder.emailError = 'The Email address '+email+' is already a confirmed or invited representative for this community';
    isError =true;
   }

    if(email!=null && email.length()>0 && validEmail(email)&& !Dfc_Util.existingRepresentative(communityId,email)){
    
    holder.emailError = '';
    isError =false;
    }        
    
   
   return holder;

  } 

  public class Holder  
  {    
  //data holder for remote action    
       public String emailError = '';
       public Boolean isInvite ;
       public Boolean existingRep;
  }
  
  
  public static Boolean validEmail(String email) {
    

  String InputString = email;
  String emailRegex = '([a-zA-Z0-9_\\-\\.]+)@((\\[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})';
  Pattern MyPattern = Pattern.compile(emailRegex);

// Then instantiate a new Matcher object "emailMatcher"
   Matcher emailMatcher = MyPattern.matcher(InputString);

  if (!emailMatcher.matches()) {
     return FALSE;
   }
   else {
    return TRUE;
   }
  
}
@RemoteAction
  public static object handleReps(string communityId,String email) {
   
   
   List<User> lisUser = [select id from User where UserName = :email];
    
  if(validEmail(email)==false) {
    return 'Please enter valid email address';
  }
  else{

   if(lisUser.isEmpty() && Dfc_Util.existingRepresentative(communityId,email)==false){
     return 'invite';
   }
   else if(Dfc_Util.existingRepresentative(communityId,email)){

    return 'The Email address '+email+' is already a confirmed or invited representative for this community';

   }

   else{
    return addRepresentative(communityId,email);
    
   }
  }

 }

public static DFC_Community_Representative__c addRepresentative (String communityId, String email){
 DFC_Community_Representative__c  rep = Dfc_Util.addRepresentative(communityId, email);
return rep;
}

@RemoteAction
public static DFC_Community_Representative__c inviteRepresentative (String communityId, String email, String name){
 DFC_Community_Representative__c  rep = Dfc_Util.inviteRepresentative(communityId, email,name);
return rep;
}

@RemoteAction
public static void deleteRepresentative (String communityId, String id){
 Dfc_Util.deleteRepresentative(communityId, id);
}



}