src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>RSO</fullName>
        <active>true</active>
        <description>Regional Support Officer</description>
        <label>RSO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <formula>datevalue(Event_Date_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Last_Event__c</fullName>
        <formula>Event_Date_Time__c =  Session_Organiser__r.Latest_Friends_Session_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Last Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DF_Mail_NoOfFriends_Batcher.cls
global class DF_Mail_NoOfFriends_Batcher implements Database.Batchable<SObject>, Database.Stateful, Schedulable {
/*  
***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            10-08-2015
     * @description     Thank you email to active Champions for reaching 25, 50, 75, 100 and 
                then multiples of 50 number of Dementia Friends sent from RSO, approve first.  
                Separate email for 100 Friends that includes offering them a certificate if they want one.  
                Only send one email when Champion reaches a milestone, excluding 100 Friends email.  
***********************************************************************************************/
   public string query;
  
   public Id OW = Mail_Utils.getOrgWideEmail();
   public string templateName1{get;set;}
   public string templateName2{get;set;}
   
    global void execute( SchedulableContext SC )
    {
          // batch run 
      DF_Mail_NoOfFriends_Batcher o = new DF_Mail_NoOfFriends_Batcher();
      o.templatename1 = DF_Mail_Utils.VF_NO_OF_FRIENDS;
      o.templatename2 = DF_Mail_Utils.VF_NO_OF_FRIENDS_AND_CERT ;
      database.executebatch(o,1);
      
     }

     global Database.QueryLocator start(Database.BatchableContext BC)
     {
          Id rt = DF_Utils.getDfcRecordTypeId(DF_Utils.RT_CHAMPION);
          Date dt = Date.valueOf('2015-09-01') ;
           
            String query = 
                'Select Id, ' +
                'Portal_Contact__c,' +
                'Total_No_of_Friends_Created__c' +
                ' From ' +
                ' DF_Contact__c ' +
                ' Where RecordtypeId =: rt ' +
                ' and Status__c = \'' + DF_Utils.STATUS_CONVERTED +'\'' +             
                ' and Total_No_of_Friends_Created__c >= 25 ' +
                ' and  Id in ' +
                ' ( ' +
                ' select Session_Organiser__c  from DF_Event__c where Event_Status__c = \'' + DF_Utils.EVENT_STATUS_COMPLETED +'\'' +
                ' and Is_Last_Event__c = true '+
                ' and Event_Date__c >=: dt  '+
                ' )';
                
                
    
            system.debug('+++Query+++'+ query);

            return Database.getQueryLocator(query);
       }

    global void execute(Database.BatchableContext BC, List<SObject> scope){
       
       Map<String, EmailTemplate> mapTemp= Mail_Utils.getemailTemplateMap();
       templateName1= (mapTemp.get(templateName1 ).DeveloperName);  
       templateName2= (mapTemp.get(templateName2 ).DeveloperName);
       Map<string,Task> tskMap = new Map<string,Task>();
         
       List<DF_Contact__c> lisDFcon = new List <DF_Contact__c>();
       List<Messaging.SingleEmailMessage> lisEmails = new List<Messaging.SingleEmailMessage>();
                           
                  
       for ( sObject s : scope ){
       
           DF_Contact__c  c = (DF_Contact__c)s;
           lisDFcon.add(c);
       }
           
       if( lisDFcon.size()==0 ){ return; }
           
       tskMap=DF_Mail_Utils.getNextEmailCounterRequired(lisDFcon, Df_Mail_Utils.DFC_CONGRATS_REACHING_X_DF );
       system.debug('TASK MAP'+TSKMap);
           
       for ( DF_Contact__c con: lisDFcon) {
           
           
           Integer conTotal = integer.valueof(con.Total_No_of_Friends_Created__c);
           Decimal x = conTotal / 50;
           Long L = x.round();
           Integer i= integer.valueOf(x);
           
         if(! tskMap.isEmpty()) {
         
          
           if( conTotal >= 25 && conTotal <= 49  && tskMap.get(con.id+'~'+ Df_Mail_Utils.DFC_CONGRATS_REACHING_X_DF +'.'+ '25')==null){                 
                lisEmails.add(Mail_Utils.getTemplatedEmail(templateName1, con.Portal_Contact__c, con.id, OW, true, null));                                        
           }      
           
           if( conTotal >= 50 && conTotal <= 74 && tskMap.get(con.id+'~'+ Df_Mail_Utils.DFC_CONGRATS_REACHING_X_DF +'.'+ '50')==null){           
                lisEmails.add(Mail_Utils.getTemplatedEmail(templateName1, con.Portal_Contact__c, con.id, OW, true, null));     
           }

           if( conTotal >= 75 && conTotal <= 99 && tskMap.get(con.id+'~'+ Df_Mail_Utils.DFC_CONGRATS_REACHING_X_DF +'.'+ '75')==null){                  
                lisEmails.add(Mail_Utils.getTemplatedEmail(templateName1, con.Portal_Contact__c, con.id, OW, true, null));
           }

           if( conTotal >= 100 && tskMap.get(con.id+'~'+ Df_Mail_Utils.DFC_CONGRATS_REACHING_X_DF +'.'+ '100')==null){
                lisEmails.add(Mail_Utils.getTemplatedEmail(templateName2, con.Portal_Contact__c, con.id, OW, true, null));             
           } 
           
                     
           if(conTotal >= 150 && tskMap.get(con.id+'~'+ Df_Mail_Utils.DFC_CONGRATS_REACHING_X_DF +'.'+ i)==null && tskMap.get(con.id+'~'+ Df_Mail_Utils.DFC_CONGRATS_REACHING_X_DF +'.'+ '100')!=null) {
            
               Task tk = tskMap.get(con.id+'~'+ Df_Mail_Utils.DFC_CONGRATS_REACHING_X_DF +'.'+ '100');
               system.debug('task for 100 email'+tk);
                  
                   if( tk!=null ){ 
                   Integer friendsTotal= integer.valueOf(tk.Description.substringBetween('created','Dementia Friends').replaceAll( '\\s+', ''));
                   Decimal dNoOfFriends = friendsTotal/50;
                   Integer intNoOfFriends = integer.valueOf(DNoOfFriends);
                   
                      if (IntNoOfFriends != i ){ 
                
                        lisEmails.add(Mail_Utils.getTemplatedEmail(templateName1, con.Portal_Contact__c, con.id, OW, true, null)); 
                        
                        }

                    } 

            }
          
          } else {
        
             if( conTotal >= 25 && conTotal <= 49 ) {                 
                    lisEmails.add(Mail_Utils.getTemplatedEmail(templateName1, con.Portal_Contact__c, con.id, OW, true, null));                  
               }      
             
             if( conTotal >= 50 && conTotal <= 74 ){
                    lisEmails.add(Mail_Utils.getTemplatedEmail(templateName1, con.Portal_Contact__c, con.id, OW, true, null));     
               }
             
             if( conTotal >= 75 && conTotal <= 99 ) {                  
                    lisEmails.add(Mail_Utils.getTemplatedEmail(templateName1, con.Portal_Contact__c, con.id, OW, true, null));
               }
             
             if( conTotal >= 100 ) {             
               lisEmails.add(Mail_Utils.getTemplatedEmail(templateName2, con.Portal_Contact__c, con.id, OW, true, null));
               }
             
         }
          
       
       }
       
       if ( lisEmails.size() > 0 ) { Messaging.sendEmail(lisEmails); }
      
    
     }


      global void finish(Database.BatchableContext BC)
      {
          // do something interesting
      }
    }