src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Ext Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation ID</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portal_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Champion__c</fullName>
        <label>Type of Champion</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Super Champion</fullName>
                </value>
                <value>
                    <fullName>Welsh Champion</fullName>
                </value>
                <value>
                    <fullName>Staff Champion</fullName>
                </value>
                <value>
                    <fullName>Scouts</fullName>
                </value>
                <value>
                    <fullName>Young Persons Champion</fullName>
                </value>
                <value>
                    <fullName>Digital Champion</fullName>
                </value>
                <value>
                    <fullName>PR Champion</fullName>
                </value>
                <value>
                    <fullName>Children’s Champion</fullName>
                </value>
                <value>
                    <fullName>Fast tracked</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Mentor Champion</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Type 3</fullName>
                </value>
                <value>
                    <fullName>Type 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Admin</fullName>
        <active>true</active>
        <label>Admin</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>DF Events</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Information Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Partner External Id</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WEBManageMySessions_Test.cls
@isTest
public class WEBManageMySessions_Test {
	@testsetup  static void mytestdata(){   
        DF_DataFactory_Test.getTestData();
     	 /*Select DF_Event__c RecordTypeId for "Dementia Friend Awareness Session" .
        RecordType rTypedf = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Awareness_Session' and SobjectType = 'DF_Event__c'];

        //Select DF_Contact__c RecordTypeId for "Dementia Friend Champion".
        RecordType rTypedfc = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Champion' and SobjectType = 'DF_Contact__c'];
              
        //New Partner_Organisation__c Record to be added to the DF_Contact__c test Data.
        Partner_Organisation__c pa = new Partner_Organisation__c(Name='Test Org', DFC_Code__c='ABC123', Partner_External_Id__c=1234);
        insert pa; 
        
        //New DF_Contact__c Record to be added to the test Data.
        DF_Contact__c df = new DF_Contact__c(RecordTypeId = rTypedfc.id, Name='Test DFC', Partner_Organisation_ID__c = pa.id, Contact_Ext_Id__c = 12345678
                                             ,First_Name__c = 'Test', Last_Name__c ='DFC'
                                             ,email__c= 'email'+datetime.now().format('YYYYMMDDhhmmsshhmm')+'@alztest.com');
        insert df;
        
        //New DF_Event__c Record to be added to the test Data.
        DF_Event__c dfEvent1 = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent1', Session_Organiser__c = df.Id, Event_Date_Time__c = system.now());
        
        DF_Event__c dfEvent2 = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent2', Session_Organiser__c = df.Id, Event_Date_Time__c = system.now());
        
        DF_Event__c dfEvent3 = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent3', Session_Organiser__c = df.Id, Event_Date_Time__c = system.now());
        
        DF_Event__c dfEvent4 = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent4', Session_Organiser__c = df.Id, Event_Date_Time__c = system.now());
        
        DF_Event__c dfEvent5 = new DF_Event__c(RecordTypeId = rTypedf.id, Name = 'Test DFEvent5', Session_Organiser__c = df.Id, Event_Date_Time__c = system.now());
        
   		
        insert (new List<DF_Event__c>{dfEvent1,dfEvent2, dfEvent3, dfEvent4, dfEvent5});*/
    }
    
    @isTest
    static void testManagesession() {
        RecordType rTypedfc = [Select Id from RecordType where DeveloperName ='Dementia_Friend_Champion' and SobjectType = 'DF_Contact__c'];
        DF_Contact__c champDfContact = [SELECT Id,Email__c, Portal_User__c,RecordTypeId 
                     FROM DF_Contact__c
                     WHERE Email__c = 'test.testcontact2@myemail.com'
                     LIMIT 1];
        User u = [SELECT Id FROM User WHERE UserName = :champDfContact.Email__c limit 1];
		champDfContact.Type_of_Champion__c = 'Super Champion';
        champDfContact.RecordTypeId = rTypedfc.Id;
        update champDfContact;
        
        Test.setCurrentPage( new PageReference('/apex/WEBChampionManageMySessions'));
        //User admin = new User(Id = champDfContact.Portal_User__c);
        System.runAs(u){
            //System.assertEquals(UserInfo.getUserType() , 'Guest', 'Not Logged in');
            WEBManageMySessions manage = new WEBManageMySessions();
            List<DF_Event__c> upcoming = manage.upcomingRequestedEvents;
            List<DF_Event__c> reqFeedback = manage.requestedEventsRequiringFeedback;
            List<DF_Event__c> unapproved = manage.unapprovedRequestedEvents;
            List<DF_Event__c> upcomingCreated = manage.upcomingCreatedEvents;
            List<DF_Event__c> pastCreated = manage.pastCreatedEvents;
            List<DF_Event__c> createdReqFeedback = manage.createdEventsRequiringFeedback;
            try{
            Page_Snippet__c totalSnippet = manage.totalFriendsSnippet;
            }catch(exception exp){}
        }
    	
    }
    
    
}