src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>DF_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Region</label>
        <referenceTo>DF_Region__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Champions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>RSO</fullName>
        <active>true</active>
        <description>Regional Support Officer</description>
        <label>RSO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Region__c.object
<CustomObject>
    <description>Dementia Friends Region</description>
    <fields>
        <fullName>RSO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Regional Support Officer</description>
        <label>Regional Support Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DFRegions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Office_Location__c</fullName>
        <label>Office Location</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_RSODetailsController.cls
public without sharing class DF_WEBC_RSODetailsController extends DF_WEBC_ControllerBase{

public User rso {get;set;}
public DF_Region__c region {get;set;}
public string regionName {get{if(region==null){return null;}return region.name;}}
public string email {get{if(region==null || rso==null){return null;}return rso.email;}}
public string phone {get{if(region==null || rso==null){return null;}return rso.phone;}}
public Integer friendsCount {get;set;}
public Boolean isChampion;

public DF_WEBC_RSODetailsController(){

String RT_CHAMPION = DF_Utils.getDfcRecordTypeId(DF_Utils.RT_CHAMPION);
String STATUS_CONVERTED = DF_Utils.STATUS_CONVERTED;

isChampion = DF_Utils.isChampion(currentDfc);

if(isChampion && currentDfc.DF_Region__c!=null){

    List<DF_Region__c> lisRegions = [select Id,RSO__c,name  from DF_Region__c where id =: currentDfc.DF_Region__c];
    if(lisRegions.size()>0)
    {
    List<User> lisrso = new List<User>();
    lisrso=[select Name,phone,Office_Location__c,CommunityNickname,firstName,LastName,email,FullPhotoUrl,SmallPhotoUrl from  User where id =: lisRegions[0].RSO__c];
    if(lisrso.size()>0){
    rso = lisrso[0];
}
    region = lisRegions[0];
    


    List<aggregateResult> RegionAgg= [SELECT DF_Region__c
                                            ,COUNT(id)
                                            ,SUM(Total_No_of_Friends_Created__c) TotFriends                                           
  	                                        FROM DF_Contact__c 
                                            WHERE RecordTypeId =: RT_CHAMPION 
                                            AND Status__c =: STATUS_CONVERTED 
                                            AND  DF_Region__c =: lisRegions[0].Id
                                            GROUP BY DF_Region__c];

        IF (RegionAgg.size()>0){
            
            FOR (AggregateResult argRec : RegionAgg){

                Double totalFriends =(Double)argRec.get('TotFriends');
                friendsCount = totalFriends.intValue();
              }

          }
        }
    }

 }

}