src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <label>Event End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_Of_Attendee_Records__c</fullName>
        <label>Number Of Attendees Booked</label>
        <summaryFilterItems>
            <field>DF_EventAttendee__c.Event_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>DF_EventAttendee__c.DF_Event__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Friends Logged</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Places__c</fullName>
        <label>Total session audience capacity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting for approval</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Open - waiting for champion</fullName>
                </value>
                <value>
                    <fullName>Matched with champion</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session_Organiser_Firstname__c</fullName>
        <formula>Session_Organiser__r.First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Session Organiser Firstname</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser_Lastname__c</fullName>
        <formula>Session_Organiser__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Session Organiser Lastname</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session Requester</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Events (Session Requester)</relationshipLabel>
        <relationshipName>Session_Requester</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Awareness_Session</fullName>
        <active>true</active>
        <description>Events organised by DF Champions</description>
        <label>Dementia Friend Information Session</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/WEBChampionManageMySessions.cls
/******************************************************************************************
 *  Cloud Symphony
 *  
 *  Purpose : APEX controller class for VF Page WEBChampionManageMySessions.
 *  Author  : CSL
 *  Date    : 27-02-2014
 *  Version : 1.0
 *
 *  Description:    Apex Class controller for the WEBChampionManageMySessions page.
 *               
 *  Modification History
 *  Date            Who         Description 
 *    09/01         LV          added nonOfFriends variable
*******************************************************************************************/
public without sharing class WEBChampionManageMySessions extends DF_WEBC_ControllerBase {
    
    public final String STATUS_AVAILABLE = 'Available';
    public final String STATUS_CANCELLED = 'Cancelled';
    public final String STATUS_FULL = 'Full';
    public static final String SESSION_RT = 'Dementia_Friend_Awareness_Session';

    public string noOfFriends {get;set;}
    public List<DF_Event__c> upcomingEvents {
        get {
            if (upcomingEvents == null)
                upcomingEvents = new List<DF_EVENT__c>();
            
            return upcomingEvents;
        }
        set;
    }

    public List<DF_Event__c> pastEvents {
        get {
            if (pastEvents == null)
                pastEvents = new List<DF_EVENT__c>();
            
            return pastEvents;
        }
        set;
    }

    public List<DF_Event__c> eventsRequiringFeedback {
        get {
            if (eventsRequiringFeedback == null)
                eventsRequiringFeedback = new List<DF_EVENT__c>();
            
            return eventsRequiringFeedback;
        }
        set;
    }
        
    public List<DF_Event__c> unapprovedEvents {
        get {
            if (unapprovedEvents == null)
                unapprovedEvents = new List<DF_EVENT__c>();
            
            return unapprovedEvents;
        }
        set;
    }

    public Integer noUpcomingEvents {get;set;}
    public Integer noPastEvents {get;set;}
    public Integer noEventsRequiringFeedback {get;set;}
    
    

    public Boolean isChampion {get;set;}
    public Boolean isChampionConverted {get; set;}
    public Boolean isChampionRetired {get; set;}
    public Boolean isChampionHiatus {get; set;}
    
    public String messageArea {get;set;}
    public String messageAreaClass {get;set;}
    public Boolean infoSessionUpdated {get;set;}
    public Boolean sessionDropped {get;set;}

    public Page_Snippet__c totalFriendsSnippet {
        get {
            if (totalFriendsSnippet == null){
                totalFriendsSnippet = [select p.Body_Text__c, p.Unique_Name__c from Page_Snippet__c p where p.Unique_Name__c = 'DementiaFriendsTotalSnippet' LIMIT 1];
            }
            return totalFriendsSnippet;
        }
        set ;
    }
    
     public Double offset {get; set;}
     
    
    //Constructor
    public WEBChampionManageMySessions() {

        System.debug('*** WEBChampionManageMySessions : Checking User');

        isChampion = DF_Utils.isChampion(currentDfc);
        isChampionConverted = DF_Utils.isChampionConverted(currentDfc);
        isChampionRetired= DF_Utils.isChampionRetired(currentDfc);
        isChampionHiatus = DF_Utils.isChampionHiatus(currentDfc);
        
        if (ApexPages.currentPage().getParameters().get('infoSessionUpdated') == 'true') {
            infoSessionUpdated = true;
        } else {
            infoSessionUpdated = false;
        }
        
        if (ApexPages.currentPage().getParameters().get('sessionDropped') == 'true') {
            sessionDropped = true;
        } else {
            sessionDropped = false;
        }
        
        noPastEvents = 0;
        noUpcomingEvents = 0;
        noEventsRequiringFeedback = 0;
        offset = DF_Utils.offset;
        System.debug('*** WEBChampionManageMySessions : User Champion ' + isChampion);
		
        
        if (currentDfc != null && isChampion) {
            // +++ EVENT SELECTIONS FOR CHAMPIONS +++

            String sdt = Datetime.now().format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().getDisplayName());
            Datetime dt = Datetime.valueOf(sdt);
            eventsRequiringFeedback = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c 
                                       FROM DF_Event__c 
                                       WHERE Event_Status__c != 'Cancelled' 
                                       AND Session_Organiser__c = : currentDfc.Id 
                                       AND Event_End_Date_Time__c <: dt 
                                       AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) 
                                       And RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                                       ORDER BY Event_Date_Time__c DESC];
            
            upcomingEvents = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c 
                              FROM DF_Event__c 
                              WHERE Session_Organiser__c = :currentDfc.Id 
                              AND Event_End_Date_Time__c >=: dt 
                              AND Event_Status__c != :STATUS_CANCELLED 
                              AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                              ORDER BY Event_Date_Time__c DESC];
            
            pastEvents = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c 
                          FROM DF_Event__c 
                          WHERE Session_Organiser__c = :currentDfc.Id 
                          AND Event_End_Date_Time__c <:dt 
                          AND Number_of_Attendees__c > 0 
                          AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                          ORDER BY Event_Date_Time__c DESC];
        
        } else if (currentDfc != null && !isChampion) {
            // +++ EVENT SELECTIONS FOR FRIENDS +++

            String sdt = Datetime.now().format('yyyy-MM-dd HH:mm:ss', UserInfo.getTimeZone().getDisplayName());
            Datetime dt = Datetime.valueOf(sdt);
            unapprovedEvents = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c 
                                FROM DF_Event__c 
                                WHERE Event_Status__c != 'Not Live / Approved' 
                                AND Session_Requester__c = : currentDfc.Id 
                                AND Event_End_Date_Time__c <: dt 
                                And RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                                ORDER BY Event_Date_Time__c DESC];
            
            eventsRequiringFeedback = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c 
                                       FROM DF_Event__c 
                                       WHERE Event_Status__c != 'Cancelled' 
                                       AND Session_Requester__c = : currentDfc.Id 
                                       AND Event_End_Date_Time__c <: dt 
                                       AND (Number_of_Attendees__c = null OR Number_of_Attendees__c = 0) 
                                       And RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                                       ORDER BY Event_Date_Time__c DESC];
            
            upcomingEvents = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c 
                              FROM DF_Event__c 
                              WHERE Session_Requester__c = :currentDfc.Id 
                              AND Event_End_Date_Time__c >=: dt 
                              AND Event_Status__c != :STATUS_CANCELLED 
                              AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                              ORDER BY Event_Date_Time__c DESC];
            
            pastEvents = [SELECT Id, Name, Event_Date_Time__c, Street__c, City__c, County__c, Postcode__c, Number_of_Attendees__c, Number_of_Attendee_Records__c, Number_of_Places__c, Request_Status__c, Event_Status__c, Session_Organiser_Firstname__c, Session_Organiser_Lastname__c, Session_Organiser__r.Contact_Number__c 
                          FROM DF_Event__c 
                          WHERE Session_Requester__c = :currentDfc.Id 
                          AND Event_End_Date_Time__c <:dt 
                          AND Number_of_Attendees__c > 0 
                          AND RecordTypeId = : DF_Utils.getsObjectRecordTypeId('DF_Event__c',SESSION_RT) 
                          ORDER BY Event_Date_Time__c DESC];
        }

        if (eventsRequiringFeedback != null){
            noEventsRequiringFeedback = eventsRequiringFeedback.size();
        }
        
        if (pastEvents != null){
            noPastEvents = pastEvents.size();
        }
        
        if (upcomingEvents != null) {
            noUpcomingEvents = upcomingEvents.size();
        }

        if (ApexPages.currentPage().getParameters().get('eventshare') != null){
        
            noOfFriends = ApexPages.currentPage().getParameters().get('eventshare');    
        
        }
    }
}