src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>BirthDate__c</fullName>
        <label>BirthDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Verefied__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Champion Code has been entered</description>
        <label>Champion Code Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ethnic_Group__c</fullName>
        <label>Ethnic Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arab</fullName>
                </value>
                <value>
                    <fullName>Asian – Any other background</fullName>
                </value>
                <value>
                    <fullName>Asian – Bangladeshi</fullName>
                </value>
                <value>
                    <fullName>Asian – Chinese</fullName>
                </value>
                <value>
                    <fullName>Asian – Indian</fullName>
                </value>
                <value>
                    <fullName>Asian – Pakistani</fullName>
                </value>
                <value>
                    <fullName>Black – African</fullName>
                </value>
                <value>
                    <fullName>Black – Any other background</fullName>
                </value>
                <value>
                    <fullName>Black – Caribbean</fullName>
                </value>
                <value>
                    <fullName>Mixed – Any other background</fullName>
                </value>
                <value>
                    <fullName>Mixed - White and Asian</fullName>
                </value>
                <value>
                    <fullName>Mixed – White and Black African</fullName>
                </value>
                <value>
                    <fullName>Mixed – White and Black Caribbean</fullName>
                </value>
                <value>
                    <fullName>Not disclosed</fullName>
                </value>
                <value>
                    <fullName>Other – Any other ethnic group</fullName>
                </value>
                <value>
                    <fullName>White – Any other background</fullName>
                </value>
                <value>
                    <fullName>White – British (English/Welsh/Scottish/Northern Irish)</fullName>
                </value>
                <value>
                    <fullName>White – Gypsy or Irish Traveller</fullName>
                </value>
                <value>
                    <fullName>White - Irish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Why_do_you_want_to_become_a_Champion__c</fullName>
        <label>Why do you want to become a Champion?</label>
        <type>TextArea</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Newsletters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletters</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WEBFriendConvertToChampion.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX class for the WEBFriendConvertToChampion VF Page
 *            
 *  Author  : Lakshmi Vasudevan
 *  Date    : 22-04-2016
 *  Version : 1.0
 *
 *  Description:    WEBFriendConvertToChampion class holds methods and properties used in the
 *                  WEBFriendConvertToChampion VF Page   
 *               
 *  Modification History
 *  Date            Who         Description 
 *           
*/
public without sharing class WEBFriendConvertToChampion extends DF_WEBC_ControllerBase {
  
  public final String EMPTY_FIELD_VALUE_MSG = 'Value is required and can\'t be empty';
  public String standardErrorMsg {get;set;}  
  public String birthDateError {get; set;}
  public String birthDateString {get;set;}
  public String whychampion {get;set;}
  public String whychampionError {get;set;}
  public Boolean isError = FALSE;
  public DF_Contact__c dfContactRecord {get; set;}

    public User thisUser {
        get {
            return WEBController.thisUser;
        }
        set;
    }
    
  
  public WEBFriendConvertToChampion(){
  	
  	standardErrorMsg = '';
    birthDateError = '';
    whychampionError ='';

   dfContactRecord =  [Select d.Contact_Number__c, d.Code_Verefied__c, d.Email__c, d.Title__c, d.Newsletters__c, d.Street__c, d.Portal_Contact__c, d.Last_Name__c, d.First_Name__c, d.County__c, d.City__c, d.Postcode__c, d.Country__c, d.BirthDate__c, Gender__c, Ethnic_Group__c From DF_Contact__c d where d.Portal_Contact__c = :thisUser.ContactId LIMIT 1];
   currentDfc = DF_Utils.getDFContactForUser(UserInfo.getUserId());
   
   if ( dfContactRecord.BirthDate__c != null ) {
            DateTime dt = dfContactRecord.birthDate__c;
            birthDateString = dt.format('dd/MM/yyyy');
    }         
    system.debug('birthdate string '+birthDateString);     
            
}

@TestVisible  private Date getDate(String sDateString) {
        
        
        try { 
            String[] parts = sDateString.split('/');
            Date dt = null;
            dt = Date.newInstance(Integer.valueOf(parts[2]),Integer.valueOf(parts[1]),Integer.valueOf(parts[0]));       
            return dt;
            
        } catch (Exception x) {
            
            return null; 
            
        }
    
    }
  
   public PageReference convertToChampion(){
   	
    standardErrorMsg = '';	
    isError = false;
    birthDateError='';
    if ( whychampion == null || whychampion.length() == 0 ) {
      whychampionError = EMPTY_FIELD_VALUE_MSG;
      isError=TRUE;
    }
    if ( birthDateString == null || birthDateString.length() == 0 ) {
        
            birthDateError = EMPTY_FIELD_VALUE_MSG;
            isError=TRUE;
        
        } else {

            Date dt = getDate(birthDateString);
            system.debug('Edit Champion Details : bdy ' + birthDateString);
            system.debug('Edit Champion Details : bdy ' + dt.format());

            if ( dt == null ) {
                
                birthDateError = 'Birth Date is invalid format (DD/MM/YYY)';
                isError = TRUE;
            
            } else { 
                    
                Date dtNow = Date.Today();      
                Integer m = dt.monthsBetween(dtNow);
                system.debug('Update Champion : Months ' + m);
                
                if ( m < 192 ) {
                    
                    birthDateError = DF_Utils.AGE_MSG;
                    isError=TRUE;
                }
                
                if ( m == 192 && dt.day() > dtNow.Day()) {
                    
                    birthDateError = DF_Utils.AGE_MSG;
                    isError=TRUE;
                    
                }
                
            }
            
        }  

        
        if (isError){
            return null;
        }
        
     
                
                dfContactRecord.BirthDate__c = getDate(birthDateString);
                Date dt = getDate(birthDateString);
                dfContactRecord.BirthDate__c = dt;
                dfContactRecord.Status__c = ( dfContactRecord.Code_Verefied__c ? DF_Utils.STATUS_CONVERTED : DF_Utils.STATUS_PROSPECTIVE );
                dfContactRecord.RecordTypeId = DF_Utils.getDfcRecordTypeId(DF_Utils.RT_CHAMPION);
                dfContactRecord.Why_do_you_want_to_become_a_Champion__c = whychampion;
                update dfContactRecord;
       
       PageReference pr = Page.WEBChampion;
            pr.getParameters().put('nr','true');
            return pr;
            
       
    
    }
  

  
}