src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>About_me__c</fullName>
        <label>About me</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Champion_exchange_access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has champion exchange access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Champion_Training__c</fullName>
        <label>Date of Champion Training</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interests__c</fullName>
        <label>Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Audience: Children</fullName>
                </value>
                <value>
                    <fullName>Audience: Young adults</fullName>
                </value>
                <value>
                    <fullName>Audience: Large groups</fullName>
                </value>
                <value>
                    <fullName>Audience: Black, Asian and minority ethnic communities</fullName>
                </value>
                <value>
                    <fullName>Audience: Adults with a learning disability</fullName>
                </value>
                <value>
                    <fullName>Audience: D/deaf</fullName>
                </value>
                <value>
                    <fullName>Audience: Adults with a visual impairment</fullName>
                </value>
                <value>
                    <fullName>Languages: BSL</fullName>
                </value>
                <value>
                    <fullName>Languages: Other</fullName>
                </value>
                <value>
                    <fullName>Languages: Welsh</fullName>
                </value>
                <value>
                    <fullName>Sector: Health &amp; social care</fullName>
                </value>
                <value>
                    <fullName>Sector: Retail</fullName>
                </value>
                <value>
                    <fullName>Sector: Finance</fullName>
                </value>
                <value>
                    <fullName>Sector: Leisure &amp; tourism</fullName>
                </value>
                <value>
                    <fullName>Sector: Housing</fullName>
                </value>
                <value>
                    <fullName>Sector: Utilities</fullName>
                </value>
                <value>
                    <fullName>Sector: Transport</fullName>
                </value>
                <value>
                    <fullName>Sector: Faith groups</fullName>
                </value>
                <value>
                    <fullName>Skills: Promotion</fullName>
                </value>
                <value>
                    <fullName>Skills: Working with the press</fullName>
                </value>
                <value>
                    <fullName>Skills: IT</fullName>
                </value>
                <value>
                    <fullName>Skills: Social media</fullName>
                </value>
                <value>
                    <fullName>Other: Local Dementia Friendly Community</fullName>
                </value>
                <value>
                    <fullName>Other: Rural communities</fullName>
                </value>
                <value>
                    <fullName>Other: Events</fullName>
                </value>
                <value>
                    <fullName>Other: Campaining</fullName>
                </value>
                <value>
                    <fullName>Other: Volunteering</fullName>
                </value>
                <value>
                    <fullName>Other: Fundraising</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c &amp; &quot;,  &quot; &amp; First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Interests__c</fullName>
        <label>Other Interests</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordType_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordType Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Completed_Info_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total No of Completed Info Sessions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Why_do_you_want_to_become_a_Champion__c</fullName>
        <label>Why do you want to become a Champion?</label>
        <type>TextArea</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ExchangeDFCDetailController.cls
public without sharing class ExchangeDFCDetailController{

    
    @AuraEnabled
    public static DF_Contact__c getDFCDetails(string uId) {
        User u = new User();
        u = [select contactId from User where Id =: uId];
         system.debug('returned dfc'+ [Select Id,name from DF_Contact__c WHERE Portal_Contact__c=:u.contactId][0]);
        
        DF_Contact__c dfc = new DF_Contact__c();
        dfc = [Select About_me__c,Champion_exchange_access__c,Date_of_Champion_Training__c,Title__c,city__c,Why_do_you_want_to_become_a_Champion__c,First_Name__c,name__c,name,recordtype_name__c,County__c,Total_No_of_Friends_Created__c,Total_No_of_Completed_Info_Sessions__c,interests__c,Other_interests__c from DF_Contact__c WHERE Portal_Contact__c=:u.contactId][0];
        return dfc;
  
    }
     @AuraEnabled
    public static List<String> getpickval() {
        List<String> options = new List<String>();

        Schema.DescribeFieldResult fieldResult = DF_Contact__c.Interests__c.getDescribe();

        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }       
        return options;
    }
    
     @AuraEnabled 
     public static DF_Contact__c saveDFC(DF_Contact__c dfcon){
        update dfcon;
        return dfcon;
    }  
    
     @AuraEnabled
    public static String getCurrentUser() {
      string toReturn;  
        if(UserInfo.getUserType()!='Guest'){
      toReturn =UserInfo.getUserId();
        system.debug('returned user'+toReturn);
        }
      return toReturn.substring(0, 15);
   }
    
      @AuraEnabled
    public static String getCurrentUserName() {
      string toReturn;  
        if(UserInfo.getUserType()!='Guest'){
      toReturn =UserInfo.getFirstName();
        system.debug('returned user'+toReturn);
        }
      return toReturn;
   }
    
     @AuraEnabled
    public static User getUserProfile(String uid) {
      User toReturn = new User();  
       
      toReturn =[SELECT Id,email,name FROM User WHERE Id = :uid  LIMIT 1][0];
        system.debug('returned user'+toReturn);
        
      return toReturn;
   }
    
    
    
   
    @AuraEnabled 
     public static DF_Contact__c cancelSave(DF_Contact__c dfcon){
      DF_Contact__c dfc = new DF_Contact__c();
      dfc = [Select Date_of_Champion_Training__c,Title__c,city__c,Why_do_you_want_to_become_a_Champion__c,First_Name__c,name__c,name,recordtype_name__c,County__c,Total_No_of_Friends_Created__c,Total_No_of_Completed_Info_Sessions__c,interests__c,Other_interests__c from DF_Contact__c WHERE Id=:dfcon.Id ];
      return dfc; 
     }

}