src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Type_of_Champion__c</fullName>
        <label>Type of Champion</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Super Champion</fullName>
                </value>
                <value>
                    <fullName>Welsh Champion</fullName>
                </value>
                <value>
                    <fullName>Staff Champion</fullName>
                </value>
                <value>
                    <fullName>Scouts</fullName>
                </value>
                <value>
                    <fullName>Young Persons Champion</fullName>
                </value>
                <value>
                    <fullName>Digital Champion</fullName>
                </value>
                <value>
                    <fullName>PR Champion</fullName>
                </value>
                <value>
                    <fullName>Children’s Champion</fullName>
                </value>
                <value>
                    <fullName>Fast tracked</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Mentor Champion</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Type 3</fullName>
                </value>
                <value>
                    <fullName>Type 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend</fullName>
        <active>true</active>
        <label>Dementia Friend</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_EventListingHelper_Test.cls
@isTest
public class DF_EventListingHelper_Test {

     @testSetup static void setup() {
        // Create the test data once and then run all methods on the dataset
        DF_DataFactory_Test.getTestData();  
        
    }
    
    static testmethod void getRequestedSessionsChampAsOrganiser_positive() {
        
        Id rtId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Dementia_Friend_Champion' AND SObjectType = 'DF_Contact__c'].Id;
        DF_Contact__c champDfContact = [SELECT Id 
                     FROM DF_Contact__c
                     WHERE RecordTypeId = :rtId
                     LIMIT 1];
        
		champDfContact.Type_of_Champion__c = 'Super Champion';
        update champDfContact;
        
        DF_EventListingHelper.getRequestedSessions(true, true, champDfContact.Id);
    	
    }
    
    static testmethod void getRequestedSessionsChampAsRequester_positive() {
        
        Id rtId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Dementia_Friend_Champion' AND SObjectType = 'DF_Contact__c'].Id;
        Id champId = [SELECT Id 
                     FROM DF_Contact__c
                     WHERE RecordTypeId = :rtId
                     LIMIT 1].Id;
        
        DF_EventListingHelper.getRequestedSessions(true, true, champId);
    	
    }
    
    static testmethod void getDeliveredSessionsChamp_positive() {
        
        Id rtId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Dementia_Friend_Champion' AND SObjectType = 'DF_Contact__c'].Id;
        Id champId = [SELECT Id 
                     FROM DF_Contact__c
                     WHERE RecordTypeId = :rtId
                     LIMIT 1].Id;
        
        DF_EventListingHelper.getDeliveredSessions(champId);
    	
    }
    
    static testmethod void getRequestedSessionsFriend_positive() {
        
        Id rtId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Dementia_Friend' AND SObjectType = 'DF_Contact__c'].Id;
        Id friendId = [SELECT Id 
                     FROM DF_Contact__c
                     WHERE RecordTypeId = :rtId LIMIT 1].Id;
        
        DF_EventListingHelper.getRequestedSessions(false, false, friendId);
    	
    }
    
    static testmethod void getCreatedSessionsChamp_positive() {
        
        Id rtId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Dementia_Friend_Champion' AND SObjectType = 'DF_Contact__c'].Id;
        Id champId = [SELECT Id 
                     FROM DF_Contact__c
                     WHERE RecordTypeId = :rtId LIMIT 1].Id;
        
        DF_EventListingHelper.getCreatedSessions(champId);
    	
    }
}