src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Pack_Request__c.object
<CustomObject>
    <description>A request for the Little Book OF Friendship</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Pack Requests</relationshipLabel>
        <relationshipName>DF_Pack_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DF Pack Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Pack Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF_Pack Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DF_Pack_RequestTriggerHandler.cls
public class DF_Pack_RequestTriggerHandler{


    private boolean m_isExecuting = false;
    private integer BatchSize = 0;    
    private Map<String, String> mapRegionPostcodes;
    private String RT_Champion;
 
  public DF_Pack_RequestTriggerHandler(boolean isExecuting, integer size){

        m_isExecuting = isExecuting;
        BatchSize = size;

  }


  public void OnBeforeInsert(List<DF_Pack_Request__c> dfPackRequests, Map<ID, DF_Pack_Request__c> DFPackRequestMap){

  UpdateAddressInfo(dfPackRequests,DFPackRequestMap);
    
  }
  
  public void OnBeforeUpdate(List<DF_Pack_Request__c> dfPackRequests, Map<ID, DF_Pack_Request__c> DFPackRequestMap){

 
    
  }


  public void UpdateAddressInfo( List<DF_Pack_Request__c> dfPackRequests, Map<ID, DF_Pack_Request__c> DFPackRequestMap){
   
   List<DF_Pack_Request__c> lisPackRequests = new List<DF_Pack_Request__c> ();
   
   Set<Id>  contactIds  = new Set<Id> ();
   for ( DF_Pack_Request__c pack : dfPackRequests ){
     contactIds.add(pack.DF_Contact__c);
    
   }
   
 List< DF_Contact__c> lisDFContact = [Select Id,City__c,Street__c,PostCode__c,County__c,Country__c from DF_Contact__c where Id in:contactIds];
   
   for ( DF_Pack_Request__c pack : dfPackRequests ){
   
    for(DF_Contact__c con :lisDFContact){
   
          pack.City__c = con.City__c;
          pack.Street__c = con.Street__c;
          pack.PostCode__c = con.PostCode__c;
          pack.County__c = con.County__c;
          pack.Country__c = con.Country__c;
    
       lisPackRequests.add(pack);
    
   }
   
   }
   
}



}