src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Contact_Inbound_Change__c.object
<CustomObject>
    <description>Changes to DF contact records on progress</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>DF Contact Inbound Changes</relationshipLabel>
        <relationshipName>DF_Contact_Inbound_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DF Contact Inbound Change</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>DF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DF Contact Inbound Changes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DF_Contact_Inbound_ChangeTHandler_Test.cls
@isTest
public  class DF_Contact_Inbound_ChangeTHandler_Test {
	/*  
***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            11-03-2016
     * @description     Test class for DF_Contact_Inbound_ChangeTriggerHandler
***********************************************************************************************/
	static testMethod void CoverMethod () {
		
		 Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
		 DF_Contact__c dc = (DF_Contact__c )mapTestData.get('Champion');
		 DF_Contact_Inbound_Change__c dcc = new DF_Contact_Inbound_Change__c(
		 Related_DF_Contact__c =  dc.Id,
		 First_Name__c = 'TFname',
		 Last_Name__c = 'TLname'		 
		 );
		 test.starttest();
		 
		 insert dcc;
	}
    
}