src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DF_Mail_ChampCloseSession_Bch_Test.cls
@isTest
public  class DF_Mail_ChampCloseSession_Bch_Test {
/*  
***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            10-08-2015
     * @description     Test class for DF_Mail_ChampCloseSession_Batcher
***********************************************************************************************/


static testMethod void MainTest () {
    
    Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
    DF_Contact__c DFchamp = (DF_Contact__c )mapTestData.get('Champion'); 
    DF_Event__c DFe = (DF_Event__c )mapTestData.get('FriendSession');
    
    Id OW = Mail_Utils.getOrgWideEmail() ; 
    
    Datetime d = System.today().addDays( -14 );
       
    DFchamp.Status__c = 'Converted';
    DFe.Event_Status__c = 'Available';
    DFe.Event_Date_Time__c = d;
    
    test.starttest(); 
    update DFe;
    update DFchamp ;
    
    DF_Mail_ChampCloseSession_Batcher batch = new DF_Mail_ChampCloseSession_Batcher ();
    batch.query =  'Select ID, Portal_Contact__c from DF_Contact__c where id=:DFchamp.id';
     
    batch.templateName = DF_Mail_Utils.VF_CLOSE_SESSIONS_AFTER_14_DAYS;
    batch.days = -14;
    database.executebatch(batch,1);
    System.assert(true);
    
    
    
   
}

static testMethod void MainTest2 () {
    
    Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
    DF_Contact__c DFchamp = (DF_Contact__c )mapTestData.get('Champion'); 
    DF_Event__c DFe = (DF_Event__c )mapTestData.get('FriendSession');
     
    
    Id OW = Mail_Utils.getOrgWideEmail() ; 
    
    Datetime d = System.today().addDays( -30 );
    
    DFchamp.Status__c = 'Converted';
    DFe.Event_Status__c = 'Available';
    DFe.Event_Date_Time__c = d;
    
    test.starttest(); 
    update DFe;
    update DFchamp ;
    
    DF_Mail_ChampCloseSession_Batcher batch = new DF_Mail_ChampCloseSession_Batcher ();
    batch.query =  'Select ID, Portal_Contact__c from DF_Contact__c  where  id=:DFchamp.id';
    
     
        
    batch.templateName = DF_Mail_Utils.VF_CLOSE_SESSIONS_AFTER_30_DAYS;
    batch.days = -30;
    database.executebatch(batch,1);
    System.assert(true);   
     
   
}

static testMethod void MainTest3 () {
    
    Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
    DF_Contact__c DFchamp = (DF_Contact__c )mapTestData.get('Champion'); 
    DF_Event__c DFe = (DF_Event__c )mapTestData.get('FriendSession');
     
    
    Id OW = Mail_Utils.getOrgWideEmail() ; 
    
    Datetime d = System.today().addDays( -45 );
    
    DFchamp.Status__c = 'Converted';
    DFe.Event_Status__c = 'Available';
    DFe.Event_Date_Time__c = d;
    
    test.starttest();
    update DFe;
    update DFchamp ;
    
    DF_Mail_ChampCloseSession_Batcher batch = new DF_Mail_ChampCloseSession_Batcher ();
    batch.query =  'Select ID, Portal_Contact__c from DF_Contact__c  where  id=:DFchamp.id';
    batch.templateName = DF_Mail_Utils.VF_CLOSE_SESSIONS_AFTER_45_DAYS;
    batch.days = -45;
    database.executebatch(batch,1);
    System.assert(true);   
     
   
}

}