src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>isVerifyEmailNotSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>created to indicate people who hasn&apos;t received verify email on 21/07/2016</description>
        <label>isVerifyEmailNotSent</label>
        <type>Checkbox</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchSendVerificationEmail_Test.cls
@isTest
private class BatchSendVerificationEmail_Test {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
        DF_Contact__c dfc = (DF_Contact__c )mapTestData.get('Champion');
        dfc.isVerifyEmailNotSent__c = true;
        update dfc;
        BatchSendVerificationEmail batch = new BatchSendVerificationEmail();
        test.starttest();
        Database.executeBatch( batch, 1 ); 
    }
}