src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Football_Team__c</fullName>
        <label>Football Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Football_Teams</valueSetName>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_FootballTeamSelection_Controller.cls
public with sharing class DF_WEBC_FootballTeamSelection_Controller {
	
	public DF_WEBC_FootballTeamSelection_Controller() {
		
	}

	public List<SelectOption> getFootballTeams()
	{
	  
	  List<SelectOption> options = new List<SelectOption>();
	        
	   Schema.DescribeFieldResult fieldResult = DF_Contact__c.Football_Team__c.getDescribe();
	   List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
	        
	   for( Schema.PicklistEntry f : ple)
	   {
	      options.add(new SelectOption(f.getLabel(), f.getValue()));
	   }       
	   
	   return options;
	}

}