src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>DF_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Region</label>
        <referenceTo>DF_Region__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Champions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>RSO</fullName>
        <active>true</active>
        <description>Regional Support Officer</description>
        <label>RSO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Region__c.object
<CustomObject>
    <description>Dementia Friends Region</description>
    <label>DF Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DF_WEBC_RSODetailsCtr_Test.cls
@isTest
public without sharing class DF_WEBC_RSODetailsCtr_Test {
    
    @isTest static void test_method_one() {
    Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();        
    DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('Champion'); 
    DF_Region__c dfr =  (DF_Region__c)mapTestData.get('Region'); 
    User u = (User)mapTestData.get('User2');
    User rso = (User)mapTestData.get('adminUser');
    
    dfc.status__c = 'Converted';
    update dfc;
    system.runAs(u){
     Test.setCurrentPage(Page.WEBChampion);
     DF_WEBC_RSODetailsController controller = new DF_WEBC_RSODetailsController();
     controller.currentDfc = dfc;
        system.assertNotEquals(null,controller.currentDfc.df_region__c);
     system.assertEquals(true,controller.isChampion);
   }

}
}