src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Friends Logged</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskTriggerHandler_Test.cls
@isTest
public class TaskTriggerHandler_Test{

 static testmethod void covermethod(){
 
 Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
 

 DF_Contact__c Dc1 = (DF_Contact__c )mapTestData.get('Champion2');
  
  DF_Event__c DFe = (DF_Event__c )mapTestData.get('FriendSession2');
  
   DFe.Event_Status__c = DF_Utils.EVENT_STATUS_COMPLETED;  
   DFe.Number_of_Attendees__c =100;
   Dc1.Total_No_of_Friends_Created__c =26;

  
   test.starttest();
   update Dc1;
   update DFe;
   
   DF_Mail_NoOfFriends_Batcher batch = new DF_Mail_NoOfFriends_Batcher();
   batch.templatename1 = DF_Mail_Utils.VF_NO_OF_FRIENDS;
   batch.templatename2 = DF_Mail_Utils.VF_NO_OF_FRIENDS_AND_CERT ;
   Database.executeBatch( batch, 1 );
   
   Task tsk =new Task();
   tsk.Description ='creating 26 Dementia Friends Email Id:TEREF16';
   tsk.WhatId=Dc1.Id;
   insert tsk;
   Task t = [Select DFC_Email_Tracker__c,Description from Task where Id=:tsk.Id];
  system.assert(integer.valueOf(t.Description.substringBetween('creating','Dementia Friends').replaceAll( '\\s+', ''))==26);
   Task tsk2 =new Task();
   tsk2.Description ='Email Id:TEREF1';
   tsk2.WhatId=Dc1.Id;
   insert tsk2;
   
   Task t2 = [Select DFC_Email_Tracker__c from Task where Id=:tsk2.Id];
   system.assert(t2.DFC_Email_Tracker__c=='TEREF1');
  }

}