src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_Organisation_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation ID</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>DF Champions</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Friends_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Number of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>Dementia_Friend_Champion</fullName>
        <active>true</active>
        <label>Dementia Friend Champion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchUpdateOldFriendCountsByChamps_Test.cls
/*  
***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            15-07-2016
     * @description     Test class for BatchUpdateOldFriendCountsByChamps
*************************/
@isTest
private class BatchUpdateOldFriendCountsByChamps_Test {

     @testsetup  static void mytestdata(){   
     DFP_DataFactory_Test.TestDataCreation();
   
    }
    static testMethod void myUnitTest() {
          
     List<Partner_Organisation__c> partner = [select id,name from Partner_Organisation__c where name='Test Partner Name' limit 1 ];
     List<DF_Contact__c> dfc  = [select id,Partner_Organisation_Id__c from DF_Contact__c where email__c = 'test.testcontact@myemail.com' limit 1]; 
     dfc[0].Partner_Organisation_Id__c =  partner[0].Id;
     dfc[0].Total_No_of_Friends_Created__c = 8;
     dfc[0].RecordTypeId = DF_Utils.getsObjectRecordTypeId('DF_Contact__c','Dementia_Friend_Champion');
     update dfc[0];
   
     BatchUpdateOldFriendCountsByChamps batch = new BatchUpdateOldFriendCountsByChamps();
    
     test.starttest();
    Database.executeBatch( batch,4);
   
        
    }
}