src/objects/DF_Contact__c.object
<CustomObject>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Of_Friends_Created__c</fullName>
        <label>ZZNumber Of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Of_Friends_Created_by_Champions__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number Of Friends Created by Champions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Of_Offline_Friends_Created__c</fullName>
        <label>Number Of Offline Friends Created</label>
        <summarizedField>Partner_Organisation_Event__c.Participant_Count__c</summarizedField>
        <summaryFilterItems>
            <field>Partner_Organisation_Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Offline Event</value>
        </summaryFilterItems>
        <summaryForeignKey>Partner_Organisation_Event__c.Partner_Organisation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_Of_Online_Friends_Created__c</fullName>
        <label>Number Of Online Friends Created</label>
        <summarizedField>Partner_Organisation_Event__c.Participant_Count__c</summarizedField>
        <summaryFilterItems>
            <field>Partner_Organisation_Event__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner Online Event</value>
        </summaryFilterItems>
        <summaryForeignKey>Partner_Organisation_Event__c.Partner_Organisation__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Champions_Identified__c</fullName>
        <label>Number of Champions Identified</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Number_Of_Friends_Created__c</fullName>
        <formula>Total_Number_Of_Friends_by_Champions__c +Number_Of_Offline_Friends_Created__c +Number_Of_Online_Friends_Created__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Number Of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Number_Of_Friends_by_Champions__c</fullName>
        <formula>Number_Of_Friends_Created_by_Champions__c +  Number_of_friends_by_org_sessions__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Number Of Friends by Champions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PO_Administrator__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>PO Administrators</relationshipLabel>
        <relationshipName>PO_Administrators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Organisation</label>
        <referenceTo>Partner_Organisation__c</referenceTo>
        <relationshipLabel>PO Administrators</relationshipLabel>
        <relationshipName>PO_Administrators</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO Administrator</label>
    <nameField>
        <displayFormat>POA{000000}</displayFormat>
        <label>POA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Administrators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_WEBC_PartnerHome_Controller.cls
/******************************************************************************************
 *  Alzheimers
 *  
 *  Purpose : APEX class for the DF_WEBC_PartnerHome VF Page
 *        
 *  Author  : Lakshmi Vasudevan
 *  Date    : Apr 2016
 *  Version : 1.0
 *
 *  Description:      
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
public without sharing class DF_WEBC_PartnerHome_Controller extends DF_WEBC_ControllerBase {
   public final String ID_PARAM = 'Id';
   public Boolean hasActions {get; set;}
   public Partner_Organisation__c selectedPartner {get;set;}
   public List<Partner_Organisation__c> lisPartners {get;set;}
   public string partnerCode {get;set;}
   public Boolean actionRecordSaved {get;set;}
   public Boolean orgDetailsUpdated { get;set;}
   public Page_Snippet__c totalFriendsSnippet {
        get {
            if (totalFriendsSnippet == null) {                            
                List<Page_Snippet__c> lis = [select p.Body_Text__c, p.Unique_Name__c from Page_Snippet__c p where p.Unique_Name__c = 'DementiaFriendsTotalSnippet' LIMIT 1];
                if ( !lis.isEmpty() ) {
                    totalFriendsSnippet = lis[0];
                }
            }
            return totalFriendsSnippet;
        }
        set ;
    }

    public boolean showSaveConfirmation {

        get {
            return ApexPages.currentPage().getParameters().get('ds') != null;
        }

        set;
    }


  
  
    public DF_WEBC_PartnerHome_Controller() {

        currentDfc = DF_Utils.getDFContactForUser(UserInfo.getUserId());  
        Set<Id> partnerIds = new Set<Id>();
        
        

          if ( currentDfc!= null ) {
              
           for( po_administrator__c a:[select partner_organisation__c from po_administrator__c where df_contact__c =:currentDfc.id ]){
              
           partnerIds.add(a.partner_organisation__c);
              
           }
           lisPartners = [select Id, Name, Number_of_Friends_Created__c, Number_of_Champions_Identified__c, DFC_Code__c 
                            from Partner_Organisation__c where Id in : partnerIds ];
            
            
           if (ApexPages.currentPage().getParameters().get(ID_PARAM) != null){
           selectedPartner =[select Id,DFC_code__c,Total_Number_Of_Friends_by_Champions__c,Name,Number_Of_Friends_Created_By_Champions__c,Number_Of_Offline_Friends_Created__c,Number_Of_Online_Friends_Created__c,Total_Number_Of_Friends_Created__c, Number_of_Champions_Identified__c,Number_of_Friends_Created__c from Partner_Organisation__c where Id=:ApexPages.currentPage().getParameters().get(ID_PARAM)];
          
            hasActions = DFP_Utils.hasActions(selectedPartner.Id);
            partnerCode =selectedPartner.DFC_code__c;
         }

      }    

    if (ApexPages.currentPage().getParameters().get('record-saved') != null){
        
       actionRecordSaved = true;        
     
     } 

    if (ApexPages.currentPage().getParameters().get('details-updated') != null){
        
       orgDetailsUpdated = true;        
     
     } 

    }
    
    

    

}