src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Digital_Friend_Signup_Time__c</fullName>
        <description>The date the DF Contact became a Digital Friend. This is the date the contact watched the video to 
4 mins and 10 seconds.</description>
        <inlineHelpText>When did the DF Contact watch the Video</inlineHelpText>
        <label>Digital Friend Signup Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Watched_video_type__c</fullName>
        <label>Watched video type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BSL</fullName>
                </value>
                <value>
                    <fullName>Standard Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_FriendVideo_Controller.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Controller for Friend Video Component
 *  Author  : Gary Grant
 *  Date    : April 2015
 *  Version : 
 *
 *               
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ????                           
*******************************************************************************************/

public without sharing class DF_WEBC_FriendVideo_Controller extends WEBC_ControllerBase {
	
	public boolean watchedVideo { 

		get {
			if ( !isLoggedIn ) { return false; }
			DF_Contact__c dfc = DF_Utils.getDFContactForUser(UserInfo.getUserId());
			return (dfc.Digital_Friend_Signup_Time__c ==null);
		}
		set;

	}

	public void doSetVideoWatched() {
      String videoType= Apexpages.currentPage().getParameters().get('videoType');
      
      system.debug('FriendVideo :video type'+videoType);
		system.debug('FriendVideo : Start');

		if ( !isLoggedIn ) { return; }
		DF_Contact__c dfc = DF_Utils.getDFContactForUser(UserInfo.getUserId());
		if ( dfc.Digital_Friend_Signup_Time__c != null ) { return; }
		
		dfc.Digital_Friend_Signup_Time__c = System.now();
		dfc.Watched_video_type__c = (videoType!=null?videoType:'');
		update dfc;
	  
	}

}