src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Portal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DF Contacts</relationshipLabel>
        <relationshipName>DF_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Champion__c</fullName>
        <label>Type of Champion</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Super Champion</fullName>
                </value>
                <value>
                    <fullName>Welsh Champion</fullName>
                </value>
                <value>
                    <fullName>Staff Champion</fullName>
                </value>
                <value>
                    <fullName>Scouts</fullName>
                </value>
                <value>
                    <fullName>Young Persons Champion</fullName>
                </value>
                <value>
                    <fullName>Digital Champion</fullName>
                </value>
                <value>
                    <fullName>PR Champion</fullName>
                </value>
                <value>
                    <fullName>Children’s Champion</fullName>
                </value>
                <value>
                    <fullName>Fast tracked</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
                <value>
                    <fullName>Mentor Champion</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Type 3</fullName>
                </value>
                <value>
                    <fullName>Type 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <recordTypes>
        <fullName>RSO</fullName>
        <active>true</active>
        <description>Regional Support Officer</description>
        <label>RSO</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <formula>datevalue(Event_Date_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session_Organiser__c</fullName>
        <label>Session Organiser</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Sessions Organised</relationshipLabel>
        <relationshipName>DF_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DF_Mail_ChampCloseSession_Batcher.cls
global class DF_Mail_ChampCloseSession_Batcher implements Database.Batchable<SObject>, Database.Stateful, Schedulable{

/*  
***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            10-08-2015
     * @description     Email to converted Champions who have not closed information Session in 14 days
                        of event date, sent by RSO
***********************************************************************************************/

   public string query;
  
   public Id OW = Mail_Utils.getOrgWideEmail();
   public string templateName{get;set;}
   public Integer days {get;set;}
   
        global void execute( SchedulableContext SC )
        {
          // batch run 
          DF_Mail_ChampCloseSession_Batcher batch = new DF_Mail_ChampCloseSession_Batcher();
          batch.days = -14;
          Database.executeBatch( batch, 1 );
        }

        global Database.QueryLocator start(Database.BatchableContext BC)
        {
          Date dt = System.today().addDays( days );
          Date d =date.newinstance(dT.year(), dT.month(), dT.day());
          
          Id rt = DF_Utils.getDfcRecordTypeId(DF_Utils.RT_CHAMPION);

          system.debug('++date returned++'+d);
          system.debug('++recordtype returned++'+rt); 
            String query = 
                'Select Id,' +
                'Portal_Contact__c' +
                ' From ' +
                'DF_Contact__c ' +
                'Where RecordtypeId=: rt '+
                'and Type_of_Champion__c excludes (\'VIP\')' +
                'and Status__c = \'' + DF_Utils.STATUS_CONVERTED +'\' ' +             
                'and id in '+
                '('+
                'select Session_Organiser__c from DF_Event__c where RecordType.DeveloperName = \'' + DF_Utils.RT_FRIENDS_SESSION +'\' ' +  
                'and Event_Status__c not in(\'Cancelled\',\'Completed\',\'Closed\')'+
                'and Event_Date__c =: d '+
                ')';
       
                
                
    
            system.debug('+++Query+++'+ query);

            return Database.getQueryLocator(query);
        
        }

        global void execute(Database.BatchableContext BC, List<SObject> scope)
        {
         
         List<Messaging.SingleEmailMessage> lisEmails = new List<Messaging.SingleEmailMessage>();

         for ( sObject s : scope ) {                   
           DF_Contact__c  con = (DF_Contact__c)s;           
           Map<String, EmailTemplate> mapTemp= Mail_Utils.getemailTemplateMap();
           templateName= (mapTemp.get(templatename).DeveloperName);
           lisEmails.add(Mail_Utils.getTemplatedEmail(templateName, con.Portal_Contact__c, con.id, OW, true, null));
          }

          if ( lisEmails.size() > 0 ) { Messaging.sendEmail(lisEmails); }

        }


        global void finish(Database.BatchableContext BC)
        {
          // do something interesting
        }
  }