src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_DFCAddressUpdatePCA_Batcher_Test.cls
@isTest
private class DF_DFCAddressUpdatePCA_Batcher_Test{
    
    static testmethod void doTest1()
    {
        
        Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();     
        DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('DFc');  
        dfc.Postcode__c=' N16 8AZ';
        Test.startTest();
        update dfc;
    }
    
    static testmethod void doTest2()
    {
        DF_DFCAddressUpdatePCA_Batcher dfpca = new DF_DFCAddressUpdatePCA_Batcher();
        Database.executeBatch(dfpca,4);
    }
    
}