src/objects/DF_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>On Hiatus/Resting</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>DF Contact</label>
    <nameField>
        <label>DF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Push_Notifications__c.object
<CustomObject>
    <fields>
        <fullName>DF_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DF Contact</label>
        <referenceTo>DF_Contact__c</referenceTo>
        <relationshipLabel>Push Notifications</relationshipLabel>
        <relationshipName>Push_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Unread</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Push Notification</label>
    <nameField>
        <displayFormat>PN{000000}</displayFormat>
        <label>Push Notifications Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_WEBC_PushMessages_Test.cls
@isTest
private class DF_WEBC_PushMessages_Test {
    
    @isTest static void test_method_one() {
    Map<String, Object> mapTestData= DF_DataFactory_Test.getTestData();        
        DF_Contact__c dfc = (DF_Contact__c)mapTestData.get('Champion');  
        dfc.Status__c =DF_Utils.STATUS_CONVERTED;
        update dfc;
        Push_Notifications__c pn = new Push_Notifications__c();
        pn.Message__c='tesrt';
        pn.title__c='test title';
        pn.DF_Contact__c = dfc.Id;
        pn.Status__c ='Unread';
        insert pn;
     User u = (User)mapTestData.get('User2');

    

        PageReference pr = Page.DF_WEBC_PushMessages;
            test.setCurrentPage(pr);
            test.starttest();
         DF_WEBC_PushMessages.deleteMessage(pn.id);
         DF_WEBC_PushMessages controller = new DF_WEBC_PushMessages();
         controller.currentdfc=dfc;
         List<Push_Notifications__c> lispn=controller.champMessages;
       system.assertNotEquals(null, lispn);
     
    }
    
    @isTest static void test_method_two() {
        // Implement test code
    }
    
}