src/objects/DF_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DF Event</label>
    <nameField>
        <label>DF Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DF Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WEBChampionSessionPrintAttendeesTest.cls
@isTest(seeAllData=false)
public with sharing class WEBChampionSessionPrintAttendeesTest {
    static testMethod void printAttendeesTest() {
        WEBChampionSessionPrintAttendees controller ;
        Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData(); 
        DF_Event__c De = (DF_Event__c )mapTestData.get('FriendSession');
        De.Event_Status__c = 'Available';

        Test.startTest();
       update  De;
        ApexPages.currentPage().getParameters().put('eventId', De.Id);
        
        controller = new WEBChampionSessionPrintAttendees();

        System.assertNotEquals(null, controller.isChampion);
        System.assertNotEquals(null, controller.attendees);
        System.assertNotEquals(null, controller.noOfAttendees);
        
        Test.stoptest();
    }
}