src/objects/DFC_Action_Area__c.object
<CustomObject>
    <description>From BSI Code of Practise PAS 1365</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Sequence</description>
        <inlineHelpText>BSI Action area Sequence</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DFC Action Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC Action Areas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Dfc_ActionArea_TriggerHandler_Test.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Test Class for Dfc_ActionArea_TriggerHandler
 *  Author  : Lakshmi Vasudevan
 *  Date    : 31-05-2016
 *  Version : 0.1 Unit Test
 *
 *               
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ????                           
*******************************************************************************************/
@isTest
private class Dfc_ActionArea_TriggerHandler_Test {


     @testSetup
    public static void setupData() {

        Dfc_DataFactory_Test.TestDataCreation(); 

    }
    
    static testMethod void myUnitTest() {
      DFC_Action_Area__c act =[select id,name from DFC_Action_Area__c  limit 1];
      DFC_Community__c community = [select id,name from DFC_Community__c limit 1];
      
      test.starttest();
      
      update act;
       DFC_Action_Area__c a= new DFC_Action_Area__c();
            a.Name = 'Action Area test';
            a.Active__c = true;
            a.Sequence__c = 10;
      insert a;
        
    }
}