src/objects/DFC_Alliance__c.object
<CustomObject>
    <description>Dementia Action Alliance</description>
    <fields>
        <fullName>Region__c</fullName>
        <description>Alliance Region</description>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <label>DFC Alliance</label>
    <nameField>
        <label>Alliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC Alliances</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <fields>
        <fullName>Central_Location__c</fullName>
        <description>Does this Dementia Friendly Community have a central location ? Yes or No</description>
        <label>Central Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The Country where the community is located. This will determine the approval process</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Wales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>DFC_County__c</referenceTo>
        <relationshipLabel>DFC Communities</relationshipLabel>
        <relationshipName>DFC_Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DA_Alliance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Dementia Action Alliance that thae Dementia Friendly Community is associated with</description>
        <label>DA Alliance</label>
        <referenceTo>DFC_Alliance__c</referenceTo>
        <relationshipLabel>DA_Alliance</relationshipLabel>
        <relationshipName>Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Approved__c</fullName>
        <description>The date the Community was approved</description>
        <label>Date Approved</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rural</fullName>
                </value>
                <value>
                    <fullName>Village</fullName>
                </value>
                <value>
                    <fullName>Town</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The Community Location</description>
        <inlineHelpText>You can give the name of the village / town / city, region and county for example.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Community Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Population__c</fullName>
        <inlineHelpText>Please give the approximate size of the population for the community becoming dementia friendly</inlineHelpText>
        <label>Population Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Region of England or Wales that the Community is in. This determines the Regional Lead which is the first approver</description>
        <label>Region</label>
        <referenceTo>DFC_DAA_Region__c</referenceTo>
        <relationshipLabel>DFC Communities</relationshipLabel>
        <relationshipName>DFC_Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DFC_County__c.object
<CustomObject>
    <description>The County in England where the Dementia Friendly Community is located</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Wales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region of England</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>East of England</fullName>
                </value>
                <value>
                    <fullName>London</fullName>
                </value>
                <value>
                    <fullName>North East</fullName>
                </value>
                <value>
                    <fullName>North West</fullName>
                </value>
                <value>
                    <fullName>South East</fullName>
                </value>
                <value>
                    <fullName>South West</fullName>
                </value>
                <value>
                    <fullName>West Midlands</fullName>
                </value>
                <value>
                    <fullName>Yorkshire and the Humber</fullName>
                </value>
                <value>
                    <fullName>East Midlands</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DFC County</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC Counties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DFC_DAA_Region__c.object
<CustomObject>
    <description>The list of regions on the DAA Website

South West
South East
London
East of England
East Midlands
West Midlands
Yorkshire and Humber
North West
North East</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Wales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DFC DAA Region</label>
    <nameField>
        <label>DFC DAA Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC DAA Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Dfc_CommunityPublicListing.cls
/* The 'without sharing' keywords in the class declaration 
   to ensure that the sharing rules for the current user are not enforced.

    Public Listing of Dementia Friendly Communities

    https://dfdev-dfdev.cs18.force.com/WebArticle?page=dfc-public-listing#.VwecehMrLdS

   ****/

public without sharing class Dfc_CommunityPublicListing {

    Public String daa { get;set; }
    Public String country { get;set; }
    Public String county { get;set; } 
    Public String region { get;set; } 

    public Dfc_CommunityPublicListing() {
        region = '';
        List<DFC_Community__c> c = communities;     
    }

    /*
     *   Returns a list of Regions to select from - with the Active Community Count per region
     */
    public List<SelectOption> regions { 

        get {

            Map<String, Integer> mapCount = new Map<String, Integer>();

            
            // Get the Active Community Count for each Region in the selected Country
            AggregateResult[] lisCount = 
                                [SELECT Region__c r, count(Id) c FROM DFC_Community__c 
                                 WHERE ( Status__c = 'Active' and Country__c =: country ) 
                                 GROUP BY Region__c ];

            for ( AggregateResult agr : lisCount ) {

                mapCount.put((String)agr.get('r'), (Integer)agr.get('c'));

            }

            regions = new List<SelectOption>();
            List<DFC_DAA_Region__c> lisRegions = [ select Id, Name from DFC_DAA_Region__c order by Name];
            for ( DFC_DAA_Region__c region : lisRegions ) {

                Integer iCount = (Integer)mapCount.get(region.Name);
                if ( iCount != null ) { 
                    String sLabel = region.Name + ' (' + iCount + ')';
                    regions.add(new SelectOption(region.Name, sLabel));
                }

            }

            return regions;
        }

        private set;

    }

    public List<SelectOption> daas { 

        get {

            List<DFC_Alliance__c> lis;


            daas = new List<SelectOption>();

            if (country=='Wales') return daas;

            if ( region == null || region == '' ) { 

                daa = ''; 
                lis = [ select Id, Name from DFC_Alliance__c order by Name ];

            } else { 

                lis = [ select Id, Name from DFC_Alliance__c where Region__c =:region order by Name];
            }


            Map<String, Integer> mapCount = new Map<String, Integer>();
            AggregateResult[] lisCount = [select DA_Alliance__c r, count(id) c from DFC_Community__c where Status__c = 'Active' group by DA_Alliance__c ];
            for ( AggregateResult agr : lisCount ) {

                mapCount.put((String)agr.get('r'), (Integer)agr.get('c'));

            }

            for ( DFC_Alliance__c daa : lis ) {

                Integer iCount = (Integer)mapCount.get(daa.id);
                if ( iCount != null ) { 
                    String sLabel = daa.Name + ' (' + iCount + ')';
                    daas.add(new SelectOption(daa.id, sLabel));
                }
            }

            return daas;
        }

        private set;

    }

    /*
     *   Returns the list of Active communities that match the selected 
     *   Country, Region and DAA filters -  if any - otherwise retuns all Active Communities
     */
    public List<DFC_Community__c> communities {

        get {
                 String status = 'Active';

                 String soql = 
                 'SELECT   Id, Name, Name__c, Central_Location__c, Status__c, Country__c, Region__c, '+
                         ' County__r.Name, Location__c, Location_Type__c, Population__c, Date_Approved__c, '+
                         ' DA_Alliance__r.Url__c, DA_Alliance__r.Name' + 
                 ' FROM DFC_Community__c ' +
                 ' WHERE Status__c =: status' ; 

                 // Add 'AND'  clauses to qualify the WHERE if there are filters selected
                 if ( country != null && country != '' ) {
                    soql = soql + ' and Country__c =: country ';
                 }

                 if ( region != null && region != '' ) {
                    soql = soql + ' and Region__c =: region ';
                 }

                 if ( daa != null && daa != '' ) {
                    soql = soql + ' and DA_Alliance__c =: daa ';
                 }

                 soql = soql + ' order by Name__c';

                 communities = Database.query(soql);

                return communities;

        }
        private set;
    }



}