src/objects/DFC_Alliance__c.object
<CustomObject>
    <description>Dementia Action Alliance</description>
    <label>DFC Alliance</label>
    <nameField>
        <label>Alliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC Alliances</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <fields>
        <fullName>Location__c</fullName>
        <description>The Community Location</description>
        <inlineHelpText>You can give the name of the village / town / city, region and county for example.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Community Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DFC_Community_Action_Area__c.object
<CustomObject>
    <description>Links action areas to a community</description>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipLabel>DFC Community Action Area</relationshipLabel>
        <relationshipName>Action_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DFC Community Action Area</label>
    <nameField>
        <displayFormat>DFCMA - {000000}</displayFormat>
        <label>Action Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Community Action Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Community_Representative__c.object
<CustomObject>
    <description>A person taking responsibility for meeting the requirements of the recognition process</description>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipName>Representatives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DFC Representative</label>
    <nameField>
        <displayFormat>DFCR - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Dfc_CommunityServiceCtrl_Test.cls
@isTest
private class Dfc_CommunityServiceCtrl_Test
{

	@testSetup
	public static void setupData() {

		Dfc_DataFactory_Test.TestDataCreation();

	}

	@isTest
	static void itShould()
	{

		User testUser = [SELECT Id FROM User WHERE Email = 'test1.testcontact@myemail.com'];

		// Run as the test user	
	
	
		DFC_Community__c community = [SELECT Id from DFC_Community__c limit 1];

		DFC_Community_Action_Area__c[] lisAreas = [select Id, name from DFC_Community_Action_Area__c where Community__c =: community.id];

		DFC_Community_Representative__c rep = [select Id from DFC_Community_Representative__c limit 1];

		test.startTest();


		DFC_Community__c comm = (DFC_Community__c)Dfc_CommunityServiceController.getCommunity(community.id);
		System.assertEquals('Here Somewhere', comm.Location__c);

		System.RunAs(testUser) {
		
			Dfc_CommunityServiceController.updateCommunity(comm, lisAreas);		
			Dfc_CommunityServiceController.addRepresentative(comm.id, 'test3.testcontact@myemail.com');
			Dfc_CommunityServiceController.inviteRepresentative(comm.id, 'test4.testcontact@myemail.com', 'Test4 TestContact');

			
			Dfc_CommunityServiceController.deleteRepresentative(comm.id, rep.id);
	    

			Object o = Dfc_CommunityServiceController.getCommunityWithContext(community.Id) ;

		}

	}

	@isTest
	static void itShould2()
	{
	
		Dfc_ErrorResponse error = (DFC_ErrorResponse)Dfc_CommunityServiceController.getCommunity('xxx');

		DFC_Community__c community = [ SELECT Id FROM DFC_Community__c limit 1];
		DFC_Community_Action_Area__c[] lisAreas = [SELECT id, name FROM DFC_Community_Action_Area__c WHERE  Community__c =: community.id];
		community.Name__c = '';

		error = (Dfc_ErrorResponse)Dfc_CommunityServiceController.updateCommunity(community, lisAreas);
		String s = error.getMessage();
		s = error.getType();
		s = error.getStackTrace();
		boolean b = error.getIsErrorResponse();

	}

	@isTest
	static void itShould3()
	{
	
		Dfc_ErrorResponse error = (Dfc_ErrorResponse)Dfc_CommunityServiceController.inviteRepresentative('xxx', 'xxx', 'xxx');
		String s = error.getMessage();
		s = error.getType();
		s = error.getStackTrace();

	}

	@isTest
	static void itShould4()
	{
	
		Dfc_ErrorResponse error = (Dfc_ErrorResponse)Dfc_CommunityServiceController.deleteRepresentative('xxx', 'xxx');
		String s = error.getMessage();
		s = error.getType();
		s = error.getStackTrace();

	}



	@isTest
	static void itShould5()
	{
	
		DFC_Community__c community = [select Id from DFC_Community__c limit 1];
		Dfc_CommunityServiceController.addRepresentative(community.id, 'test3.testcontact@myemail.com');
		Dfc_CommunityServiceController.addRepresentative(community.id, 'test3.testcontact@myemail.com');

	}

	@isTest
	static void isShould6()
	{

		User u = [select Id from User where Email = 'test1.testcontact@myemail.com'];	
		DFC_Alliance__c alliance = [select Id from DFC_Alliance__c limit 1];


		System.runAs(u) {

			String s = Dfc_CommunityServiceController.getCurrentUserId();
			Object o = Dfc_CommunityServiceController.getCommunitiesForDaa(alliance.Id);


		}

	}



}