src/objects/DFC_Alliance__c.object
<CustomObject>
    <description>Dementia Action Alliance</description>
    <fields>
        <fullName>DAA_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DAA Region</label>
        <referenceTo>DFC_DAA_Region__c</referenceTo>
        <relationshipLabel>DFC Alliances</relationshipLabel>
        <relationshipName>DFC_Alliances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Alliance Region</description>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>DFC Alliance</label>
    <nameField>
        <label>Alliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC Alliances</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DFC_DAA_Region__c.object
<CustomObject>
    <description>The list of regions on the DAA Website

South West
South East
London
East of England
East Midlands
West Midlands
Yorkshire and Humber
North West
North East</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Wales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DFC DAA Region</label>
    <nameField>
        <label>DFC DAA Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC DAA Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Dfc_Alliance_TriggerHandler.cls
/*
 *  The Dementia Action Alliances records are populated from the DAA website
 *  We need to link each Alliance to it's region in England
 *
 */


public without sharing class Dfc_Alliance_TriggerHandler {
    
    public Dfc_Alliance_TriggerHandler() {
    
    }
    
    public void OnBeforeInsert(DFC_Alliance__c[] lis) {

         applyRegionId(lis, null);

    }

    public void OnBeforeUpdate(DFC_Alliance__c[] lisOld, DFC_Alliance__c[] lisNew, Map<ID, DFC_Alliance__c> mapOld) {

            applyRegionId(lisNew, mapOld);          

    }

    private void applyRegionId(Dfc_Alliance__c[] lis, Map<ID, DFC_Alliance__c> mapOld ) {


        // Get all the English regions and put them in a map
        List<DFC_DAA_Region__c> lisRegions = [select Id, Name from DFC_DAA_Region__c where Country__c='England'];

        Map<String, DFC_DAA_Region__c> mapRegions = new Map<String, DFC_DAA_Region__c>();
        for ( DFC_DAA_Region__c region : lisRegions ) {
            mapRegions.put( region.Name, region );
        }

        // Loop thru the Alliances and update the Region id based on the Name of the region in England
        for ( DFC_Alliance__c alliance : lis ) {

            DFC_DAA_Region__c region = mapRegions.get(alliance.Region__c);
            if ( region != null ) {
                alliance.DAA_Region__c = region.Id;
                
            }

        }

   }


}