src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <fields>
        <fullName>DAA_Regional_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The DAA Regional Lead, who will be notified when a new community is created</description>
        <label>DAA Regional Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DFC_Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DFC_DAA_Region__c.object
<CustomObject>
    <description>The list of regions on the DAA Website

South West
South East
London
East of England
East Midlands
West Midlands
Yorkshire and Humber
North West
North East</description>
    <fields>
        <fullName>DAA_Regional_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DAA Regional Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DFC_DAA_Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DFC DAA Region</label>
    <nameField>
        <label>DFC DAA Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC DAA Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Dfc_DAA_Region_TriggerHdler_Test.cls
@isTest
public class Dfc_DAA_Region_TriggerHdler_Test {

	public Dfc_DAA_Region_TriggerHdler_Test() {


	}

	@testSetup
	public static void setupData() {

		Dfc_DataFactory_Test.TestDataCreation();

	}

	@isTest
	public static void doTest() {

		DFC_Community__c community = [select Id from DFC_Community__c limit 1];
		update community;

		DFC_DAA_Region__c region = [select Id, DAA_Regional_Lead__c from DFC_DAA_Region__c limit 1];
		User u = [select Id from User where Id !=: region.DAA_Regional_Lead__c limit 1];

		region.DAA_Regional_Lead__c = u.id;
		update region;


	}

}