src/objects/DFC_Action_Area__c.object
<CustomObject>
    <description>From BSI Code of Practise PAS 1365</description>
    <label>DFC Action Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC Action Areas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DFC_Community_Action_Area__c.object
<CustomObject>
    <description>Links action areas to a community</description>
    <fields>
        <fullName>Action_Area__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Action Area</label>
        <referenceTo>DFC_Action_Area__c</referenceTo>
        <relationshipLabel>DFC Community Action Area</relationshipLabel>
        <relationshipName>DFC_Community_Action_Area</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipLabel>DFC Community Action Area</relationshipLabel>
        <relationshipName>Action_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DFC Community Action Area</label>
    <nameField>
        <displayFormat>DFCMA - {000000}</displayFormat>
        <label>Action Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Community Action Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Dfc_ActionArea_TriggerHandler.cls
public without sharing class Dfc_ActionArea_TriggerHandler {
	

	public Dfc_ActionArea_TriggerHandler() {
		
	}
	
	public void OnAfterInsert(List<DFC_Action_Area__c> lisUpdated){
		
		handleNewActionArea(lisupdated);
		
	}
	
	
	public void OnBeforeUpdate(List<DFC_Action_Area__c> lisOldActionArea,List<DFC_Action_Area__c> lisUpdated,Map<Id,DFC_Action_Area__c> oldActionAreaMap){
		
		handleNewActionArea(lisupdated);
		
	}

	private void handleNewActionArea(List<DFC_Action_Area__c> lisUpdated) {


		List<DFC_Community_Action_Area__c> lisToAdd = new List<DFC_Community_Action_Area__c>();

		List<DFC_Community__c> communities = [select id, (select id, Action_Area__c from Action_Areas__r) from DFC_Community__c];
		
		// Loop all the updated DFC_Action_Area__c
		for ( DFC_Action_Area__c area : lisUpdated ) {


			// For this Area, loop all Communities (watch max batch size here....)
			for ( DFC_Community__c community : communities ) {

				Set<String> existingList = new Set<String>();				

				// For this Community, loop the DFC_Community_Action_Areas__c
				for ( DFC_Community_Action_Area__c caa : community.Action_Areas__r ) {

					 // Capture which action areas already exist
					 existingList.add(caa.Action_Area__c);	

				}

				// if the area does not exist for this community, create it and add it to the list
				if ( !existingList.contains(area.id) ) {

					DFC_Community_Action_Area__c caa = new DFC_Community_Action_Area__c();
					caa.Action_Area__c = area.Id;
                 	caa.Community__c = community.Id;
                 	lisToAdd.add(caa);

				}


			}

		} 

		insert lisToAdd;

	}


}