src/objects/DFC_Action_Area__c.object
<CustomObject>
    <description>From BSI Code of Practise PAS 1365</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Sequence</description>
        <inlineHelpText>BSI Action area Sequence</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DFC Action Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC Action Areas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DFC_Alliance__c.object
<CustomObject>
    <description>Dementia Action Alliance</description>
    <fields>
        <fullName>DAA_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DAA Region</label>
        <referenceTo>DFC_DAA_Region__c</referenceTo>
        <relationshipLabel>DFC Alliances</relationshipLabel>
        <relationshipName>DFC_Alliances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Alliance Region</description>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>DFC Alliance</label>
    <nameField>
        <label>Alliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC Alliances</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <fields>
        <fullName>Central_Location__c</fullName>
        <description>Does this Dementia Friendly Community have a central location ? Yes or No</description>
        <label>Central Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DAA_Region__c</fullName>
        <formula>Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DAA Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DAA_Regional_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The DAA Regional Lead, who will be notified when a new community is created</description>
        <label>DAA Regional Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DFC_Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DA_Alliance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Dementia Action Alliance that thae Dementia Friendly Community is associated with</description>
        <label>DA Alliance</label>
        <referenceTo>DFC_Alliance__c</referenceTo>
        <relationshipLabel>DA_Alliance</relationshipLabel>
        <relationshipName>Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Community Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Region of England or Wales that the Community is in. This determines the Regional Lead which is the first approver</description>
        <label>Region</label>
        <referenceTo>DFC_DAA_Region__c</referenceTo>
        <relationshipLabel>DFC Communities</relationshipLabel>
        <relationshipName>DFC_Communities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DFC_Community_Action_Area__c.object
<CustomObject>
    <description>Links action areas to a community</description>
    <fields>
        <fullName>Action_Area__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Action Area</label>
        <referenceTo>DFC_Action_Area__c</referenceTo>
        <relationshipLabel>DFC Community Action Area</relationshipLabel>
        <relationshipName>DFC_Community_Action_Area</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipLabel>DFC Community Action Area</relationshipLabel>
        <relationshipName>Action_Areas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DFC Community Action Area</label>
    <nameField>
        <displayFormat>DFCMA - {000000}</displayFormat>
        <label>Action Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Community Action Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_DAA_Region__c.object
<CustomObject>
    <description>The list of regions on the DAA Website

South West
South East
London
East of England
East Midlands
West Midlands
Yorkshire and Humber
North West
North East</description>
    <fields>
        <fullName>DAA_Regional_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DAA Regional Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DFC_DAA_Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>DFC DAA Region</label>
    <nameField>
        <label>DFC DAA Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFC DAA Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Dfc_Community_TriggerHandler.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX DFC Community Trigger Handler
 *
 *            Dementia Friendly Communities that have a central location need to be first approved by the 'Regional Lead'
 *            for the associated Dementia Action Alliance  (DFC_Alliance__c)

 *            Each Dementia Action Alliance belongs to a Region and the DAA Region record specifies
 *            the user who is the Regional Lead  (DAA_Regional_Lead__c)
 *
 *  Author  : Gary Grant
 *  Date    : 4/1/2015
 *  Version : 0.1 Unit Test
 *  
 *               
 *  Modification History
 *  Date            Who         Description 
 *
*******************************************************************************************/

public without sharing class Dfc_Community_TriggerHandler {
	

	public Dfc_Community_TriggerHandler() {

    System.debug('Dfc_Community_TriggerHandler()');
		
	}

	public void OnBeforeInsert(DFC_Community__c[] itemsNew, Map<ID, DFC_Community__c> itemsNewMap){

		applyRegionalLead(itemsNew);

   }

 	public void OnBeforeUpdate(DFC_Community__c[] itemsOld, Map<ID, DFC_Community__c> itemsOldMap, 
                               DFC_Community__c[] itemsNew, Map<ID, DFC_Community__c> itemsNewMap){

		applyRegionalLead(itemsNew);

  }

  /*
   *  If the Community is Submitted for recognition, the status is changed from Draft to Requested
   */

  public void onAfterUpdate(DFC_Community__c[] itemsOld, Map<ID, DFC_Community__c> itemsOldMap, 
                            DFC_Community__c[] itemsNew, Map<ID, DFC_Community__c> itemsNewMap) {
    
        System.debug('================= in onAfterUpdate method of Dfc_Community_TriggerHandler');

        for ( DFC_Community__c item : itemsNew ) {

           System.debug('=================' + item.Name__c);

            DFC_Community__c itemOld = itemsOldMap.get(item.Id);
            if ( item.Status__c == 'Requested' && itemOld.Status__c == 'Draft') {

                System.debug('=================  submitIntoApproval' + item.Name__c);

                submitIntoApproval(item);

            }
        }
    }

  public void onAfterInsert(DFC_Community__c[] itemsNew){
  	
  	populateActionAreas(itemsNew);
  }

  private void submitIntoApproval(DFC_Community__c community) {

        /// Create an approval request for the Community
        Approval.ProcessSubmitRequest asr = new Approval.ProcessSubmitRequest();
        asr.setObjectId(community.Id);

        System.debug('======================= Submitting community '+community.Name__c + community.Name__c + ' for approval');
        //asr.setComments('======================= Submitting community  request for approval.');

    
        //  Need to handle the case where the user record for the user doing the approval is Inactive
        //  Process failed. First exception on row 0; first error: MANAGER_NOT_DEFINED, Manager undefined.: []
        try {
              Approval.ProcessResult result = Approval.process(asr);
 
        } catch (Exception ex) {
            system.debug('ERROR SUBMITTING APPROVAL: ' + ex);
            // send an error to the administrators
/*
            ApexPages.addMessages(e);

             Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
             String[] toAddresses = new String[] {'developer@acme.com'};
             mail.setToAddresses(toAddresses);
             mail.setReplyTo('developer@acme.com');
             mail.setSenderDisplayName('Apex error message');
             mail.setSubject('Error from Org&nbsp;: ' + UserInfo.getOrganizationName());
             mail.setPlainTextBody(e.getMessage());
             Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); */

        }

    }

    /* Where the Community has a central location, Update the Regional Lead field on the Community record 
     * based on the Community Region. This name is required for the approval process
     */
    private void applyRegionalLead(DFC_Community__c[] communities) {


        System.debug('================= Apply Regional Lead');

      // Get a map of all Regions and their Regional Leads (bulkification)
      Map <Id, DFC_DAA_Region__c> mapRegions = new 
      Map <Id, DFC_DAA_Region__c>( [SELECT Id, DAA_Regional_Lead__c FROM DFC_DAA_Region__c] );

      // For each DFC Community, if there is a Central Location and the Region is populated, update the Regional Lead field
      for (DFC_Community__c community : communities) {

        if ( community.Central_Location__c !='No' && community.Region__c != null ) {

          DFC_DAA_Region__c region = mapRegions.get(community.Region__c);

          if ( region != null ) {
            community.DAA_Regional_Lead__c = region.DAA_Regional_Lead__c;

          } 
        }
      }

/*

      // Get a map of all Dementia Action Alliances and their Regional Leads (bulkification)
      Map<Id, DFC_Alliance__c> mapAlliances = new 
      Map<Id, DFC_Alliance__c>([SELECT Id, DAA_Region__r.DAA_Regional_Lead__c FROM DFC_Alliance__c]);

      // For each DFC Community, if the Alliance is populated, update the Regional Lead field
    	for (DFC_Community__c community : communities) {

    		if ( community.DA_Alliance__c != null ) {

    			DFC_Alliance__c alliance = mapAlliances.get(community.DA_Alliance__c);

    			if ( alliance != null ) {
    				community.DAA_Regional_Lead__c = alliance.DAA_Region__r.DAA_Regional_Lead__c;

    			}	
    		}
    	}

      */

    }

    private void populateActionAreas(DFC_Community__c[] communities){
    
     DFC_Action_Area__c[] actionAreas =  [SELECT Name, Id FROM DFC_Action_Area__c where Active__c = true order by Sequence__c ASC];
     
     List<String> ids = new List<String>();
     for ( DFC_Community__c community : communities ) { ids.add(community.id); }

     DFC_Community_Action_Area__c[] commActionAreas =  [SELECT Name, Id, Action_Area__c, Community__c FROM DFC_Community_Action_Area__c where Community__c in:ids ];

     Map<String, DFC_Community_Action_Area__c> mapCommAreas = new Map<String, DFC_Community_Action_Area__c>();
     
     for ( DFC_Community_Action_Area__c commArea : commActionAreas ) { 

        String key = commArea.Community__c + '~' + commArea.Action_Area__c;
        mapCommAreas.put(key, commArea);
     
     }

     List < DFC_Community_Action_Area__c> lisToInsert = new List< DFC_Community_Action_Area__c>();
      
     for (DFC_Community__c community : communities) {
            
        for (DFC_Action_Area__c area : actionAreas) {     
      
          String key = community.id + '~' + area.id; 
          if ( mapCommAreas.get(key) == null ) { 

               DFC_Community_Action_Area__c caa = new DFC_Community_Action_Area__c();
               caa.Action_Area__c = area.Id;
               caa.Community__c = community.Id;
               lisToInsert.add(caa);

          }
      
        }               
    }
    
    insert lisToInsert;
    
    }
    
    /*
    private void populateActionAreas(DFC_Community__c[] communities){
    
     DFC_Action_Area__c[] actionAreas =  [SELECT Name, Id FROM DFC_Action_Area__c where Active__c = true order by Sequence__c ASC];
      List < DFC_Community_Action_Area__c> lisToInsert = new List< DFC_Community_Action_Area__c>();
      
      for (DFC_Community__c community : communities) {
      	
      	if(community.Number_Of_Action_Areas__c ==0){
          for (DFC_Action_Area__c area : actionAreas) {   	
    		
    		
    		
    			 DFC_Community_Action_Area__c caa = new DFC_Community_Action_Area__c();
                 caa.Action_Area__c = area.Id;
                 caa.Community__c = community.Id;
                 lisToInsert.add(caa);
    			
    			
    		}
    	}
    }
    
    insert lisToInsert;
    }
  */
}