src/objects/DFC_Assessment__c.object
<CustomObject>
    <label>DFC Assessment</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>DFC Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Assessment_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Assessment</label>
        <referenceTo>DFC_Assessment__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entered_Answer__c</fullName>
        <description>The answer text ot the options the user selected</description>
        <label>Entered Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>DFC Assessment Answer</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>DFC Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Assessment Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Dfc_AssessmentStoreController_Test.cls
@isTest
without sharing class Dfc_AssessmentStoreController_Test {

    @testSetup
    static void setupData() {  Dfc_DataFactory_Test.TestDataCreation(); }

    @isTest
  	static void itShould()
  	{

  		// Get the test user linked to the Active Community
  		User testUser = [SELECT Id FROM User WHERE Email = 'test2.testcontact@myemail.com'];	


  		
  		System.runAs(testUser) {

  				Test.startTest();

          List<DFC_Community__c> communities = Dfc_Util.getCommunitiesForCurrentUser();

  				// Get the Assessment for Year 1

          DFC_Community__c community = communities[0];
          		
      		Integer assessmentYear = 1;
      		Object obj= Dfc_AssessmentStoreController.getAssessmentForCommunityAndYear(community.Id, assessmentYear) ;

      		DFC_Assessment__c assessment = (DFC_Assessment__c)obj;


  				// Get the Answers for that assessment
  				List<DFC_Assessment_Answer__c> answers =  
  				[SELECT Id,  Entered_Answer__c FROM DFC_Assessment_Answer__c 
  				 WHERE Assessment__c = :assessment.Id];

				  Dfc_AssessmentStoreController.updateAssessment(assessment.Id, 'Draft', answers);

				  Dfc_AssessmentStoreController.updateAssessment(assessment.Id, 'Draft', null);



                 // Now test getting an Assessment for year 99
			    assessmentYear = 99;
          obj= Dfc_AssessmentStoreController.getAssessmentForCommunityAndYear(community.Id, assessmentYear) ;
  			
  			}

  			Test.stopTest();

  			

    }

}