src/objects/DFC_Activity__c.object
<CustomObject>
    <description>Community Activities linked to a specific Focus Area</description>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <referenceTo>DFC_Community__c</referenceTo>
        <relationshipName>Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DFC Activity</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DFC_Community__c.object
<CustomObject>
    <description>Dementia Friendly Community - Application for Recognition</description>
    <fields>
        <fullName>Name__c</fullName>
        <label>Community Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>DFC Community</label>
    <nameField>
        <displayFormat>DFC-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFC Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Dfc_AttachmentService_Test.cls
@IsTest 
class Dfc_AttachmentService_Test {
    
    @testSetup
    public static void setupData() {

        Dfc_DataFactory_Test.TestDataCreation(); 

    }
    
  @IsTest 
    static void testserveAttachment() {

        DFC_Community__c community= [select Id from DFC_Community__c c where c.Name__c = 'ACTIVE TEST COMMUNITY' LIMIT 1]; 

        DFC_Activity__c activity = [select Id from DFC_Activity__c a where a.Community__c = :community.Id LIMIT 1]; 
     
        System.debug('+++++++++ Activity ID  '+activity.Id);

        Attachment attachment = [Select Id from Attachment where ParentId =: activity.Id];
        // http://blog.jeffdouglas.com/2012/03/21/writing-unit-tests-for-v24-apex-rest-services/

        System.debug('Attachment Id : ' + attachment.id);

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        // pass the req and resp objects to the method     
        req.requestURI = '/dfc/attachment';          
        req.httpMethod = 'GET';

        //Create and add the signed and encrypted payload with a date expiration
        String x = Dfc_Util.createSignedPayload(attachment.id);
        req.addParameter('id', x);

        RestContext.request = req;
        RestContext.response = res;

        Dfc_AttachmentService.serveAttachment();

  }

}