src/objects/Edt_Item__c.object
<CustomObject>
    <fields>
        <fullName>Text1__c</fullName>
        <inlineHelpText>Enter the text that you want to appear on the page in this field</inlineHelpText>
        <label>Text1</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text2__c</fullName>
        <label>Text2</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text3__c</fullName>
        <label>Text3</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value4__c</fullName>
        <label>Value4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value5__c</fullName>
        <label>Value5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value6__c</fullName>
        <label>Value6</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Editable Item</label>
    <nameField>
        <displayFormat>EDT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Editable Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EdtComponentController.cls
public virtual class EdtComponentController 
{
    public String itemGroup { get; set; }
    public String itemKey { get; set; }
    
    public String itemValue1 { get { checkStore(); return itemValue1; } set; }
    public String itemValue2 { get { checkStore(); return itemValue2; } set; }
    public String itemValue3 { get { checkStore(); return itemValue3; } set; }
    public String itemValue4 { get { checkStore(); return itemValue4; } set; }
    public String itemValue5 { get { checkStore(); return itemValue5; } set; }
    public String itemValue6 { get { checkStore(); return itemValue6; } set; }
    public String itemText1 { get { checkStore(); return itemText1; } set; }
    public String itemText2 { get { checkStore(); return itemText2; } set; }
    public String itemText3 { get { checkStore(); return itemText3; } set; }
    
    public String htmlClass { get; set; }
    public String htmlStyle { get; set; }
    
    public EdtPageContext pageContext { get; set; }

    private Boolean storeChecked = false;
    
    public void checkStore() { checkstore(true); }
    public void checkStore(boolean bCache)
    {
        if (bCache && storeChecked) { return; }
        Edt_Item__c item = pageContext.readStore(itemGroup, itemKey);
    
        if (item!=null) {
    
          itemValue1 = item.Value1__c;
          itemValue2 = item.Value2__c;
          itemValue3 = item.Value3__c;
          itemValue4 = item.Value4__c;
          itemValue5 = item.Value5__c;
          itemValue6 = item.Value6__c;
          itemText1 = item.Text1__c;
          itemText2 = item.Text2__c;
          itemText3 = item.Text3__c;

          if ( item.Attachments!=null && item.Attachments.size()>0 ) {

              itemAttachmentId = item.Attachments[0].id;  

          }


        }
        storeChecked = true;
    }

    public Boolean hasAttachment { get { checkstore(false); return itemAttachmentId != null; } private set; }
    public String itemAttachmentId { get { checkstore(); return itemAttachmentId; } set; }
    public Attachment attachment { get;set; }
    public Attachment getAttachment() 
    {
            if ( attachment != null ) { return attachment; }
            checkStore();
            if ( itemAttachmentId == null ) return null;
            attachment = [select id, Name, ContentType, Body from Attachment where id=:itemAttachmentId limit 1]; 

            return attachment;            
    }

  	private String itemId;
    public String getItemId()
    {
        if (itemId==null) itemId = pageContext.generateId();
        return itemId;
	}
	    
}