src/objects/Edt_Item__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Editable Item</label>
    <nameField>
        <displayFormat>EDT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Editable Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EdtDownloadController.cls
/* 

Redirect to an attachment on an Editable Item 
Gary Grant
May 2016	

*/

public without sharing class EdtDownloadController {

	public String keyParam {get;set;}
	public String grpParam {get;set;}

	public EdtDownloadController() {
		
	}

	public PageReference doRedirect() {

		keyParam = ApexPages.currentPage().getParameters().get('key');
		grpParam = ApexPages.currentPage().getParameters().get('group');
		return getRedirect(keyParam, grpParam);

	}

	public PageReference getRedirect(String key, String grp) {

		try { 
	
			Edt_Item__c item = [select id, (select id, ContentType from Attachments limit 1) from Edt_item__c where Group__c =:grp and Key__c=:key];
			Attachment att = item.Attachments[0];
			return new PageReference('/servlet/servlet.FileDownload?file=' + att.id);

		} catch (Exception x) {

			return null;

		}	

	}

}