src/objects/Edt_Item__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text1__c</fullName>
        <inlineHelpText>Enter the text that you want to appear on the page in this field</inlineHelpText>
        <label>Text1</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text2__c</fullName>
        <label>Text2</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text3__c</fullName>
        <label>Text3</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value4__c</fullName>
        <label>Value4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value5__c</fullName>
        <label>Value5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value6__c</fullName>
        <label>Value6</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Editable Item</label>
    <nameField>
        <displayFormat>EDT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Editable Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CkeDownloadHandler_Test.cls
@isTest
private class CkeDownloadHandler_Test
{

    @testSetup
    public static void setupData() {

        Edt_Item__c item = new Edt_Item__c();
        item.Text1__c = 'xxx';
        item.Text2__c = 'xxx';
        item.Text3__c = 'xxx';

        item.Value1__c = 'xxx';
        item.Value2__c = 'xxx';
        item.Value3__c = 'xxx';
        item.Value4__c = 'xxx';
        item.Value5__c = 'xxx';
        item.Value6__c = 'xxx';

        item.Group__c = 'cke-downloads';
        item.Key__c = 'pack';

        insert item;

        Attachment attach=new Attachment();

        attach.Name='Unit Test Attachment ';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.Body=bodyBlob;
        attach.ParentId=item.id;
        attach.ContentType = 'application/msword';
        attach.IsPrivate = false;
        attach.Description = 'Test';

        insert attach;
        
    }

    @isTest
    static void doTest() {
    
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = 'https://cs9.salesforce.com/services/apexrest/cupcake-download/pack';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;

        CkeDownloadHandler.serveAttachment();        

    }


    @isTest
    static void doTest2() {
    
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = 'https://cs9.salesforce.com/services/apexrest/cupcake-download/book';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;

        CkeDownloadHandler.serveAttachment();        

    }


}