src/objects/Edt_Item__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text1__c</fullName>
        <inlineHelpText>Enter the text that you want to appear on the page in this field</inlineHelpText>
        <label>Text1</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Editable Item</label>
    <nameField>
        <displayFormat>EDT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Editable Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CkeUrlRewriter_Test.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Test Class for DF_WEBC_UrlRewriter
 *  Author  : Gary Grant
 *  Date    : 22-02-2016
 *  Version : 0.1 Unit Test
 *
 *               
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ????                           
*******************************************************************************************/
@isTest
public with sharing class CkeUrlRewriter_Test {

    @testSetup
    public static void setupdata()
    {

        Edt_Item__c item = new Edt_Item__c();
        item.Text1__c = 'pack';
        
        item.Group__c = 'cke-downloads';
        item.Key__c = 'pack';

        insert item;

        Attachment attach=new Attachment();

        attach.Name='Unit Test Attachment ';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.Body=bodyBlob;
        attach.ParentId=item.id;
        attach.ContentType = 'application/msword';
        attach.IsPrivate = false;
        attach.Description = 'Test';

        insert attach;


    }


	public CkeUrlRewriter_Test() {
		
	}
    
    @isTest
    static void testMapUrl() {

     
        system.debug('Entering re-writer test');
     
        CkeUrlRewriter rewriter = new CkeUrlRewriter();

        PageReference pr = new PageReference('/request-a-pack');         
        PageReference redirect = rewriter.mapRequestUrl(pr); 

        pr = new PageReference('/request-a-pack?a=b');         
        redirect = rewriter.mapRequestUrl(pr); 

        pr = new PageReference('/download-pack');
        redirect = rewriter.mapRequestUrl(pr);        

        pr = new PageReference('/download-pack?a=b');
        redirect = rewriter.mapRequestUrl(pr);        

        List<PageReference> lis = rewriter.generateUrlFor(new List<PageReference>());
       

    }



}