src/objects/Edt_Item__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text1__c</fullName>
        <inlineHelpText>Enter the text that you want to appear on the page in this field</inlineHelpText>
        <label>Text1</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text2__c</fullName>
        <label>Text2</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text3__c</fullName>
        <label>Text3</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value4__c</fullName>
        <label>Value4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value5__c</fullName>
        <label>Value5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value6__c</fullName>
        <label>Value6</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Editable Item</label>
    <nameField>
        <displayFormat>EDT{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Editable Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EdtPageContext.cls
public class EdtPageContext 
{
    private Integer seq = 100;
    private Map<String, Map<String, Edt_Item__c>> groupCache = new Map<String, Map<String, Edt_Item__c>>();
    public boolean editEnabled { get;set; }

    public final static String ENABLING_PERMISSION_SET = 'Cke_Administrators';

    public EdtPageContext() {

        PermissionSetAssignment[] ass = [ SELECT Id FROM PermissionSetAssignment where Assignee.Id = :UserInfo.getUserId() and PermissionSet.Name = :ENABLING_PERMISSION_SET ];
        editEnabled = (!ass.isEmpty());

    }

    public Edt_Item__c readStore(String itemGroup, String itemKey)
    {
        Map<String, Edt_Item__c> grp = groupCache.get(itemGroup);
        if (grp == null) {
            Edt_Item__c[] items = [select Id, (select id, ContentType from Attachments order by CreatedDate desc limit 1), Group__c, Key__c, Value2__c, Value1__c, Value3__c, Value4__c, Value5__c, Value6__c, Text1__C, Text2__C, Text3__C from Edt_Item__c where Group__c = :itemGroup ];
            grp = new Map<String, Edt_Item__c>();
            for (Edt_Item__c item : items) grp.put(item.Key__c, item);
            groupCache.put(itemGroup, grp);
        }
        return grp.get(itemKey);
    }
    
    public String generateId()
    {
        return 'EDT'+seq++;
    }

}