src/objects/News_Flash__c.object
<CustomObject>
    <description>This object used to display a single News Flash message across the top of the Dementia Friends website</description>
    <fields>
        <fullName>Date_to_be_published__c</fullName>
        <label>Date to be published</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Body__c</fullName>
        <label>Main Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>News Flash</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>News Flash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News Flashes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Page__c.object
<CustomObject>
    <description>Main article page, parent to any Sections</description>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of this page / article</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_text__c</fullName>
        <description>Unique text value for this page / article</description>
        <label>Unique Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Page_Display_Snippet__c.object
<CustomObject>
    <description>Junction object to associate Page Snippets with Pages.</description>
    <fields>
        <fullName>Page_Snippet__c</fullName>
        <label>Page Snippet</label>
        <referenceTo>Page_Snippet__c</referenceTo>
        <relationshipLabel>Page Display Snippets</relationshipLabel>
        <relationshipName>Page_Display_Snippets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Page Display Snippets</relationshipLabel>
        <relationshipName>Page_Display_Snippets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Page Display Snippet</label>
    <nameField>
        <displayFormat>PDS-{0000}</displayFormat>
        <label>Page Display Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Display Snippets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Link_Title__c</fullName>
        <inlineHelpText>The URL of the blue link at the bottom of the snippet</inlineHelpText>
        <label>Link Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_URL__c</fullName>
        <inlineHelpText>The URL of the blue link at the bottom of the snippet</inlineHelpText>
        <label>Link URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Slide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DF_WEBC_HomePage.cls
public class DF_WEBC_HomePage extends DF_WEBC_ControllerBase {

    public News_Flash__c newsFlash {
    
        get {
            if (newsFlash == null){
                List<News_Flash__c> nfList = new List<News_Flash__c>();
                nfList = [Select n.Main_Body__c, n.IsActive__c, n.Date_to_be_published__c From News_Flash__c n where n.IsActive__c = true ORDER BY n.Date_to_be_published__c DESC LIMIT 1];
                if (nfList.size() > 0){
                    newsFlash = nfList[0];
                }else {
                    newsFlash = new News_Flash__c();
                }
            }
            
            return newsFlash;
        }
    
        set;
    
    }
    
    public List<DF_WEBC_HomePage.Slide> slides {
    	
    	get { 
    		
    		List<Slide> lis = new List<Slide>();
    		
    		List<Page_Display_Snippet__c> lisSnippets = 
    		
    				[select Page_Snippet__r.Title__c, Page_Snippet__r.Body_Text__c, Page_Snippet__c, Page_Snippet__r.Link_Title__c, Page_Snippet__r.Link_Url__c from Page_Display_Snippet__c 
    						where Page__r.Unique_text__c = 'Home_Page' and Page_Snippet__r.Position__c = 'slide'];
    		
    		for (Page_Display_Snippet__c pds : lisSnippets) {    		
    			Slide slide = new Slide(pds);
    			lis.add(slide);    			
    		}
    		
    		return lis;
    	}
    	
    	
    	set;}
    
    public class Slide
    {
    	
    	public String fileId {get;set;}
    	public String title {get;set;}
    	public String body {get;set;}
        public String link_title {get;set;}
        public String link_url {get;set;}
    	
    	public slide(Page_Display_Snippet__c pds) {
    		
    		title = pds.Page_Snippet__r.Title__c;
    		body = pds.Page_Snippet__r.Body_Text__c;

            link_title = pds.Page_Snippet__r.Link_Title__c;
            link_url = pds.Page_Snippet__r.Link_Url__c;
    		
            List<Attachment> attachedFiles = [select Id from Attachment where parentId =:pds.Page_Snippet__c limit 1];
        	if( attachedFiles != null && attachedFiles.size() > 0 ) {
            	fileId = attachedFiles[0].Id;
        	}
    		
    	}
    	
    	public slide() {
    		
    	}
    	
    }
    
    
}