src/objects/News_Flash__c.object
<CustomObject>
    <description>This object used to display a single News Flash message across the top of the Dementia Friends website</description>
    <fields>
        <fullName>Date_to_be_published__c</fullName>
        <label>Date to be published</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Body__c</fullName>
        <label>Main Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>News Flash</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>News Flash Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News Flashes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Page__c.object
<CustomObject>
    <description>Main article page, parent to any Sections</description>
    <fields>
        <fullName>Unique_text__c</fullName>
        <description>Unique text value for this page / article</description>
        <label>Unique Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Page Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Page_Display_Snippet__c.object
<CustomObject>
    <description>Junction object to associate Page Snippets with Pages.</description>
    <fields>
        <fullName>Page_Snippet__c</fullName>
        <label>Page Snippet</label>
        <referenceTo>Page_Snippet__c</referenceTo>
        <relationshipLabel>Page Display Snippets</relationshipLabel>
        <relationshipName>Page_Display_Snippets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Page Display Snippets</relationshipLabel>
        <relationshipName>Page_Display_Snippets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Page Display Snippet</label>
    <nameField>
        <displayFormat>PDS-{0000}</displayFormat>
        <label>Page Display Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Display Snippets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Slide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DF_WEBC_HomePage_Test.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX Test Class for DF_WEBC_HomePage
 *  Author  : Lakshmi Rajendram
 *  Date    : 12-03-2015
 *  Version : 0.1 Unit Test
 *
 *               
 *  Modification History
 *  Date            Who         Description 
 *  dd-mm-yyyy      ??          ????                           
*******************************************************************************************/
@isTest
public class DF_WEBC_HomePage_Test {
    
    
    static testMethod void testWEBC_HomePage() {
    
        DF_WEBC_HomePage ctl=new DF_WEBC_HomePage();

        News_Flash__c  NF1=ctl.newsFlash;
        News_Flash__c  NF=new News_Flash__c (IsActive__c=true,Date_to_be_published__c=system.today(),Main_Body__c='atestb');
        insert NF;

        DF_WEBC_HomePage ctl2 = new DF_WEBC_HomePage();
        ctl2.newsFlash =null;

        News_Flash__c  NF2=ctl2.newsFlash;

        Page_Snippet__c  ps=new Page_Snippet__c (Name__c='test',Position__c = 'slide');
        insert ps;

        Page__c p=new Page__c(Unique_text__c = 'Home_Page');
        insert p;

        Page_Display_Snippet__c  pds= new  Page_Display_Snippet__c(Page__c=p.id,Page_Snippet__c=ps.id);
        insert pds;
       
        List<DF_WEBC_HomePage.Slide> lisSlides = ctl.slides; 
        
    }
        
    
}