src/objects/Page_Display_Snippet__c.object
<CustomObject>
    <description>Junction object to associate Page Snippets with Pages.</description>
    <fields>
        <fullName>Page_Snippet__c</fullName>
        <label>Page Snippet</label>
        <referenceTo>Page_Snippet__c</referenceTo>
        <relationshipLabel>Page Display Snippets</relationshipLabel>
        <relationshipName>Page_Display_Snippets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Page Display Snippet</label>
    <nameField>
        <displayFormat>PDS-{0000}</displayFormat>
        <label>Page Display Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Display Snippets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Dfc_SnippetServiceCtl_Test.cls
@isTest
class Dfc_SnippetServiceCtl_Test
{

   @testSetup
   static void setupData() {

        Dfc_DataFactory_Test.TestDataCreation();

    }

    @isTest
    static void itShould()
    {
        List<Page_Display_Snippet__c> pageDisplaySnippets = Dfc_SnippetServiceController.getSnippets('dfc_apply');
        
        String key = 'dfc-apply-submit-intro';
        List<Page_Snippet__c> lis = [select Id, Name, Body_Text__c from Page_Snippet__c where Unique_Name__c = :key];        
        
        Page_Snippet__c snippet = lis[0];
       
        
        snippet.Body_Text__c = 'Updated';
        
        Dfc_SnippetServiceController.updateSnippet(snippet);
        
        
    }
}