src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Organisations</relationshipLabel>
        <relationshipName>DF_Partner_Organisations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DFC_Code__c</fullName>
        <label>DFC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Of_Friends_Created__c</fullName>
        <label>ZZNumber Of Friends Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Champions_Identified__c</fullName>
        <label>Number of Champions Identified</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_AdminHome_Controller.cls
/******************************************************************************************
 *  Alzheimers
 *  
 *  Purpose : APEX class for the Admin User Home VF Page
 *			  
 *  Author  : Gary Grant
 *  Date    : 13-03-15
 *  Version : 1.0
 *
 *  Description:    	
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
public without sharing class DF_WEBC_AdminHome_Controller extends DF_WEBC_ControllerBase {
   
    public Page_Snippet__c totalFriendsSnippet {
        get {
            if (totalFriendsSnippet == null) {                            
                List<Page_Snippet__c> lis = [select p.Body_Text__c, p.Unique_Name__c from Page_Snippet__c p where p.Unique_Name__c = 'DementiaFriendsTotalSnippet' LIMIT 1];
                if ( !lis.isEmpty() ) {
                    totalFriendsSnippet = lis[0];
                }
            }
            return totalFriendsSnippet;
        }
        set ;
    }

    public boolean showSaveConfirmation {

        get {
            return ApexPages.currentPage().getParameters().get('ds') != null;
        }

        set;
    }


    public Partner_Organisation__c partner {get;set;}
	
    public DF_WEBC_AdminHome_Controller() {

        User u = WEBC_CommunityWrapper.currentUser;

        try {

            if ( u!= null ) {
               partner = [select Id, Name, Number_of_Friends_Created__c, Number_of_Champions_Identified__c, DFC_Code__c 
                            from Partner_Organisation__c where Account__c =: u.Accountid ];
            }

        } catch (Exception x) {
            system.debug('No partner org found for User : ' + UserInfo.getUserId());
            return;
        }

                    
    }

    public void clicked(){}

    public Decimal friendCount {

        get {
            return partner.Number_of_Friends_Created__c;
        }

        set {

            if ( partner != null ) {
                partner.Number_of_Friends_Created__c = value;
                update partner;
            }
        }



    }


}