src/objects/Page_Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Body_Text__c</fullName>
        <label>Body Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page Snippet</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Page Snippet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Page Snippets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Dfc_SnippetStoreController_Test.cls
@isTest
class Dfc_SnippetStoreController_Test
{

  @testSetup
  static void setupData() {

    Dfc_DataFactory_Test.TestDataCreation();

  }

  @isTest
  static void itShould()
  {
  
    String s =  (String) Dfc_SnippetStoreController.readSnippet('dfc-apply-submit-intro');
 
    List<Page_Snippet__c> lis = [select Id, Name, Body_Text__c from Page_Snippet__c where Unique_Name__c = 'dfc-apply-submit-intro'];        
    Page_Snippet__c snippet1 = lis[0];

    snippet1.Body_Text__c= 'updated';
    Object o = Dfc_SnippetStoreController.updateSnippet(snippet1);

    Object p;

    //Dfc_ErrorResponse e = (Dfc_ErrorResponse)Dfc_SnippetStoreController.readSnippet('null');
    Dfc_ErrorResponse e = (Dfc_ErrorResponse)Dfc_SnippetStoreController.updateSnippet(new Page_Snippet__c());

  }

  
}