src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Sector__c</fullName>
        <description>update to picklist values must update DF_WEBC_RegisterOrg component selectlist values and partner resources-category field</description>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Organisation_Resources__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_added__c</fullName>
        <label>Date added</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Partner Organisation Resources</label>
    <nameField>
        <displayFormat>POR{00000}</displayFormat>
        <label>Partner Organisation Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Organisation Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_WEBC_PartnerResources_Ctr.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : APEX controller class for VF Page DF_WEBC_PartnerResourses.
 *  Author  : Lakshmi Vasudevan
 *  Date    : 05-2016
 *  Version : 1.0
 *
 *  Description:    Apex Class controller for the DF_WEBC_PartnerResources_Ctr class.
 *                  Will return a list of Session Resources to the Session Resources page
 *               
 *  Modification History
 *  Date            Who         Description 
 *            
*******************************************************************************************/
public with sharing class DF_WEBC_PartnerResources_Ctr extends DF_WEBC_ControllerBase {
    
    public final String ID_PARAM = 'Id';
    public Boolean isChampion {get;set;}
    public Boolean isConverted {get; set;}
    public Boolean isChampionConverted {get; set;}
    public Id partnerId{get; set;}
    public boolean hasActions {get; set;}
    public Partner_Organisation__c partner {get;set;}
    public String messageArea {get;set;}
    public String messageAreaClass {get;set;}

    public string sector {get;set;}
       
    public List<Partner_Organisation_Resources__c> partnerResources {
        get {
            if (partnerResources == null)
                partnerResources = new  List<Partner_Organisation_Resources__c>();

            return partnerResources;
        }
        set;
    }

    // Map of File Attachments
    public Map<Id, Attachment> att {
        get {
            if (att == null)
                att = new Map<Id, Attachment>();
            return att;
        }
        set;
    }

    //Constructor   
    public DF_WEBC_PartnerResources_Ctr() {
        

        isChampion = WEBController.isChampion;
        isConverted = WEBController.isChampionConverted;
        isChampionConverted = WEBController.isChampionConverted;
        partnerId = ApexPages.currentPage().getParameters().get(ID_PARAM);
        partner = DFP_Utils.currentOrg(partnerId); 
        hasActions = DFP_Utils.hasActions(partnerId);       
        sector = partner.Sector__c;
        if (sector != null) {
        
            Integer r = 0;
        //select all session resources where category match to selected org sector 
                List<Partner_Organisation_Resources__c> resourceTemp = [SELECT Id,Name, Name__c,date_added__c,(Select Id, Name, BodyLength, ContentType From Attachments LIMIT 1) FROM Partner_Organisation_Resources__c WHERE Category__c = :sector  ORDER BY Name__c];
                List<Partner_Organisation_Resources__c> resources = new List<Partner_Organisation_Resources__c>();

                // Grab the 1st (and hopefully only) attachement        
                for (Partner_Organisation_Resources__c sr : resourceTemp) {

                    if (sr.Attachments != null && sr.Attachments.size() > 0) {
                        att.put(sr.Id,sr.Attachments[0]);
                        partnerResources.add(sr);
                        System.debug('*** Found Attachment - ' + sr.Attachments[0].Name);
                    }
                
                }

        }
    }     


       
}