src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Sector__c</fullName>
        <description>update to picklist values must update DF_WEBC_RegisterOrg component selectlist values and partner resources-category field</description>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_PartnerVideos_Controller_Test.cls
/***********************************************************************************************
     * @author          Lakshmi Rajendram 
     * @date            22-09-2015
     * @description     DF_WEBC_PartnerVideos_Controller
***********************************************************************************************/
@isTest
public class DF_WEBC_PartnerVideos_Controller_Test {

    @testsetup  static void mytestdata(){   
     DFP_DataFactory_Test.TestDataCreation();
   
    }
 static testmethod void covermethod(){
     
     List<Partner_Organisation__c> partner = [select id,Sector__c,name from Partner_Organisation__c where name='Test Partner Name' limit 1 ];
     List<User> u  = [select id,name from User where email = 'test.testcontact@myemail.com' limit 1]; 


     System.runAs(u[0]) { 
        test.starttest();
        DF_WEBC_PartnerVideos_Controller ctr = new DF_WEBC_PartnerVideos_Controller();
        system.assertEquals(true,DF_WEBC_PartnerVideos_Controller.isPartnerFound('testpo123'));
        system.assertEquals(false,DF_WEBC_PartnerVideos_Controller.isPartnerFound(''));
        ctr.code = 'testpo123';
        ctr.init();
        


     }
 
    }
    
     static testmethod void covermethod2(){
     
     List<Partner_Organisation__c> partner = [select id,Sector__c,name from Partner_Organisation__c where name='Test Partner Name' limit 1 ];
     List<User> u  = [select id,name from User where email = 'test.testcontact@myemail.com' limit 1]; 


     System.runAs(u[0]) { 
        test.starttest();
        DF_WEBC_PartnerVideos_Controller ctr = new DF_WEBC_PartnerVideos_Controller();
        ctr.init();
        


     }
 
    }


}