src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Sector__c</fullName>
        <description>update to picklist values must update DF_WEBC_RegisterOrg component selectlist values and partner resources-category field</description>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Organisation_Resources__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_added__c</fullName>
        <label>Date added</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Partner Organisation Resources</label>
    <nameField>
        <displayFormat>POR{00000}</displayFormat>
        <label>Partner Organisation Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Organisation Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_WEBC_PartnerResources_Ctr_Test.cls
/************************************************************************************************
*Alzheimer's Society

     * @author          Lakshmi Vasudevan 
     * @date            23-05-2016
     * @description     Test class for DF_WEBC_PartnerResources_Ctr
***********************************************************************************************/
@isTest
private class DF_WEBC_PartnerResources_Ctr_Test {
	
	@testsetup  static void mytestdata(){   
     DFP_DataFactory_Test.TestDataCreation();
   
    }

    static testMethod void myUnitTest() {
      
     List<Partner_Organisation__c> partner = [select id,Sector__c,name from Partner_Organisation__c where name='Test Partner Name' limit 1 ];
     List<User> u  = [select id,name from User where email = 'test.testcontact@myemail.com' limit 1]; 
     
     Partner_Organisation_Resources__c oRes = new Partner_Organisation_Resources__c (Category__c='test Sector',Name__c='test',date_added__c=date.today());
     insert oRes;
       
     
      
     Blob b = Blob.valueOf('Test Data');  
      
     Attachment attachment = new Attachment();  
     attachment.ParentId = oRes.id;  
     attachment.Name = 'Test Attachment for Parent';  
     attachment.Body = b;  
      
     insert(attachment); 
     PageReference pageRef = Page.DF_WEBC_PartnerResources;
     pageRef.getParameters().put('id',partner[0].Id);
     test.setCurrentPage(pageRef);
        
     system.runAs(u[0]){ 
     
     test.starttest(); 
      
       DF_WEBC_PartnerResources_Ctr partnerRes = new DF_WEBC_PartnerResources_Ctr(); 
       partnerRes.partnerId = partner[0].Id;
       partnerRes.Sector =partner[0].Sector__c;
      // system.assertnotequals(null,webResource.sessionResources);
       //system.assertnotequals(null,webResource.att);
       //system.assertnotequals(null,webResource.sessionCategories);
      // WEBChampionSessionResources.sessionResourceCategory inCl = new WEBChampionSessionResources.sessionResourceCategory();
       
     }    
        
    }
}