src/objects/Partner_Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Organisations</relationshipLabel>
        <relationshipName>DF_Partner_Organisations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Employees__c</fullName>
        <label>Number of Employees</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-10</fullName>
                </value>
                <value>
                    <fullName>11-250</fullName>
                </value>
                <value>
                    <fullName>251-1000</fullName>
                </value>
                <value>
                    <fullName>1001-5000</fullName>
                </value>
                <value>
                    <fullName>5001-20000</fullName>
                </value>
                <value>
                    <fullName>20001+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>update to picklist values must update DF_WEBC_RegisterOrg component selectlist values and partner resources-category field</description>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health &amp; Social Care</fullName>
                </value>
                <value>
                    <fullName>Local Authority</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Public Service</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Leisure</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Power &amp; Utilities</fullName>
                </value>
                <value>
                    <fullName>Allied Healthcare Professionals</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector_other__c</fullName>
        <label>Sector - other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Partner Organisation</label>
    <nameField>
        <label>Partner Organisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Organisations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DF_WEBC_EditPartnerDetailsCtr_Test.cls
/************************************************************************************************
     * @author          Lakshmi Vasudevan 
     * @date            06-10-2016
     * @description     Test class for DF_WEBC_EditPartnerController
***********************************************************************************************/
@isTest
public with sharing class DF_WEBC_EditPartnerDetailsCtr_Test {

	@testsetup  static void mytestdata(){   
     DFP_DataFactory_Test.TestDataCreation();   
    }
	 static testMethod void EditOrgTest() {
	 
     List<Partner_Organisation__c> partner = [select id,name,Account__c,Number_of_Employees__c,Sector__c,Sector_other__c from Partner_Organisation__c where name='Test Partner Name' limit 1 ];
     List<Account> partnerAcc = [select id,name,BillingPostalCode,BillingCity,BillingStreet,BillingState,BillingCountry,Phone from Account where Id=:partner[0].Account__c limit 1 ];
     List<User> u  = [select id,name from User where email = 'test.testcontact@myemail.com' limit 1]; 
     PageReference pageRef = Page.DF_WEBC_EditPartnerDetails;
     pageRef.getParameters().put('id',partner[0].Id);
     test.setCurrentPage(pageRef);
        
     system.runAs(u[0]){
     
		     test.starttest();  
		     DF_WEBC_EditPartnerDetailsController controller = new DF_WEBC_EditPartnerDetailsController();
		      controller.partnerId =partner[0].Id;
		      controller.street =partnerAcc[0].billingStreet;
		      controller.phone=partnerAcc[0].phone;
		      controller.county=partnerAcc[0].billingstate;
		      controller.city=partnerAcc[0].billingcity;
		      controller.country=partnerAcc[0].billingcountry;
		      controller.postCode=partnerAcc[0].billingpostalCode;
		      controller.employees=partner[0].number_of_employees__c;
		      controller.sector=partner[0].sector__c;
		      controller.sectorOther=partner[0].sector_other__c;
		      List<SelectOption> sectorList=controller.sectorList ;
		      List<SelectOption> empnoList =controller.empnoList;
		      
		      System.assertNotEquals(null,controller.saveDetails());
		      System.assertNotEquals(null,controller.cancel());	
			}
    }

}