src/objects/PO_Administrator__c.object
<CustomObject>
    <fields>
        <fullName>Invited_Email__c</fullName>
        <label>Invited Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invited_Name__c</fullName>
        <label>Invited Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PO Administrator</label>
    <nameField>
        <displayFormat>POA{000000}</displayFormat>
        <label>POA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Administrators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PO_AdministratorTriggerHandler_Test.cls
/************************************************************************************************
*Alzheimer's Society

     * @author          Lakshmi Vasudevan 
     * @date            24-05-2016
     * @description     Test class for PO_AdministratorTriggerHandler
***********************************************************************************************/

@isTest
private class PO_AdministratorTriggerHandler_Test {
	
	@testsetup  static void mytestdata(){   
     DFP_DataFactory_Test.TestDataCreation();
   
    }
    
    static testMethod void myUnitTest() {
    
     List<PO_Administrator__c> invite = [select id,invited_email__c,invited_name__c from PO_Administrator__c where status__c ='Invited' limit 1];
     List<PO_Administrator__c> lisPOAdmin =new List<PO_Administrator__c>();
     lisPOAdmin.add(invite[0]);
     test.starttest();
     PO_AdministratorTriggerHandler handler = new PO_AdministratorTriggerHandler();
    
    }
}