src/objects/Pure360_Event_Report__c.object
<CustomObject>
    <fields>
        <fullName>Click_Date__c</fullName>
        <label>Click Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Click_Url__c</fullName>
        <label>Click Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_ID__c</fullName>
        <label>Delivery_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MessageName__c</fullName>
        <label>MessageName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>deliveryDate__c</fullName>
        <label>Delivery Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>firstName__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lastName__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>notificationSubject__c</fullName>
        <label>Notification Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pure360 Event Report</label>
    <nameField>
        <displayFormat>PE{00000}</displayFormat>
        <label>Pure360 Event Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pure360 Event Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_Pure360EventReport_Webservice.cls
@RestResource(urlMapping='/pure360EventReport/*')
global without sharing class DF_Pure360EventReport_Webservice {
       
   
 @HttpPost
 global static void doPost() {
  system.debug('pure http post' );
   RestRequest  req = RestContext.request;
   RestResponse res = RestContext.response;
      system.debug('Here is the request - '+req);
      system.debug('Here is the request headers - '+req.headers);
      system.debug('Here is the request params - '+req.params);
      system.debug('Here is the request remote address - '+req.remoteAddress);
      system.debug('Here is the request body - '+req.requestBody);
      system.debug('Here is the request url - '+req.requestURI);
      system.debug('Here is the request resource path - '+req.resourcePath);
    
   
 List<Pure360_Event_Report__c> lisEvents = new List<Pure360_Event_Report__c>();
   
  Pure360_Event_Report__c report = new Pure360_Event_Report__c();
  report.type__c = System.RestContext.request.params.get('type');
  report.deliveryDate__c = DF_Utils.getDatetimeforUnixTimeStamp(System.RestContext.request.params.get('deliveryDate'));
  report.Delivery_ID__c = System.RestContext.request.params.get('Delivery_ID');
  report.MessageName__c = System.RestContext.request.params.get('messageName');
  report.lastName__c = System.RestContext.request.params.get('lastName');
  report.firstName__c = System.RestContext.request.params.get('firstName');
  report.Event_Date__c = DF_Utils.getDatetimeforUnixTimeStamp(System.RestContext.request.params.get('Event_date'));
  report.notificationSubject__c = System.RestContext.request.params.get('notificationSubject');
  report.email__c = System.RestContext.request.params.get('email');
  report.Click_Date__c = DF_Utils.getDatetimeforUnixTimeStamp(System.RestContext.request.params.get('Click_Date'));
  report.Click_Url__c = System.RestContext.request.params.get('Click_Url');

  lisEvents.add(report);
     
    if(lisEvents.size()>0){
      insert lisEvents;
    }  
  
  
 }
 //String type,String Event_date,String email,String mobile,String messageName,String deliveryDate,String device_type,String device_OS,String device_Browser,String Delivery_ID,String firstName,String lastName,String notificationSubject,String Click_Date

    
}