src/objects/Push_Notifications__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Unread</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Push Notification</label>
    <nameField>
        <displayFormat>PN{000000}</displayFormat>
        <label>Push Notifications Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DF_WEBC_PushMessages.cls
global with sharing class DF_WEBC_PushMessages extends DF_WEBC_ControllerBase {

public List<Push_Notifications__c> champMessages{get;set;}
//public String pushMId {get;set;}

    global DF_WEBC_Pushmessages() {
        
    champMessages = new List<Push_Notifications__c>();
    if(currentdfc!=null)  {
        for(Push_Notifications__c pn :DF_Utils.pushMessages(currentdfc)){
            champMessages.add(pn);

        }
      }
    }

    @RemoteAction
    global static void deleteMessage(id pushMId){
         List<Push_Notifications__c> pn =new  List<Push_Notifications__c>();
         
         //system.debug('message to delete @@'+pushMId);
         for( Push_Notifications__c push: [select Message__c,Status__c from Push_Notifications__c where Id=:pushMId]){

            push.Status__c ='Read';
            pn.add(push);
         }
         
         
          if(pn.size()>0) {update pn;
            }

    }
}