src/objects/Session_Category__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Session Resource Category</label>
    <nameField>
        <label>Session Resource Category  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Resource Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Session_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Resource_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Session Resource Category</label>
        <referenceTo>Session_Category__c</referenceTo>
        <relationshipLabel>Session Resources</relationshipLabel>
        <relationshipName>Session_Resources</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Pre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Session Resource</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Session Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/WEBChampionSessionResources_Test.cls
@istest
public class WEBChampionSessionResources_Test{
  static testmethod void testWEBChampionSessionResources()
    {
     Map<String, Object> mapTestData = DF_DataFactory_Test.getTestData();
     User u  = (User)mapTestData.get('User2');  
      Session_Category__c scat = new Session_Category__c(name='testname',Description__c='testDescription',Type__c='Post');
       insert scat;
       
      Session_Resource__c sRes = new Session_Resource__c(Name__c ='testresorce',Type__c='Post',Session_Resource_Category__c = scat.id); 
       insert sRes;
      
      Blob b = Blob.valueOf('Test Data');  
      
    Attachment attachment = new Attachment();  
    attachment.ParentId = sRes.id;  
    attachment.Name = 'Test Attachment for Parent';  
    attachment.Body = b;  
      
    insert(attachment);   
     system.runAs(u){     
     test.starttest(); 
       WEBChampionSessionResources webResource = new WEBChampionSessionResources(); 
       system.assertnotequals(null,webResource.sessionResources);
       system.assertnotequals(null,webResource.att);
       system.assertnotequals(null,webResource.sessionCategories);
       WEBChampionSessionResources.sessionResourceCategory inCl = new WEBChampionSessionResources.sessionResourceCategory();
       
     
     }
      
    }
    
    }