src/objects/WEBError_Record__c.object
<CustomObject>
    <label>WEBError Record</label>
    <nameField>
        <displayFormat>WE-{DD}{MM}{YYYY}-{0000}</displayFormat>
        <label>WEBError Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WEBError Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WEBError_Record_Detail__c.object
<CustomObject>
    <fields>
        <fullName>WEBError_Record__c</fullName>
        <label>WEBError Record</label>
        <referenceTo>WEBError_Record__c</referenceTo>
        <relationshipLabel>WEBError Record Details</relationshipLabel>
        <relationshipName>WEBError_Record_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WEBError Record Detail</label>
    <nameField>
        <displayFormat>WED-{DD}{MM}{YYYY}-{0000}</displayFormat>
        <label>WEBError Record Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WEBError Record Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchPurgeWeberror.cls
/******************************************************************************************
 *  Alzheimer's Society
 *  
 *  Purpose : Batch APEX Class to to delete weberror records that are older than 30 days.
 *  Author  : Mike Tinson
 *  Date    : 25-06-2014
 *  Version : 0.1 Unit Test
 *
 *  Description:    Batch APEX Class to delete weberror records that are older than 30 days.
 *                  
 *
 *        //Called via the Execute Anonymous window. 
 *        BatchPurgeWeberror webErrBatch = new BatchPurgeWeberror ();
 *        webErrBatch.query = 'Select name, id from weberror_record__c where owner.name=\'Mike Tinson\' and name >=\'WE-16122014-3002\' and name < \'WE-16122014-3010\'';
 *        //Invoke the Batch class.
 *        ID batchprocessid = Database.executeBatch(webErrBatch, 20);
 *                  
 *  Modification History
 *  Date            Who         Description 
 *                     
*******************************************************************************************/
global class BatchPurgeWeberror implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable 
{
Public string query;
Private string defaultQuery = 'Select name, id from weberror_record__c where  CreatedDate < LAST_N_DAYS:45 limit 50000';


global Database.QueryLocator start(Database.BatchableContext BC)
   {
    String queryCmd;
    if (query==null) {
    queryCmd = defaultQuery;
    }
    else {
    queryCmd = query;
    }
    return Database.getQueryLocator(queryCmd);
   }
global void execute(Database.BatchableContext BC, List<sObject> scope)
    {

    List<WEBError_Record__c> webErrRec = new List<WEBError_Record__c>();
    List<WEBError_Record_Detail__c> webErrDetailRec = new List<WEBError_Record_Detail__c>();
    Set<WEBError_Record__c> WebErrSet = new Set<WEBError_Record__c>();

    for(sObject s : scope){
        WEBError_Record__c wErrRec = (WEBError_Record__c)s;
        webErrRec.add(wErrRec);
    }
    System.Debug('webErrRec Size = ' + webErrRec.size());
    WebErrSet.addAll(webErrRec);
    //get associated details records
    webErrDetailRec = [select name, id from WEBError_Record_Detail__c where WEBError_Record__c in :WebErrSet];
    
     Savepoint sp = Database.setSavepoint();
       Boolean hasDMLExceptionRaised=false;
    //now delete the web errors and associated details
     try{
    
        delete webErrDetailRec;
        delete webErrRec;
     }
     catch(Exception ex){hasDMLExceptionRaised=true;}
          // Revert the database to the original state on Exception
      if(hasDMLExceptionRaised)
      {
        Database.rollback(sp); 
      }
  
    }
 
global void finish(Database.BatchableContext BC)
    {
       
    
    }
 global void execute(SchedulableContext SC) 
  {
      BatchPurgeWeberror batchPurge = new BatchPurgeWeberror();
      Database.executeBatch(batchPurge,20);
  }
}